# Promoted during sprint 7 to preserve snapshot parity while curating public output contracts.
"""Image editing with Qwen Image Edit.

Public inputs:
    prompt (required): Text prompt
    source_image (required): Source image
    seed: Random seed
    use_lora: Lightning LoRA branch toggle
    sampler_name: Sampler algorithm

Output: SaveImage (node 60).

Source:  workflow_corpus/official/edit/qwen_image_edit.json
"""
from __future__ import annotations

from vibecomfy.workflow import VibeWorkflow
from vibecomfy.templates import InputSpec, ModelAsset, ReadyMetadata, finalize, new_workflow, node

_PROMPT_DEFAULT = """Remove all UI text elements from the image. Keep the feeling that the characters and scene are in water. Also, remove the green UI elements at the bottom."""

MODELS = {
    'qwen_image_edit_fp8_e4m3fn': ModelAsset(
        filename='qwen_image_edit_fp8_e4m3fn.safetensors',
        url='https://huggingface.co/Comfy-Org/Qwen-Image-Edit_ComfyUI/resolve/main/split_files/diffusion_models/qwen_image_edit_fp8_e4m3fn.safetensors',
        subdir='diffusion_models',
        sha256='393c6743d1de2e9031b5197027b36116f2096958ccc0223526d34e1860266021',
        hf_revision='83ae44f23af827155718b906c7dcc195a37c60b4',
        size_bytes=20430635136,
    ),
    'qwen_2_5_vl_7b_fp8_scaled': ModelAsset(
        filename='qwen_2.5_vl_7b_fp8_scaled.safetensors',
        url='https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/text_encoders/qwen_2.5_vl_7b_fp8_scaled.safetensors',
        subdir='text_encoders',
        sha256='cb5636d852a0ea6a9075ab1bef496c0db7aef13c02350571e388aea959c5c0b4',
        hf_revision='c232bcb51c1523899c62d6dcaa960b2627668de5',
        size_bytes=9384670680,
    ),
    'qwen_image_vae': ModelAsset(
        filename='qwen_image_vae.safetensors',
        url='https://huggingface.co/Comfy-Org/Qwen-Image_ComfyUI/resolve/main/split_files/vae/qwen_image_vae.safetensors',
        subdir='vae',
        sha256='a70580f0213e67967ee9c95f05bb400e8fb08307e017a924bf3441223e023d1f',
        hf_revision='c232bcb51c1523899c62d6dcaa960b2627668de5',
        size_bytes=253806246,
    ),
    'qwen_image_edit_lightning_4steps_v1_0_bf16': ModelAsset(
        filename='Qwen-Image-Edit-Lightning-4steps-V1.0-bf16.safetensors',
        url='https://huggingface.co/lightx2v/Qwen-Image-Lightning/resolve/main/Qwen-Image-Edit-Lightning-4steps-V1.0-bf16.safetensors',
        subdir='loras',
        sha256='d8132c32e7df906603dd6b072ff2fb0af88ab15ef0f3ac697a2011c8b47bbeb1',
        hf_revision='e74da8d4e71a54b341de86aa9f8d2509165aa513',
        size_bytes=849608296,
    ),
}

PUBLIC_INPUTS = {
    'prompt': InputSpec(node='102:76', field='prompt', default=_PROMPT_DEFAULT, type='STRING', required=True, description='Text prompt.', media_semantics='text'),
    'seed': InputSpec(node='102:3', field='seed', default=344147753686358, type='INT', description='Random seed.'),
    'use_lora': InputSpec(node='102:111', field='value', default=False, type='BOOLEAN', description='Lightning LoRA branch toggle.'),
    'sampler_name': InputSpec(node='102:3', field='sampler_name', default='euler', type='STRING', description='Sampler algorithm.'),
    'source_image': InputSpec(node='78', field='image', default='image_qwen_image_edit_input_image.png', type='IMAGE', required=True, aliases=('input_image', 'image'), description='Source image.'),
}

# vibecomfy: narrative (generated by tools/narrate_template.py @ 0.1.0+g9c5810f+dirty)
# ported from workflow_corpus/official/edit/qwen_image_edit.json (sha256: 34d4a94e9a60c9e60ccd96b965834eee92d0428288cbe000cea6837d9b2f9a94)
READY_METADATA = ReadyMetadata.build(
    template_id='qwen_image_edit',
    capability='image_edit',
    inputs=PUBLIC_INPUTS,
    models=MODELS,
    output_prefix='',
    provenance={'source_role': 'materialized_ready_python_template', 'source_workflow': 'workflow_corpus/official/edit/qwen_image_edit.json'},
    coverage_tier='required',
    vibecomfy_version='0.1.0',
    comfy_core={'version': '0.18.2', 'tested_at': '2026-05-20T09:19:32.302139+00:00', 'commit': 'f7b38d2eb97207cd834bcc3eb2e8b1d447b96c68', 'status': 'discovered'},
)

READY_METADATA["unbound_inputs"].update({'image': '78.image', 'prompt': '102:76.prompt', 'seed': '102:3.seed'})

def build() -> VibeWorkflow:
    """Build the workflow (auto-generated)."""
    wf = new_workflow(READY_METADATA, source_path=__file__)

    # ════ INPUTS ════
    input_image = node(wf, 'LoadImage', '78',
        image=PUBLIC_INPUTS['source_image'].default,
    )
    # ════ LOADERS ════
    base_diffusion_model = node(wf, 'UNETLoader', '102:37',
        unet_name=MODELS['qwen_image_edit_fp8_e4m3fn'].filename,
        weight_dtype='default',
    )
    text_encoder = node(wf, 'CLIPLoader', '102:38',
        clip_name=MODELS['qwen_2_5_vl_7b_fp8_scaled'].filename,
        type='qwen_image',
        device='default',
    )
    vae = node(wf, 'VAELoader', '102:39',
        vae_name=MODELS['qwen_image_vae'].filename,
    )
    # ════ SAMPLING ════
    lora_steps = node(wf, 'PrimitiveInt', '102:103', value=4)
    lora_cfg = node(wf, 'PrimitiveFloat', '102:105', value=1)
    base_steps = node(wf, 'PrimitiveInt', '102:106', value=20)
    base_cfg = node(wf, 'PrimitiveFloat', '102:107', value=2.5)
    use_lora = node(wf, 'PrimitiveBoolean', '102:111', value=PUBLIC_INPUTS['use_lora'].default)
    # ════ IMAGE PREP ════
    # parity-preserved leaf: wiring into edit encoding changes source API links.
    image_scale_to_total_pixels_93 = node(wf, 'ImageScaleToTotalPixels', '93',
        upscale_method='lanczos',
        megapixels=1.5,
        resolution_steps=1,
        image=input_image.out('IMAGE'),
    )
    # ════ TEXT CONDITIONING ════
    positive_edit_conditioning = node(wf, 'TextEncodeQwenImageEdit', '102:76',
        prompt=PUBLIC_INPUTS['prompt'].default,
        clip=text_encoder.out('CLIP'),
        image=input_image.out('IMAGE'),
        vae=vae.out('VAE'),
    )
    negative_edit_conditioning = node(wf, 'TextEncodeQwenImageEdit', '102:77',
        prompt='',
        clip=text_encoder.out('CLIP'),
        image=input_image.out('IMAGE'),
        vae=vae.out('VAE'),
    )
    vaeencode = node(wf, 'VAEEncode', '102:88',
        pixels=input_image.out('IMAGE'),
        vae=vae.out('VAE'),
    )
    # ════ MODEL PATCH STACK ════
    lora = node(wf, 'LoraLoaderModelOnly', '102:89',
        lora_name=MODELS['qwen_image_edit_lightning_4steps_v1_0_bf16'].filename,
        strength_model=1,
        model=base_diffusion_model.out('MODEL'),
    )
    # BRANCH SELECTION: use_flag=False → uses 102:107 (other: 102:105).
    switch_cfg = node(wf, 'ComfySwitchNode', '102:109',
        on_false=base_cfg.out('FLOAT'),
        on_true=lora_cfg.out('FLOAT'),
        switch=use_lora.out('BOOLEAN'),
    )
    # BRANCH SELECTION: use_flag=False → uses 102:106 (other: 102:103).
    switch_steps = node(wf, 'ComfySwitchNode', '102:110',
        on_false=base_steps.out('INT'),
        on_true=lora_steps.out('INT'),
        switch=use_lora.out('BOOLEAN'),
    )
    # BRANCH SELECTION: use_flag=False → uses 102:37 (other: 102:89).
    switch_model = node(wf, 'ComfySwitchNode', '102:108',
        on_false=base_diffusion_model.out('MODEL'),
        on_true=lora.out('MODEL'),
        switch=use_lora.out('BOOLEAN'),
    )
    model_sampling = node(wf, 'ModelSamplingAuraFlow', '102:66',
        shift=3,
        model=switch_model.out('OUTPUT'),
    )
    cfgnorm = node(wf, 'CFGNorm', '102:75',
        strength=1,
        model=model_sampling.out('MODEL'),
    )
    sampler = node(wf, 'KSampler', '102:3',
        seed=PUBLIC_INPUTS['seed'].default,
        sampler_name=PUBLIC_INPUTS['sampler_name'].default,
        scheduler='simple',
        denoise=1,
        steps=switch_steps.out('OUTPUT'),
        cfg=switch_cfg.out('OUTPUT'),
        latent_image=vaeencode.out('LATENT'),
        model=cfgnorm.out('PATCHED_MODEL'),
        negative=negative_edit_conditioning.out('CONDITIONING'),
        positive=positive_edit_conditioning.out('CONDITIONING'),
    )
    # ════ DECODE ════
    decoded_image = node(wf, 'VAEDecode', '102:8',
        samples=sampler.out('LATENT'),
        vae=vae.out('VAE'),
    )
    # ════ OUTPUT ════
    image_output = node(wf, 'SaveImage', '60',
        filename_prefix='ComfyUI',
        images=decoded_image.out('IMAGE'),
    )

    return finalize(
        wf,
        PUBLIC_INPUTS,
        READY_METADATA,
        output_node='60',
        output_type='SaveImage',
        name='image',
        mime_type='image/png',
        expected_cardinality='one',
        filename_prefix='',
        source_path=__file__,
        
    )

