/** Shared z-layer contract for cross-module overlay ordering. */
export const UI_Z_LAYERS = {
  GENERATIONS_PANE_BACKDROP: 99,
  GENERATIONS_PANE: 100,
  HOME_GLASS_PANE: 100,
  LIGHTBOX_MODAL: 100010,
  TASKS_PANE_TAB_ABOVE_LIGHTBOX: 100011,
  TOAST_VIEWPORT: 100020,
  TASKS_PANE_TAB_BEHIND_LIGHTBOX: 99,
} as const;
