"""Maintenance observations and authority joins (M2 bridge, M3 freeze).

The Maintenance package is the M2 substrate for coherent maintenance
observations over the accepted Run Authority, WBC, Custody, M11 conformance,
and Native Parity sources.  It ships in shadow/report mode only: enforcement,
autonomy, repair policy, daily baselines, and lifecycle mutation stay disabled.

This package exposes the strict foundation (one canonical serializer / strict
decoder, typed nullable identities, locator-only immutable owner references,
and validated UTC event times, half-open windows, watermarks, lateness, and
correction links) from :mod:`identity`.  The M3 freeze (Plan Step 15) adds the
stable M4-facing API surface on top — the owner-source join
(:class:`~arnold_pipelines.megaplan.maintenance.contracts.ObservationEnvelope`
and :func:`~arnold_pipelines.megaplan.maintenance.observation.capture_observation`),
the occurrence-bound request reference contracts
(:mod:`~arnold_pipelines.megaplan.maintenance.operations` and
:mod:`~arnold_pipelines.megaplan.maintenance.events`), the replayable
checkpoint scheduler (:mod:`~arnold_pipelines.megaplan.maintenance.checkpoints`),
recurrence/escalation links, the independent verification surface
(:mod:`~arnold_pipelines.megaplan.maintenance.verification`), and the frozen
M3 handoff view (:mod:`~arnold_pipelines.megaplan.maintenance.handoffs`) —
resolved lazily through :func:`__getattr__` so importing the package never
pulls the heavier modules and never creates an import cycle with the incident
schema (which itself imports the identity foundation).

The package remains reference-only (SD1): it never constructs an owner
authority record and never calls a canonical owner seam; only the cloud
adapters (``arnold_pipelines.megaplan.cloud.maintenance_recovery`` /
``maintenance_canary``) may call those seams.
"""

from __future__ import annotations

import importlib
from typing import Any

from arnold_pipelines.megaplan.maintenance.identity import (
    MAINTENANCE_ENVIRONMENTS,
    MAINTENANCE_SCHEMA_VERSION,
    MAX_IDENTITY_LENGTH,
    AnyMaintenanceId,
    AttemptId,
    ChainId,
    CorrectionLink,
    EnvironmentId,
    EventWindow,
    Extensions,
    IdentityComparison,
    IdentityMismatchError,
    InvalidIdentityError,
    InvalidTimeError,
    Lateness,
    MaintenanceCodecError,
    MaintenanceError,
    ModelId,
    OwnerKind,
    OwnerRef,
    PlanId,
    ProfileId,
    RunId,
    StageId,
    TenantId,
    UtcTime,
    Watermark,
    canonical_digest,
    canonical_dumps,
    canonical_json,
    classify_lateness,
    compare_identities,
    require_identical,
    strict_loads,
    utc_now,
)

#: Frozen M4-facing API surface (Plan Step 15, T16): the exact names M4 may
#: import from ``arnold_pipelines.megaplan.maintenance``.  This vector is the
#: M4 handoff contract — the owner-source join, occurrence-bound request
#: reference, checkpoint scheduler, recurrence/escalation links, independent
#: verification, and the frozen M3 handoff view.  Adding a name is a
#: compatible extension; removing or re-binding one is a breaking change that
#: must land with a new handoff-view version.
M4_API: tuple[str, ...] = (
    # owner-source join (T6)
    "ObservationEnvelope",
    "SourceVersionVector",
    "JoinSource",
    "capture_observation",
    "CustodyRead",
    "RunAuthorityRead",
    "WbcRead",
    "ConformanceRead",
    "NativeManifestRead",
    "ProofRead",
    "RuntimeRead",
    "read_custody",
    "read_run_authority",
    "read_wbc_attempt",
    "read_conformance",
    "read_native_manifest",
    "read_proof",
    "read_runtime",
    # occurrence-bound request reference (T2/T3/T10)
    "OperationalEvent",
    "OperationalActionKind",
    "RepairRequestPayload",
    "OccurrenceCoordinates",
    "LeaseCoordinates",
    "RunAuthorityCoordinates",
    "WbcAttemptCoordinates",
    "PolicyVersionCoordinates",
    "ActionTarget",
    "ProducerPrincipal",
    "OwnerReceipts",
    # checkpoint scheduler (T7)
    "CheckpointWindowKind",
    "CANONICAL_CHECKPOINT_ORDER",
    "CHECKPOINT_WINDOW_DELTAS",
    "CheckpointDueItem",
    "due_checkpoints",
    "checkpoint_window_bounds",
    "completed_checkpoint_windows",
    "canonical_checkpoint_window",
    "SIX_HOUR_ALIAS",
    # recurrence / escalation (T13)
    "verified_recurrence",
    "RecurrenceLink",
    "RecurrencePayload",
    "RecurrenceReference",
    "EscalationReference",
    "HumanEscalationPayload",
    # independent verification (T8)
    "VerificationResult",
    "VerificationOutcome",
    "VerificationRejectReason",
    "NegativeControlResult",
    "ExpectedAuthority",
    "evaluate_verification",
    "required_checkpoint_set",
    "checkpoint_set_complete",
    "negative_controls_passed",
    "progress_beyond",
    "authoritative_progress_refs",
    # M4 handoff view (T1): accepted vector + drift, never guessed
    "MaintenanceHandoffView",
    "build_handoff_view",
    "default_handoff_registry",
    "verify_frozen_digests",
    "verify_handoff_drift",
    "HandoffRegistry",
    "HandoffResolution",
    "HandoffResolutionState",
)

#: Name -> (source submodule, attribute) for every M3/M4 API name.  Resolved
#: lazily through :func:`__getattr__` (PEP 562) so importing the package never
#: eagerly pulls the heavier modules and never forms an import cycle with
#: ``incident.schema`` (which imports this package's identity foundation).
_M4_LAZY_IMPORTS: dict[str, tuple[str, str]] = {
    # contracts
    "CompletenessState": ("contracts", "CompletenessState"),
    "CoherenceReason": ("contracts", "CoherenceReason"),
    "CoherenceState": ("contracts", "CoherenceState"),
    "EVIDENCE_PRECEDENCE": ("contracts", "EVIDENCE_PRECEDENCE"),
    "EVIDENCE_PRECEDENCE_VERSION": ("contracts", "EVIDENCE_PRECEDENCE_VERSION"),
    "FreshnessState": ("contracts", "FreshnessState"),
    "ObservationEnvelope": ("contracts", "ObservationEnvelope"),
    "SourceVersionVector": ("contracts", "SourceVersionVector"),
    "eligibility_supported": ("contracts", "eligibility_supported"),
    "precedence_rank": ("contracts", "precedence_rank"),
    # operations
    "ActionTarget": ("operations", "ActionTarget"),
    "EscalationReference": ("operations", "EscalationReference"),
    "LeaseCoordinates": ("operations", "LeaseCoordinates"),
    "OccurrenceCoordinates": ("operations", "OccurrenceCoordinates"),
    "OwnerReceipts": ("operations", "OwnerReceipts"),
    "PolicyVersionCoordinates": ("operations", "PolicyVersionCoordinates"),
    "ProducerPrincipal": ("operations", "ProducerPrincipal"),
    "ProducerRole": ("operations", "ProducerRole"),
    "RecurrenceReference": ("operations", "RecurrenceReference"),
    "RunAuthorityCoordinates": ("operations", "RunAuthorityCoordinates"),
    "WbcAttemptCoordinates": ("operations", "WbcAttemptCoordinates"),
    "assert_reference_only_contract": (
        "operations",
        "assert_reference_only_contract",
    ),
    # events
    "CheckpointVerificationPayload": ("events", "CheckpointVerificationPayload"),
    "CheckpointWindowKind": ("events", "CheckpointWindowKind"),
    "HumanEscalationPayload": ("events", "HumanEscalationPayload"),
    "InstallationPayload": ("events", "InstallationPayload"),
    "MaintenanceEvent": ("events", "MaintenanceEvent"),
    "OperationalActionKind": ("events", "OperationalActionKind"),
    "OperationalEvent": ("events", "OperationalEvent"),
    "OperationalPayload": ("events", "OperationalPayload"),
    "ProgressObservationPayload": ("events", "ProgressObservationPayload"),
    "RecurrenceLink": ("events", "RecurrenceLink"),
    "RecurrencePayload": ("events", "RecurrencePayload"),
    "RepairRequestPayload": ("events", "RepairRequestPayload"),
    "RetriggerPayload": ("events", "RetriggerPayload"),
    "SIX_HOUR_ALIAS": ("events", "SIX_HOUR_ALIAS"),
    "SourceChangePayload": ("events", "SourceChangePayload"),
    "TerminalVerificationPayload": ("events", "TerminalVerificationPayload"),
    "VerifierProvenance": ("events", "VerifierProvenance"),
    "canonical_checkpoint_window": ("events", "canonical_checkpoint_window"),
    "event_digest": ("events", "event_digest"),
    "occurrence_idempotency_key": ("events", "occurrence_idempotency_key"),
    "operational_event_digest": ("events", "operational_event_digest"),
    "verified_recurrence": ("events", "verified_recurrence"),
    # sources
    "ConformanceAdapter": ("sources", "ConformanceAdapter"),
    "ConformanceRead": ("sources", "ConformanceRead"),
    "CurrentSourceRead": ("sources", "CurrentSourceRead"),
    "CustodyAdapter": ("sources", "CustodyAdapter"),
    "CustodyRead": ("sources", "CustodyRead"),
    "NativeManifestAdapter": ("sources", "NativeManifestAdapter"),
    "NativeManifestRead": ("sources", "NativeManifestRead"),
    "ProofAdapter": ("sources", "ProofAdapter"),
    "ProofRead": ("sources", "ProofRead"),
    "RUNTIME_SOURCE_PATHS": ("sources", "RUNTIME_SOURCE_PATHS"),
    "RunAuthorityAdapter": ("sources", "RunAuthorityAdapter"),
    "RunAuthorityRead": ("sources", "RunAuthorityRead"),
    "RuntimeAdapter": ("sources", "RuntimeAdapter"),
    "RuntimeRead": ("sources", "RuntimeRead"),
    "SourceCursorRef": ("sources", "SourceCursorRef"),
    "WbcAdapter": ("sources", "WbcAdapter"),
    "WbcEventRef": ("sources", "WbcEventRef"),
    "WbcRead": ("sources", "WbcRead"),
    "read_conformance": ("sources", "read_conformance"),
    "read_custody": ("sources", "read_custody"),
    "read_native_manifest": ("sources", "read_native_manifest"),
    "read_proof": ("sources", "read_proof"),
    "read_run_authority": ("sources", "read_run_authority"),
    "read_runtime": ("sources", "read_runtime"),
    "read_wbc_attempt": ("sources", "read_wbc_attempt"),
    # observation
    "DEFAULT_MAX_ATTEMPTS": ("observation", "DEFAULT_MAX_ATTEMPTS"),
    "JoinSource": ("observation", "JoinSource"),
    "capture_observation": ("observation", "capture_observation"),
    "conformance_source": ("observation", "conformance_source"),
    "custody_source": ("observation", "custody_source"),
    "native_manifest_source": ("observation", "native_manifest_source"),
    "proof_source": ("observation", "proof_source"),
    "run_authority_source": ("observation", "run_authority_source"),
    "runtime_source": ("observation", "runtime_source"),
    "wbc_source": ("observation", "wbc_source"),
    # checkpoints
    "CANONICAL_CHECKPOINT_ORDER": ("checkpoints", "CANONICAL_CHECKPOINT_ORDER"),
    "CHECKPOINT_WINDOW_DELTAS": ("checkpoints", "CHECKPOINT_WINDOW_DELTAS"),
    "CheckpointDueItem": ("checkpoints", "CheckpointDueItem"),
    "checkpoint_window_bounds": ("checkpoints", "checkpoint_window_bounds"),
    "completed_checkpoint_windows": ("checkpoints", "completed_checkpoint_windows"),
    "due_checkpoints": ("checkpoints", "due_checkpoints"),
    # verification
    "ExpectedAuthority": ("verification", "ExpectedAuthority"),
    "NegativeControlResult": ("verification", "NegativeControlResult"),
    "VerificationOutcome": ("verification", "VerificationOutcome"),
    "VerificationRejectReason": ("verification", "VerificationRejectReason"),
    "VerificationResult": ("verification", "VerificationResult"),
    "authoritative_progress_refs": ("verification", "authoritative_progress_refs"),
    "checkpoint_set_complete": ("verification", "checkpoint_set_complete"),
    "evaluate_verification": ("verification", "evaluate_verification"),
    "negative_controls_passed": ("verification", "negative_controls_passed"),
    "progress_beyond": ("verification", "progress_beyond"),
    "required_checkpoint_set": ("verification", "required_checkpoint_set"),
    # handoffs
    "ADAPTER_VERSIONS": ("handoffs", "ADAPTER_VERSIONS"),
    "ApprovalEvidence": ("handoffs", "ApprovalEvidence"),
    "ApprovalState": ("handoffs", "ApprovalState"),
    "COMPATIBILITY_FACADE_IDENTITY": ("handoffs", "COMPATIBILITY_FACADE_IDENTITY"),
    "FROZEN_FIXTURE_DIGESTS": ("handoffs", "FROZEN_FIXTURE_DIGESTS"),
    "FROZEN_SCHEMA_DIGESTS": ("handoffs", "FROZEN_SCHEMA_DIGESTS"),
    "HANDOFF_IDS": ("handoffs", "HANDOFF_IDS"),
    "HandoffAcceptedEntry": ("handoffs", "HandoffAcceptedEntry"),
    "HandoffDriftEntry": ("handoffs", "HandoffDriftEntry"),
    "HandoffRegistry": ("handoffs", "HandoffRegistry"),
    "HandoffResolution": ("handoffs", "HandoffResolution"),
    "HandoffResolutionReason": ("handoffs", "HandoffResolutionReason"),
    "HandoffResolutionState": ("handoffs", "HandoffResolutionState"),
    "HandoffRow": ("handoffs", "HandoffRow"),
    "M3_VIEW_VERSION": ("handoffs", "M3_VIEW_VERSION"),
    "MaintenanceHandoffView": ("handoffs", "MaintenanceHandoffView"),
    "PROJECTION_API_VERSIONS": ("handoffs", "PROJECTION_API_VERSIONS"),
    "WbcCoordinates": ("handoffs", "WbcCoordinates"),
    "build_handoff_view": ("handoffs", "build_handoff_view"),
    "default_handoff_registry": ("handoffs", "default_handoff_registry"),
    "load_handoff_registry": ("handoffs", "load_handoff_registry"),
    "verify_frozen_digests": ("handoffs", "verify_frozen_digests"),
    "verify_handoff_drift": ("handoffs", "verify_handoff_drift"),
}


def __getattr__(name: str) -> Any:
    """Resolve an M3/M4 API name from its source module (PEP 562, lazy).

    Every name in :data:`M4_API` (and the wider package ``__all__``) is
    resolved on first access from its canonical source submodule, then cached
    on the package so repeated access is cheap and object identity is stable.
    Unknown names raise ``AttributeError`` exactly like a normal module.
    """
    entry = _M4_LAZY_IMPORTS.get(name)
    if entry is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module_name, attr = entry
    module = importlib.import_module(f"{__name__}.{module_name}")
    value = getattr(module, attr)
    globals()[name] = value
    return value


__all__ = [
    # Identity foundation (M2)
    "MAINTENANCE_ENVIRONMENTS",
    "MAINTENANCE_SCHEMA_VERSION",
    "MAX_IDENTITY_LENGTH",
    "AnyMaintenanceId",
    "AttemptId",
    "ChainId",
    "CorrectionLink",
    "EnvironmentId",
    "EventWindow",
    "Extensions",
    "IdentityComparison",
    "IdentityMismatchError",
    "InvalidIdentityError",
    "InvalidTimeError",
    "Lateness",
    "MaintenanceCodecError",
    "MaintenanceError",
    "ModelId",
    "OwnerKind",
    "OwnerRef",
    "PlanId",
    "ProfileId",
    "RunId",
    "StageId",
    "TenantId",
    "UtcTime",
    "Watermark",
    "canonical_digest",
    "canonical_dumps",
    "canonical_json",
    "classify_lateness",
    "compare_identities",
    "require_identical",
    "strict_loads",
    "utc_now",
    # M3/M4 API surface
    "M4_API",
    "CompletenessState",
    "CoherenceReason",
    "CoherenceState",
    "EVIDENCE_PRECEDENCE",
    "EVIDENCE_PRECEDENCE_VERSION",
    "FreshnessState",
    "ObservationEnvelope",
    "SourceVersionVector",
    "eligibility_supported",
    "precedence_rank",
    "ActionTarget",
    "EscalationReference",
    "LeaseCoordinates",
    "OccurrenceCoordinates",
    "OwnerReceipts",
    "PolicyVersionCoordinates",
    "ProducerPrincipal",
    "ProducerRole",
    "RecurrenceReference",
    "RunAuthorityCoordinates",
    "WbcAttemptCoordinates",
    "assert_reference_only_contract",
    "CheckpointVerificationPayload",
    "CheckpointWindowKind",
    "HumanEscalationPayload",
    "InstallationPayload",
    "MaintenanceEvent",
    "OperationalActionKind",
    "OperationalEvent",
    "OperationalPayload",
    "ProgressObservationPayload",
    "RecurrenceLink",
    "RecurrencePayload",
    "RepairRequestPayload",
    "RetriggerPayload",
    "SIX_HOUR_ALIAS",
    "SourceChangePayload",
    "TerminalVerificationPayload",
    "VerifierProvenance",
    "canonical_checkpoint_window",
    "event_digest",
    "occurrence_idempotency_key",
    "operational_event_digest",
    "verified_recurrence",
    "ConformanceAdapter",
    "ConformanceRead",
    "CurrentSourceRead",
    "CustodyAdapter",
    "CustodyRead",
    "NativeManifestAdapter",
    "NativeManifestRead",
    "ProofAdapter",
    "ProofRead",
    "RUNTIME_SOURCE_PATHS",
    "RunAuthorityAdapter",
    "RunAuthorityRead",
    "RuntimeAdapter",
    "RuntimeRead",
    "SourceCursorRef",
    "WbcAdapter",
    "WbcEventRef",
    "WbcRead",
    "read_conformance",
    "read_custody",
    "read_native_manifest",
    "read_proof",
    "read_run_authority",
    "read_runtime",
    "read_wbc_attempt",
    "DEFAULT_MAX_ATTEMPTS",
    "JoinSource",
    "capture_observation",
    "conformance_source",
    "custody_source",
    "native_manifest_source",
    "proof_source",
    "run_authority_source",
    "runtime_source",
    "wbc_source",
    "CANONICAL_CHECKPOINT_ORDER",
    "CHECKPOINT_WINDOW_DELTAS",
    "CheckpointDueItem",
    "checkpoint_window_bounds",
    "completed_checkpoint_windows",
    "due_checkpoints",
    "ExpectedAuthority",
    "NegativeControlResult",
    "VerificationOutcome",
    "VerificationRejectReason",
    "VerificationResult",
    "authoritative_progress_refs",
    "checkpoint_set_complete",
    "evaluate_verification",
    "negative_controls_passed",
    "progress_beyond",
    "required_checkpoint_set",
    "ADAPTER_VERSIONS",
    "ApprovalEvidence",
    "ApprovalState",
    "COMPATIBILITY_FACADE_IDENTITY",
    "FROZEN_FIXTURE_DIGESTS",
    "FROZEN_SCHEMA_DIGESTS",
    "HANDOFF_IDS",
    "HandoffAcceptedEntry",
    "HandoffDriftEntry",
    "HandoffRegistry",
    "HandoffResolution",
    "HandoffResolutionReason",
    "HandoffResolutionState",
    "HandoffRow",
    "M3_VIEW_VERSION",
    "MaintenanceHandoffView",
    "PROJECTION_API_VERSIONS",
    "WbcCoordinates",
    "build_handoff_view",
    "default_handoff_registry",
    "load_handoff_registry",
    "verify_frozen_digests",
    "verify_handoff_drift",
]
