from __future__ import annotations

from vibecomfy.porting.emit.emit_constants import _build_section_groups
from vibecomfy.porting.emit.emit_ready import _subgraph_port_index_for_instance_field
from vibecomfy.porting.emit.emit_subgraph import (
    COMFY_TYPE_TO_PY_HINT,
    READABILITY_WARNING_SUBGRAPH_INPUT_UNBOUND,
    _SubgraphDef,
    _SubgraphPort,
    _apply_subgraph_names_to_prepared,
    _build_subgraph_def,
    _disambiguated_subgraph_slugs,
    _emit_subgraph_call_statement,
    _emit_subgraph_functions,
    _short_subgraph_id_prefix,
    _slugify_identifier,
    _subgraph_call_kwargs,
    _subgraph_default_args,
    _subgraph_definitions_from_raw,
    _subgraph_docstring,
    _subgraph_emitted_node_id,
    _subgraph_input_kwarg_name,
    _subgraph_instance_port_candidate_names,
    _subgraph_instance_widget_values,
    _subgraph_node_id_required,
    _subgraph_result_base,
    _subgraph_return_expr,
    _subgraph_signature,
    _subgraph_topological_order,
    _ui_output_names,
    _unique_port_name,
    _unique_var,
    _widget_default_for_target,
    slugify_subgraph_name,
    subgraph_source_hash,
)

__all__ = [
    "READABILITY_WARNING_SUBGRAPH_INPUT_UNBOUND",
    "_SubgraphPort",
    "_SubgraphDef",
    "_subgraph_port_index_for_instance_field",
    "_build_section_groups",
    "slugify_subgraph_name",
    "_slugify_identifier",
    "_subgraph_input_kwarg_name",
    "_unique_port_name",
    "_subgraph_definitions_from_raw",
    "_disambiguated_subgraph_slugs",
    "_build_subgraph_def",
    "subgraph_source_hash",
    "_subgraph_default_args",
    "_widget_default_for_target",
    "_apply_subgraph_names_to_prepared",
    "_subgraph_result_base",
    "_unique_var",
    "COMFY_TYPE_TO_PY_HINT",
    "_emit_subgraph_functions",
    "_subgraph_topological_order",
    "_short_subgraph_id_prefix",
    "_subgraph_emitted_node_id",
    "_subgraph_node_id_required",
    "_subgraph_signature",
    "_subgraph_docstring",
    "_emit_subgraph_call_statement",
    "_subgraph_call_kwargs",
    "_subgraph_instance_port_candidate_names",
    "_subgraph_instance_widget_values",
    "_ui_output_names",
    "_subgraph_return_expr",
]
