import { chromium } from '@playwright/test';
import { openPanelViaLauncher } from './helpers/panel-open.mjs';
const browser = await chromium.launch();
const page = await browser.newPage({ viewport: { width: 1400, height: 900 } });
const logs = [];
page.on('console', msg => logs.push(`[${msg.type()}] ${msg.text()}`));
page.on('pageerror', err => logs.push(`[pageerror] ${err.message}`));
await page.goto('http://127.0.0.1:8190/', { waitUntil: 'networkidle' });
await page.waitForTimeout(2000);
const root = await openPanelViaLauncher(page, { timeout: 15000 });
console.log('panel opened');
await page.screenshot({ path: '/tmp/vibe_panel_open.png' });
const composer = page.getByRole('textbox', { name: 'Describe the workflow change...' });
await composer.fill('Wire the model output into a SaveImage node', { force: true });
const submitButton = page.getByRole('button', { name: 'Submit', exact: true });
await submitButton.click({ force: true });
console.log('submit clicked');
// Wait up to 10s for any progress / pending / in progress text
await page.waitForTimeout(500);
await page.screenshot({ path: '/tmp/vibe_panel_submit_500ms.png' });
await page.waitForTimeout(2000);
await page.screenshot({ path: '/tmp/vibe_panel_submit_2500ms.png' });
await page.waitForTimeout(5000);
await page.screenshot({ path: '/tmp/vibe_panel_submit_7500ms.png' });
const threadText = await page.locator('[class*="thread"], [class*="chat"], [class*="panel-thread"]').first().innerText({ timeout: 5000 }).catch(() => '');
const panelHtml = await root.innerHTML().catch(() => '');
await (await import('fs')).promises.writeFile('/tmp/vibe_panel_logs.txt', logs.join('\n'));
await (await import('fs')).promises.writeFile('/tmp/vibe_panel_thread_text.txt', threadText);
await (await import('fs')).promises.writeFile('/tmp/vibe_panel_dom.html', panelHtml);
console.log('screenshots saved: /tmp/vibe_panel_open.png, /tmp/vibe_panel_submit_*.png');
console.log('logs /tmp/vibe_panel_logs.txt');
console.log('thread text /tmp/vibe_panel_thread_text.txt');
await browser.close();
