# vibecomfy: manual
# Originally generated by tools/convert_ready_templates.py; now hand-maintained for runtime compatibility.
"""Auto-generated ready_template — see tools/convert_ready_templates.py."""
from __future__ import annotations

from vibecomfy.workflow import VibeWorkflow, WorkflowSource
from vibecomfy.templates import finalize_ready


READY_METADATA = {
    'comfy_core': {'version': '0.18.2', 'tested_at': '2026-05-20T09:19:32.302139+00:00', 'commit': 'f7b38d2eb97207cd834bcc3eb2e8b1d447b96c68', 'status': 'discovered'},'model_assets': [
    {
        'name': 'LTX23_audio_vae_bf16.safetensors',
        'url': 'https://huggingface.co/Kijai/LTX2.3_comfy/resolve/main/vae/LTX23_audio_vae_bf16.safetensors',
        'subdir': 'checkpoints',
    },
],
 'unbound_inputs': {'seed': 4475},
 'ready_template': 'video/ltx2_3_iamccs_audio_extend_low_ram',
 'workflow_template': 'ltx2_3_iamccs_audio_extend_low_ram',
 'capability': 'audio_extended_multisegment_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/iamccs/IAMCCS_LTX23_BEST_3SEG_AUDIOEXT_30S_FREE_LOW_RAM.json',
 'coverage_tier': 'supplemental',
 'approach': 'low-RAM three-segment audio extension',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until '
                        'their custom node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-GGUF', 'ComfyUI-KJNodes', 'ComfyUI-LTXVideo']}


def build() -> VibeWorkflow:
    """Build the workflow (auto-generated)."""
    wf = VibeWorkflow(
        READY_METADATA["ready_template"],
        WorkflowSource(
            id=READY_METADATA["ready_template"],
            path=__file__,
            source_type="ready_template",
        ),
    )

    loadimage = _node(wf, 'LoadImage', '1',
        image='ChatGPT Image Mar 27, 2026, 08_27_32 AM.png',
        widget_1='image',
    )
    vhs_loadaudioupload = _node(wf, 'VHS_LoadAudioUpload', '4')
    unetloadergguf = _node(wf, 'UnetLoaderGGUF', '5',
        widget_0='ltx-2.3-22b-dev-Q4_K_S.gguf',
    )
    dualcliploader = _node(wf, 'DualCLIPLoader', '7',
        clip_name1='gemma_3_12B_it_fp8_e4m3fn.safetensors',
        clip_name2='ltx-2.3_text_projection_bf16.safetensors',
        type='ltxv',
        device='default',
    )
    ksamplerselect = _node(wf, 'KSamplerSelect', '12',
        sampler_name='euler',
    )
    manualsigmas = _node(wf, 'ManualSigmas', '13',
        widget_0='1., 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0',
    )
    vaeloaderkj = _node(wf, 'VAELoaderKJ', '14',
        widget_0='ltx-2.3-22b-dev_video_vae.safetensors',
        widget_1='main_device',
        widget_2='bf16',
    )
    vaeloaderkj_2 = _node(wf, 'LTXVAudioVAELoader', '15',
        ckpt_name='LTX23_audio_vae_bf16.safetensors',
    )
    solidmask = _node(wf, 'SolidMask', '16',
        widget_0=0,
        widget_1=1024,
        widget_2=1024,
    )
    emptyltxvlatentvideo = _node(wf, 'EmptyLTXVLatentVideo', '17',
        width=256,
        height=256,
        length=5,
        batch_size=1,
        widget_0=256,
        widget_1=256,
        widget_2=5,
    )
    randomnoise = _node(wf, 'RandomNoise', '25',
        noise_seed=851629932274714,
        control_after_generate='randomize',
    )
    ltxvpreprocess_2 = _node(wf, 'LTXVPreprocess', '31',
        widget_0=33,
    )
    emptyltxvlatentvideo_2 = _node(wf, 'EmptyLTXVLatentVideo', '32',
        width=256,
        height=256,
        length=5,
        batch_size=1,
        widget_0=256,
        widget_1=256,
        widget_2=5,
    )
    randomnoise_2 = _node(wf, 'RandomNoise', '39',
        noise_seed=264060544821466,
        control_after_generate='randomize',
    )
    ltxvpreprocess_3 = _node(wf, 'LTXVPreprocess', '45',
        widget_0=33,
    )
    emptyltxvlatentvideo_3 = _node(wf, 'EmptyLTXVLatentVideo', '46',
        width=256,
        height=256,
        length=5,
        batch_size=1,
        widget_0=256,
        widget_1=256,
        widget_2=5,
    )
    randomnoise_3 = _node(wf, 'RandomNoise', '53',
        noise_seed=606399719654025,
        control_after_generate='randomize',
    )
    unetloader = _node(wf, 'UNETLoader', '77',
        unet_name='MelBandRoformer_fp32.safetensors',
        weight_dtype='default',
    )
    resizeimagemasknode = _node(wf, 'ResizeImageMaskNode', '2',
        widget_0='scale dimensions',
        widget_1=256,
        widget_2=1080,
        widget_3='center',
        widget_4='lanczos',
        input=loadimage.out(0),
    )
    loraloadermodelonly = _node(wf, 'LoraLoaderModelOnly', '6',
        lora_name='ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors',
        strength_model=0.7,
        model=unetloadergguf.out(0),
    )
    cliptextencode = _node(wf, 'CLIPTextEncode', '8',
        text='cinematic image to video shot of a singer actor acting and singing a song during a musical, intense expression, coherent motion, smooth camera movement, high detail, stable composition, audio-reactive motion',
        clip=dualcliploader.out(0),
    )
    cliptextencode_2 = _node(wf, 'CLIPTextEncode', '9',
        text='flicker, jitter, low quality, bad anatomy, static image, frozen frame, deformed motion',
        clip=dualcliploader.out(0),
    )
    iamccs_audioextensionmath = _node(wf, 'IAMCCS_AudioExtensionMath', '20',
        widget_0=24,
        widget_1=0,
        widget_2=240,
        widget_3=240,
        widget_4=True,
        widget_5=240,
        widget_6=0,
        audio=vhs_loadaudioupload.out(0),
    )
    resizeimagesbylongeredge = _node(wf, 'ResizeImagesByLongerEdge', '3',
        widget_0=1536,
        images=resizeimagemasknode.out(0),
    )
    ltxvconditioning = _node(wf, 'LTXVConditioning', '10',
        widget_0=8,
        negative=cliptextencode_2.out(0),
        positive=cliptextencode.out(0),
    )
    iamccs_audioextender = _node(wf, 'IAMCCS_AudioExtender', '21',
        widget_0=24,
        widget_1='left_context_only',
        widget_10=240,
        widget_11=240,
        widget_12=0,
        widget_13=0,
        widget_14=240,
        widget_15=240,
        widget_2=0.5,
        widget_3=0,
        widget_4='use_timeline_cursor',
        widget_5='snap_to_video_duration',
        widget_6='soft_clamp',
        widget_7=0,
        widget_8=10,
        widget_9=240,
        audio=vhs_loadaudioupload.out(0),
        effective_unique_frames=iamccs_audioextensionmath.out(3),
        segment_start_frames=iamccs_audioextensionmath.out(1),
    )
    iamccs_audiotimelinegate = _node(wf, 'IAMCCS_AudioTimelineGate', '30',
        widget_0=1,
        widget_1=True,
        widget_2=1,
        widget_3=True,
        widget_4=0,
        widget_5=0,
        cursor_frames_out=iamccs_audioextensionmath.out(0),
        effective_unique_frames=iamccs_audioextensionmath.out(3),
        is_last_segment=iamccs_audioextensionmath.out(8),
        remaining_frames_after=iamccs_audioextensionmath.out(7),
    )
    cfgguider = _node(wf, 'CFGGuider', '11',
        cfg=2.5,
        model=loraloadermodelonly.out(0),
        negative=ltxvconditioning.out(1),
        positive=ltxvconditioning.out(0),
    )
    ltxvpreprocess = _node(wf, 'LTXVPreprocess', '18',
        widget_0=33,
        image=resizeimagesbylongeredge.out(0),
    )
    ltxvaudiovaeencode = _node(wf, 'LTXVAudioVAEEncode', '22',
        audio=iamccs_audioextender.out(0),
        audio_vae=vaeloaderkj_2.out(0),
    )
    iamccs_audioextensionmath_2 = _node(wf, 'IAMCCS_AudioExtensionMath', '34',
        widget_0=24,
        widget_1=1,
        widget_2=249,
        widget_3=240,
        widget_4=True,
        widget_5=240,
        widget_6=0,
        audio=vhs_loadaudioupload.out(0),
        cursor_frames_in=iamccs_audiotimelinegate.out(3),
    )
    ltxvimgtovideoinplace = _node(wf, 'LTXVImgToVideoInplace', '19',
        widget_0=1,
        widget_1=False,
        image=ltxvpreprocess.out(0),
        latent=emptyltxvlatentvideo.out(0),
        vae=vaeloaderkj.out(0),
    )
    setlatentnoisemask = _node(wf, 'SetLatentNoiseMask', '23',
        mask=solidmask.out(0),
        samples=ltxvaudiovaeencode.out(0),
    )
    iamccs_audioextender_2 = _node(wf, 'IAMCCS_AudioExtender', '35',
        widget_0=24,
        widget_1='left_context_only',
        widget_10=249,
        widget_11=240,
        widget_12=0,
        widget_13=240,
        widget_14=240,
        widget_15=240,
        widget_2=0.5,
        widget_3=0,
        widget_4='use_timeline_cursor',
        widget_5='snap_to_video_duration',
        widget_6='soft_clamp',
        widget_7=1,
        widget_8=10,
        widget_9=240,
        audio=vhs_loadaudioupload.out(0),
        effective_unique_frames=iamccs_audioextensionmath_2.out(3),
        segment_start_frames=iamccs_audioextensionmath_2.out(1),
    )
    iamccs_audiotimelinegate_2 = _node(wf, 'IAMCCS_AudioTimelineGate', '44',
        widget_0=1,
        widget_1=True,
        widget_2=1,
        widget_3=True,
        widget_4=0,
        widget_5=0,
        cursor_frames_out=iamccs_audioextensionmath_2.out(0),
        effective_unique_frames=iamccs_audioextensionmath_2.out(3),
        is_last_segment=iamccs_audioextensionmath_2.out(8),
        remaining_frames_after=iamccs_audioextensionmath_2.out(7),
    )
    ltxvconcatavlatent = _node(wf, 'LTXVConcatAVLatent', '24',
        audio_latent=setlatentnoisemask.out(0),
        video_latent=ltxvimgtovideoinplace.out(0),
    )
    ltxvaudiovaeencode_2 = _node(wf, 'LTXVAudioVAEEncode', '36',
        audio=iamccs_audioextender_2.out(0),
        audio_vae=vaeloaderkj_2.out(0),
    )
    iamccs_audioextensionmath_3 = _node(wf, 'IAMCCS_AudioExtensionMath', '48',
        widget_0=24,
        widget_1=2,
        widget_2=249,
        widget_3=240,
        widget_4=True,
        widget_5=240,
        widget_6=0,
        audio=vhs_loadaudioupload.out(0),
        cursor_frames_in=iamccs_audiotimelinegate_2.out(3),
    )
    samplercustomadvanced = _node(wf, 'SamplerCustomAdvanced', '26',
        guider=cfgguider.out(0),
        latent_image=ltxvconcatavlatent.out(0),
        noise=randomnoise.out(0),
        sampler=ksamplerselect.out(0),
        sigmas=manualsigmas.out(0),
    )
    setlatentnoisemask_2 = _node(wf, 'SetLatentNoiseMask', '37',
        mask=solidmask.out(0),
        samples=ltxvaudiovaeencode_2.out(0),
    )
    iamccs_audioextender_3 = _node(wf, 'IAMCCS_AudioExtender', '49',
        widget_0=24,
        widget_1='left_context_only',
        widget_10=249,
        widget_11=240,
        widget_12=0,
        widget_13=480,
        widget_14=240,
        widget_15=240,
        widget_2=0.5,
        widget_3=0,
        widget_4='use_timeline_cursor',
        widget_5='snap_to_video_duration',
        widget_6='soft_clamp',
        widget_7=2,
        widget_8=10,
        widget_9=240,
        audio=vhs_loadaudioupload.out(0),
        effective_unique_frames=iamccs_audioextensionmath_3.out(3),
        segment_start_frames=iamccs_audioextensionmath_3.out(1),
    )
    iamccs_audiotimelinegate_3 = _node(wf, 'IAMCCS_AudioTimelineGate', '58',
        widget_0=1,
        widget_1=True,
        widget_2=1,
        widget_3=True,
        widget_4=0,
        widget_5=0,
        cursor_frames_out=iamccs_audioextensionmath_3.out(0),
        effective_unique_frames=iamccs_audioextensionmath_3.out(3),
        is_last_segment=iamccs_audioextensionmath_3.out(8),
        remaining_frames_after=iamccs_audioextensionmath_3.out(7),
    )
    ltxvseparateavlatent = _node(wf, 'LTXVSeparateAVLatent', '27',
        av_latent=samplercustomadvanced.out(0),
    )
    ltxvaudiovaeencode_3 = _node(wf, 'LTXVAudioVAEEncode', '50',
        audio=iamccs_audioextender_3.out(0),
        audio_vae=vaeloaderkj_2.out(0),
    )
    setlatentnoisemask_3 = _node(wf, 'SetLatentNoiseMask', '51',
        mask=solidmask.out(0),
        samples=ltxvaudiovaeencode_3.out(0),
    )
    iamccs_vaedecodetodisk = _node(wf, 'IAMCCS_VAEDecodeToDisk', '60',
        widget_0='iamccs_vae_frames/30s_free_low_ram/seg0',
        widget_1='seg0',
        widget_10=True,
        widget_2='jpg',
        widget_3=95,
        widget_4=True,
        widget_5='auto',
        widget_6=512,
        widget_7=64,
        widget_8=True,
        widget_9='iamccs_seam_debug',
        samples=ltxvseparateavlatent.out(0),
        vae=vaeloaderkj.out(0),
    )
    iamccs_ltx2_extensionmodule_disk = _node(wf, 'IAMCCS_LTX2_ExtensionModule_Disk', '29',
        widget_0='iamccs_vae_frames/30s_free_low_ram/seg0',
        widget_1='iamccs_extension_disk/30s_free_low_ram/seg0_extended',
        widget_10='videoclip_audio_24fps',
        widget_11='',
        widget_12=1,
        widget_2='iamccs_extension_disk/30s_free_low_ram/seg0_start',
        widget_3=9,
        widget_4='source',
        widget_5='cut',
        widget_6=True,
        widget_7='none',
        widget_8='native_workflow_safe',
        widget_9='none',
        source_dir=iamccs_vaedecodetodisk.out(0),
    )
    iamccs_startdirtovideolatent = _node(wf, 'IAMCCS_StartDirToVideoLatent', '33',
        widget_0='iamccs_extension_disk/30s_free_low_ram/seg0_start',
        widget_1='all',
        widget_2=9,
        widget_3=0,
        widget_4=1,
        widget_5=True,
        widget_6=33,
        latent=emptyltxvlatentvideo_2.out(0),
        start_dir=iamccs_ltx2_extensionmodule_disk.out(1),
        vae=vaeloaderkj.out(0),
    )
    ltxvconcatavlatent_2 = _node(wf, 'LTXVConcatAVLatent', '38',
        audio_latent=setlatentnoisemask_2.out(0),
        video_latent=iamccs_startdirtovideolatent.out(0),
    )
    samplercustomadvanced_2 = _node(wf, 'SamplerCustomAdvanced', '40',
        guider=cfgguider.out(0),
        latent_image=ltxvconcatavlatent_2.out(0),
        noise=randomnoise_2.out(0),
        sampler=ksamplerselect.out(0),
        sigmas=manualsigmas.out(0),
    )
    ltxvseparateavlatent_2 = _node(wf, 'LTXVSeparateAVLatent', '41',
        av_latent=samplercustomadvanced_2.out(0),
    )
    iamccs_vaedecodetodisk_2 = _node(wf, 'IAMCCS_VAEDecodeToDisk', '61',
        widget_0='iamccs_vae_frames/30s_free_low_ram/seg1',
        widget_1='seg1',
        widget_10=True,
        widget_2='jpg',
        widget_3=95,
        widget_4=True,
        widget_5='auto',
        widget_6=512,
        widget_7=64,
        widget_8=True,
        widget_9='iamccs_seam_debug',
        samples=ltxvseparateavlatent_2.out(0),
        vae=vaeloaderkj.out(0),
    )
    iamccs_ltx2_extensionmodule_disk_2 = _node(wf, 'IAMCCS_LTX2_ExtensionModule_Disk', '43',
        widget_0='iamccs_vae_frames/30s_free_low_ram/seg0',
        widget_1='iamccs_extension_disk/30s_free_low_ram/seg1_extended',
        widget_10='videoclip_audio_24fps',
        widget_11='',
        widget_12=0,
        widget_2='iamccs_extension_disk/30s_free_low_ram/seg1_start',
        widget_3=9,
        widget_4='source',
        widget_5='cut',
        widget_6=True,
        widget_7='none',
        widget_8='native_workflow_safe',
        widget_9='none',
        new_dir=iamccs_vaedecodetodisk_2.out(0),
        source_dir=iamccs_ltx2_extensionmodule_disk.out(0),
    )
    iamccs_startdirtovideolatent_2 = _node(wf, 'IAMCCS_StartDirToVideoLatent', '47',
        widget_0='iamccs_extension_disk/30s_free_low_ram/seg1_start',
        widget_1='all',
        widget_2=9,
        widget_3=0,
        widget_4=1,
        widget_5=True,
        widget_6=33,
        latent=emptyltxvlatentvideo_3.out(0),
        start_dir=iamccs_ltx2_extensionmodule_disk_2.out(1),
        vae=vaeloaderkj.out(0),
    )
    ltxvconcatavlatent_3 = _node(wf, 'LTXVConcatAVLatent', '52',
        audio_latent=setlatentnoisemask_3.out(0),
        video_latent=iamccs_startdirtovideolatent_2.out(0),
    )
    samplercustomadvanced_3 = _node(wf, 'SamplerCustomAdvanced', '54',
        guider=cfgguider.out(0),
        latent_image=ltxvconcatavlatent_3.out(0),
        noise=randomnoise_3.out(0),
        sampler=ksamplerselect.out(0),
        sigmas=manualsigmas.out(0),
    )
    ltxvseparateavlatent_3 = _node(wf, 'LTXVSeparateAVLatent', '55',
        av_latent=samplercustomadvanced_3.out(0),
    )
    iamccs_vaedecodetodisk_3 = _node(wf, 'IAMCCS_VAEDecodeToDisk', '62',
        widget_0='iamccs_vae_frames/30s_free_low_ram/seg2',
        widget_1='seg2',
        widget_10=True,
        widget_2='jpg',
        widget_3=95,
        widget_4=True,
        widget_5='auto',
        widget_6=512,
        widget_7=64,
        widget_8=True,
        widget_9='iamccs_seam_debug',
        samples=ltxvseparateavlatent_3.out(0),
        vae=vaeloaderkj.out(0),
    )
    iamccs_ltx2_extensionmodule_disk_3 = _node(wf, 'IAMCCS_LTX2_ExtensionModule_Disk', '57',
        widget_0='iamccs_vae_frames/30s_free_low_ram/seg0',
        widget_1='iamccs_extension_disk/30s_free_low_ram/final_extended',
        widget_10='videoclip_audio_24fps',
        widget_11='',
        widget_12=1,
        widget_2='iamccs_extension_disk/30s_free_low_ram/final_start',
        widget_3=9,
        widget_4='source',
        widget_5='cut',
        widget_6=True,
        widget_7='none',
        widget_8='native_workflow_safe',
        widget_9='none',
        new_dir=iamccs_vaedecodetodisk_3.out(0),
        source_dir=iamccs_ltx2_extensionmodule_disk_2.out(0),
    )
    iamccs_videocombinefromdir = _node(wf, 'IAMCCS_VideoCombineFromDir', '59',
        widget_0='iamccs_extension_disk/30s_free_low_ram/final_extended',
        widget_1=24,
        widget_2='IAMCCS/LTX23_BEST_3SEG_AUDIOEXT_30S_FREE_LOW_RAM',
        widget_3=19,
        widget_4='yuv420p',
        widget_5=True,
        audio=vhs_loadaudioupload.out(0),
        frames_dir=iamccs_ltx2_extensionmodule_disk_3.out(0),
    )

    finalize_ready(wf, READY_METADATA, source_path=__file__, requirements=READY_REQUIREMENTS)
    return wf


def _node(wf: VibeWorkflow, class_type: str, _id: str, _extras: dict | None = None, **kwargs):
    """Create a node, preserving the original node id from the source workflow.

    `_extras` carries kwargs whose names are not valid Python identifiers
    (e.g. "resize_type.multiple") which Python disallows as kwarg syntax.
    They are applied to the new node post-construction.
    """
    from vibecomfy.handles import Handle
    builder = wf.node(class_type, **kwargs)
    if _extras:
        for key, value in _extras.items():
            if isinstance(value, Handle):
                wf.connect(value, f"{builder.node.id}.{key}")
            else:
                builder.node.inputs[key] = value
    if builder.node.id != _id:
        old_id = builder.node.id
        node = wf.nodes.pop(old_id)
        node.id = _id
        wf.nodes[_id] = node
        for edge in wf.edges:
            if edge.to_node == old_id:
                edge.to_node = _id
            if edge.from_node == old_id:
                edge.from_node = _id
    return builder
