from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'5188': {'class_type': 'LowVRAMAudioVAELoader', 'inputs': {'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors'}},
 '5178': {'class_type': 'LTXVGemmaCLIPModelLoader',
          'inputs': {'widget_0': 'gemma_3_12B_it_fp8_e4m3fn.safetensors',
                     'widget_1': 'ltx-2-19b-distilled.safetensors',
                     'widget_2': 1024}},
 '5176': {'class_type': 'CheckpointLoaderSimple', 'inputs': {'widget_0': 'ltx-2-19b-distilled.safetensors'}},
 '5263': {'class_type': 'Any Switch (rgthree)', 'inputs': {'any_01': ['5176', 2], 'any_02': ['5220', 0]}},
 '5262': {'class_type': 'Any Switch (rgthree)', 'inputs': {'any_01': ['5178', 0], 'any_02': ['5222', 0]}},
 '5261': {'class_type': 'Any Switch (rgthree)', 'inputs': {'any_01': ['5188', 0], 'any_02': ['5221', 0]}},
 '5264': {'class_type': 'Any Switch (rgthree)', 'inputs': {'any_01': ['5259', 0], 'any_02': ['9685', 0]}},
 '5173': {'class_type': 'LTXVConditioning',
          'inputs': {'widget_0': 8, 'positive': ['5174', 0], 'negative': ['5174', 0], 'frame_rate': ['5225', 1]}},
 '5174': {'class_type': 'CLIPTextEncode', 'inputs': {'widget_0': '', 'clip': ['5262', 0], 'text': ['5175', 0]}},
 '5234': {'class_type': 'LTXVConditioning',
          'inputs': {'widget_0': 8, 'positive': ['5233', 0], 'negative': ['5233', 0], 'frame_rate': ['5225', 1]}},
 '5233': {'class_type': 'CLIPTextEncode', 'inputs': {'widget_0': '', 'clip': ['5262', 0], 'text': ['5232', 0]}},
 '9003': {'class_type': 'LTXVConditioning',
          'inputs': {'widget_0': 8, 'positive': ['9002', 0], 'negative': ['9002', 0], 'frame_rate': ['5225', 1]}},
 '9002': {'class_type': 'CLIPTextEncode', 'inputs': {'widget_0': '', 'clip': ['5262', 0], 'text': ['9001', 0]}},
 '9005': {'class_type': 'CreateVideo',
          'inputs': {'fps': ['5225', 1], 'widget_0': 8, 'images': ['9004', 0], 'audio': ['9004', 1]}},
 '5236': {'class_type': 'CreateVideo',
          'inputs': {'fps': ['5225', 1], 'widget_0': 8, 'images': ['5235', 0], 'audio': ['5235', 1]}},
 '5190': {'class_type': 'CreateVideo',
          'inputs': {'fps': ['5225', 1], 'widget_0': 8, 'images': ['5189', 0], 'audio': ['5189', 1]}},
 '5252': {'class_type': 'AudioConcat', 'inputs': {'widget_0': 'after', 'audio1': ['5189', 1], 'audio2': ['5235', 1]}},
 '9008': {'class_type': 'AudioConcat', 'inputs': {'widget_0': 'after', 'audio1': ['5252', 0], 'audio2': ['9004', 1]}},
 '5254': {'class_type': 'CreateVideo',
          'inputs': {'fps': ['5225', 1], 'widget_0': 8, 'images': ['9016', 2], 'audio': ['9008', 0]}},
 '5258': {'class_type': 'Any Switch (rgthree)', 'inputs': {'any_01': ['5259', 0], 'any_02': ['9684', 0]}},
 '5259': {'class_type': 'IAMCCS_LTX2_LoRAStackModelIO',
          'inputs': {'widget_0': 'ltx-2-19b-distilled-lora-384.safetensors',
                     'widget_1': 1,
                     'widget_2': 'no',
                     'widget_3': 0,
                     'widget_4': 'no',
                     'widget_5': 0,
                     'model': ['5176', 0]}},
 '9016': {'class_type': 'IAMCCS_LTX2_ExtensionModule',
          'inputs': {'widget_0': 10,
                     'widget_1': 'source',
                     'widget_2': 'linear_blend',
                     'widget_3': True,
                     'widget_4': 'a-1',
                     'widget_5': 'none',
                     'widget_6': 'none',
                     'widget_7': 'none',
                     'widget_8': 0,
                     'widget_9': 8,
                     'widget_10': 'none',
                     'widget_11': 0,
                     'widget_12': 1,
                     'widget_13': 0.5,
                     'widget_14': 'target_extension_ltx2',
                     'widget_15': 1,
                     'source_images': ['9015', 2],
                     'new_images': ['9004', 0]}},
 '9014': {'class_type': 'IAMCCS_LTX2_GetImageFromBatch',
          'inputs': {'widget_0': 'from_end',
                     'widget_1': 10,
                     'widget_2': 'none',
                     'widget_3': 'none',
                     'widget_4': 'none',
                     'widget_5': 'native_workflow_safe',
                     'widget_6': 10,
                     'widget_7': 0,
                     'widget_8': 10,
                     'images': ['5189', 0]}},
 '5180': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'z-image_00255_.png', 'widget_1': 'image'}},
 '5215': {'class_type': 'UnetLoaderGGUF', 'inputs': {'widget_0': 'LTX-2-dev-Q5_K_S.gguf'}},
 '9685': {'class_type': 'IAMCCS_GGUF_accelerator',
          'inputs': {'widget_0': True,
                     'widget_1': True,
                     'widget_2': True,
                     'widget_3': 1500,
                     'widget_4': True,
                     'widget_5': 'all_or_nothing',
                     'widget_6': 1024,
                     'model': ['5219', 1]}},
 '5221': {'class_type': 'VAELoaderKJ',
          'inputs': {'widget_0': 'LTX2_audio_vae_bf16.safetensors', 'widget_1': 'main_device', 'widget_2': 'bf16'}},
 '5220': {'class_type': 'VAELoaderKJ',
          'inputs': {'widget_0': 'LTX2_video_vae_2_bf16.safetensors', 'widget_1': 'main_device', 'widget_2': 'bf16'}},
 '5219': {'class_type': 'IAMCCS_ModelWithLoRA_LTX2_Staged',
          'inputs': {'model': ['5215', 0],
                     'lora_stage1': ['5218', 0],
                     'lora_stage2': ['5218', 1],
                     'model_stage2': ['5215', 0]}},
 '5218': {'class_type': 'IAMCCS_LTX2_LoRAStackStaged',
          'inputs': {'widget_0': 'ltx-2-19b-distilled-lora-384.safetensors',
                     'widget_1': 1,
                     'widget_2': 1,
                     'widget_3': 'ltx-2-19b-lora-camera-control-dolly-right.safetensors',
                     'widget_4': 0,
                     'widget_5': 0,
                     'widget_6': 'no',
                     'widget_7': 0,
                     'widget_8': 0}},
 '5265': {'class_type': 'Fast Groups Muter (rgthree)', 'inputs': {}},
 '5222': {'class_type': 'DualCLIPLoader',
          'inputs': {'widget_0': 'gemma_3_12B_it_fp8_e4m3fn.safetensors',
                     'widget_1': 'ltx-2-19b-embeddings_connector_dev_bf16.safetensors',
                     'widget_2': 'ltxv',
                     'widget_3': 'default'}},
 '9026': {'class_type': 'IAMCCS_AutoLinkArguments',
          'inputs': {'widget_0': False,
                     'widget_1': False,
                     'widget_2': False,
                     'widget_3': True,
                     'widget_4': 'None',
                     'widget_5': '',
                     'widget_6': 'TopToDown',
                     'widget_7': 'AvoidAll',
                     'widget_8': '',
                     'widget_9': True,
                     'widget_10': 'Red',
                     'widget_11': 'Orange',
                     'widget_12': 'Black',
                     'widget_13': '',
                     'widget_14': '',
                     'widget_15': 'both',
                     'widget_17': '',
                     'widget_19': ''}},
 '5210': {'class_type': 'LatentUpscaleModelLoader',
          'inputs': {'widget_0': 'ltx-2-spatial-upscaler-x2-1.0.safetensors'}},
 '5225': {'class_type': 'IAMCCS_LTX2_FrameRateSync', 'inputs': {'widget_0': 24, 'widget_1': 'fixed'}},
 '10955': {'class_type': 'EmptyImage', 'inputs': {'widget_0': 1332, 'widget_1': 720, 'widget_2': 1, 'widget_3': 0}},
 '10956': {'class_type': 'IAMCCS_LTX2_TimeFrameCount',
           'inputs': {'widget_0': 10, 'widget_1': 241, 'widget_2': 'fixed'}},
 '9006': {'class_type': 'SaveVideo',
          'inputs': {'widget_0': 'output', 'widget_1': 'mp4', 'widget_2': 'h264', 'video': ['9005', 0]}},
 '9684': {'class_type': 'IAMCCS_GGUF_accelerator',
          'inputs': {'widget_0': True,
                     'widget_1': True,
                     'widget_2': True,
                     'widget_3': 1500,
                     'widget_4': True,
                     'widget_5': 'all_or_nothing',
                     'widget_6': 1024,
                     'model': ['5219', 1]}},
 '4958': {'class_type': 'SaveVideo',
          'inputs': {'widget_0': 'output', 'widget_1': 'mp4', 'widget_2': 'h264', 'video': ['5190', 0]}},
 '5237': {'class_type': 'SaveVideo',
          'inputs': {'widget_0': 'output', 'widget_1': 'mp4', 'widget_2': 'h264', 'video': ['5236', 0]}},
 '5235': {'class_type': '8b36a85a-087e-4ee5-85ca-cccc69c5c5d0',
          'inputs': {'widget_0': 121,
                     'widget_1': 24,
                     'widget_2': 0.6,
                     'widget_3': 43,
                     'model_1': ['5258', 0],
                     'model': ['5264', 0],
                     'upscale_model_1': ['5210', 0],
                     'positive': ['5234', 0],
                     'negative': ['5234', 1],
                     'images': ['9014', 0],
                     'vae': ['5263', 0],
                     'audio_vae': ['5261', 0],
                     'image_1': ['10955', 0],
                     'length': ['10956', 0],
                     'frame_rate': ['5225', 0]}},
 '9004': {'class_type': '8b36a85a-087e-4ee5-85ca-cccc69c5c5d0',
          'inputs': {'widget_0': 121,
                     'widget_1': 24,
                     'widget_2': 0.6,
                     'widget_3': 43,
                     'model_1': ['5258', 0],
                     'model': ['5264', 0],
                     'upscale_model_1': ['5210', 0],
                     'positive': ['9003', 0],
                     'negative': ['9003', 1],
                     'images': ['9015', 1],
                     'vae': ['5263', 0],
                     'audio_vae': ['5261', 0],
                     'image_1': ['10955', 0],
                     'length': ['10956', 0],
                     'frame_rate': ['5225', 0]}},
 '5189': {'class_type': '3eaa20c4-5842-4fe4-87df-c0a7e83a6a78',
          'inputs': {'widget_0': 121,
                     'widget_1': 25,
                     'widget_2': 0.6,
                     'widget_3': 43,
                     'model_1': ['5258', 0],
                     'model': ['5264', 0],
                     'upscale_model_1': ['5210', 0],
                     'positive': ['5173', 0],
                     'negative': ['5173', 1],
                     'images': ['5180', 0],
                     'vae': ['5263', 0],
                     'audio_vae': ['5261', 0],
                     'image_1': ['10955', 0],
                     'length': ['10956', 0],
                     'frame_rate': ['5225', 0]}},
 '5232': {'class_type': 'PrimitiveStringMultiline',
          'inputs': {'widget_0': 'man runs away from camera. the camera cranes up and show him run into the distance '
                                 'down the street at a busy New York night.'}},
 '5175': {'class_type': 'PrimitiveStringMultiline',
          'inputs': {'widget_0': 'Cinematic action packed shot. the man says silently: "We need to run." the camera '
                                 'zooms in on his mouth then immediately screams: "NOW!". the camera zooms back out, '
                                 'he turns around, and starts running away, the camera tracks his run in hand held '
                                 'style.'}},
 '9001': {'class_type': 'PrimitiveStringMultiline',
          'inputs': {'widget_0': 'the camera cranes up and show the whole streets of new york.'}},
 '9025': {'class_type': 'IAMCCS_AutoLinkConverter', 'inputs': {'arg': ['9026', 0]}},
 '9015': {'class_type': 'IAMCCS_LTX2_ExtensionModule',
          'inputs': {'widget_0': 10,
                     'widget_1': 'source',
                     'widget_2': 'linear_blend',
                     'widget_3': True,
                     'widget_4': 'a-1',
                     'widget_5': 'none',
                     'widget_6': 'none',
                     'widget_7': 'none',
                     'widget_8': 0,
                     'widget_9': 8,
                     'widget_10': 'none',
                     'widget_11': 0,
                     'widget_12': 1,
                     'widget_13': 0.5,
                     'widget_14': 'target_extension_ltx2',
                     'widget_15': 1,
                     'source_images': ['5189', 0],
                     'new_images': ['5235', 0]}},
 '5255': {'class_type': 'SaveVideo',
          'inputs': {'widget_0': 'output', 'widget_1': 'mp4', 'widget_2': 'h264', 'video': ['5254', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 3154},
 'ready_template': 'video/ltx2_3_iamccs_long_i2v',
 'workflow_template': 'ltx2_3_iamccs_long_i2v',
 'capability': 'long_image_to_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/iamccs/IAMCCS_LTX2_I2V_LONG_LENGTH.json',
 'coverage_tier': 'supplemental',
 'approach': 'long low-VRAM image-to-video',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until their custom '
                        'node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-GGUF', 'ComfyUI-KJNodes', 'ComfyUI-LTXVideo']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/ltx2_3_iamccs_long_i2v"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
