from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'3': {'class_type': 'ResizeImagesByLongerEdge', 'inputs': {'widget_0': 1536, 'images': ['2', 0]}},
 '18': {'class_type': 'LTXVPreprocess', 'inputs': {'widget_0': 33, 'image': ['3', 0]}},
 '19': {'class_type': 'LTXVImgToVideoInplace',
        'inputs': {'widget_0': 1, 'widget_1': False, 'vae': ['14', 0], 'image': ['18', 0], 'latent': ['17', 0]}},
 '22': {'class_type': 'LTXVAudioVAEEncode', 'inputs': {'audio': ['21', 0], 'audio_vae': ['15', 0]}},
 '23': {'class_type': 'SetLatentNoiseMask', 'inputs': {'samples': ['22', 0], 'mask': ['16', 0]}},
 '26': {'class_type': 'SamplerCustomAdvanced',
        'inputs': {'noise': ['25', 0],
                   'guider': ['11', 0],
                   'sampler': ['12', 0],
                   'sigmas': ['13', 0],
                   'latent_image': ['24', 0]}},
 '50': {'class_type': 'LTXVAudioVAEEncode', 'inputs': {'audio': ['49', 0], 'audio_vae': ['15', 0]}},
 '27': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['26', 0]}},
 '41': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['40', 0]}},
 '40': {'class_type': 'SamplerCustomAdvanced',
        'inputs': {'noise': ['39', 0],
                   'guider': ['11', 0],
                   'sampler': ['12', 0],
                   'sigmas': ['13', 0],
                   'latent_image': ['38', 0]}},
 '38': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['33', 0], 'audio_latent': ['37', 0]}},
 '37': {'class_type': 'SetLatentNoiseMask', 'inputs': {'samples': ['36', 0], 'mask': ['16', 0]}},
 '36': {'class_type': 'LTXVAudioVAEEncode', 'inputs': {'audio': ['35', 0], 'audio_vae': ['15', 0]}},
 '31': {'class_type': 'LTXVPreprocess', 'inputs': {'widget_0': 33}},
 '39': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 264060544821466, 'widget_1': 'randomize'}},
 '6': {'class_type': 'LoraLoaderModelOnly',
       'inputs': {'widget_0': 'ltx-2.3-22b-distilled-lora-dynamic_fro09_avg_rank_105_bf16.safetensors',
                  'widget_1': 0.7,
                  'model': ['5', 0]}},
 '7': {'class_type': 'DualCLIPLoader',
       'inputs': {'widget_0': 'gemma_3_12B_it_fp8_e4m3fn.safetensors',
                  'widget_1': 'ltx-2.3_text_projection_bf16.safetensors',
                  'widget_2': 'ltxv',
                  'widget_3': 'default'}},
 '14': {'class_type': 'VAELoaderKJ',
        'inputs': {'widget_0': 'ltx-2.3-22b-dev_video_vae.safetensors', 'widget_1': 'main_device', 'widget_2': 'bf16'}},
 '15': {'class_type': 'VAELoaderKJ',
        'inputs': {'widget_0': 'ltx-2.3-22b-dev_audio_vae.safetensors', 'widget_1': 'main_device', 'widget_2': 'bf16'}},
 '10': {'class_type': 'LTXVConditioning', 'inputs': {'widget_0': 8, 'positive': ['8', 0], 'negative': ['9', 0]}},
 '9': {'class_type': 'CLIPTextEncode',
       'inputs': {'widget_0': 'flicker, jitter, low quality, bad anatomy, static image, frozen frame, deformed motion',
                  'clip': ['7', 0]}},
 '16': {'class_type': 'SolidMask', 'inputs': {'widget_0': 0, 'widget_1': 1024, 'widget_2': 1024}},
 '25': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 851629932274714, 'widget_1': 'randomize'}},
 '11': {'class_type': 'CFGGuider',
        'inputs': {'widget_0': 2.5, 'model': ['6', 0], 'positive': ['10', 0], 'negative': ['10', 1]}},
 '13': {'class_type': 'ManualSigmas',
        'inputs': {'widget_0': '1., 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0'}},
 '12': {'class_type': 'KSamplerSelect', 'inputs': {'widget_0': 'euler'}},
 '51': {'class_type': 'SetLatentNoiseMask', 'inputs': {'samples': ['50', 0], 'mask': ['16', 0]}},
 '52': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['47', 0], 'audio_latent': ['51', 0]}},
 '54': {'class_type': 'SamplerCustomAdvanced',
        'inputs': {'noise': ['53', 0],
                   'guider': ['11', 0],
                   'sampler': ['12', 0],
                   'sigmas': ['13', 0],
                   'latent_image': ['52', 0]}},
 '55': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['54', 0]}},
 '20': {'class_type': 'IAMCCS_AudioExtensionMath',
        'inputs': {'widget_0': 24,
                   'widget_1': 0,
                   'widget_2': 240,
                   'widget_3': 240,
                   'widget_4': True,
                   'widget_5': 240,
                   'widget_6': 0,
                   'audio': ['4', 0]}},
 '30': {'class_type': 'IAMCCS_AudioTimelineGate',
        'inputs': {'widget_0': 1,
                   'widget_1': True,
                   'widget_2': 1,
                   'widget_3': True,
                   'widget_4': 0,
                   'widget_5': 0,
                   'remaining_frames_after': ['20', 7],
                   'effective_unique_frames': ['20', 3],
                   'is_last_segment': ['20', 8],
                   'cursor_frames_out': ['20', 0]}},
 '21': {'class_type': 'IAMCCS_AudioExtender',
        'inputs': {'widget_0': 24,
                   'widget_1': 'left_context_only',
                   'widget_2': 0.5,
                   'widget_3': 0,
                   'widget_4': 'use_timeline_cursor',
                   'widget_5': 'snap_to_video_duration',
                   'widget_6': 'soft_clamp',
                   'widget_7': 0,
                   'widget_8': 10,
                   'widget_9': 240,
                   'widget_10': 240,
                   'widget_11': 240,
                   'widget_12': 0,
                   'widget_13': 0,
                   'widget_14': 240,
                   'widget_15': 240,
                   'audio': ['4', 0],
                   'segment_start_frames': ['20', 1],
                   'effective_unique_frames': ['20', 3]}},
 '2': {'class_type': 'ResizeImageMaskNode',
       'inputs': {'widget_0': 'scale dimensions',
                  'widget_1': 256,
                  'widget_2': 1080,
                  'widget_3': 'center',
                  'widget_4': 'lanczos',
                  'input': ['1', 0]}},
 '35': {'class_type': 'IAMCCS_AudioExtender',
        'inputs': {'widget_0': 24,
                   'widget_1': 'left_context_only',
                   'widget_2': 0.5,
                   'widget_3': 0,
                   'widget_4': 'use_timeline_cursor',
                   'widget_5': 'snap_to_video_duration',
                   'widget_6': 'soft_clamp',
                   'widget_7': 1,
                   'widget_8': 10,
                   'widget_9': 240,
                   'widget_10': 249,
                   'widget_11': 240,
                   'widget_12': 0,
                   'widget_13': 240,
                   'widget_14': 240,
                   'widget_15': 240,
                   'audio': ['4', 0],
                   'segment_start_frames': ['34', 1],
                   'effective_unique_frames': ['34', 3]}},
 '44': {'class_type': 'IAMCCS_AudioTimelineGate',
        'inputs': {'widget_0': 1,
                   'widget_1': True,
                   'widget_2': 1,
                   'widget_3': True,
                   'widget_4': 0,
                   'widget_5': 0,
                   'remaining_frames_after': ['34', 7],
                   'effective_unique_frames': ['34', 3],
                   'is_last_segment': ['34', 8],
                   'cursor_frames_out': ['34', 0]}},
 '34': {'class_type': 'IAMCCS_AudioExtensionMath',
        'inputs': {'widget_0': 24,
                   'widget_1': 1,
                   'widget_2': 249,
                   'widget_3': 240,
                   'widget_4': True,
                   'widget_5': 240,
                   'widget_6': 0,
                   'audio': ['4', 0],
                   'cursor_frames_in': ['30', 3]}},
 '53': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 606399719654025, 'widget_1': 'randomize'}},
 '58': {'class_type': 'IAMCCS_AudioTimelineGate',
        'inputs': {'widget_0': 1,
                   'widget_1': True,
                   'widget_2': 1,
                   'widget_3': True,
                   'widget_4': 0,
                   'widget_5': 0,
                   'remaining_frames_after': ['48', 7],
                   'effective_unique_frames': ['48', 3],
                   'is_last_segment': ['48', 8],
                   'cursor_frames_out': ['48', 0]}},
 '49': {'class_type': 'IAMCCS_AudioExtender',
        'inputs': {'widget_0': 24,
                   'widget_1': 'left_context_only',
                   'widget_2': 0.5,
                   'widget_3': 0,
                   'widget_4': 'use_timeline_cursor',
                   'widget_5': 'snap_to_video_duration',
                   'widget_6': 'soft_clamp',
                   'widget_7': 2,
                   'widget_8': 10,
                   'widget_9': 240,
                   'widget_10': 249,
                   'widget_11': 240,
                   'widget_12': 0,
                   'widget_13': 480,
                   'widget_14': 240,
                   'widget_15': 240,
                   'audio': ['4', 0],
                   'segment_start_frames': ['48', 1],
                   'effective_unique_frames': ['48', 3]}},
 '45': {'class_type': 'LTXVPreprocess', 'inputs': {'widget_0': 33}},
 '46': {'class_type': 'EmptyLTXVLatentVideo',
        'inputs': {'width': 256,
                   'height': 256,
                   'length': 5,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'widget_3': 1}},
 '47': {'class_type': 'IAMCCS_StartDirToVideoLatent',
        'inputs': {'widget_0': 'iamccs_extension_disk/30s_free_low_ram/seg1_start',
                   'widget_1': 'all',
                   'widget_2': 9,
                   'widget_3': 0,
                   'widget_4': 1,
                   'widget_5': True,
                   'widget_6': 33,
                   'vae': ['14', 0],
                   'latent': ['46', 0],
                   'start_dir': ['43', 1]}},
 '62': {'class_type': 'IAMCCS_VAEDecodeToDisk',
        'inputs': {'widget_0': 'iamccs_vae_frames/30s_free_low_ram/seg2',
                   'widget_1': 'seg2',
                   'widget_2': 'jpg',
                   'widget_3': 95,
                   'widget_4': True,
                   'widget_5': 'auto',
                   'widget_6': 512,
                   'widget_7': 64,
                   'widget_8': True,
                   'widget_9': 'iamccs_seam_debug',
                   'widget_10': True,
                   'samples': ['55', 0],
                   'vae': ['14', 0]}},
 '17': {'class_type': 'EmptyLTXVLatentVideo',
        'inputs': {'width': 256,
                   'height': 256,
                   'length': 5,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'widget_3': 1}},
 '32': {'class_type': 'EmptyLTXVLatentVideo',
        'inputs': {'width': 256,
                   'height': 256,
                   'length': 5,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'widget_3': 1}},
 '33': {'class_type': 'IAMCCS_StartDirToVideoLatent',
        'inputs': {'widget_0': 'iamccs_extension_disk/30s_free_low_ram/seg0_start',
                   'widget_1': 'all',
                   'widget_2': 9,
                   'widget_3': 0,
                   'widget_4': 1,
                   'widget_5': True,
                   'widget_6': 33,
                   'vae': ['14', 0],
                   'latent': ['32', 0],
                   'start_dir': ['29', 1]}},
 '48': {'class_type': 'IAMCCS_AudioExtensionMath',
        'inputs': {'widget_0': 24,
                   'widget_1': 2,
                   'widget_2': 249,
                   'widget_3': 240,
                   'widget_4': True,
                   'widget_5': 240,
                   'widget_6': 0,
                   'audio': ['4', 0],
                   'cursor_frames_in': ['44', 3]}},
 '5': {'class_type': 'UnetLoaderGGUF', 'inputs': {'widget_0': 'ltx-2.3-22b-dev-Q4_K_S.gguf'}},
 '77': {'class_type': 'UNETLoader', 'inputs': {'widget_0': 'MelBandRoformer_fp32.safetensors', 'widget_1': 'default'}},
 '24': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['19', 0], 'audio_latent': ['23', 0]}},
 '61': {'class_type': 'IAMCCS_VAEDecodeToDisk',
        'inputs': {'widget_0': 'iamccs_vae_frames/30s_free_low_ram/seg1',
                   'widget_1': 'seg1',
                   'widget_2': 'jpg',
                   'widget_3': 95,
                   'widget_4': True,
                   'widget_5': 'auto',
                   'widget_6': 512,
                   'widget_7': 64,
                   'widget_8': True,
                   'widget_9': 'iamccs_seam_debug',
                   'widget_10': True,
                   'samples': ['41', 0],
                   'vae': ['14', 0]}},
 '59': {'class_type': 'IAMCCS_VideoCombineFromDir',
        'inputs': {'widget_0': 'iamccs_extension_disk/30s_free_low_ram/final_extended',
                   'widget_1': 24,
                   'widget_2': 'IAMCCS/LTX23_BEST_3SEG_AUDIOEXT_30S_FREE_LOW_RAM',
                   'widget_3': 19,
                   'widget_4': 'yuv420p',
                   'widget_5': True,
                   'audio': ['4', 0],
                   'frames_dir': ['57', 0]}},
 '60': {'class_type': 'IAMCCS_VAEDecodeToDisk',
        'inputs': {'widget_0': 'iamccs_vae_frames/30s_free_low_ram/seg0',
                   'widget_1': 'seg0',
                   'widget_2': 'jpg',
                   'widget_3': 95,
                   'widget_4': True,
                   'widget_5': 'auto',
                   'widget_6': 512,
                   'widget_7': 64,
                   'widget_8': True,
                   'widget_9': 'iamccs_seam_debug',
                   'widget_10': True,
                   'samples': ['27', 0],
                   'vae': ['14', 0]}},
 '1': {'class_type': 'LoadImage',
       'inputs': {'widget_0': 'ChatGPT Image Mar 27, 2026, 08_27_32 AM.png', 'widget_1': 'image'}},
 '4': {'class_type': 'VHS_LoadAudioUpload', 'inputs': {}},
 '8': {'class_type': 'CLIPTextEncode',
       'inputs': {'widget_0': 'cinematic image to video shot of a singer actor acting and singing a song during a '
                              'musical, intense expression, coherent motion, smooth camera movement, high detail, '
                              'stable composition, audio-reactive motion',
                  'clip': ['7', 0]}},
 '29': {'class_type': 'IAMCCS_LTX2_ExtensionModule_Disk',
        'inputs': {'widget_0': 'iamccs_vae_frames/30s_free_low_ram/seg0',
                   'widget_1': 'iamccs_extension_disk/30s_free_low_ram/seg0_extended',
                   'widget_2': 'iamccs_extension_disk/30s_free_low_ram/seg0_start',
                   'widget_3': 9,
                   'widget_4': 'source',
                   'widget_5': 'cut',
                   'widget_6': True,
                   'widget_7': 'none',
                   'widget_8': 'native_workflow_safe',
                   'widget_9': 'none',
                   'widget_10': 'videoclip_audio_24fps',
                   'widget_11': '',
                   'widget_12': 1,
                   'source_dir': ['60', 0]}},
 '43': {'class_type': 'IAMCCS_LTX2_ExtensionModule_Disk',
        'inputs': {'widget_0': 'iamccs_vae_frames/30s_free_low_ram/seg0',
                   'widget_1': 'iamccs_extension_disk/30s_free_low_ram/seg1_extended',
                   'widget_2': 'iamccs_extension_disk/30s_free_low_ram/seg1_start',
                   'widget_3': 9,
                   'widget_4': 'source',
                   'widget_5': 'cut',
                   'widget_6': True,
                   'widget_7': 'none',
                   'widget_8': 'native_workflow_safe',
                   'widget_9': 'none',
                   'widget_10': 'videoclip_audio_24fps',
                   'widget_11': '',
                   'widget_12': 0,
                   'source_dir': ['29', 0],
                   'new_dir': ['61', 0]}},
 '57': {'class_type': 'IAMCCS_LTX2_ExtensionModule_Disk',
        'inputs': {'widget_0': 'iamccs_vae_frames/30s_free_low_ram/seg0',
                   'widget_1': 'iamccs_extension_disk/30s_free_low_ram/final_extended',
                   'widget_2': 'iamccs_extension_disk/30s_free_low_ram/final_start',
                   'widget_3': 9,
                   'widget_4': 'source',
                   'widget_5': 'cut',
                   'widget_6': True,
                   'widget_7': 'none',
                   'widget_8': 'native_workflow_safe',
                   'widget_9': 'none',
                   'widget_10': 'videoclip_audio_24fps',
                   'widget_11': '',
                   'widget_12': 1,
                   'source_dir': ['43', 0],
                   'new_dir': ['62', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4475},
 'ready_template': 'video/ltx2_3_iamccs_audio_extend_low_ram',
 'workflow_template': 'ltx2_3_iamccs_audio_extend_low_ram',
 'capability': 'audio_extended_multisegment_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/iamccs/IAMCCS_LTX23_BEST_3SEG_AUDIOEXT_30S_FREE_LOW_RAM.json',
 'coverage_tier': 'supplemental',
 'approach': 'low-RAM three-segment audio extension',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until their custom '
                        'node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-GGUF', 'ComfyUI-KJNodes', 'ComfyUI-LTXVideo']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/ltx2_3_iamccs_audio_extend_low_ram"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
