from __future__ import annotations

from vibecomfy.registry.ready_template import build_authored_ready_workflow
from vibecomfy.patches.ltx_lowvram import apply as apply_ltx_lowvram
from vibecomfy.patches.requirements import ensure_custom_nodes
from vibecomfy.patches.resolution import resolution

NODES = (('1241',
  'LTXVConditioning',
  {'frame_rate': ['4978', 0], 'negative': ['2612', 0], 'positive': ['2483', 0], 'widget_0': 24}),
 ('2004', 'LoadImage', {'widget_0': 'example.png', 'widget_1': 'image'}),
 ('2483',
  'CLIPTextEncode',
  {'clip': ['4960', 0],
   'widget_0': 'A traditional Japanese tea ceremony takes place in a tatami room as a host carefully prepares matcha. '
               'Soft traditional koto music plays in the background, adding to the serene atmosphere. The bamboo whisk '
               'taps rhythmically against the ceramic bowl while water simmers in an iron kettle. Guests kneel in '
               'formal seiza position, watching in respectful silence. The host bows and presents the tea bowl, '
               'turning it precisely before offering it to the first guest with soft-spoken words.'}),
 ('2612',
  'CLIPTextEncode',
  {'clip': ['4960', 0], 'widget_0': 'pc game, console game, video game, cartoon, childish, ugly'}),
 ('3059',
  'EmptyLTXVLatentVideo',
  {'length': ['4979', 0], 'widget_0': 960, 'widget_1': 544, 'widget_2': 121, 'widget_3': 1}),
 ('3159',
  'LTXVImgToVideoConditionOnly',
  {'bypass': ['4977', 0],
   'image': ['3336', 0],
   'latent': ['3059', 0],
   'vae': ['3940', 2],
   'widget_0': 0.7,
   'widget_1': False}),
 ('3336', 'LTXVPreprocess', {'image': ['4981', 0], 'widget_0': 18}),
 ('3940',
  'LowVRAMCheckpointLoader',
  {'ckpt_name': 'ltx-2.3-22b-dev.safetensors', 'dependencies': ['4960', 0], 'widget_0': 'ltx-2.3-22b-dev.safetensors'}),
 ('3980',
  'LTXVEmptyLatentAudio',
  {'audio_vae': ['4010', 0],
   'frame_rate': ['4985', 0],
   'frames_number': ['4979', 0],
   'widget_0': 97,
   'widget_1': 25,
   'widget_2': 1}),
 ('4010',
  'LowVRAMAudioVAELoader',
  {'ckpt_name': 'ltx-2.3-22b-dev.safetensors', 'widget_0': 'ltx-2.3-22b-dev.safetensors'}),
 ('4528', 'LTXVConcatAVLatent', {'audio_latent': ['3980', 0], 'video_latent': ['3159', 0]}),
 ('4802',
  'SamplerCustomAdvanced',
  {'guider': ['4808', 0],
   'latent_image': ['4528', 0],
   'noise': ['4814', 0],
   'sampler': ['4967', 0],
   'sigmas': ['4966', 0]}),
 ('4808',
  'MultimodalGuider',
  {'model': ['4968', 0],
   'negative': ['1241', 1],
   'parameters': ['4964', 0],
   'positive': ['1241', 0],
   'widget_0': '28'}),
 ('4814', 'RandomNoise', {'widget_0': 42, 'widget_1': 'fixed'}),
 ('4818', 'LTXVAudioVAEDecode', {'audio_vae': ['4010', 0], 'samples': ['4824', 1]}),
 ('4819', 'CreateVideo', {'audio': ['4818', 0], 'fps': ['4978', 0], 'images': ['4983', 0], 'widget_0': 30}),
 ('4823', 'SaveVideo', {'video': ['4819', 0], 'widget_0': 'output_F', 'widget_1': 'auto', 'widget_2': 'auto'}),
 ('4824', 'LTXVSeparateAVLatent', {'av_latent': ['4802', 0]}),
 ('4828', 'CFGGuider', {'model': ['4922', 0], 'negative': ['1241', 1], 'positive': ['1241', 0], 'widget_0': 1}),
 ('4829',
  'SamplerCustomAdvanced',
  {'guider': ['4828', 0],
   'latent_image': ['4528', 0],
   'noise': ['4832', 0],
   'sampler': ['4831', 0],
   'sigmas': ['4971', 0]}),
 ('4831', 'KSamplerSelect', {'widget_0': 'euler_ancestral_cfg_pp'}),
 ('4832', 'RandomNoise', {'widget_0': 43, 'widget_1': 'fixed'}),
 ('4845', 'LTXVSeparateAVLatent', {'av_latent': ['4829', 0]}),
 ('4848', 'LTXVAudioVAEDecode', {'audio_vae': ['4010', 0], 'samples': ['4845', 1]}),
 ('4849', 'CreateVideo', {'audio': ['4848', 0], 'fps': ['4978', 0], 'images': ['4982', 0], 'widget_0': 30}),
 ('4852', 'SaveVideo', {'video': ['4849', 0], 'widget_0': 'output_D', 'widget_1': 'auto', 'widget_2': 'auto'}),
 ('4922',
  'LoraLoaderModelOnly',
  {'model': ['3940', 0], 'widget_0': 'ltxv/ltx2/ltx-2.3-22b-distilled-lora-384-1.1.safetensors', 'widget_1': 0.5}),
 ('4923',
  'GemmaAPITextEncode',
  {'api_key': ['4973', 0],
   'widget_0': '',
   'widget_1': '',
   'widget_2': 'ltx-2.3-22b-dev.safetensors',
   'widget_3': 'ltx-2.3-22b-dev.safetensors'}),
 ('4960',
  'LTXAVTextEncoderLoader',
  {'widget_0': 'comfy_gemma_3_12B_it.safetensors', 'widget_1': 'ltx-2.3-22b-dev.safetensors', 'widget_2': 'default'}),
 ('4961',
  'GemmaAPITextEncode',
  {'api_key': ['4973', 0],
   'widget_0': '',
   'widget_1': 'pc game, console game, video game, cartoon, childish, ugly',
   'widget_2': False,
   'widget_3': 'ltx-2.3-22b-dev.safetensors'}),
 ('4963',
  'GuiderParameters',
  {'widget_0': 'AUDIO',
   'widget_1': 7,
   'widget_2': 1,
   'widget_3': True,
   'widget_4': 0.7,
   'widget_5': 3,
   'widget_6': 0,
   'widget_7': True}),
 ('4964',
  'GuiderParameters',
  {'parameters': ['4963', 0],
   'widget_0': 'VIDEO',
   'widget_1': 3,
   'widget_2': 1,
   'widget_3': True,
   'widget_4': 0.9,
   'widget_5': 3,
   'widget_6': 0,
   'widget_7': True}),
 ('4966',
  'LTXVScheduler',
  {'latent': ['4528', 0], 'widget_0': 15, 'widget_1': 2.05, 'widget_2': 0.95, 'widget_3': True, 'widget_4': 0.1}),
 ('4967',
  'ClownSampler_Beta',
  {'widget_0': 0.25, 'widget_1': 'exponential/res_2s', 'widget_2': 94, 'widget_3': 'fixed', 'widget_4': True}),
 ('4968',
  'LoraLoaderModelOnly',
  {'model': ['3940', 0], 'widget_0': 'ltxv/ltx2/ltx-2.3-22b-distilled-lora-384-1.1.safetensors', 'widget_1': 0.2}),
 ('4971', 'ManualSigmas', {'widget_0': '1.0, 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0'}),
 ('4973', 'PrimitiveString', {'widget_0': ''}),
 ('4977', 'PrimitiveBoolean', {'widget_0': True}),
 ('4978', 'PrimitiveFloat', {'widget_0': 24}),
 ('4979', 'PrimitiveInt', {'widget_0': 121, 'widget_1': 'fixed'}),
 ('4981',
  'ResizeImageMaskNode',
  {'input': ['2004', 0], 'widget_0': 'scale longer dimension', 'widget_1': 1536, 'widget_2': 'lanczos'}),
 ('4982',
  'LTXVTiledVAEDecode',
  {'latents': ['4845', 0],
   'vae': ['3940', 2],
   'widget_0': 2,
   'widget_1': 2,
   'widget_2': 6,
   'widget_3': False,
   'widget_4': 'auto',
   'widget_5': 'auto'}),
 ('4983',
  'LTXVTiledVAEDecode',
  {'latents': ['4824', 0],
   'vae': ['3940', 2],
   'widget_0': 2,
   'widget_1': 2,
   'widget_2': 6,
   'widget_3': False,
   'widget_4': 'auto',
   'widget_5': 'auto'}),
 ('4985', 'LTXFloatToInt', {'a': ['4978', 0], 'widget_0': 0}))

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 1919},
 'ready_template': 'video/ltx2_3_t2v',
 'workflow_template': 'ltx2_3_t2v',
 'capability': 'text_to_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/ltx2_3_single_stage_distilled_full.json',
 'coverage_tier': 'required',
 'approach': None,
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until their custom '
                        'node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-LTXVideo']}


def build():
    workflow = build_authored_ready_workflow(
        NODES,
        READY_METADATA,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template"),
        requirements=READY_REQUIREMENTS,
        registered_inputs={'prompt': ('2483', 'widget_0')},
    )
    apply_ltx_lowvram(workflow)
    resolution(384, 256, 9).apply(workflow)
    ensure_custom_nodes(workflow, READY_REQUIREMENTS["custom_nodes"])
    workflow.register_input("prompt", "2483", "widget_0", workflow.nodes["2483"].inputs.get("widget_0"))
    return workflow
