from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'92': {'class_type': 'SimpleCalculatorKJ', 'inputs': {'widget_0': 'a', 'a': ['91', 0]}},
 '91': {'class_type': 'GetNode', 'inputs': {'widget_0': 'fps'}},
 '127': {'class_type': 'GetNode', 'inputs': {'widget_0': 'frames'}},
 '137': {'class_type': 'GetNode', 'inputs': {'widget_0': 'fps'}},
 '129': {'class_type': 'GetNode', 'inputs': {'widget_0': 'height'}},
 '128': {'class_type': 'GetNode', 'inputs': {'widget_0': 'width'}},
 '171': {'class_type': 'SetNode', 'inputs': {'widget_0': 'upscale_model', 'LATENT_UPSCALE_MODEL': ['182', 0]}},
 '172': {'class_type': 'SetNode', 'inputs': {'widget_0': 'vae_audio', 'VAE': ['175', 0]}},
 '173': {'class_type': 'SetNode', 'inputs': {'widget_0': 'vae', 'VAE': ['181', 0]}},
 '174': {'class_type': 'MarkdownNote',
         'inputs': {'widget_0': '## LTX-2 Prompting Tips\n'
                                '1. **Core Actions**: Describe events and actions as they occur over time  \n'
                                '2. **Audio**: Describe sounds and dialogue needed for the scene  \n'
                                '3. **Reference Image**: Do not repeat details already present  \n'
                                '4. **Consistency**: Avoid instructions that do not match the reference image, as this '
                                'will degrade results'}},
 '175': {'class_type': 'VAELoaderKJ',
         'inputs': {'widget_0': 'LTX23_audio_vae_bf16.safetensors', 'widget_1': 'main_device', 'widget_2': 'bf16'}},
 '177': {'class_type': 'SetNode', 'inputs': {'widget_0': 'vae_tiny', 'VAE': ['180', 0]}},
 '180': {'class_type': 'VAELoader', 'inputs': {'widget_0': 'taeltx2_3.safetensors'}},
 '181': {'class_type': 'VAELoader', 'inputs': {'widget_0': 'LTX23_video_vae_bf16.safetensors'}},
 '183': {'class_type': 'MarkdownNote',
         'inputs': {'widget_0': 'Width & height settings must be divisible by 32 + 1. \n'
                                'Frame count must be divisible by 8 + 1. \n'
                                '\n'
                                '\n'
                                'Running with invalid parameters **will not cause errors**. Instead, the flow will '
                                'silently choose the closest valid parameters. \n'
                                '\n'
                                'By default, we are using 720p resolution. You can try 1920*1088 if you have a '
                                'powerful GPU.'}},
 '188': {'class_type': 'SetNode', 'inputs': {'widget_0': 'clip', 'CLIP': ['190', 0]}},
 '93': {'class_type': 'GetNode', 'inputs': {'widget_0': 'fps'}},
 '204': {'class_type': 'GetNode', 'inputs': {'widget_0': 'final_audio'}},
 '203': {'class_type': 'GetNode', 'inputs': {'widget_0': 'final_video'}},
 '147': {'class_type': 'GetNode', 'inputs': {'widget_0': 'vae'}},
 '153': {'class_type': 'SetNode', 'inputs': {'widget_0': 'final_video', 'IMAGE': ['149', 0]}},
 '154': {'class_type': 'SetNode', 'inputs': {'widget_0': 'final_audio', 'AUDIO': ['150', 0]}},
 '1': {'class_type': 'KSamplerSelect', 'inputs': {'widget_0': 'euler_ancestral_cfg_pp'}},
 '5': {'class_type': 'ManualSigmas', 'inputs': {'widget_0': '0.909375, 0.725, 0.421875, 0.0'}},
 '190': {'class_type': 'DualCLIPLoader',
         'inputs': {'widget_0': 'gemma_3_12B_it_fp4_mixed.safetensors',
                    'widget_1': 'ltx-2.3_text_projection_bf16.safetensors',
                    'widget_2': 'ltxv',
                    'widget_3': 'default'}},
 '124': {'class_type': 'GetNode', 'inputs': {'widget_0': 'clip'}},
 '182': {'class_type': 'LatentUpscaleModelLoader',
         'inputs': {'widget_0': 'ltx-2.3-spatial-upscaler-x2-1.1.safetensors'}},
 '230': {'class_type': 'SetNode', 'inputs': {'widget_0': 'model_with_lora', 'MODEL': ['2107', 0]}},
 '192': {'class_type': 'SetNode', 'inputs': {'widget_0': 'model', 'MODEL': ['2107', 0]}},
 '2072': {'class_type': 'SetNode', 'inputs': {'widget_0': 'height', 'INT': ['2079', 0]}},
 '2073': {'class_type': 'SetNode', 'inputs': {'widget_0': 'width', 'INT': ['2080', 0]}},
 '2074': {'class_type': 'SetNode', 'inputs': {'widget_0': 'fps', 'FLOAT': ['2076', 0]}},
 '75': {'class_type': 'SetNode', 'inputs': {'widget_0': 'firstframe', 'IMAGE': ['2083', 0]}},
 '226': {'class_type': 'PathchSageAttentionKJ', 'inputs': {'widget_0': 'auto', 'widget_1': False, 'model': ['186', 0]}},
 '227': {'class_type': 'LTX2MemoryEfficientSageAttentionPatch', 'inputs': {'widget_0': True, 'model': ['226', 0]}},
 '228': {'class_type': 'LTXVChunkFeedForward', 'inputs': {'widget_0': 2, 'widget_1': 4096, 'model': ['227', 0]}},
 '229': {'class_type': 'LTX2AttentionTunerPatch',
         'inputs': {'widget_0': '',
                    'widget_1': 1,
                    'widget_2': 1,
                    'widget_3': 1,
                    'widget_4': 1,
                    'widget_5': True,
                    'model': ['228', 0]}},
 '16': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': '= enhanced prompt = ', 'clip': ['124', 0], 'text': ['2070', 0]}},
 '2083': {'class_type': 'ResizeImagesByLongerEdge', 'inputs': {'widget_0': 1536, 'images': ['44', 0]}},
 '199': {'class_type': 'SetNode', 'inputs': {'widget_0': 'model_nag', 'MODEL': ['197', 0]}},
 '2': {'class_type': 'LTXVScheduler',
       'inputs': {'steps': 1,
                  'widget_0': 1,
                  'widget_1': 2.05,
                  'widget_2': 0.95,
                  'widget_3': True,
                  'widget_4': 0.1,
                  'latent': ['24', 0]}},
 '122': {'class_type': 'GetNode', 'inputs': {'widget_0': 'model'}},
 '187': {'class_type': 'UNETLoader',
         'inputs': {'widget_0': 'ltx-2.3-22b-distilled-1.1_transformer_only_fp8_scaled.safetensors',
                    'widget_1': 'default'}},
 '186': {'class_type': 'LoraLoaderModelOnly',
         'inputs': {'widget_0': 'LTX\\v2\\ltx-2.3-22b-distilled-1.1_lora-dynamic_fro09_avg_rank_111_bf16.safetensors',
                    'widget_1': 0.6,
                    'model': ['187', 0]}},
 '215': {'class_type': 'ManualSigmas',
         'inputs': {'widget_0': '1.0, 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0'}},
 '70': {'class_type': 'GetNode', 'inputs': {'widget_0': 'width'}},
 '71': {'class_type': 'GetNode', 'inputs': {'widget_0': 'height'}},
 '193': {'class_type': 'GetNode', 'inputs': {'widget_0': 'vae_tiny'}},
 '198': {'class_type': 'LTX2SamplingPreviewOverride',
         'inputs': {'widget_0': 8, 'model': ['122', 0], 'vae': ['193', 0]}},
 '2107': {'class_type': 'Power Lora Loader (rgthree)', 'inputs': {'widget_3': '', 'model': ['229', 0]}},
 '2112': {'class_type': 'SetNode', 'inputs': {'widget_0': 'firstframe_strength', 'FLOAT': ['2110', 0]}},
 '2113': {'class_type': 'SetNode', 'inputs': {'widget_0': 'lastframe_strength', 'FLOAT': ['2108', 0]}},
 '189': {'class_type': 'DualCLIPLoaderGGUF',
         'inputs': {'widget_0': 'gemma-3-12b-it-Q2_K.gguf',
                    'widget_1': 'ltx-2.3_text_projection_bf16.safetensors',
                    'widget_2': 'ltxv'}},
 '179': {'class_type': 'MarkdownNote',
         'inputs': {'widget_0': 'If using some user made LTX-2 loras they sometimes are not trained on audio, so it '
                                'will produce very noisy audio outputs. Try use KJNodes LTX-2 Lora Loader Advanced in '
                                'such cases, and set the non video strenght to zero\n'}},
 '184': {'class_type': 'MarkdownNote', 'inputs': {'widget_0': 'taeltx2_3.safetensors'}},
 '191': {'class_type': 'UnetLoaderGGUF',
         'inputs': {'widget_0': 'LTXvideo\\LTX-2\\quantstack\\LTX-2.3-distilled-Q4_K_S.gguf'}},
 '170': {'class_type': 'MarkdownNote',
         'inputs': {'widget_0': 'If low on Ram/Vram, try width height to 832 x 480 or 960 x 544.  If you can, run at '
                                '1280 x 720 or higher.\n'
                                '\n'
                                '\n'
                                'Length in seconds :  try 5, 10 or 20. \n'
                                'fps : 24 or 25 (or 48 or 50 if your pc can run it)'}},
 '176': {'class_type': 'MarkdownNote',
         'inputs': {'widget_0': 'Download models from here:\n'
                                '\n'
                                '\n'
                                'https://huggingface.co/Kijai/LTX2.3_comfy\n'
                                '\n'
                                'Text encoder : https://huggingface.co/Comfy-Org/ltx-2'}},
 '2075': {'class_type': 'SetNode', 'inputs': {'widget_0': 'frames', 'INT': ['2077', 1]}},
 '2077': {'class_type': 'SimpleCalculatorKJ',
          'inputs': {'widget_0': '((round((a * b -1) / 8)) * 8) + 1 ', 'a': ['2078', 0], 'b': ['2076', 0]}},
 '148': {'class_type': 'GetNode', 'inputs': {'widget_0': 'vae_audio'}},
 '4': {'class_type': 'KSamplerSelect', 'inputs': {'widget_0': 'euler_cfg_pp'}},
 '21': {'class_type': 'SamplerCustomAdvanced',
        'inputs': {'noise': ['14', 0],
                   'guider': ['8', 0],
                   'sampler': ['4', 0],
                   'sigmas': ['216', 0],
                   'latent_image': ['34', 0]}},
 '2081': {'class_type': 'SetNode', 'inputs': {'widget_0': 'enhance_prompt', 'BOOLEAN': ['2082', 0]}},
 '2192': {'class_type': 'ComfyMathExpression', 'inputs': {'widget_0': 'a/2', 'values.a': ['219', 0]}},
 '2191': {'class_type': 'ComfyMathExpression', 'inputs': {'widget_0': 'a/2', 'values.a': ['220', 0]}},
 '220': {'class_type': 'GetNode', 'inputs': {'widget_0': 'width'}},
 '219': {'class_type': 'GetNode', 'inputs': {'widget_0': 'height'}},
 '2172': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'image (12).png', 'widget_1': 'image'}},
 '49': {'class_type': 'ResizeImagesByLongerEdge', 'inputs': {'widget_0': 1536, 'images': ['48', 0]}},
 '78': {'class_type': 'SetNode', 'inputs': {'widget_0': 'middleframe', 'IMAGE': ['49', 0]}},
 '2169': {'class_type': 'SetNode', 'inputs': {'widget_0': 'lastframe', 'IMAGE': ['2168', 0]}},
 '2168': {'class_type': 'ResizeImagesByLongerEdge', 'inputs': {'widget_0': 1536, 'images': ['2171', 0]}},
 '32': {'class_type': 'EmptyLTXVLatentVideo',
        'inputs': {'width': ['2191', 1],
                   'height': ['2192', 1],
                   'length': ['127', 0],
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'widget_3': 1}},
 '2217': {'class_type': 'SetNode', 'inputs': {'widget_0': 'firstframe_resized', 'IMAGE': ['44', 0]}},
 '44': {'class_type': 'ImageResizeKJv2',
        'inputs': {'widget_0': 960,
                   'widget_1': 544,
                   'widget_2': 'lanczos',
                   'widget_3': 'crop',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'center',
                   'widget_6': 32,
                   'widget_7': 'cpu',
                   'image': ['45', 0],
                   'width': ['70', 0],
                   'height': ['71', 0]}},
 '2218': {'class_type': 'SetNode', 'inputs': {'widget_0': 'middleframe_resized', 'IMAGE': ['48', 0]}},
 '48': {'class_type': 'ImageResizeKJv2',
        'inputs': {'widget_0': 512,
                   'widget_1': 512,
                   'widget_2': 'lanczos',
                   'widget_3': 'crop',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'center',
                   'widget_6': 32,
                   'widget_7': 'cpu',
                   'image': ['47', 0],
                   'width': ['44', 1],
                   'height': ['44', 2]}},
 '2219': {'class_type': 'SetNode', 'inputs': {'widget_0': 'lastframe_resized', 'IMAGE': ['2171', 0]}},
 '2171': {'class_type': 'ImageResizeKJv2',
          'inputs': {'widget_0': 512,
                     'widget_1': 512,
                     'widget_2': 'lanczos',
                     'widget_3': 'crop',
                     'widget_4': '0, 0, 0',
                     'widget_5': 'center',
                     'widget_6': 32,
                     'widget_7': 'cpu',
                     'image': ['2172', 0],
                     'width': ['48', 1],
                     'height': ['48', 2]}},
 '117': {'class_type': 'GetNode', 'inputs': {'widget_0': 'vae_audio'}},
 '2215': {'class_type': 'SetNode', 'inputs': {'widget_0': 'latent_audio', 'LATENT': ['9', 0]}},
 '146': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['21', 0]}},
 '2163': {'class_type': 'GetNode', 'inputs': {'widget_0': 'positive_guider'}},
 '2154': {'class_type': 'GetNode', 'inputs': {'widget_0': 'negative_guider'}},
 '2084': {'class_type': 'LTXVPreprocess', 'inputs': {'widget_0': 18, 'image': ['225', 0]}},
 '225': {'class_type': 'GetNode', 'inputs': {'widget_0': 'firstframe'}},
 '2174': {'class_type': 'LTXVPreprocess', 'inputs': {'widget_0': 18, 'image': ['2173', 0]}},
 '2173': {'class_type': 'GetNode', 'inputs': {'widget_0': 'middleframe'}},
 '50': {'class_type': 'LTXVPreprocess', 'inputs': {'widget_0': 18, 'image': ['224', 0]}},
 '224': {'class_type': 'GetNode', 'inputs': {'widget_0': 'lastframe'}},
 '2187': {'class_type': 'GetNode', 'inputs': {'widget_0': 'firstframe_strength'}},
 '2189': {'class_type': 'GetNode', 'inputs': {'widget_0': 'middleframe_strength'}},
 '2188': {'class_type': 'GetNode', 'inputs': {'widget_0': 'lastframe_strength'}},
 '2216': {'class_type': 'SimpleCalculatorKJ', 'inputs': {'widget_0': 'a/2', 'variables.a': ['2175', 0]}},
 '2068': {'class_type': 'GetNode', 'inputs': {'widget_0': 'enhance_prompt'}},
 '2102': {'class_type': '19e3f7e8-881c-4a61-a360-1c463734043a', 'inputs': {}},
 '2067': {'class_type': 'GetNode', 'inputs': {'widget_0': 'clip'}},
 '2167': {'class_type': 'GetNode', 'inputs': {'widget_0': 'positive_guider2'}},
 '2166': {'class_type': 'GetNode', 'inputs': {'widget_0': 'negative_guider2'}},
 '2070': {'class_type': '8fa4f93a-67ee-463f-ba43-249580c0bfb1',
          'inputs': {'clip': ['2067', 0], 'image': ['2102', 0], '_1': ['2103', 0]}},
 '216': {'class_type': 'ManualSigmas', 'inputs': {'widget_0': '0.85, 0.7250, 0.4219, 0.0'}},
 '14': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 43, 'widget_1': 'fixed'}},
 '2076': {'class_type': 'PrimitiveFloat', 'inputs': {'widget_0': 8}},
 '200': {'class_type': 'GetNode', 'inputs': {'widget_0': 'model_nag'}},
 '201': {'class_type': 'GetNode', 'inputs': {'widget_0': 'model_nag'}},
 '8': {'class_type': 'CFGGuider',
       'inputs': {'widget_0': 2.5, 'model': ['201', 0], 'positive': ['2182', 0], 'negative': ['2182', 1]}},
 '2233': {'class_type': 'SetNode', 'inputs': {'widget_0': 'negative', 'CONDITIONING': ['11', 0]}},
 '11': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': 'blurry, oversaturated, pixelated, low resolution, grainy, distorted, noise, '
                               'compression artifacts, jpeg artifacts, glitches, watermark, text, logo, signature, '
                               'copyright, subtitles, distorted sound, saturated sound, loud',
                   'clip': ['124', 0]}},
 '150': {'class_type': 'LTXVAudioVAEDecode', 'inputs': {'samples': ['146', 1], 'audio_vae': ['148', 0]}},
 '196': {'class_type': 'GetNode', 'inputs': {'widget_0': 'negative'}},
 '197': {'class_type': 'LTX2_NAG',
         'inputs': {'widget_0': 11,
                    'widget_1': 0.25,
                    'widget_2': 2.5,
                    'widget_3': True,
                    'model': ['198', 0],
                    'nag_cond_video': ['196', 0],
                    'nag_cond_audio': ['196', 0]}},
 '133': {'class_type': 'GetNode', 'inputs': {'widget_0': 'upscale_model'}},
 '120': {'class_type': 'GetNode', 'inputs': {'widget_0': 'vae'}},
 '2185': {'class_type': 'SetNode', 'inputs': {'widget_0': 'middleframe_count', 'INT': ['2216', 1]}},
 '47': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'image (11).png', 'widget_1': 'image'}},
 '2255': {'class_type': 'GetNode', 'inputs': {'widget_0': 'vae'}},
 '2175': {'class_type': 'GetNode', 'inputs': {'widget_0': 'frames'}},
 '36': {'class_type': 'CFGGuider',
        'inputs': {'widget_0': 2.5, 'model': ['200', 0], 'positive': ['2221', 0], 'negative': ['2221', 1]}},
 '2110': {'class_type': 'PrimitiveFloat', 'inputs': {'widget_0': 8}},
 '18': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['13', 0]}},
 '13': {'class_type': 'SamplerCustomAdvanced',
        'inputs': {'noise': ['15', 0],
                   'guider': ['36', 0],
                   'sampler': ['1', 0],
                   'sigmas': ['215', 0],
                   'latent_image': ['24', 0]}},
 '2155': {'class_type': 'GetNode', 'inputs': {'widget_0': 'vae'}},
 '2106': {'class_type': 'GetNode', 'inputs': {'widget_0': 'lastframe'}},
 '2226': {'class_type': 'GetNode', 'inputs': {'widget_0': 'lastframe_strength'}},
 '2220': {'class_type': 'GetNode', 'inputs': {'widget_0': 'firstframe'}},
 '2156': {'class_type': 'LTXVCropGuides',
          'inputs': {'positive': ['2167', 0], 'negative': ['2166', 0], 'latent': ['146', 0]}},
 '149': {'class_type': 'VAEDecodeTiled',
         'inputs': {'widget_0': 512,
                    'widget_1': 64,
                    'widget_2': 4096,
                    'widget_3': 8,
                    'samples': ['2156', 2],
                    'vae': ['147', 0]}},
 '2164': {'class_type': 'SetNode', 'inputs': {'widget_0': 'positive_guider2', 'CONDITIONING': ['2182', 0]}},
 '2165': {'class_type': 'SetNode', 'inputs': {'widget_0': 'negative_guider2', 'CONDITIONING': ['2182', 1]}},
 '34': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['2182', 2], 'audio_latent': ['18', 1]}},
 '2260': {'class_type': 'GetNode', 'inputs': {'widget_0': 'positive_guider'}},
 '2259': {'class_type': 'GetNode', 'inputs': {'widget_0': 'negative_guider'}},
 '2222': {'class_type': 'LTXVCropGuides',
          'inputs': {'positive': ['2260', 0], 'negative': ['2259', 0], 'latent': ['18', 0]}},
 '2080': {'class_type': 'INTConstant', 'inputs': {'widget_0': 1280}},
 '2079': {'class_type': 'INTConstant', 'inputs': {'widget_0': 720}},
 '2078': {'class_type': 'INTConstant', 'inputs': {'widget_0': 15}},
 '2082': {'class_type': 'PrimitiveBoolean', 'inputs': {'widget_0': True}},
 '45': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'sodacan_01.png', 'widget_1': 'image'}},
 '2103': {'class_type': 'PrimitiveStringMultiline',
          'inputs': {'widget_0': 'Make this come alive with cinematic motion, smooth animation. \n'
                                 '\n'
                                 'The scene starts with a close up of an LTX soda can with ic cubes around it. \n'
                                 '\n'
                                 'All of a suddent an arm comes into frame and grabs the soda can, and lifts the soda '
                                 'can up. \n'
                                 '\n'
                                 'Camera pans up smoothly to show a woman holding the soda can. She talks with a soft '
                                 'British voice, and she says :" An LTX a day, keeps the doctor away". Then she '
                                 'laghts, and finally she drinks from the soda can. '}},
 '9': {'class_type': 'LTXVEmptyLatentAudio',
       'inputs': {'frames_number': ['127', 0],
                  'frame_rate': ['92', 1],
                  'widget_0': 5,
                  'widget_1': 8,
                  'widget_2': 1,
                  'audio_vae': ['117', 0]}},
 '2214': {'class_type': 'GetNode', 'inputs': {'widget_0': 'latent_audio'}},
 '24': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['2221', 2], 'audio_latent': ['2214', 0]}},
 '2277': {'class_type': 'SetNode', 'inputs': {'widget_0': 'middleframe_strength', 'FLOAT': ['2278', 0]}},
 '2108': {'class_type': 'PrimitiveFloat', 'inputs': {'widget_0': 8}},
 '2109': {'class_type': 'MarkdownNote',
          'inputs': {'widget_0': '**LAST FRAME STRENGTH**\n'
                                 '\n'
                                 'If you plan to continue from last frame and need it to be more exactly as input '
                                 'image set it to about 0.7 or more\n'
                                 '\n'
                                 '(if **middle frame** is too strong, and the model cant "reach that spot in time", it '
                                 'might also glitch a bit. Setting middle frame low is usually best) \n'
                                 '\n'
                                 'But all depends on what kind of input frames and output you aim for \n'}},
 '2278': {'class_type': 'PrimitiveFloat', 'inputs': {'widget_0': 8}},
 '2281': {'class_type': 'GetNode', 'inputs': {'widget_0': 'middleframe_strength'}},
 '2280': {'class_type': 'GetNode', 'inputs': {'widget_0': 'lastframe_strength'}},
 '2279': {'class_type': 'GetNode', 'inputs': {'widget_0': 'firstframe_strength'}},
 '43': {'class_type': 'VHS_VideoCombine',
        'inputs': {'images': ['203', 0], 'audio': ['204', 0], 'frame_rate': ['137', 0]}},
 '15': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 42, 'widget_1': 'fixed'}},
 '2276': {'class_type': 'GetNode', 'inputs': {'widget_0': 'firstframe_strength'}},
 '2182': {'class_type': 'LTXVAddGuideMulti',
          'inputs': {'widget_0': '2',
                     'widget_1': 0,
                     'widget_2': 1,
                     'widget_3': -1,
                     'widget_4': 1,
                     'positive': ['2222', 0],
                     'negative': ['2222', 1],
                     'vae': ['2155', 0],
                     'latent': ['2222', 2],
                     'num_guides.image_1': ['2220', 0],
                     'num_guides.strength_1': ['2276', 0],
                     'num_guides.image_2': ['2106', 0],
                     'num_guides.strength_2': ['2226', 0]}},
 '10': {'class_type': 'LTXVConditioning',
        'inputs': {'widget_0': 8, 'positive': ['16', 0], 'negative': ['11', 0], 'frame_rate': ['93', 0]}},
 '2223': {'class_type': 'SetNode', 'inputs': {'widget_0': 'positive_guider', 'CONDITIONING': ['2221', 0]}},
 '2224': {'class_type': 'SetNode', 'inputs': {'widget_0': 'negative_guider', 'CONDITIONING': ['2221', 1]}},
 '2221': {'class_type': 'LTXVAddGuideMulti',
          'inputs': {'widget_0': '3',
                     'widget_1': 0,
                     'widget_2': 0.7,
                     'widget_3': 0,
                     'widget_4': 0.25,
                     'widget_5': -1,
                     'widget_6': 1,
                     'positive': ['10', 0],
                     'negative': ['10', 1],
                     'vae': ['2255', 0],
                     'latent': ['32', 0],
                     'num_guides.image_1': ['2084', 0],
                     'num_guides.strength_1': ['2279', 0],
                     'num_guides.image_2': ['2174', 0],
                     'num_guides.frame_idx_2': ['2216', 1],
                     'num_guides.strength_2': ['2281', 0],
                     'num_guides.image_3': ['50', 0],
                     'num_guides.strength_3': ['2280', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4831},
 'ready_template': 'video/ltx2_3_runexx_first_middle_last_frame',
 'workflow_template': 'ltx2_3_runexx_first_middle_last_frame',
 'capability': 'first_middle_last_frame_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/runexx/LTX-2.3_FML2V_First_Middle_Last_Frame_guider.json',
 'coverage_tier': 'supplemental',
 'approach': 'multi-anchor image-guided video',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until their custom '
                        'node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-GGUF', 'ComfyUI-KJNodes', 'ComfyUI-LTXVideo', 'ComfyUI-VideoHelperSuite']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/ltx2_3_runexx_first_middle_last_frame"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
