from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'1241': {'class_type': 'LTXVConditioning',
          'inputs': {'widget_0': 8, 'positive': ['2483', 0], 'negative': ['2612', 0], 'frame_rate': ['5000', 2]}},
 '5012': {'class_type': 'LTXAddVideoICLoRAGuide',
          'inputs': {'widget_0': 0,
                     'widget_1': 1,
                     'widget_2': 1,
                     'widget_3': 'disabled',
                     'widget_4': False,
                     'widget_5': 128,
                     'widget_6': 32,
                     'positive': ['1241', 0],
                     'negative': ['1241', 1],
                     'vae': ['3940', 2],
                     'latent': ['3159', 0],
                     'image': ['5028', 0],
                     'latent_downscale_factor': ['5011', 1]}},
 '4528': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['5012', 2], 'audio_latent': ['3980', 0]}},
 '3980': {'class_type': 'LTXVEmptyLatentAudio',
          'inputs': {'frames_number': ['5029', 2],
                     'frame_rate': ['5066', 0],
                     'widget_0': 5,
                     'widget_1': 8,
                     'widget_2': 1,
                     'audio_vae': ['4010', 0]}},
 '3059': {'class_type': 'EmptyLTXVLatentVideo',
          'inputs': {'width': ['5029', 0],
                     'height': ['5029', 1],
                     'length': ['5029', 2],
                     'widget_0': 256,
                     'widget_1': 256,
                     'widget_2': 5,
                     'widget_3': 1}},
 '4829': {'class_type': 'SamplerCustomAdvanced',
          'inputs': {'noise': ['4832', 0],
                     'guider': ['4828', 0],
                     'sampler': ['4831', 0],
                     'sigmas': ['5025', 0],
                     'latent_image': ['4528', 0]}},
 '5013': {'class_type': 'LTXVCropGuides',
          'inputs': {'positive': ['5012', 0], 'negative': ['5012', 1], 'latent': ['4845', 0]}},
 '4845': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['4829', 0]}},
 '4986': {'class_type': 'DWPreprocessor',
          'inputs': {'widget_0': 'enable',
                     'widget_1': 'enable',
                     'widget_2': 'enable',
                     'widget_3': 256,
                     'widget_4': 'yolox_l.onnx',
                     'widget_5': 'dw-ll_ucoco_384_bs5.torchscript.pt',
                     'widget_6': 'disable',
                     'image': ['5026', 0]}},
 '4010': {'class_type': 'LowVRAMAudioVAELoader', 'inputs': {'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors'}},
 '3940': {'class_type': 'LowVRAMCheckpointLoader', 'inputs': {'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors'}},
 '5021': {'class_type': 'GemmaAPITextEncode',
          'inputs': {'widget_0': '',
                     'widget_1': '',
                     'widget_2': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_3': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'api_key': ['5022', 0]}},
 '5022': {'class_type': 'PrimitiveString', 'inputs': {'widget_0': ''}},
 '5023': {'class_type': 'LTXAVTextEncoderLoader',
          'inputs': {'text_encoder': 'gemma_3_12B_it_fp4_mixed.safetensors',
                     'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_0': 'gemma_3_12B_it_fp4_mixed.safetensors',
                     'widget_1': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_2': 'default'}},
 '2612': {'class_type': 'CLIPTextEncode',
          'inputs': {'widget_0': 'pc game, console game, video game, cartoon, childish, ugly', 'clip': ['5023', 0]}},
 '4828': {'class_type': 'CFGGuider',
          'inputs': {'widget_0': 2.5, 'model': ['5011', 0], 'positive': ['5012', 0], 'negative': ['5012', 1]}},
 '5000': {'class_type': 'GetVideoComponents', 'inputs': {'video': ['5001', 0]}},
 '5028': {'class_type': 'ResizeImageMaskNode',
          'inputs': {'widget_0': 'scale to multiple',
                     'widget_1': 256,
                     'widget_2': 'lanczos',
                     'input': ['4991', 0],
                     'resize_type.multiple': ['5034', 0]}},
 '5029': {'class_type': 'GetImageSize', 'inputs': {'image': ['5028', 0]}},
 '5025': {'class_type': 'ManualSigmas',
          'inputs': {'widget_0': '1.0, 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0'}},
 '5034': {'class_type': 'SimpleMath+', 'inputs': {'widget_0': 'a*32', 'a': ['5011', 1]}},
 '5020': {'class_type': 'GemmaAPITextEncode',
          'inputs': {'widget_0': '',
                     'widget_1': 'pc game, console game, video game, cartoon, childish, ugly',
                     'widget_2': False,
                     'widget_3': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'api_key': ['5022', 0]}},
 '2004': {'class_type': 'LoadImage',
          'inputs': {'image': 'example.png', 'widget_0': 'example.png', 'widget_1': 'image'}},
 '5019': {'class_type': 'PrimitiveBoolean', 'inputs': {'widget_0': True}},
 '5001': {'class_type': 'LoadVideo',
          'inputs': {'file': 'ltx_smoke_guide.mp4',
                     'video': 'ltx_smoke_guide.mp4',
                     'widget_0': 'ltx_smoke_guide.mp4',
                     'widget_1': 'image'}},
 '4832': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 42, 'widget_1': 'fixed'}},
 '5061': {'class_type': 'DepthAnything_V2', 'inputs': {'da_model': ['5060', 0], 'images': ['5026', 0]}},
 '5026': {'class_type': 'ResizeImageMaskNode',
          'inputs': {'widget_0': 'scale shorter dimension',
                     'widget_1': 256,
                     'widget_2': 'lanczos',
                     'input': ['5000', 0]}},
 '5011': {'class_type': 'LTXICLoRALoaderModelOnly',
          'inputs': {'lora_name': 'ltx-2.3-22b-ic-lora-union-control-ref0.5.safetensors',
                     'widget_0': 'ltx-2.3-22b-ic-lora-union-control-ref0.5.safetensors',
                     'widget_1': 1,
                     'model': ['4922', 0]}},
 '5060': {'class_type': 'DownloadAndLoadDepthAnythingV2Model',
          'inputs': {'model': 'depth_anything_v2_vits_fp32.safetensors', 'precision': 'fp32'}},
 '5063': {'class_type': 'Note',
          'inputs': {'widget_0': 'These are example annotators to convert reference video into proper guidance that '
                                 'the model can work with.\n'
                                 'Feel free to explore and choose whichever settings or alternative that best suits '
                                 'your needs.'}},
 '4831': {'class_type': 'KSamplerSelect', 'inputs': {'widget_0': 'euler_ancestral_cfg_pp'}},
 '4852': {'class_type': 'SaveVideo',
          'inputs': {'widget_0': 'output', 'widget_1': 'auto', 'widget_2': 'auto', 'video': ['4849', 0]}},
 '2483': {'class_type': 'CLIPTextEncode',
          'inputs': {'widget_0': 'Apocalyptic landscape with abandoned buildings, overgrown with foliage and trees. '
                                 'The sky is clear and the sun is setting, with the horizon turning bright red. The '
                                 'buildings are delapidated, falling apart and crumbling due to being abandoned for so '
                                 'long.\n'
                                 'The air is full of silence and the only thing to be heard is a young girl breathing '
                                 'and saying: "Where is everyone?"',
                     'clip': ['5023', 0]}},
 '4991': {'class_type': 'CannyEdgePreprocessor',
          'inputs': {'widget_0': 92, 'widget_1': 200, 'widget_2': 256, 'image': ['5026', 0]}},
 '4922': {'class_type': 'LoraLoaderModelOnly',
          'inputs': {'widget_0': 'ltxv/ltx2/ltx-2.3-22b-distilled-lora-384-1.1.safetensors',
                     'widget_1': 0.5,
                     'model': ['3940', 0]}},
 '5065': {'class_type': 'LTXVTiledVAEDecode',
          'inputs': {'widget_0': 2,
                     'widget_1': 2,
                     'widget_2': 6,
                     'widget_3': False,
                     'widget_4': 'auto',
                     'widget_5': 'auto',
                     'vae': ['3940', 2],
                     'latents': ['5013', 2]}},
 '4848': {'class_type': 'LTXVAudioVAEDecode', 'inputs': {'samples': ['4845', 1], 'audio_vae': ['4010', 0]}},
 '4849': {'class_type': 'CreateVideo',
          'inputs': {'fps': ['5000', 2], 'widget_0': 8, 'images': ['5065', 0], 'audio': ['4848', 0]}},
 '5066': {'class_type': 'LTXFloatToInt', 'inputs': {'widget_0': 0, 'a': ['5000', 2]}},
 '3159': {'class_type': 'LTXVImgToVideoConditionOnly',
          'inputs': {'widget_0': 1,
                     'widget_1': False,
                     'vae': ['3940', 2],
                     'image': ['5035', 0],
                     'latent': ['3059', 0],
                     'bypass': ['5019', 0]}},
 '5035': {'class_type': 'ResizeImageMaskNode',
          'inputs': {'widget_0': 'scale longer dimension',
                     'widget_1': 256,
                     'widget_2': 'lanczos',
                     'input': ['2004', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4952},
 'ready_template': 'video/ltx2_3_lightricks_iclora_union_control',
 'workflow_template': 'ltx2_3_lightricks_iclora_union_control',
 'capability': 'union_control_video_guided_i2v',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/lightricks_2_3/LTX-2.3_ICLoRA_Union_Control_Distilled.json',
 'coverage_tier': 'supplemental',
 'approach': 'official IC-LoRA union control workflow with depth/pose-style guide preprocessing',
 'runtime_note': 'Requires additional VideoDepthAnything/DWPose model setup beyond the core LTX smoke stack.',
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until their custom '
                        'node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [],
 'custom_nodes': ['ComfyUI-DepthAnythingV2', 'ComfyUI-KJNodes', 'ComfyUI-LTXVideo', 'comfyui_controlnet_aux']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/ltx2_3_lightricks_iclora_union_control"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
