from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'162': {'class_type': 'EmptyLTXVLatentVideo',
         'inputs': {'width': ['241', 1],
                    'height': ['241', 2],
                    'length': ['364', 0],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 5,
                    'widget_3': 1}},
 '269': {'class_type': 'LTXVPreprocess', 'inputs': {'widget_0': 33, 'image': ['241', 0]}},
 '350': {'class_type': 'SaveAudioMP3', 'inputs': {'widget_0': 'audio/ComfyUI', 'widget_1': 'V0', 'audio': ['348', 0]}},
 '347': {'class_type': 'LoadAudio', 'inputs': {'widget_0': 'man voice 2 LONG.mp3'}},
 '366': {'class_type': 'TrimAudioDuration', 'inputs': {'widget_0': 0, 'widget_1': 20, 'audio': ['376', 0]}},
 '372': {'class_type': 'Note', 'inputs': {'widget_0': 'Load a character voice audio for voice clone'}},
 '301': {'class_type': 'UnetLoaderGGUF', 'inputs': {'widget_0': 'LTX-2-dev-Q4_K_S.gguf'}},
 '411': {'class_type': 'LowVRAMAudioVAELoader', 'inputs': {'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors'}},
 '416': {'class_type': 'IAMCCS_LTX2_LoRAStackModelIO',
         'inputs': {'widget_0': 'ltx-2-19b-distilled-lora-384.safetensors',
                    'widget_1': 1,
                    'widget_2': 'no',
                    'widget_3': 0,
                    'widget_4': 'no',
                    'widget_5': 0,
                    'model': ['413', 0]}},
 '413': {'class_type': 'CheckpointLoaderSimple', 'inputs': {'widget_0': 'ltx-2-19b-distilled.safetensors'}},
 '412': {'class_type': 'LTXVGemmaCLIPModelLoader',
         'inputs': {'widget_0': 'gemma_3_12B_it_fp8_e4m3fn.safetensors',
                    'widget_1': 'ltx-2-19b-distilled.safetensors',
                    'widget_2': 1024}},
 '305': {'class_type': 'VAELoaderKJ',
         'inputs': {'widget_0': 'LTX2_video_vae_2_bf16.safetensors', 'widget_1': 'main_device', 'widget_2': 'bf16'}},
 '322': {'class_type': 'IAMCCS_ModelWithLoRA_LTX2', 'inputs': {'model': ['301', 0], 'lora': ['321', 0]}},
 '303': {'class_type': 'DualCLIPLoader',
         'inputs': {'widget_0': 'gemma_3_12B_it_fp8_e4m3fn.safetensors',
                    'widget_1': 'ltx-2-19b-embeddings_connector_dev_bf16.safetensors',
                    'widget_2': 'ltxv',
                    'widget_3': 'default'}},
 '387': {'class_type': 'LTXVAudioVAEEncode', 'inputs': {'audio': ['362', 0], 'audio_vae': ['452', 0]}},
 '388': {'class_type': 'SolidMask',
         'inputs': {'widget_0': 0, 'widget_1': 512, 'widget_2': 512, 'width': ['241', 1], 'height': ['241', 2]}},
 '348': {'class_type': 'FL_ChatterboxTurboTTS',
         'inputs': {'widget_0': 'Hello! I am a goblin <laugh>  a real goblin. <sarcastic>  Are You a real human?',
                    'widget_1': 0.8,
                    'widget_2': 1000,
                    'widget_3': 0.95,
                    'widget_4': 1.2,
                    'widget_5': 42,
                    'widget_6': 'fixed',
                    'widget_7': False,
                    'widget_8': True,
                    'audio_prompt': ['347', 0]}},
 '409': {'class_type': 'Audio To Text (mtb)',
         'inputs': {'widget_0': 'auto', 'widget_1': False, 'pipeline': ['433', 0], 'audio': ['365', 0]}},
 '433': {'class_type': 'Load Whisper (mtb)', 'inputs': {'widget_0': 'tiny', 'widget_1': True}},
 '370': {'class_type': 'ShowText|pysssss',
         'inputs': {'widget_0': ' Hey, how are you? Well, I suppose you already know me, but wait a moment. Are human? '
                                "I mean, I am not. So I've been thinking about it all day. Believe me.",
                    'text': ['410', 0]}},
 '410': {'class_type': 'easy cleanGpuUsed', 'inputs': {'anything': ['409', 0]}},
 '377': {'class_type': 'MelBandRoFormerModelLoader', 'inputs': {'widget_0': 'MelBandRoformer_fp32.safetensors'}},
 '365': {'class_type': 'MelBandRoFormerSampler', 'inputs': {'model': ['377', 0], 'audio': ['441', 0]}},
 '362': {'class_type': 'SetNode', 'inputs': {'widget_0': 'audio_vocals', 'AUDIO': ['365', 0]}},
 '379': {'class_type': 'FB_Qwen3TTSVoiceClonePrompt',
         'inputs': {'widget_0': '',
                    'widget_1': '1.7B',
                    'widget_2': 'auto',
                    'widget_3': 'fp32',
                    'widget_4': 'sage_attn',
                    'widget_5': True,
                    'widget_6': True,
                    'ref_audio': ['366', 0],
                    'ref_text': ['373', 0]}},
 '363': {'class_type': 'Audio Duration (mtb)', 'inputs': {'audio': ['441', 0]}},
 '243': {'class_type': 'LoadAudio', 'inputs': {'widget_0': 'man voice 1.mp3'}},
 '380': {'class_type': 'PreviewAudio', 'inputs': {'audio': ['362', 0]}},
 '290': {'class_type': 'Seed (rgthree)',
         'inputs': {'widget_0': 923615063061116, 'widget_1': '', 'widget_2': '', 'widget_3': ''}},
 '166': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['239', 0], 'audio_latent': ['389', 0]}},
 '245': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['474', 0]}},
 '384': {'class_type': 'CR Float To Integer', 'inputs': {'_float': ['382', 0]}},
 '239': {'class_type': 'LTXVImgToVideoInplace',
         'inputs': {'widget_0': 0.8, 'widget_1': False, 'vae': ['893', 2], 'image': ['269', 0], 'latent': ['162', 0]}},
 '389': {'class_type': 'SetLatentNoiseMask', 'inputs': {'samples': ['387', 0], 'mask': ['388', 0]}},
 '375': {'class_type': 'IAMCCS_HwSupporterAny',
         'inputs': {'widget_0': 'low_vram',
                    'widget_1': True,
                    'widget_2': 'auto_used_plus',
                    'widget_3': 1.25,
                    'widget_4': 1,
                    'widget_5': 0,
                    'widget_6': 'auto',
                    'widget_7': 'auto',
                    'widget_8': True,
                    'widget_9': True,
                    'widget_10': False,
                    'widget_11': 'overwrite',
                    'widget_12': 'run',
                    'widget_13': 'copy',
                    'widget_14': 'copy',
                    'widget_15': True,
                    'input': ['379', 0]}},
 '311': {'class_type': 'VAELoaderKJ',
         'inputs': {'widget_0': 'LTX2_audio_vae_bf16.safetensors', 'widget_1': 'main_device', 'widget_2': 'bf16'}},
 '451': {'class_type': 'IAMCCS_MultiSwitch',
         'inputs': {'widget_0': 'input_03', 'widget_1': True, 'input_01': ['416', 0], 'input_02': ['322', 0]}},
 '475': {'class_type': 'IAMCCS_GGUF_accelerator',
         'inputs': {'widget_0': 'auto_oom_safe',
                    'widget_1': True,
                    'widget_2': True,
                    'widget_3': 1500,
                    'widget_4': True,
                    'widget_5': 'all_or_nothing',
                    'widget_6': 1024,
                    'model': ['451', 0]}},
 '453': {'class_type': 'IAMCCS_MultiSwitch',
         'inputs': {'widget_0': 'VAE h', 'widget_1': True, 'input_01': ['413', 2], 'input_02': ['305', 0]}},
 '454': {'class_type': 'IAMCCS_MultiSwitch',
         'inputs': {'widget_0': 'CLIP L', 'widget_1': True, 'input_01': ['412', 0], 'input_02': ['303', 0]}},
 '275': {'class_type': 'PreviewImage', 'inputs': {'images': ['241', 0]}},
 '457': {'class_type': 'IAMCCS_AutoLinkArguments',
         'inputs': {'widget_0': False,
                    'widget_1': False,
                    'widget_2': False,
                    'widget_3': True,
                    'widget_4': False,
                    'widget_5': 'None',
                    'widget_6': '',
                    'widget_7': 'TopToDown',
                    'widget_8': 'AvoidAll',
                    'widget_9': True,
                    'widget_10': 'Orange',
                    'widget_11': 'Green',
                    'widget_12': 'Gray',
                    'widget_13': 'White',
                    'widget_14': '',
                    'widget_15': '',
                    'widget_16': 'both',
                    'widget_18': ''}},
 '474': {'class_type': 'IAMCCS_SamplerAdvancedVersion1',
         'inputs': {'widget_0': True,
                    'widget_1': True,
                    'noise': ['178', 0],
                    'guider': ['153', 0],
                    'sampler': ['154', 0],
                    'sigmas': ['238', 0],
                    'latent_image': ['166', 0]}},
 '178': {'class_type': 'RandomNoise',
         'inputs': {'widget_0': 24838260293478, 'widget_1': 'fixed', 'noise_seed': ['290', 0]}},
 '153': {'class_type': 'CFGGuider',
         'inputs': {'widget_0': 2.5, 'model': ['893', 0], 'positive': ['164', 0], 'negative': ['164', 1]}},
 '154': {'class_type': 'KSamplerSelect', 'inputs': {'widget_0': 'lcm'}},
 '238': {'class_type': 'BasicScheduler',
         'inputs': {'steps': 1, 'widget_0': 1, 'widget_1': 8, 'widget_2': 1, 'model': ['893', 0]}},
 '164': {'class_type': 'LTXVConditioning',
         'inputs': {'widget_0': 8, 'positive': ['169', 0], 'negative': ['165', 0], 'frame_rate': ['382', 0]}},
 '467': {'class_type': 'SamplerCustomAdvanced', 'inputs': {}},
 '452': {'class_type': 'IAMCCS_MultiSwitch',
         'inputs': {'widget_0': 'VAE AUDIO LOW', 'widget_1': True, 'input_01': ['411', 0], 'input_02': ['311', 0]}},
 '165': {'class_type': 'CLIPTextEncode',
         'inputs': {'widget_0': 'blurry, out of focus, overexposed, underexposed, low contrast, washed out colors, '
                                'excessive noise, grainy texture, poor lighting, flickering, motion blur, distorted '
                                'proportions, unnatural skin tones, deformed facial features, asymmetrical face, '
                                'missing facial features, extra limbs, disfigured hands, wrong hand count, artifacts '
                                'around text, unreadable text on shirt or hat, incorrect lettering on cap (“PNTR”), '
                                'incorrect t-shirt slogan (“JUST DO IT”), missing microphone, misplaced microphone, '
                                'inconsistent perspective, camera shake, incorrect depth of field, background too '
                                'sharp, background clutter, distracting reflections, harsh shadows, inconsistent '
                                'lighting direction, color banding, cartoonish rendering, 3D CGI look, unrealistic '
                                'materials, uncanny valley effect, incorrect ethnicity, wrong gender, exaggerated '
                                'expressions, smiling, laughing, exaggerated sadness, wrong gaze direction, eyes '
                                'looking at camera, mismatched lip sync, silent or muted audio, distorted voice, '
                                'robotic voice, echo, background noise, off-sync audio, missing sniff sounds, '
                                'incorrect dialogue, added dialogue, repetitive speech, jittery movement, awkward '
                                'pauses, incorrect timing, unnatural transitions, inconsistent framing, tilted camera, '
                                'missing door or shelves, missing shallow depth of field, flat lighting, inconsistent '
                                'tone, cinematic oversaturation, stylized filters, or AI artifacts.',
                    'clip': ['893', 1]}},
 '169': {'class_type': 'CLIPTextEncode', 'inputs': {'widget_0': '', 'clip': ['893', 1], 'text': ['293', 0]}},
 '382': {'class_type': 'PrimitiveFloat', 'inputs': {'widget_0': 8}},
 '241': {'class_type': 'ImageResizeKJv2',
         'inputs': {'widget_0': 720,
                    'widget_1': 1280,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'top',
                    'widget_6': 32,
                    'widget_7': 'cpu',
                    'image': ['240', 0]}},
 '450': {'class_type': 'IAMCCS_bus_group',
         'inputs': {'widget_0': 'groups',
                    'widget_1': True,
                    'widget_2': False,
                    'widget_3': 'models',
                    'widget_4': '',
                    'widget_5': False,
                    'widget_7': '',
                    'widget_8': 'none',
                    'widget_10': False,
                    'widget_11': False,
                    'widget_12': False}},
 '293': {'class_type': 'Text Multiline', 'inputs': {'widget_0': 'video of a goblin talking to the camera'}},
 '374': {'class_type': 'FB_Qwen3TTSVoiceClone',
         'inputs': {'widget_0': 'this is only a test! check it out!',
                    'widget_1': '1.7B',
                    'widget_2': 'auto',
                    'widget_3': 'bf16',
                    'widget_4': 'Auto',
                    'widget_5': '',
                    'widget_6': 663647919912928,
                    'widget_7': 'fixed',
                    'widget_8': 2048,
                    'widget_9': 0.8,
                    'widget_10': 20,
                    'widget_11': 1,
                    'widget_12': 1.05,
                    'widget_13': True,
                    'widget_14': 'auto',
                    'widget_15': True,
                    'ref_audio': ['366', 0],
                    'voice_clone_prompt': ['375', 0],
                    'ref_text': ['373', 0]}},
 '376': {'class_type': 'LoadAudio', 'inputs': {'widget_0': 'EdgarLetfall.mp3'}},
 '240': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'ComfyUI_00126_.png', 'widget_1': 'image'}},
 '321': {'class_type': 'IAMCCS_LTX2_LoRAStack',
         'inputs': {'widget_0': 'ltx-2-19b-distilled-lora-384.safetensors',
                    'widget_1': 0.7,
                    'widget_2': 'ltx-2-19b-lora-camera-control-static.safetensors',
                    'widget_3': 1,
                    'widget_4': 'no',
                    'widget_5': 0}},
 '373': {'class_type': 'ShowText|pysssss',
         'inputs': {'widget_0': ' How are you? I am from metallurgia, Elfica, a fantasy tale from our dear. Welcome to '
                                'our show. And sit down and listen carefully.',
                    'text': ['407', 0]}},
 '407': {'class_type': 'easy cleanGpuUsed', 'inputs': {'anything': ['406', 0]}},
 '406': {'class_type': 'Audio To Text (mtb)',
         'inputs': {'widget_0': 'auto', 'widget_1': False, 'pipeline': ['405', 0], 'audio': ['376', 0]}},
 '405': {'class_type': 'Load Whisper (mtb)', 'inputs': {'widget_0': 'tiny', 'widget_1': True}},
 '456': {'class_type': 'IAMCCS_AutoLinkConverter', 'inputs': {'arg': ['457', 0]}},
 '441': {'class_type': 'IAMCCS_MultiSwitch',
         'inputs': {'widget_0': 'input_6',
                    'widget_1': True,
                    'input_01': ['243', 0],
                    'input_03': ['348', 0],
                    'input_05': ['374', 0]}},
 '364': {'class_type': 'MathExpression|pysssss',
         'inputs': {'widget_0': '((a*0.001)*b)', 'a': ['363', 0], 'b': ['384', 0]}},
 '893': {'class_type': 'IAMCCS_HwSupporter',
         'inputs': {'widget_0': 'auto',
                    'widget_1': True,
                    'widget_2': 'manual',
                    'widget_3': 0,
                    'widget_4': 1,
                    'widget_5': 0,
                    'widget_6': 'auto',
                    'widget_7': False,
                    'widget_8': 'off',
                    'widget_9': 'auto',
                    'widget_10': 'auto',
                    'widget_11': False,
                    'widget_12': True,
                    'widget_13': False,
                    'widget_14': 'overwrite',
                    'widget_15': '(not probed)',
                    'widget_16': 'run',
                    'widget_17': 'copy',
                    'widget_18': True,
                    'model': ['475', 0],
                    'clip': ['454', 0],
                    'vae': ['453', 0]}},
 '974': {'class_type': 'ShowText|pysssss', 'inputs': {'text': ['893', 3]}},
 '448': {'class_type': 'IAMCCS_bus_group',
         'inputs': {'widget_0': 'both',
                    'widget_1': False,
                    'widget_2': True,
                    'widget_3': '',
                    'widget_4': '',
                    'widget_5': False,
                    'widget_7': '',
                    'widget_8': 'none',
                    'widget_9': False}},
 '234': {'class_type': 'IAMCCS_VAEDecodeTiledSafe',
         'inputs': {'widget_0': True,
                    'widget_1': 'manual',
                    'widget_2': 512,
                    'widget_3': 32,
                    'widget_4': 64,
                    'widget_5': 32,
                    'widget_6': True,
                    'widget_7': 'overwrite',
                    'widget_8': 'run',
                    'widget_9': 'copy',
                    'widget_10': 'copy',
                    'samples': ['245', 0],
                    'vae': ['893', 2]}},
 '190': {'class_type': 'VHS_VideoCombine', 'inputs': {'images': ['234', 0], 'audio': ['441', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4446},
 'ready_template': 'video/ltx2_3_iamccs_audio_image_to_video',
 'workflow_template': 'ltx2_3_iamccs_audio_image_to_video',
 'capability': 'audio_image_to_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/iamccs/IAMCCS_LTX2_AU_IMG2V.json',
 'coverage_tier': 'supplemental',
 'approach': 'audio plus image-to-video',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until their custom '
                        'node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-GGUF', 'ComfyUI-KJNodes', 'ComfyUI-LTXVideo', 'ComfyUI-VideoHelperSuite']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/ltx2_3_iamccs_audio_image_to_video"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
