from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'3059': {'class_type': 'EmptyLTXVLatentVideo',
          'inputs': {'width': 256,
                     'height': 256,
                     'length': ['4988', 0],
                     'widget_0': 256,
                     'widget_1': 256,
                     'widget_2': 5,
                     'widget_3': 1}},
 '3980': {'class_type': 'LTXVEmptyLatentAudio',
          'inputs': {'frames_number': ['4988', 0],
                     'frame_rate': ['5000', 0],
                     'widget_0': 5,
                     'widget_1': 8,
                     'widget_2': 1,
                     'audio_vae': ['4010', 0]}},
 '4528': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['3159', 0], 'audio_latent': ['3980', 0]}},
 '3159': {'class_type': 'LTXVImgToVideoConditionOnly',
          'inputs': {'widget_0': 0.7,
                     'widget_1': False,
                     'vae': ['3940', 2],
                     'image': ['3336', 0],
                     'latent': ['3059', 0],
                     'bypass': ['4987', 0]}},
 '1241': {'class_type': 'LTXVConditioning',
          'inputs': {'widget_0': 8, 'positive': ['2483', 0], 'negative': ['2612', 0], 'frame_rate': ['4989', 0]}},
 '4976': {'class_type': 'KSamplerSelect', 'inputs': {'widget_0': 'euler_cfg_pp'}},
 '4971': {'class_type': 'SamplerCustomAdvanced',
          'inputs': {'noise': ['4967', 0],
                     'guider': ['4964', 0],
                     'sampler': ['4976', 0],
                     'sigmas': ['4985', 0],
                     'latent_image': ['4969', 0]}},
 '4964': {'class_type': 'CFGGuider',
          'inputs': {'widget_0': 2.5, 'model': ['4922', 0], 'positive': ['1241', 0], 'negative': ['1241', 1]}},
 '4980': {'class_type': 'GemmaAPITextEncode',
          'inputs': {'widget_0': '',
                     'widget_1': '',
                     'widget_2': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_3': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'api_key': ['4979', 0]}},
 '4979': {'class_type': 'PrimitiveString', 'inputs': {'widget_0': ''}},
 '3336': {'class_type': 'LTXVPreprocess', 'inputs': {'widget_0': 18, 'image': ['4990', 0]}},
 '2612': {'class_type': 'CLIPTextEncode',
          'inputs': {'widget_0': 'pc game, console game, video game, cartoon, childish, ugly', 'clip': ['4982', 0]}},
 '4832': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 43, 'widget_1': 'fixed'}},
 '4828': {'class_type': 'CFGGuider',
          'inputs': {'widget_0': 2.5, 'model': ['4922', 0], 'positive': ['1241', 0], 'negative': ['1241', 1]}},
 '4831': {'class_type': 'KSamplerSelect', 'inputs': {'widget_0': 'euler_ancestral_cfg_pp'}},
 '4829': {'class_type': 'SamplerCustomAdvanced',
          'inputs': {'noise': ['4832', 0],
                     'guider': ['4828', 0],
                     'sampler': ['4831', 0],
                     'sigmas': ['4984', 0],
                     'latent_image': ['4528', 0]}},
 '4967': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 42, 'widget_1': 'fixed'}},
 '4984': {'class_type': 'ManualSigmas',
          'inputs': {'widget_0': '1.0, 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0'}},
 '4985': {'class_type': 'ManualSigmas', 'inputs': {'widget_0': '0.85, 0.7250, 0.4219, 0.0'}},
 '4969': {'class_type': 'LTXVConcatAVLatent', 'inputs': {'video_latent': ['4970', 0], 'audio_latent': ['4845', 1]}},
 '4970': {'class_type': 'LTXVImgToVideoConditionOnly',
          'inputs': {'widget_0': 1,
                     'widget_1': False,
                     'vae': ['3940', 2],
                     'image': ['4990', 0],
                     'latent': ['4845', 0],
                     'bypass': ['4987', 0]}},
 '4989': {'class_type': 'PrimitiveFloat', 'inputs': {'widget_0': 8}},
 '4988': {'class_type': 'PrimitiveInt', 'inputs': {'widget_0': 5, 'widget_1': 'fixed'}},
 '4981': {'class_type': 'GemmaAPITextEncode',
          'inputs': {'widget_0': '',
                     'widget_1': 384,
                     'widget_2': False,
                     'widget_3': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'api_key': ['4979', 0]}},
 '4990': {'class_type': 'ResizeImageMaskNode',
          'inputs': {'widget_0': 'scale longer dimension',
                     'widget_1': 256,
                     'widget_2': 'lanczos',
                     'input': ['2004', 0]}},
 '4010': {'class_type': 'LowVRAMAudioVAELoader', 'inputs': {'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors'}},
 '3940': {'class_type': 'LowVRAMCheckpointLoader', 'inputs': {'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors'}},
 '4922': {'class_type': 'LoraLoaderModelOnly',
          'inputs': {'widget_0': 'ltxv/ltx2/ltx-2.3-22b-distilled-lora-384-1.1.safetensors',
                     'widget_1': 0.5,
                     'model': ['3940', 0]}},
 '4982': {'class_type': 'LTXAVTextEncoderLoader',
          'inputs': {'text_encoder': 'gemma_3_12B_it_fp4_mixed.safetensors',
                     'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_0': 'gemma_3_12B_it_fp4_mixed.safetensors',
                     'widget_1': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_2': 'default'}},
 '4845': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['4829', 0]}},
 '4973': {'class_type': 'LTXVSeparateAVLatent', 'inputs': {'av_latent': ['4971', 0]}},
 '4848': {'class_type': 'LTXVAudioVAEDecode', 'inputs': {'samples': ['4973', 1], 'audio_vae': ['4010', 0]}},
 '4849': {'class_type': 'CreateVideo',
          'inputs': {'fps': ['4989', 0], 'widget_0': 8, 'images': ['4995', 0], 'audio': ['4848', 0]}},
 '4852': {'class_type': 'SaveVideo',
          'inputs': {'widget_0': 'output', 'widget_1': 'auto', 'widget_2': 'auto', 'video': ['4849', 0]}},
 '4995': {'class_type': 'LTXVTiledVAEDecode',
          'inputs': {'widget_0': 2,
                     'widget_1': 2,
                     'widget_2': 6,
                     'widget_3': False,
                     'widget_4': 'auto',
                     'widget_5': 'auto',
                     'vae': ['3940', 2],
                     'latents': ['4973', 0]}},
 '4999': {'class_type': 'Note',
          'inputs': {'widget_0': 'Do explore various samplers and cfg values (although we advise them to be kept close '
                                 'to 1)'}},
 '4997': {'class_type': 'Note',
          'inputs': {'widget_0': 'Make sure to adjust the number of tiles and overlap to fit your hardware.\n'
                                 '(fewer tiles will result in faster execution, but will require more memory) '}},
 '2483': {'class_type': 'CLIPTextEncode',
          'inputs': {'widget_0': 'A traditional Japanese tea ceremony takes place in a tatami room as a host carefully '
                                 'prepares matcha. Soft traditional koto music plays in the background, adding to the '
                                 'serene atmosphere. The bamboo whisk taps rhythmically against the ceramic bowl while '
                                 'water simmers in an iron kettle. Guests kneel in formal seiza position, watching in '
                                 'respectful silence. The host bows and presents the tea bowl, turning it precisely '
                                 'before offering it to the first guest with soft-spoken words.',
                     'clip': ['4982', 0]}},
 '2004': {'class_type': 'LoadImage',
          'inputs': {'image': 'example.png', 'widget_0': 'example.png', 'widget_1': 'image'}},
 '4987': {'class_type': 'PrimitiveBoolean', 'inputs': {'widget_0': True}},
 '5000': {'class_type': 'LTXFloatToInt', 'inputs': {'widget_0': 0, 'a': ['4989', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 3779},
 'ready_template': 'video/ltx2_3_lightricks_two_stage',
 'workflow_template': 'ltx2_3_lightricks_two_stage',
 'capability': 'text_or_image_to_video_upscale',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/lightricks_2_3/LTX-2.3_T2V_I2V_Two_Stage_Distilled.json',
 'coverage_tier': 'required',
 'approach': 'official two-stage low-VRAM T2V/I2V with latent spatial upscaler',
 'runtime_note': None,
 'discord_signal': 'Longer clips and upscale passes were recurring LTX channel themes.',
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until their custom '
                        'node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-LTXVideo']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/ltx2_3_lightricks_two_stage"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
