from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'1241': {'class_type': 'LTXVConditioning',
          'inputs': {'widget_0': 8, 'positive': ['2483', 0], 'negative': ['2612', 0], 'frame_rate': ['5105', 2]}},
 '4828': {'class_type': 'CFGGuider',
          'inputs': {'widget_0': 2.5, 'model': ['5011', 0], 'positive': ['5012', 0], 'negative': ['5012', 1]}},
 '4832': {'class_type': 'RandomNoise', 'inputs': {'widget_0': 42, 'widget_1': 'fixed'}},
 '5022': {'class_type': 'PrimitiveString', 'inputs': {'widget_0': ''}},
 '4831': {'class_type': 'KSamplerSelect', 'inputs': {'widget_0': 'euler_ancestral'}},
 '5023': {'class_type': 'LTXAVTextEncoderLoader',
          'inputs': {'text_encoder': 'gemma_3_12B_it_fp4_mixed.safetensors',
                     'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_0': 'gemma_3_12B_it_fp4_mixed.safetensors',
                     'widget_1': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_2': 'default'}},
 '5108': {'class_type': 'CreateVideo',
          'inputs': {'fps': 8, 'widget_0': 8, 'images': ['5114', 1], 'audio': ['5105', 1]}},
 '4829': {'class_type': 'SamplerCustomAdvanced',
          'inputs': {'noise': ['4832', 0],
                     'guider': ['4828', 0],
                     'sampler': ['4831', 0],
                     'sigmas': ['5025', 0],
                     'latent_image': ['5012', 2]}},
 '5025': {'class_type': 'ManualSigmas',
          'inputs': {'widget_0': '1.0, 0.99375, 0.9875, 0.98125, 0.975, 0.909375, 0.725, 0.421875, 0.0'}},
 '5013': {'class_type': 'LTXVCropGuides',
          'inputs': {'positive': ['5012', 0], 'negative': ['5012', 1], 'latent': ['4829', 0]}},
 '5109': {'class_type': 'SaveVideo',
          'inputs': {'widget_0': 'output', 'widget_1': 'auto', 'widget_2': 'auto', 'video': ['5108', 0]}},
 '5111': {'class_type': 'SimpleMath+', 'inputs': {'widget_0': 'a*32', 'a': ['5011', 1]}},
 '5029': {'class_type': 'GetImageSize', 'inputs': {'image': ['5112', 0]}},
 '5112': {'class_type': 'ResizeImageMaskNode',
          'inputs': {'widget_0': 'scale to multiple',
                     'widget_1': 256,
                     'widget_2': 'lanczos',
                     'input': ['5105', 0],
                     'resize_type.multiple': ['5111', 0]}},
 '5105': {'class_type': 'GetVideoComponents', 'inputs': {'video': ['5106', 0]}},
 '3059': {'class_type': 'EmptyLTXVLatentVideo',
          'inputs': {'width': ['5029', 0],
                     'height': ['5029', 1],
                     'length': ['5029', 2],
                     'widget_0': 256,
                     'widget_1': 256,
                     'widget_2': 5,
                     'widget_3': 1}},
 '5012': {'class_type': 'LTXAddVideoICLoRAGuide',
          'inputs': {'widget_0': 0,
                     'widget_1': 1,
                     'widget_2': 1,
                     'widget_3': 'disabled',
                     'widget_4': False,
                     'widget_5': 128,
                     'widget_6': 32,
                     'positive': ['1241', 0],
                     'negative': ['1241', 1],
                     'vae': ['3940', 2],
                     'latent': ['3059', 0],
                     'image': ['5112', 0]}},
 '5117': {'class_type': 'Note',
          'inputs': {'widget_0': 'Set OPENCV_IO_ENABLE_OPENEXR=1 in your shell before launching ComfyUI, otherwise '
                                 'save_exr will fail'}},
 '5118': {'class_type': 'Note',
          'inputs': {'widget_0': "EXR output is best viewed in DJV — standard image viewers won't display linear HDR "
                                 'correctly.'}},
 '5119': {'class_type': 'Note',
          'inputs': {'widget_0': 'equires ltx-2.3-22b-ic-lora-hdr-0.9.safetensors from '
                                 'Lightricks/LTX-2.3-22b-IC-LoRA-HDR. Place in models/loras/'}},
 '5113': {'class_type': 'Note',
          'inputs': {'widget_0': 'The flow will generate the closest 8XF-1 in the input video length\n'
                                 '\n'
                                 'Expected runinng times on H1 machine\n'
                                 '\n'
                                 'Full HD 1080*1920\n'
                                 ' 161 frames 100 secs\n'
                                 ' 241 frames 152 secs\n'
                                 ' \n'
                                 '\n'
                                 '\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0\xa0'}},
 '5011': {'class_type': 'LTXICLoRALoaderModelOnly',
          'inputs': {'lora_name': 'ltx-2.3-22b-ic-lora-hdr-0.9.safetensors',
                     'widget_0': 'ltx-2.3-22b-ic-lora-hdr-0.9.safetensors',
                     'widget_1': 1,
                     'model': ['5125', 0]}},
 '5125': {'class_type': 'LTXICLoRALoaderModelOnly',
          'inputs': {'lora_name': 'ltx-2.3-22b-distilled-lora-384-1.1.safetensors',
                     'widget_0': 'ltx-2.3-22b-distilled-lora-384-1.1.safetensors',
                     'widget_1': 0.5,
                     'model': ['3940', 0]}},
 '3940': {'class_type': 'LowVRAMCheckpointLoader', 'inputs': {'ckpt_name': 'ltx-2.3-22b-dev-fp8.safetensors'}},
 '5114': {'class_type': 'LTXVHDRDecodePostprocess',
          'inputs': {'widget_0': 7.1,
                     'widget_1': True,
                     'widget_2': 'output/hdr_exr3',
                     'widget_3': 'frame',
                     'widget_4': True,
                     'image': ['4851', 0]}},
 '5121': {'class_type': 'Note', 'inputs': {'widget_0': 'in case of OOM use tile_size of 768\ntemporal size 16'}},
 '4851': {'class_type': 'VAEDecodeTiled',
          'inputs': {'widget_0': 768,
                     'widget_1': 256,
                     'widget_2': 8,
                     'widget_3': 4,
                     'samples': ['5013', 2],
                     'vae': ['3940', 2]}},
 '5120': {'class_type': 'Note',
          'inputs': {'widget_0': 'Exposure adjusts the SDR preview only (in stops, ±10 EV). Does not affect hdr_linear '
                                 'or the saved EXR.'}},
 '5020': {'class_type': 'GemmaAPITextEncode',
          'inputs': {'widget_0': '',
                     'widget_1': 'pc game, console game, video game, cartoon, childish, ugly',
                     'widget_2': False,
                     'widget_3': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'api_key': ['5022', 0]}},
 '5021': {'class_type': 'GemmaAPITextEncode',
          'inputs': {'widget_0': '',
                     'widget_1': '',
                     'widget_2': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'widget_3': 'ltx-2.3-22b-dev-fp8.safetensors',
                     'api_key': ['5022', 0]}},
 '2483': {'class_type': 'CLIPTextEncode', 'inputs': {'widget_0': 'HDR footage', 'clip': ['5023', 0]}},
 '2612': {'class_type': 'CLIPTextEncode',
          'inputs': {'widget_0': 'pc game, console game, video game, ugly, still, static, slow', 'clip': ['5023', 0]}},
 '5106': {'class_type': 'LoadVideo',
          'inputs': {'file': 'ltx_smoke_guide.mp4',
                     'video': 'ltx_smoke_guide.mp4',
                     'widget_0': 'ltx_smoke_guide.mp4',
                     'widget_1': 'image'}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 3853},
 'ready_template': 'video/ltx2_3_lightricks_iclora_hdr',
 'workflow_template': 'ltx2_3_lightricks_iclora_hdr',
 'capability': 'video_guided_hdr',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/ltxvideo/lightricks_2_3/LTX-2.3_ICLoRA_HDR_Distilled.json',
 'coverage_tier': 'required',
 'approach': 'official IC-LoRA HDR video guide',
 'runtime_note': None,
 'discord_signal': 'IC-LoRA, relight/HDR, and guide-video workflows were recurring LTX channel themes.',
 'smoke_resolution': '256x256x5_frames',
 'ltx_best_practices': ['Use the official Lightricks workflows as runtime gates where possible.',
                        'Patch smoke runs to fp8/fp4 model assets, tiny frame counts, and low-VRAM loaders.',
                        'Bypass latent spatial upscalers in smoke runs until HiddenSwitch Comfy exposes '
                        'model_mmap_residency for LatentUpscaleModelManageable.',
                        'Keep community audio, lip-sync, and long-form workflows as ready templates until their custom '
                        'node packs and service credentials are declared.'],
 'comfy_configuration': {'reserve_vram': 12, 'cache_none': True, 'fp8_e4m3fn_text_enc': True}}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-LTXVideo']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/ltx2_3_lightricks_iclora_hdr"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
