from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'46': {'class_type': 'WanVideoTextEmbedBridge', 'inputs': {'positive': ['49', 0], 'negative': ['50', 0]}},
 '50': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'clip': ['48', 0]}},
 '49': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': 'high quality nature video featuring a red panda balancing on a bamboo stem while a '
                               "bird lands on it's head, on the background there is a waterfall",
                   'clip': ['48', 0]}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '85': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '83': {'class_type': 'SetNode', 'inputs': {'widget_0': 'VAE', 'WANVAE': ['38', 0]}},
 '86': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '89': {'class_type': 'GetNode', 'inputs': {'widget_0': 'InputImage'}},
 '63': {'class_type': 'WanVideoImageToVideoEncode',
        'inputs': {'width': ['97', 1],
                   'height': ['97', 2],
                   'num_frames': ['105', 0],
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'widget_3': 0.030000000000000006,
                   'widget_4': 1,
                   'widget_5': 1,
                   'widget_6': True,
                   'widget_7': True,
                   'vae': ['85', 0],
                   'start_image': ['98', 0],
                   'control_embeds': ['104', 0]}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': 'high quality video of an old man',
                   'widget_1': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_2': True,
                   't5': ['11', 0],
                   'model_to_offload': ['22', 0]}},
 '28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'vae': ['86', 0],
                   'samples': ['27', 0]}},
 '102': {'class_type': 'CameraPoseVisualizer',
         'inputs': {'widget_0': '',
                    'widget_1': 0.2,
                    'widget_2': 0.3,
                    'widget_3': 1,
                    'widget_4': False,
                    'widget_5': True,
                    'widget_6': False,
                    'cameractrl_poses': ['99', 0]}},
 '52': {'class_type': 'WanVideoTeaCache',
        'inputs': {'widget_0': 0.08000000000000002,
                   'widget_1': 6,
                   'widget_2': -1,
                   'widget_3': 'offload_device',
                   'widget_4': 'true',
                   'widget_5': 'e0'}},
 '90': {'class_type': 'WanVideoExperimentalArgs',
        'inputs': {'widget_0': '',
                   'widget_1': True,
                   'widget_2': False,
                   'widget_3': 0,
                   'widget_4': True,
                   'widget_5': 1,
                   'widget_6': 1.25,
                   'widget_7': 20}},
 '105': {'class_type': 'INTConstant', 'inputs': {'widget_0': 81}},
 '80': {'class_type': 'Reroute', 'inputs': {}},
 '87': {'class_type': 'ImageConcatMulti',
        'inputs': {'widget_0': 3,
                   'widget_1': 'left',
                   'widget_2': True,
                   'widget_3': None,
                   'image_1': ['28', 0],
                   'image_2': ['89', 0],
                   'image_3': ['102', 0]}},
 '58': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'oldman_upscaled.png', 'widget_1': 'image'}},
 '97': {'class_type': 'ImageResizeKJv2',
        'inputs': {'width': 256,
                   'height': 256,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 'lanczos',
                   'widget_3': 'crop',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'center',
                   'widget_6': 16,
                   'image': ['58', 0]}},
 '99': {'class_type': 'ADE_CameraPoseBasic',
        'inputs': {'widget_0': 'Zoom Out',
                   'widget_1': 0.10000000000000002,
                   'widget_2': 40,
                   'frame_length': ['105', 0]}},
 '103': {'class_type': 'PreviewImage', 'inputs': {'images': ['102', 0]}},
 '98': {'class_type': 'SetNode', 'inputs': {'widget_0': 'InputImage', 'IMAGE': ['97', 0]}},
 '104': {'class_type': 'WanVideoFunCameraEmbeds',
         'inputs': {'widget_0': 832,
                    'widget_1': 480,
                    'widget_2': 1,
                    'widget_3': 0,
                    'widget_4': 1,
                    'poses': ['99', 0],
                    'width': ['97', 1],
                    'height': ['97', 2]}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 6,
                   'widget_2': 5,
                   'widget_3': 43,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'unipc',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': '',
                   'widget_10': 'comfy',
                   'widget_11': '',
                   'model': ['22', 0],
                   'text_embeds': ['16', 0],
                   'image_embeds': ['80', 0],
                   'cache_args': ['52', 0],
                   'experimental_args': ['90', 0]}},
 '39': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 15, 'widget_1': False, 'widget_2': False, 'widget_3': True, 'widget_4': 0}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\Wan2.1-Fun-V1.1-1.3B-Control-Camera.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa'}},
 '48': {'class_type': 'CLIPLoader',
        'inputs': {'widget_0': 'umt5_xxl_fp8_e4m3fn_scaled.safetensors', 'widget_1': 'wan', 'widget_2': 'default'}},
 '30': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['87', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 5213},
 'ready_template': 'video/wanvideo_wrapper_21_14b_fun_control_camera',
 'workflow_template': 'wanvideo_wrapper_21_14b_fun_control_camera',
 'capability': 'camera_control_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan21_14b_fun_control_camera.json',
 'coverage_tier': 'supplemental',
 'approach': 'WanVideoFun camera-control workflow',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_21_14b_fun_control_camera"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
