from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'93': {'class_type': 'WanVideoSLG', 'inputs': {'widget_0': '11', 'widget_1': 0, 'widget_2': 1}},
 '94': {'class_type': 'WanVideoOviCFG',
        'inputs': {'widget_0': 3, 'original_text_embeds': ['85', 0], 'ovi_negative_text_embeds': ['96', 1]}},
 '111': {'class_type': 'WanVideoEncode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'widget_5': 0,
                    'widget_6': 1,
                    'vae': ['87', 0],
                    'image': ['110', 0]}},
 '96': {'class_type': 'WanVideoTextEncodeCached',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': '',
                   'widget_3': 'robotic, muffled, echo, distorted',
                   'widget_4': 'disabled',
                   'widget_5': True,
                   'widget_6': 'gpu'}},
 '81': {'class_type': 'WanVideoEmptyEmbeds',
        'inputs': {'width': ['110', 1],
                   'height': ['110', 2],
                   'num_frames': 5,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'extra_latents': ['111', 0]}},
 '12': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo/Ovi/Wan_2_1_Ovi_video_model_bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'widget_5': 'default',
                   'compile_args': ['91', 0],
                   'extra_model': ['78', 0]}},
 '110': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': 256,
                    'height': 256,
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'center',
                    'widget_6': 32,
                    'widget_7': 'cpu',
                    'image': ['109', 0]}},
 '87': {'class_type': 'WanVideoVAELoader', 'inputs': {'widget_0': 'Wan2_2_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '109': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'oldman_upscaled.png', 'widget_1': 'image'}},
 '78': {'class_type': 'WanVideoExtraModelSelect',
        'inputs': {'widget_0': 'WanVideo/Ovi/Wan_2_1_Ovi_audio_model_bf16.safetensors'}},
 '91': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '86': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 'default',
                   'vae': ['87', 0],
                   'samples': ['80', 0]}},
 '90': {'class_type': 'WanVideoDecodeOviAudio', 'inputs': {'mmaudio_vae': ['89', 0], 'samples': ['80', 0]}},
 '118': {'class_type': 'WanVideoEasyCache',
         'inputs': {'widget_0': 0.015, 'widget_1': 10, 'widget_2': -1, 'widget_3': 'offload_device'}},
 '83': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 15,
                   'widget_1': False,
                   'widget_2': False,
                   'widget_3': True,
                   'widget_4': 0,
                   'widget_5': 1,
                   'widget_6': False}},
 '80': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 4,
                   'widget_2': 5,
                   'widget_3': 42,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'unipc',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': False,
                   'widget_10': 'default',
                   'widget_11': 0,
                   'widget_12': -1,
                   'widget_13': False,
                   'model': ['84', 0],
                   'image_embeds': ['81', 0],
                   'text_embeds': ['94', 0],
                   'samples': ['125', 0],
                   'cache_args': ['118', 0],
                   'slg_args': ['93', 0]}},
 '89': {'class_type': 'OviMMAudioVAELoader',
        'inputs': {'widget_0': 'mmaudio_vae_16k_fp32.safetensors',
                   'widget_1': 'mmaudio_vocoder_bigvgan_best_netG_fp32.safetensors',
                   'widget_2': 'fp32'}},
 '108': {'class_type': 'PreviewAudio', 'inputs': {'audio': ['90', 0]}},
 '84': {'class_type': 'WanVideoSetBlockSwap', 'inputs': {'model': ['12', 0], 'block_swap_args': ['83', 0]}},
 '125': {'class_type': 'WanVideoEmptyMMAudioLatents', 'inputs': {'widget_0': 157}},
 '85': {'class_type': 'WanVideoTextEncodeCached',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'A tired old man is very sarcastically saying: <S>Oh great, they are making me talk now '
                               'too.<E>. <AUDCAP>Clear older male voices speaking dialogue, subtle outdoor '
                               'ambience.<ENDAUDCAP>',
                   'widget_3': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_4': 'disabled',
                   'widget_5': False,
                   'widget_6': 'gpu'}},
 '88': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['86', 0], 'audio': ['90', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4588},
 'ready_template': 'video/wanvideo_wrapper_22_5b_ovi_audio_i2v',
 'workflow_template': 'wanvideo_wrapper_22_5b_ovi_audio_i2v',
 'capability': 'audio_image_to_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan22_5b_ovi_audio_i2v.json',
 'coverage_tier': 'supplemental',
 'approach': 'Ovi image-to-video with audio',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_22_5b_ovi_audio_i2v"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
