from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'46': {'class_type': 'WanVideoTextEmbedBridge', 'inputs': {'positive': ['49', 0], 'negative': ['50', 0]}},
 '50': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'clip': ['48', 0]}},
 '48': {'class_type': 'CLIPLoader',
        'inputs': {'widget_0': 'umt5_xxl_fp16.safetensors', 'widget_1': 'wan', 'widget_2': 'default'}},
 '49': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': 'high quality nature video featuring a red panda balancing on a bamboo stem while a '
                               "bird lands on it's head, on the background there is a waterfall",
                   'clip': ['48', 0]}},
 '11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '70': {'class_type': 'WanVideoEncode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 0,
                   'widget_6': 1,
                   'vae': ['38', 0],
                   'image': ['71', 0]}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_2_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\2_2\\wan2.2_ti2v_5B_fp16.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'compile_args': ['35', 0]}},
 '78': {'class_type': 'WanVideoEmptyEmbeds',
        'inputs': {'width': ['71', 1],
                   'height': ['71', 2],
                   'num_frames': 5,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'extra_latents': ['70', 0]}},
 '58': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'image (658).png', 'widget_1': 'image'}},
 '28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 'default',
                   'vae': ['38', 0],
                   'samples': ['27', 0]}},
 '90': {'class_type': 'WanVideoExperimentalArgs',
        'inputs': {'widget_0': '',
                   'widget_1': True,
                   'widget_2': False,
                   'widget_3': 0,
                   'widget_4': False,
                   'widget_5': 1,
                   'widget_6': 1.25,
                   'widget_7': 20,
                   'widget_8': True}},
 '94': {'class_type': 'WanVideoEasyCache',
        'inputs': {'widget_0': 0.015, 'widget_1': 10, 'widget_2': -1, 'widget_3': 'offload_device'}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 5,
                   'widget_2': 8,
                   'widget_3': 47,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'flowmatch_pusa',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': '',
                   'widget_10': 'comfy',
                   'widget_11': 0,
                   'widget_12': -1,
                   'widget_13': '',
                   'model': ['22', 0],
                   'image_embeds': ['78', 0],
                   'text_embeds': ['16', 0],
                   'cache_args': ['94', 0],
                   'slg_args': ['91', 0],
                   'experimental_args': ['90', 0]}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': 'the woman starts to play a violin',
                   'widget_1': 'Bright tones, overexposed, static, blurred details, subtitles, style, works, '
                               'paintings, images, static, overall gray, worst quality, low quality, JPEG compression '
                               'residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, '
                               'deformed, disfigured, misshapen limbs, fused fingers, still picture, messy background, '
                               'three legs, many people in the background, walking backwards"',
                   'widget_2': True,
                   'widget_3': False,
                   'widget_4': 'gpu',
                   't5': ['11', 0],
                   'model_to_offload': ['22', 0]}},
 '91': {'class_type': 'WanVideoSLG', 'inputs': {'widget_0': '7,8,9', 'widget_1': 0.1, 'widget_2': 0.7}},
 '92': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['28', 0]}},
 '71': {'class_type': 'ImageResizeKJv2',
        'inputs': {'width': 256,
                   'height': 256,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 'lanczos',
                   'widget_3': 'crop',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'center',
                   'widget_6': 32,
                   'widget_7': 'cpu',
                   'widget_8': '<tr><td>Output: </td><td><b>1</b> x <b>1024</b> x <b>1024 | 12.00MB</b></td></tr>',
                   'image': ['58', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 3534},
 'ready_template': 'video/wanvideo_wrapper_22_5b_i2v',
 'workflow_template': 'wanvideo_wrapper_22_5b_i2v',
 'capability': 'image_to_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan22_5b_i2v.json',
 'coverage_tier': 'supplemental',
 'approach': 'WanVideoWrapper 2.2 5B image-to-video',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_22_5b_i2v"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
