from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'48': {'class_type': 'CLIPLoader',
        'inputs': {'widget_0': 'umt5_xxl_fp16.safetensors', 'widget_1': 'wan', 'widget_2': 'default'}},
 '49': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': 'high quality nature video featuring a red panda balancing on a bamboo stem while a '
                               "bird lands on it's head, on the background there is a waterfall",
                   'clip': ['48', 0]}},
 '45': {'class_type': 'WanVideoVRAMManagement', 'inputs': {'widget_0': 1}},
 '39': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 20, 'widget_1': False, 'widget_2': False, 'widget_3': True, 'widget_4': 0}},
 '28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'vae': ['145', 0],
                   'samples': ['155', 0]}},
 '11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '50': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'clip': ['48', 0]}},
 '129': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['128', 0]}},
 '124': {'class_type': 'DownloadAndLoadFlorence2Model',
         'inputs': {'widget_0': 'MiaoshouAI/Florence-2-base-PromptGen-v2.0', 'widget_1': 'fp16', 'widget_2': 'sdpa'}},
 '130': {'class_type': 'GetImageRangeFromBatch', 'inputs': {'widget_0': 0, 'widget_1': 1, 'images': ['59', 0]}},
 '123': {'class_type': 'Florence2Run',
         'inputs': {'widget_0': '',
                    'widget_1': 'detailed_caption',
                    'widget_2': True,
                    'widget_3': False,
                    'widget_4': 1024,
                    'widget_5': 3,
                    'widget_6': True,
                    'widget_7': '',
                    'widget_8': 1,
                    'widget_9': 'fixed',
                    'image': ['130', 0],
                    'florence2_model': ['124', 0]}},
 '131': {'class_type': 'PreviewImage', 'inputs': {'images': ['130', 0]}},
 '125': {'class_type': 'ShowText|pysssss',
         'inputs': {'widget_0': 'A man in a suit and tie walking down a hallway. He has a friendly expression and is '
                                'looking directly at the camera. The hallway has beige walls adorned with framed black '
                                'and white photographs. There is a door on the left side of the hallway and a poster '
                                'on the wall. The lighting is soft and natural. The image is high quality and has a '
                                'watermark in the bottom right corner.',
                    'widget_1': 'A man in a suit and tie walking down a hallway. He has a friendly expression and is '
                                'looking directly at the camera. The hallway has beige walls adorned with framed black '
                                'and white photographs. There is a door on the left side of the hallway and a poster '
                                'on the wall. The lighting is soft and natural. The image is high quality and has a '
                                'watermark in the bottom right corner.',
                    'text': ['123', 2]}},
 '140': {'class_type': 'SetNode', 'inputs': {'widget_0': 'WanModel', 'WANVIDEOMODEL': ['22', 0]}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': 'video of an autumnal forest scene',
                   'widget_1': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_2': True,
                   't5': ['11', 0],
                   'positive_prompt': ['123', 2]}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '144': {'class_type': 'SetNode', 'inputs': {'widget_0': 'WanVAE', 'WANVAE': ['38', 0]}},
 '145': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanVAE'}},
 '59': {'class_type': 'ImageResizeKJ',
        'inputs': {'widget_0': 832,
                   'widget_1': 480,
                   'widget_2': 'lanczos',
                   'widget_3': False,
                   'widget_4': 16,
                   'widget_5': 'center',
                   'image': ['129', 0]}},
 '147': {'class_type': 'SetNode', 'inputs': {'widget_0': 'InputVideo', 'IMAGE': ['59', 0]}},
 '58': {'class_type': 'WanVideoEncode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 0,
                   'widget_6': 1,
                   'vae': ['146', 0],
                   'image': ['147', 0]}},
 '156': {'class_type': 'SetNode', 'inputs': {'widget_0': 'InputLatents', 'LATENT': ['58', 0]}},
 '139': {'class_type': 'PreviewImage', 'inputs': {'images': ['138', 0]}},
 '128': {'class_type': 'VHS_LoadVideo', 'inputs': {'video': 'wolf_interpolated.mp4'}},
 '122': {'class_type': 'AddLabel',
         'inputs': {'widget_0': 10,
                    'widget_1': 2,
                    'widget_2': 48,
                    'widget_3': 32,
                    'widget_4': 'white',
                    'widget_5': 'black',
                    'widget_6': 'FreeMonoBoldOblique.otf',
                    'widget_7': 'input',
                    'widget_8': 'up',
                    'image': ['28', 0],
                    'text': ['74', 0]}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '127': {'class_type': 'WanVideoExperimentalArgs',
         'inputs': {'widget_0': '', 'widget_1': True, 'widget_2': False, 'widget_3': 0}},
 '141': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanModel'}},
 '143': {'class_type': 'GetNode', 'inputs': {'widget_0': 'TextEmbeds'}},
 '46': {'class_type': 'WanVideoTextEmbedBridge', 'inputs': {'positive': ['49', 0], 'negative': ['50', 0]}},
 '142': {'class_type': 'SetNode', 'inputs': {'widget_0': 'TextEmbeds', 'WANVIDEOTEXTEMBEDS': ['16', 0]}},
 '146': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanVAE'}},
 '155': {'class_type': 'WanVideoSampler',
         'inputs': {'steps': 1,
                    'widget_0': 1,
                    'widget_1': 6,
                    'widget_2': 5,
                    'widget_3': 42,
                    'widget_4': 'fixed',
                    'widget_5': True,
                    'widget_6': 'unipc',
                    'widget_7': 0,
                    'widget_8': 1,
                    'widget_9': False,
                    'widget_10': 'comfy',
                    'model': ['141', 0],
                    'text_embeds': ['143', 0],
                    'image_embeds': ['56', 0],
                    'cache_args': ['52', 0],
                    'experimental_args': ['127', 0]}},
 '52': {'class_type': 'WanVideoTeaCache',
        'inputs': {'widget_0': 0.10000000000000002,
                   'widget_1': 6,
                   'widget_2': -1,
                   'widget_3': 'offload_device',
                   'widget_4': 'true',
                   'widget_5': 'e0'}},
 '30': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['122', 0]}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\Wan2_1_kwai_recammaster_1_3B_step20000_bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa'}},
 '138': {'class_type': 'ReCamMasterPoseVisualizer',
         'inputs': {'widget_0': 0.10000000000000002,
                    'widget_1': 0.20000000000000004,
                    'widget_2': 0.4000000000000001,
                    'widget_3': 0.5000000000000001,
                    'camera_poses': ['56', 1]}},
 '157': {'class_type': 'GetNode', 'inputs': {'widget_0': 'InputLatents'}},
 '56': {'class_type': 'WanVideoReCamMasterCameraEmbed', 'inputs': {'camera_poses': ['205', 0], 'latents': ['157', 0]}},
 '206': {'class_type': 'WanVideoReCamMasterGenerateOrbitCamera', 'inputs': {'widget_0': 81, 'widget_1': 90}},
 '74': {'class_type': 'WidgetToString',
        'inputs': {'widget_0': 0,
                   'widget_1': 'camera_type',
                   'widget_2': False,
                   'widget_3': '',
                   'widget_4': 2,
                   'any_input': ['205', 0]}},
 '205': {'class_type': 'WanVideoReCamMasterDefaultCamera', 'inputs': {'widget_0': 'pan_right', 'latents': ['157', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4285},
 'ready_template': 'video/wanvideo_wrapper_13b_recammaster',
 'workflow_template': 'wanvideo_wrapper_13b_recammaster',
 'capability': 'camera_control_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan13b_recammaster.json',
 'coverage_tier': 'supplemental',
 'approach': 'ReCamMaster camera-control workflow',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_13b_recammaster"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
