from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True}},
 '64': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True}},
 '52': {'class_type': 'WanVideoTeaCache',
        'inputs': {'widget_0': 0.1, 'widget_1': 1, 'widget_2': -1, 'widget_3': 'offload_device', 'widget_4': 'true'}},
 '28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'vae': ['38', 0],
                   'samples': ['27', 0]}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': 'video of a wolf',
                   'widget_1': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_2': True,
                   't5': ['11', 0]}},
 '30': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['103', 0]}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '97': {'class_type': 'VHS_LoadVideo', 'inputs': {'video': 'wolf_interpolated.mp4'}},
 '95': {'class_type': 'WanVideoEncode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 0,
                   'widget_6': 1.0000000000000002,
                   'vae': ['38', 0],
                   'image': ['104', 0]}},
 '104': {'class_type': 'ImageBlur', 'inputs': {'widget_0': 4, 'widget_1': 1, 'image': ['97', 0]}},
 '103': {'class_type': 'ImageConcatMulti',
         'inputs': {'widget_0': 2,
                    'widget_1': 'right',
                    'widget_2': False,
                    'widget_3': None,
                    'image_1': ['104', 0],
                    'image_2': ['28', 0]}},
 '98': {'class_type': 'WanVideoLoraSelect',
        'inputs': {'widget_0': 'WanVid\\wan2.1-1.3b-control-lora-tile-v1.1_comfy.safetensors',
                   'widget_1': 1,
                   'widget_2': False}},
 '96': {'class_type': 'WanVideoControlEmbeds', 'inputs': {'widget_0': 0, 'widget_1': 0.7, 'latents': ['95', 0]}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 6,
                   'widget_2': 5,
                   'widget_3': 0,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'unipc',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': '',
                   'widget_10': 'comfy',
                   'model': ['22', 0],
                   'text_embeds': ['16', 0],
                   'image_embeds': ['96', 0],
                   'cache_args': ['52', 0]}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\wan2.1_t2v_1.3B_fp16.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'lora': ['98', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4407},
 'ready_template': 'video/wanvideo_wrapper_13b_control_lora',
 'workflow_template': 'wanvideo_wrapper_13b_control_lora',
 'capability': 'control_lora_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan13b_control_lora.json',
 'coverage_tier': 'supplemental',
 'approach': 'WanVideoWrapper 1.3B control LoRA',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_13b_control_lora"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
