from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'90': {'class_type': 'WanVideoExperimentalArgs',
        'inputs': {'widget_0': '',
                   'widget_1': True,
                   'widget_2': False,
                   'widget_3': 0,
                   'widget_4': False,
                   'widget_5': 1,
                   'widget_6': 1.25,
                   'widget_7': 20,
                   'widget_8': True,
                   'widget_9': 0}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'Wan2_2-TI2V-5B-FastWanFullAttn_bf16.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'compile_args': ['35', 0]}},
 '103': {'class_type': 'WanVideoControlnetLoader',
         'inputs': {'widget_0': 'wan2.2-ti2v-5b-controlnet-depth-v1/diffusion_pytorch_model.safetensors',
                    'widget_1': 'bf16',
                    'widget_2': 'disabled',
                    'widget_3': 'main_device'}},
 '105': {'class_type': 'WanVideoControlnet',
         'inputs': {'widget_0': 1,
                    'widget_1': 3,
                    'widget_2': 0,
                    'widget_3': 1,
                    'model': ['22', 0],
                    'controlnet': ['103', 0],
                    'control_images': ['109', 0]}},
 '107': {'class_type': 'WanVideoEnhanceAVideo', 'inputs': {'widget_0': 2, 'widget_1': 0, 'widget_2': 1}},
 '94': {'class_type': 'WanVideoEasyCache',
        'inputs': {'widget_0': 0.015, 'widget_1': 10, 'widget_2': -1, 'widget_3': 'offload_device'}},
 '11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '104': {'class_type': 'MiDaS-DepthMapPreprocessor',
         'inputs': {'widget_0': 6.283185307179586, 'widget_1': 0.1, 'widget_2': 512, 'image': ['101', 0]}},
 '109': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': ['117', 0],
                    'height': ['118', 0],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'nearest-exact',
                    'widget_3': 'stretch',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'center',
                    'widget_6': 2,
                    'widget_7': 'cpu',
                    'image': ['104', 0]}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 5,
                   'widget_2': 8,
                   'widget_3': 47,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'flowmatch_pusa',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': '',
                   'widget_10': 'comfy',
                   'widget_11': 0,
                   'widget_12': -1,
                   'widget_13': '',
                   'model': ['105', 0],
                   'image_embeds': ['106', 0],
                   'text_embeds': ['16', 0],
                   'feta_args': ['107', 0],
                   'cache_args': ['94', 0],
                   'slg_args': ['91', 0],
                   'experimental_args': ['90', 0]}},
 '91': {'class_type': 'WanVideoSLG', 'inputs': {'widget_0': '7,8,9', 'widget_1': 0.1, 'widget_2': 0.7}},
 '28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 'default',
                   'vae': ['38', 0],
                   'samples': ['27', 0]}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': 'Close-up shot with soft lighting, focusing sharply on the lower half of a young '
                               "woman's face. Her lips are slightly parted as she blows an enormous bubblegum bubble. "
                               'The bubble is semi-transparent, shimmering gently under the light, and surprisingly '
                               'contains a miniature aquarium inside, where two orange-and-white goldfish slowly swim, '
                               'their fins delicately fluttering as if in an aquatic universe. The background is a '
                               'pure light blue color.',
                   'widget_1': 'Bright tones, overexposed, static, blurred details, subtitles, style, works, '
                               'paintings, images, static, overall gray, worst quality, low quality, JPEG compression '
                               'residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, '
                               'deformed, disfigured, misshapen limbs, fused fingers, still picture, messy background, '
                               'three legs, many people in the background, walking backwards"',
                   'widget_2': True,
                   'widget_3': False,
                   'widget_4': 'gpu',
                   't5': ['11', 0],
                   'model_to_offload': ['105', 0]}},
 '101': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': ['117', 0],
                    'height': ['118', 0],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'nearest-exact',
                    'widget_3': 'stretch',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'center',
                    'widget_6': 2,
                    'widget_7': 'cpu',
                    'image': ['98', 0]}},
 '38': {'class_type': 'WanVideoVAELoader', 'inputs': {'widget_0': 'Wan2_2_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '112': {'class_type': 'PreviewAnimation', 'inputs': {'widget_0': 24, 'images': ['109', 0]}},
 '92': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['28', 0]}},
 '114': {'class_type': 'WanVideoEncode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'widget_5': 0,
                    'widget_6': 1,
                    'vae': ['38', 0],
                    'image': ['113', 0]}},
 '113': {'class_type': 'GetImagesFromBatchIndexed', 'inputs': {'widget_0': '0', 'images': ['101', 0]}},
 '98': {'class_type': 'VHS_LoadVideo', 'inputs': {'video': 'wolf_interpolated.mp4', 'frame_load_cap': ['116', 0]}},
 '106': {'class_type': 'WanVideoEmptyEmbeds',
         'inputs': {'width': ['117', 0],
                    'height': ['118', 0],
                    'num_frames': 5,
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 5,
                    'extra_latents': ['114', 0]}},
 '116': {'class_type': 'INTConstant', 'inputs': {'widget_0': 121}},
 '115': {'class_type': 'PreviewImage', 'inputs': {'images': ['113', 0]}},
 '117': {'class_type': 'INTConstant', 'inputs': {'widget_0': 1280}},
 '118': {'class_type': 'INTConstant', 'inputs': {'widget_0': 704}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4725},
 'ready_template': 'video/wanvideo_wrapper_22_5b_i2v_controlnet',
 'workflow_template': 'wanvideo_wrapper_22_5b_i2v_controlnet',
 'capability': 'image_to_video_controlnet',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan22_5b_i2v_controlnet.json',
 'coverage_tier': 'supplemental',
 'approach': 'WanVideoWrapper 2.2 5B image-to-video ControlNet',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_22_5b_i2v_controlnet"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
