# vibecomfy: manual
"""Kijai WanVideoWrapper workflow bundled as a VibeComfy ready template."""
from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow

API_WORKFLOW = {'11': {'_ui': {'bgcolor': '#593930',
                'color': '#332922',
                'flags': {},
                'id': 11,
                'inputs': [],
                'mode': 0,
                'order': 10,
                'outputs': [{'links': [15], 'name': 'wan_t5_model', 'slot_index': 0, 'type': 'WANTEXTENCODER'}],
                'pos': [205.93421936035156, -21.262622833251953],
                'properties': {'Node name for S&R': 'LoadWanVideoT5TextEncoder',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [377.1661376953125, 130],
                'type': 'LoadWanVideoT5TextEncoder',
                'widgets_values': ['umt5-xxl-enc-bf16.safetensors', 'bf16', 'offload_device', 'disabled']},
        'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '16': {'_ui': {'bgcolor': '#593930',
                'color': '#332922',
                'flags': {},
                'id': 16,
                'inputs': [{'link': 15, 'name': 't5', 'shape': 7, 'type': 'WANTEXTENCODER'},
                           {'link': None, 'name': 'model_to_offload', 'shape': 7, 'type': 'WANVIDEOMODEL'}],
                'mode': 0,
                'order': 18,
                'outputs': [{'links': [30, 152], 'name': 'text_embeds', 'slot_index': 0, 'type': 'WANVIDEOTEXTEMBEDS'}],
                'pos': [675.8850708007812, -36.032100677490234],
                'properties': {'Node name for S&R': 'WanVideoTextEncode',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [474.3573303222656, 316.48370361328125],
                'type': 'WanVideoTextEncode',
                'widgets_values': ['old man gets up and jumps into the lake',
                                   '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                                   True,
                                   False,
                                   'gpu']},
        'class_type': 'WanVideoTextEncode',
        'inputs': {'t5': ['11', 0],
                   'widget_0': 'old man gets up and jumps into the lake',
                   'widget_1': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_2': True,
                   'widget_3': False,
                   'widget_4': 'gpu'}},
 '22': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 22,
                'inputs': [{'link': 111, 'name': 'compile_args', 'shape': 7, 'type': 'WANCOMPILEARGS'},
                           {'link': None, 'name': 'block_swap_args', 'shape': 7, 'type': 'BLOCKSWAPARGS'},
                           {'link': None, 'name': 'lora', 'shape': 7, 'type': 'WANVIDLORA'},
                           {'link': None, 'name': 'vram_management_args', 'shape': 7, 'type': 'VRAM_MANAGEMENTARGS'},
                           {'link': None, 'name': 'vace_model', 'shape': 7, 'type': 'VACEPATH'},
                           {'link': None, 'name': 'fantasytalking_model', 'shape': 7, 'type': 'FANTASYTALKINGMODEL'},
                           {'link': None, 'name': 'multitalk_model', 'shape': 7, 'type': 'MULTITALKMODEL'}],
                'mode': 0,
                'order': 14,
                'outputs': [{'links': [155], 'name': 'model', 'slot_index': 0, 'type': 'WANVIDEOMODEL'}],
                'pos': [-10, -740],
                'properties': {'Node name for S&R': 'WanVideoModelLoader',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [477.4410095214844, 274],
                'type': 'WanVideoModelLoader',
                'widgets_values': ['WanVideo\\2_2\\Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors',
                                   'fp16_fast',
                                   'fp8_e4m3fn_scaled',
                                   'offload_device',
                                   'sageattn']},
        'class_type': 'WanVideoModelLoader',
        'inputs': {'compile_args': ['35', 0],
                   'widget_0': 'WanVideo\\2_2\\Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors',
                   'widget_1': 'fp16_fast',
                   'widget_2': 'fp8_e4m3fn_scaled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sageattn'}},
 '27': {'_ui': {'flags': {},
                'id': 27,
                'inputs': [{'link': 109, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 138, 'name': 'image_embeds', 'type': 'WANVIDIMAGE_EMBEDS'},
                           {'link': 30, 'name': 'text_embeds', 'shape': 7, 'type': 'WANVIDEOTEXTEMBEDS'},
                           {'link': None, 'name': 'samples', 'shape': 7, 'type': 'LATENT'},
                           {'link': None, 'name': 'feta_args', 'shape': 7, 'type': 'FETAARGS'},
                           {'link': None, 'name': 'context_options', 'shape': 7, 'type': 'WANVIDCONTEXT'},
                           {'link': None, 'name': 'cache_args', 'shape': 7, 'type': 'CACHEARGS'},
                           {'link': None, 'name': 'flowedit_args', 'shape': 7, 'type': 'FLOWEDITARGS'},
                           {'link': None, 'name': 'slg_args', 'shape': 7, 'type': 'SLGARGS'},
                           {'link': None, 'name': 'loop_args', 'shape': 7, 'type': 'LOOPARGS'},
                           {'link': None, 'name': 'experimental_args', 'shape': 7, 'type': 'EXPERIMENTALARGS'},
                           {'link': None, 'name': 'sigmas', 'shape': 7, 'type': 'SIGMAS'},
                           {'link': None, 'name': 'unianimate_poses', 'shape': 7, 'type': 'UNIANIMATE_POSE'},
                           {'link': None, 'name': 'fantasytalking_embeds', 'shape': 7, 'type': 'FANTASYTALKING_EMBEDS'},
                           {'link': None, 'name': 'uni3c_embeds', 'shape': 7, 'type': 'UNI3C_EMBEDS'},
                           {'link': None, 'name': 'multitalk_embeds', 'shape': 7, 'type': 'MULTITALK_EMBEDS'},
                           {'link': None, 'name': 'freeinit_args', 'shape': 7, 'type': 'FREEINITARGS'},
                           {'link': 163, 'name': 'steps', 'type': 'INT', 'widget': {'name': 'steps'}},
                           {'link': 167, 'name': 'cfg', 'type': 'FLOAT', 'widget': {'name': 'cfg'}},
                           {'link': 153,
                            'name': 'end_step',
                            'shape': 7,
                            'type': 'INT',
                            'widget': {'name': 'end_step'}}],
                'mode': 0,
                'order': 25,
                'outputs': [{'links': [143], 'name': 'samples', 'slot_index': 0, 'type': 'LATENT'}],
                'pos': [1833.1953125, -394.93426513671875],
                'properties': {'Node name for S&R': 'WanVideoSampler',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [315, 975],
                'type': 'WanVideoSampler',
                'widgets_values': [6, 1, 8, 43, 'fixed', True, 'dpm++_sde', 0, 1, False, 'comfy', 0, 10, '']},
        'class_type': 'WanVideoSampler',
        'inputs': {'cfg': ['95', 0],
                   'end_step': ['91', 0],
                   'image_embeds': ['89', 0],
                   'model': ['80', 0],
                   'steps': ['94', 0],
                   'text_embeds': ['16', 0],
                   'widget_0': 6,
                   'widget_1': 1,
                   'widget_10': 'comfy',
                   'widget_11': 0,
                   'widget_12': 10,
                   'widget_13': '',
                   'widget_2': 8,
                   'widget_3': 43,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'dpm++_sde',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': False}},
 '28': {'_ui': {'bgcolor': '#533',
                'color': '#322',
                'flags': {},
                'id': 28,
                'inputs': [{'link': 43, 'name': 'vae', 'type': 'WANVAE'},
                           {'link': 151, 'name': 'samples', 'type': 'LATENT'}],
                'mode': 0,
                'order': 27,
                'outputs': [{'links': [76], 'name': 'images', 'slot_index': 0, 'type': 'IMAGE'}],
                'pos': [2620.946533203125, -519.3373413085938],
                'properties': {'Node name for S&R': 'WanVideoDecode',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [315, 198],
                'type': 'WanVideoDecode',
                'widgets_values': [False, 272, 272, 144, 128, 'default']},
        'class_type': 'WanVideoDecode',
        'inputs': {'samples': ['90', 0],
                   'vae': ['38', 0],
                   'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 'default'}},
 '35': {'_ui': {'flags': {},
                'id': 35,
                'inputs': [],
                'mode': 0,
                'order': 3,
                'outputs': [{'links': [111, 112],
                             'name': 'torch_compile_args',
                             'slot_index': 0,
                             'type': 'WANCOMPILEARGS'}],
                'pos': [-550, -870],
                'properties': {'Node name for S&R': 'WanVideoTorchCompileSettings',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [390.5999755859375, 202],
                'type': 'WanVideoTorchCompileSettings',
                'widgets_values': ['inductor', False, 'default', False, 64, True, 128]},
        'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '38': {'_ui': {'bgcolor': '#533',
                'color': '#322',
                'flags': {},
                'id': 38,
                'inputs': [],
                'mode': 0,
                'order': 4,
                'outputs': [{'links': [43, 137], 'name': 'vae', 'slot_index': 0, 'type': 'WANVAE'}],
                'pos': [1373.9725341796875, -991.5189208984375],
                'properties': {'Node name for S&R': 'WanVideoVAELoader',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [315, 82],
                'type': 'WanVideoVAELoader',
                'widgets_values': ['wanvideo\\Wan2_1_VAE_bf16.safetensors', 'bf16']},
        'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '39': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 39,
                'inputs': [],
                'mode': 0,
                'order': 11,
                'outputs': [{'links': [156, 159], 'name': 'block_swap_args', 'slot_index': 0, 'type': 'BLOCKSWAPARGS'}],
                'pos': [516.8650512695312, -526.5733642578125],
                'properties': {'Node name for S&R': 'WanVideoBlockSwap',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [315, 154],
                'type': 'WanVideoBlockSwap',
                'widgets_values': [20, False, False, False, 1]},
        'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 20, 'widget_1': False, 'widget_2': False, 'widget_3': False, 'widget_4': 1}},
 '44': {'_ui': {'bgcolor': '#653',
                'color': '#432',
                'flags': {},
                'id': 44,
                'inputs': [],
                'mode': 0,
                'order': 2,
                'outputs': [],
                'pos': [-960, -810],
                'properties': {},
                'size': [303.0501403808594, 88],
                'type': 'Note',
                'widgets_values': ['If you have Triton installed, connect this for ~30% speed increase']},
        'class_type': 'Note',
        'inputs': {'widget_0': 'If you have Triton installed, connect this for ~30% speed increase'}},
 '46': {'_ui': {'flags': {},
                'id': 46,
                'inputs': [{'link': 54, 'name': 'positive', 'type': 'CONDITIONING'},
                           {'link': 55, 'name': 'negative', 'shape': 7, 'type': 'CONDITIONING'}],
                'mode': 2,
                'order': 19,
                'outputs': [{'links': None, 'name': 'text_embeds', 'type': 'WANVIDEOTEXTEMBEDS'}],
                'pos': [804.0042724609375, 662.6546020507812],
                'properties': {'Node name for S&R': 'WanVideoTextEmbedBridge',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [315, 46],
                'type': 'WanVideoTextEmbedBridge',
                'widgets_values': []},
        'class_type': 'WanVideoTextEmbedBridge',
        'inputs': {'negative': ['50', 0], 'positive': ['49', 0]}},
 '48': {'_ui': {'bgcolor': '#653',
                'color': '#432',
                'flags': {},
                'id': 48,
                'inputs': [],
                'mode': 2,
                'order': 0,
                'outputs': [{'links': [52, 53], 'name': 'CLIP', 'slot_index': 0, 'type': 'CLIP'}],
                'pos': [-5.996182441711426, 672.6546020507812],
                'properties': {'Node name for S&R': 'CLIPLoader', 'cnr_id': 'comfy-core', 'ver': '0.3.44'},
                'size': [315, 106],
                'type': 'CLIPLoader',
                'widgets_values': ['umt5_xxl_fp16.safetensors', 'wan', 'default']},
        'class_type': 'CLIPLoader',
        'inputs': {'widget_0': 'umt5_xxl_fp16.safetensors', 'widget_1': 'wan', 'widget_2': 'default'}},
 '49': {'_ui': {'bgcolor': '#653',
                'color': '#432',
                'flags': {},
                'id': 49,
                'inputs': [{'link': 52, 'name': 'clip', 'type': 'CLIP'}],
                'mode': 2,
                'order': 12,
                'outputs': [{'links': [54], 'name': 'CONDITIONING', 'slot_index': 0, 'type': 'CONDITIONING'}],
                'pos': [354.00396728515625, 672.6546020507812],
                'properties': {'Node name for S&R': 'CLIPTextEncode', 'cnr_id': 'comfy-core', 'ver': '0.3.44'},
                'size': [400, 200],
                'type': 'CLIPTextEncode',
                'widgets_values': ['high quality nature video featuring a red panda balancing on a bamboo stem while a '
                                   "bird lands on it's head, on the background there is a waterfall"]},
        'class_type': 'CLIPTextEncode',
        'inputs': {'clip': ['48', 0],
                   'widget_0': 'high quality nature video featuring a red panda balancing on a bamboo stem while a '
                               "bird lands on it's head, on the background there is a waterfall"}},
 '50': {'_ui': {'bgcolor': '#653',
                'color': '#432',
                'flags': {},
                'id': 50,
                'inputs': [{'link': 53, 'name': 'clip', 'type': 'CLIP'}],
                'mode': 2,
                'order': 13,
                'outputs': [{'links': [55], 'name': 'CONDITIONING', 'slot_index': 0, 'type': 'CONDITIONING'}],
                'pos': [354.00396728515625, 922.6547241210938],
                'properties': {'Node name for S&R': 'CLIPTextEncode', 'cnr_id': 'comfy-core', 'ver': '0.3.44'},
                'size': [400, 200],
                'type': 'CLIPTextEncode',
                'widgets_values': ['色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走']},
        'class_type': 'CLIPTextEncode',
        'inputs': {'clip': ['48', 0],
                   'widget_0': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走'}},
 '51': {'_ui': {'bgcolor': '#653',
                'color': '#432',
                'flags': {},
                'id': 51,
                'inputs': [],
                'mode': 0,
                'order': 1,
                'outputs': [],
                'pos': [24.003835678100586, 502.65411376953125],
                'properties': {},
                'size': [253.16725158691406, 88],
                'type': 'Note',
                'widgets_values': ['You can also use native ComfyUI text encoding with these nodes instead of the '
                                   "original, the models are node specific and can't otherwise be mixed."]},
        'class_type': 'Note',
        'inputs': {'widget_0': 'You can also use native ComfyUI text encoding with these nodes instead of the '
                               "original, the models are node specific and can't otherwise be mixed."}},
 '56': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 56,
                'inputs': [{'link': None, 'name': 'prev_lora', 'shape': 7, 'type': 'WANVIDLORA'},
                           {'link': None, 'name': 'blocks', 'shape': 7, 'type': 'SELECTEDBLOCKS'}],
                'mode': 0,
                'order': 9,
                'outputs': [{'links': [110], 'name': 'lora', 'type': 'WANVIDLORA'}],
                'pos': [-765.4373168945312, -481.49810791015625],
                'properties': {'Node name for S&R': 'WanVideoLoraSelect',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [659.4812622070312, 150],
                'type': 'WanVideoLoraSelect',
                'widgets_values': ['WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                                   3,
                                   False,
                                   False]},
        'class_type': 'WanVideoLoraSelect',
        'inputs': {'widget_0': 'WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                   'widget_1': 3,
                   'widget_2': False,
                   'widget_3': False}},
 '60': {'_ui': {'flags': {},
                'id': 60,
                'inputs': [{'link': 77, 'name': 'images', 'type': 'IMAGE'},
                           {'link': None, 'name': 'audio', 'shape': 7, 'type': 'AUDIO'},
                           {'link': None, 'name': 'meta_batch', 'shape': 7, 'type': 'VHS_BatchManager'},
                           {'link': None, 'name': 'vae', 'shape': 7, 'type': 'VAE'}],
                'mode': 0,
                'order': 29,
                'outputs': [{'links': None, 'name': 'Filenames', 'type': 'VHS_FILENAMES'}],
                'pos': [3150, -390],
                'properties': {'Node name for S&R': 'VHS_VideoCombine',
                               'cnr_id': 'comfyui-videohelpersuite',
                               'ver': '0a75c7958fe320efcb052f1d9f8451fd20c730a8'},
                'size': [698.6392211914062, 1026.63916015625],
                'type': 'VHS_VideoCombine',
                'widgets_values': {'crf': 19,
                                   'filename_prefix': 'WanVideo2_2_I2V',
                                   'format': 'video/h264-mp4',
                                   'frame_rate': 16,
                                   'loop_count': 0,
                                   'pingpong': False,
                                   'pix_fmt': 'yuv420p',
                                   'save_metadata': True,
                                   'save_output': False,
                                   'trim_to_audio': False,
                                   'videopreview': {'hidden': False,
                                                    'params': {'filename': 'WanVideo2_2_I2V_00006.mp4',
                                                               'format': 'video/h264-mp4',
                                                               'frame_rate': 16,
                                                               'fullpath': 'N:\\AI\\ComfyUI\\temp\\WanVideo2_2_I2V_00006.mp4',
                                                               'subfolder': '',
                                                               'type': 'temp',
                                                               'workflow': 'WanVideo2_2_I2V_00006.png'},
                                                    'paused': False}}},
        'class_type': 'VHS_VideoCombine',
        'inputs': {'crf': 19,
                   'filename_prefix': 'WanVideo2_2_I2V',
                   'format': 'video/h264-mp4',
                   'frame_rate': 16,
                   'images': ['69', 0],
                   'loop_count': 0,
                   'pingpong': False,
                   'pix_fmt': 'yuv420p',
                   'save_metadata': True,
                   'save_output': False,
                   'trim_to_audio': False,
                   'videopreview': {'hidden': False,
                                    'params': {'filename': 'WanVideo2_2_I2V_00006.mp4',
                                               'format': 'video/h264-mp4',
                                               'frame_rate': 16,
                                               'fullpath': 'N:\\AI\\ComfyUI\\temp\\WanVideo2_2_I2V_00006.mp4',
                                               'subfolder': '',
                                               'type': 'temp',
                                               'workflow': 'WanVideo2_2_I2V_00006.png'},
                                    'paused': False}}},
 '67': {'_ui': {'flags': {},
                'id': 67,
                'inputs': [],
                'mode': 0,
                'order': 5,
                'outputs': [{'links': [71], 'name': 'IMAGE', 'type': 'IMAGE'},
                            {'links': None, 'name': 'MASK', 'type': 'MASK'}],
                'pos': [330.2861633300781, -1144.739013671875],
                'properties': {'Node name for S&R': 'LoadImage', 'cnr_id': 'comfy-core', 'ver': '0.3.44'},
                'size': [274.080078125, 314],
                'type': 'LoadImage',
                'widgets_values': ['oldman_upscaled.png', 'image']},
        'class_type': 'LoadImage',
        'inputs': {'widget_0': 'oldman_upscaled.png', 'widget_1': 'image'}},
 '68': {'_ui': {'flags': {},
                'id': 68,
                'inputs': [{'link': 71, 'name': 'image', 'type': 'IMAGE'},
                           {'link': None, 'name': 'mask', 'shape': 7, 'type': 'MASK'}],
                'mode': 0,
                'order': 16,
                'outputs': [{'links': [139], 'name': 'IMAGE', 'type': 'IMAGE'},
                            {'links': [141], 'name': 'width', 'type': 'INT'},
                            {'links': [142], 'name': 'height', 'type': 'INT'},
                            {'links': None, 'name': 'mask', 'type': 'MASK'}],
                'pos': [696.0801391601562, -1143.5843505859375],
                'properties': {'Node name for S&R': 'ImageResizeKJv2',
                               'cnr_id': 'comfyui-kjnodes',
                               'ver': 'a6b867b63a29ca48ddb15c589e17a9f2d8530d57'},
                'size': [270, 336],
                'type': 'ImageResizeKJv2',
                'widgets_values': [720,
                                   720,
                                   'lanczos',
                                   'crop',
                                   '0, 0, 0',
                                   'center',
                                   32,
                                   'cpu',
                                   '<tr><td>Output: </td><td><b>1</b> x <b>704</b> x <b>704 | 5.67MB</b></td></tr>']},
        'class_type': 'ImageResizeKJv2',
        'inputs': {'image': ['67', 0],
                   'widget_0': 720,
                   'widget_1': 720,
                   'widget_2': 'lanczos',
                   'widget_3': 'crop',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'center',
                   'widget_6': 32,
                   'widget_7': 'cpu',
                   'widget_8': '<tr><td>Output: </td><td><b>1</b> x <b>704</b> x <b>704 | 5.67MB</b></td></tr>'}},
 '69': {'_ui': {'flags': {},
                'id': 69,
                'inputs': [{'link': 76, 'name': 'image', 'type': 'IMAGE'}],
                'mode': 0,
                'order': 28,
                'outputs': [{'links': [77], 'name': 'image', 'type': 'IMAGE'},
                            {'label': '704 width', 'links': None, 'name': 'width', 'type': 'INT'},
                            {'label': '704 height', 'links': None, 'name': 'height', 'type': 'INT'},
                            {'label': '81 count', 'links': None, 'name': 'count', 'type': 'INT'}],
                'pos': [2725.78076171875, -249.85873413085938],
                'properties': {'Node name for S&R': 'GetImageSizeAndCount',
                               'cnr_id': 'comfyui-kjnodes',
                               'ver': 'a6b867b63a29ca48ddb15c589e17a9f2d8530d57'},
                'size': [240.41265869140625, 86],
                'type': 'GetImageSizeAndCount',
                'widgets_values': []},
        'class_type': 'GetImageSizeAndCount',
        'inputs': {'image': ['28', 0]}},
 '71': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 71,
                'inputs': [{'link': 112, 'name': 'compile_args', 'shape': 7, 'type': 'WANCOMPILEARGS'},
                           {'link': None, 'name': 'block_swap_args', 'shape': 7, 'type': 'BLOCKSWAPARGS'},
                           {'link': None, 'name': 'lora', 'shape': 7, 'type': 'WANVIDLORA'},
                           {'link': None, 'name': 'vram_management_args', 'shape': 7, 'type': 'VRAM_MANAGEMENTARGS'},
                           {'link': None, 'name': 'vace_model', 'shape': 7, 'type': 'VACEPATH'},
                           {'link': None, 'name': 'fantasytalking_model', 'shape': 7, 'type': 'FANTASYTALKINGMODEL'},
                           {'link': None, 'name': 'multitalk_model', 'shape': 7, 'type': 'MULTITALKMODEL'}],
                'mode': 0,
                'order': 15,
                'outputs': [{'links': [160], 'name': 'model', 'slot_index': 0, 'type': 'WANVIDEOMODEL'}],
                'pos': [-10, -380],
                'properties': {'Node name for S&R': 'WanVideoModelLoader',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [477.4410095214844, 274],
                'type': 'WanVideoModelLoader',
                'widgets_values': ['WanVideo\\2_2\\Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors',
                                   'fp16_fast',
                                   'fp8_e4m3fn_scaled',
                                   'offload_device',
                                   'sageattn']},
        'class_type': 'WanVideoModelLoader',
        'inputs': {'compile_args': ['35', 0],
                   'widget_0': 'WanVideo\\2_2\\Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors',
                   'widget_1': 'fp16_fast',
                   'widget_2': 'fp8_e4m3fn_scaled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sageattn'}},
 '79': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 79,
                'inputs': [{'link': 161, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 169, 'name': 'lora', 'shape': 7, 'type': 'WANVIDLORA'}],
                'mode': 0,
                'order': 24,
                'outputs': [{'links': [144], 'name': 'model', 'type': 'WANVIDEOMODEL'}],
                'pos': [969.6483764648438, -216.53614807128906],
                'properties': {'Node name for S&R': 'WanVideoSetLoRAs',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [222.27981567382812, 46],
                'type': 'WanVideoSetLoRAs',
                'widgets_values': []},
        'class_type': 'WanVideoSetLoRAs',
        'inputs': {'lora': ['97', 0], 'model': ['93', 0]}},
 '80': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 80,
                'inputs': [{'link': 157, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 110, 'name': 'lora', 'shape': 7, 'type': 'WANVIDLORA'}],
                'mode': 0,
                'order': 23,
                'outputs': [{'links': [109], 'name': 'model', 'type': 'WANVIDEOMODEL'}],
                'pos': [985.8822021484375, -458.0684814453125],
                'properties': {'Node name for S&R': 'WanVideoSetLoRAs',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [222.27981567382812, 46],
                'type': 'WanVideoSetLoRAs',
                'widgets_values': []},
        'class_type': 'WanVideoSetLoRAs',
        'inputs': {'lora': ['56', 0], 'model': ['92', 0]}},
 '89': {'_ui': {'bgcolor': '#533',
                'color': '#322',
                'flags': {},
                'id': 89,
                'inputs': [{'link': 137, 'name': 'vae', 'type': 'WANVAE'},
                           {'link': None, 'name': 'clip_embeds', 'shape': 7, 'type': 'WANVIDIMAGE_CLIPEMBEDS'},
                           {'link': 139, 'name': 'start_image', 'shape': 7, 'type': 'IMAGE'},
                           {'link': None, 'name': 'end_image', 'shape': 7, 'type': 'IMAGE'},
                           {'link': None, 'name': 'control_embeds', 'shape': 7, 'type': 'WANVIDIMAGE_EMBEDS'},
                           {'link': None, 'name': 'temporal_mask', 'shape': 7, 'type': 'MASK'},
                           {'link': None, 'name': 'extra_latents', 'shape': 7, 'type': 'LATENT'},
                           {'link': None, 'name': 'add_cond_latents', 'shape': 7, 'type': 'ADD_COND_LATENTS'},
                           {'link': 141, 'name': 'width', 'type': 'INT', 'widget': {'name': 'width'}},
                           {'link': 142, 'name': 'height', 'type': 'INT', 'widget': {'name': 'height'}}],
                'mode': 0,
                'order': 22,
                'outputs': [{'links': [138, 149], 'name': 'image_embeds', 'type': 'WANVIDIMAGE_EMBEDS'}],
                'pos': [1401.11962890625, -698.7300415039062],
                'properties': {'Node name for S&R': 'WanVideoImageToVideoEncode',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '7e290c67bff1f906cdab84523018573f6c9d4d7f'},
                'size': [308.2320251464844, 390],
                'type': 'WanVideoImageToVideoEncode',
                'widgets_values': [832, 480, 81, 0, 1, 1, True, False, False]},
        'class_type': 'WanVideoImageToVideoEncode',
        'inputs': {'height': ['68', 2],
                   'start_image': ['68', 0],
                   'vae': ['38', 0],
                   'widget_0': 832,
                   'widget_1': 480,
                   'widget_2': 81,
                   'widget_3': 0,
                   'widget_4': 1,
                   'widget_5': 1,
                   'widget_6': True,
                   'widget_7': False,
                   'widget_8': False,
                   'width': ['68', 1]}},
 '90': {'_ui': {'flags': {},
                'id': 90,
                'inputs': [{'link': 144, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 149, 'name': 'image_embeds', 'type': 'WANVIDIMAGE_EMBEDS'},
                           {'link': 152, 'name': 'text_embeds', 'shape': 7, 'type': 'WANVIDEOTEXTEMBEDS'},
                           {'link': 143, 'name': 'samples', 'shape': 7, 'type': 'LATENT'},
                           {'link': None, 'name': 'feta_args', 'shape': 7, 'type': 'FETAARGS'},
                           {'link': None, 'name': 'context_options', 'shape': 7, 'type': 'WANVIDCONTEXT'},
                           {'link': None, 'name': 'cache_args', 'shape': 7, 'type': 'CACHEARGS'},
                           {'link': None, 'name': 'flowedit_args', 'shape': 7, 'type': 'FLOWEDITARGS'},
                           {'link': None, 'name': 'slg_args', 'shape': 7, 'type': 'SLGARGS'},
                           {'link': None, 'name': 'loop_args', 'shape': 7, 'type': 'LOOPARGS'},
                           {'link': None, 'name': 'experimental_args', 'shape': 7, 'type': 'EXPERIMENTALARGS'},
                           {'link': None, 'name': 'sigmas', 'shape': 7, 'type': 'SIGMAS'},
                           {'link': None, 'name': 'unianimate_poses', 'shape': 7, 'type': 'UNIANIMATE_POSE'},
                           {'link': None, 'name': 'fantasytalking_embeds', 'shape': 7, 'type': 'FANTASYTALKING_EMBEDS'},
                           {'link': None, 'name': 'uni3c_embeds', 'shape': 7, 'type': 'UNI3C_EMBEDS'},
                           {'link': None, 'name': 'multitalk_embeds', 'shape': 7, 'type': 'MULTITALK_EMBEDS'},
                           {'link': None, 'name': 'freeinit_args', 'shape': 7, 'type': 'FREEINITARGS'},
                           {'link': 164, 'name': 'steps', 'type': 'INT', 'widget': {'name': 'steps'}},
                           {'link': 154,
                            'name': 'start_step',
                            'shape': 7,
                            'type': 'INT',
                            'widget': {'name': 'start_step'}}],
                'mode': 0,
                'order': 26,
                'outputs': [{'links': [151], 'name': 'samples', 'slot_index': 0, 'type': 'LATENT'}],
                'pos': [2206.047119140625, -393.0194396972656],
                'properties': {'Node name for S&R': 'WanVideoSampler',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [315, 975],
                'type': 'WanVideoSampler',
                'widgets_values': [6, 1, 8, 43, 'fixed', True, 'dpm++_sde', 0, 1, False, 'comfy', 10, -1, '']},
        'class_type': 'WanVideoSampler',
        'inputs': {'image_embeds': ['89', 0],
                   'model': ['79', 0],
                   'samples': ['27', 0],
                   'start_step': ['91', 0],
                   'steps': ['94', 0],
                   'text_embeds': ['16', 0],
                   'widget_0': 6,
                   'widget_1': 1,
                   'widget_10': 'comfy',
                   'widget_11': 10,
                   'widget_12': -1,
                   'widget_13': '',
                   'widget_2': 8,
                   'widget_3': 43,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'dpm++_sde',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': False}},
 '91': {'_ui': {'bgcolor': '#29699c',
                'color': '#1b4669',
                'flags': {},
                'id': 91,
                'inputs': [],
                'mode': 0,
                'order': 6,
                'outputs': [{'links': [153, 154], 'name': 'value', 'type': 'INT'}],
                'pos': [1554.34130859375, 293.0675964355469],
                'properties': {'Node name for S&R': 'INTConstant',
                               'cnr_id': 'comfyui-kjnodes',
                               'ver': 'a6b867b63a29ca48ddb15c589e17a9f2d8530d57'},
                'size': [200, 58],
                'title': 'Split_step',
                'type': 'INTConstant',
                'widgets_values': [3]},
        'class_type': 'INTConstant',
        'inputs': {'widget_0': 3}},
 '92': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 92,
                'inputs': [{'link': 155, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 156, 'name': 'block_swap_args', 'shape': 7, 'type': 'BLOCKSWAPARGS'}],
                'mode': 0,
                'order': 20,
                'outputs': [{'links': [157], 'name': 'model', 'type': 'WANVIDEOMODEL'}],
                'pos': [538.2930908203125, -699.6842041015625],
                'properties': {'Node name for S&R': 'WanVideoSetBlockSwap',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '7e290c67bff1f906cdab84523018573f6c9d4d7f'},
                'size': [201.76815795898438, 46],
                'type': 'WanVideoSetBlockSwap'},
        'class_type': 'WanVideoSetBlockSwap',
        'inputs': {'block_swap_args': ['39', 0], 'model': ['22', 0]}},
 '93': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 93,
                'inputs': [{'link': 160, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 159, 'name': 'block_swap_args', 'shape': 7, 'type': 'BLOCKSWAPARGS'}],
                'mode': 0,
                'order': 21,
                'outputs': [{'links': [161], 'name': 'model', 'type': 'WANVIDEOMODEL'}],
                'pos': [548.8602294921875, -260.6182556152344],
                'properties': {'Node name for S&R': 'WanVideoSetBlockSwap',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '7e290c67bff1f906cdab84523018573f6c9d4d7f'},
                'size': [201.76815795898438, 46],
                'type': 'WanVideoSetBlockSwap'},
        'class_type': 'WanVideoSetBlockSwap',
        'inputs': {'block_swap_args': ['39', 0], 'model': ['71', 0]}},
 '94': {'_ui': {'bgcolor': '#29699c',
                'color': '#1b4669',
                'flags': {},
                'id': 94,
                'inputs': [],
                'mode': 0,
                'order': 7,
                'outputs': [{'links': [163, 164, 165], 'name': 'value', 'type': 'INT'}],
                'pos': [1446.0140380859375, -77.41889953613281],
                'properties': {'Node name for S&R': 'INTConstant',
                               'cnr_id': 'comfyui-kjnodes',
                               'ver': 'a6b867b63a29ca48ddb15c589e17a9f2d8530d57'},
                'size': [200, 58],
                'title': 'Steps',
                'type': 'INTConstant',
                'widgets_values': [6]},
        'class_type': 'INTConstant',
        'inputs': {'widget_0': 6}},
 '95': {'_ui': {'flags': {},
                'id': 95,
                'inputs': [{'link': 165, 'name': 'steps', 'type': 'INT', 'widget': {'name': 'steps'}}],
                'mode': 0,
                'order': 17,
                'outputs': [{'links': [167], 'name': 'float_list', 'type': 'FLOAT'}],
                'pos': [1455.8336181640625, 44.19880294799805],
                'properties': {'Node name for S&R': 'CreateCFGScheduleFloatList',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '7e290c67bff1f906cdab84523018573f6c9d4d7f'},
                'size': [298.3199157714844, 178],
                'type': 'CreateCFGScheduleFloatList',
                'widgets_values': [30, 2, 2, 'linear', 0, 0.01]},
        'class_type': 'CreateCFGScheduleFloatList',
        'inputs': {'steps': ['94', 0],
                   'widget_0': 30,
                   'widget_1': 2,
                   'widget_2': 2,
                   'widget_3': 'linear',
                   'widget_4': 0,
                   'widget_5': 0.01}},
 '97': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 97,
                'inputs': [{'link': None, 'name': 'prev_lora', 'shape': 7, 'type': 'WANVIDLORA'},
                           {'link': None, 'name': 'blocks', 'shape': 7, 'type': 'SELECTEDBLOCKS'}],
                'mode': 0,
                'order': 8,
                'outputs': [{'links': [169], 'name': 'lora', 'type': 'WANVIDLORA'}],
                'pos': [-717.8909301757812, -252.48538208007812],
                'properties': {'Node name for S&R': 'WanVideoLoraSelect',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '998a69cc0acbec503001b8b0ce0a5d5404420e1e'},
                'size': [624.4888305664062, 150],
                'type': 'WanVideoLoraSelect',
                'widgets_values': ['WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                                   1,
                                   False,
                                   False]},
        'class_type': 'WanVideoLoraSelect',
        'inputs': {'widget_0': 'WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                   'widget_1': 1,
                   'widget_2': False,
                   'widget_3': False}}}

READY_METADATA = {'approach': 'Kijai WanVideoWrapper Wan 2.2 A14B I2V high/low two-phase workflow with Lightx2v LoRA',
 'capability': 'image_to_video',
 'coverage_tier': 'production_parity_candidate',
 'model_assets': [{'directory': 'diffusion_models/WanVideo/2_2',
                   'name': 'Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/I2V/Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors'},
                  {'directory': 'diffusion_models/WanVideo/2_2',
                   'name': 'Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/I2V/Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors'},
                  {'directory': 'vae/wanvideo',
                   'name': 'Wan2_1_VAE_bf16.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan2_1_VAE_bf16.safetensors'},
                  {'directory': 'text_encoders',
                   'name': 'umt5-xxl-enc-bf16.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/umt5-xxl-enc-bf16.safetensors'},
                  {'directory': 'loras/WanVideo/Lightx2v',
                   'name': 'lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors'}],
 'ready_template': 'video/wanvideo_wrapper_22_14b_i2v_kijai',
 'runtime_note': 'Worker scratchpads patch image, prompt, seed, resolution, frame count, and force VHS output saving.',
 'smoke_resolution': '832x480x81_frames',
 'source_role': 'materialized_kijai_reference_workflow',
 'source_url': 'https://raw.githubusercontent.com/kijai/ComfyUI-WanVideoWrapper/main/example_workflows/wanvideo_2_2_I2V_A14B_example_WIP.json',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wanvideo_2_2_I2V_A14B_example_WIP.json',
 'unbound_inputs': {'end_step': '91.widget_0',
                    'height': '68.widget_1',
                    'image': '67.widget_0',
                    'negative_prompt': '16.widget_1',
                    'num_frames': '89.widget_2',
                    'prompt': '16.widget_0',
                    'seed': '27.widget_3',
                    'steps': '94.widget_0',
                    'width': '68.widget_0'},
 'workflow_template': 'wanvideo_wrapper_22_14b_i2v_kijai'}

READY_REQUIREMENTS = {'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper'],
 'models': [{'directory': 'diffusion_models/WanVideo/2_2',
             'name': 'Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/I2V/Wan2_2-I2V-A14B-HIGH_fp8_e4m3fn_scaled_KJ.safetensors'},
            {'directory': 'diffusion_models/WanVideo/2_2',
             'name': 'Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/I2V/Wan2_2-I2V-A14B-LOW_fp8_e4m3fn_scaled_KJ.safetensors'},
            {'directory': 'vae/wanvideo',
             'name': 'Wan2_1_VAE_bf16.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan2_1_VAE_bf16.safetensors'},
            {'directory': 'text_encoders',
             'name': 'umt5-xxl-enc-bf16.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/umt5-xxl-enc-bf16.safetensors'},
            {'directory': 'loras/WanVideo/Lightx2v',
             'name': 'lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors'}]}

def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        READY_METADATA,
        source_path=__file__,
        workflow_id='video/wanvideo_wrapper_22_14b_i2v_kijai',
        requirements=READY_REQUIREMENTS,
    )
