from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 'default',
                   'vae': ['120', 0],
                   'samples': ['27', 0]}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\S2V\\Wan2_2-S2V-14B_fp8_e4m3fn_scaled_KJ.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'fp8_e4m3fn_scaled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'compile_args': ['35', 0]}},
 '60': {'class_type': 'WanVideoLoraSelectMulti',
        'inputs': {'widget_0': 'WanVideo\\Lightx2v\\lightx2v_T2V_14B_cfg_step_distill_v2_lora_rank64_bf16.safetensors',
                   'widget_1': 1.2,
                   'widget_2': 'none',
                   'widget_3': 1,
                   'widget_4': 'none',
                   'widget_5': 1,
                   'widget_6': 'none',
                   'widget_7': 1,
                   'widget_8': 'none',
                   'widget_9': 1,
                   'widget_10': False,
                   'widget_11': False}},
 '58': {'class_type': 'WanVideoSetLoRAs', 'inputs': {'model': ['22', 0], 'lora': ['60', 0]}},
 '39': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 32,
                   'widget_1': False,
                   'widget_2': False,
                   'widget_3': True,
                   'widget_4': 0,
                   'widget_5': 1,
                   'widget_6': False}},
 '56': {'class_type': 'WanVideoSetBlockSwap', 'inputs': {'model': ['58', 0], 'block_swap_args': ['39', 0]}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '119': {'class_type': 'SetNode', 'inputs': {'widget_0': 'VAE', 'WANVAE': ['38', 0]}},
 '120': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '109': {'class_type': 'WanVideoEncode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'widget_5': 0,
                    'widget_6': 0.5,
                    'vae': ['122', 0],
                    'image': ['111', 0]}},
 '37': {'class_type': 'WanVideoEmptyEmbeds',
        'inputs': {'width': ['74', 1],
                   'height': ['74', 2],
                   'num_frames': ['71', 0],
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5}},
 '72': {'class_type': 'WanVideoEncode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 0,
                   'widget_6': 1,
                   'vae': ['121', 0],
                   'image': ['125', 0]}},
 '121': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '94': {'class_type': 'VHS_LoadAudio', 'inputs': {}},
 '66': {'class_type': 'LoadAudio',
        'inputs': {'widget_0': '0321. Alphaville - Big In Japan.mp3', 'widget_1': None, 'widget_2': None}},
 '82': {'class_type': 'MelBandRoFormerSampler', 'inputs': {'model': ['81', 0], 'audio': ['106', 2]}},
 '98': {'class_type': 'NormalizeAudioLoudness', 'inputs': {'widget_0': -23, 'audio': ['82', 0]}},
 '64': {'class_type': 'AudioEncoderEncode', 'inputs': {'audio_encoder': ['65', 0], 'audio': ['98', 0]}},
 '65': {'class_type': 'AudioEncoderLoader', 'inputs': {'widget_0': 'wav2vec_xlsr_53_english_fp32.safetensors'}},
 '81': {'class_type': 'MelBandRoFormerModelLoader',
        'inputs': {'widget_0': 'MelBandRoFormer\\MelBandRoformer_fp16.safetensors'}},
 '74': {'class_type': 'ImageResizeKJv2',
        'inputs': {'width': ['137', 0],
                   'height': ['138', 0],
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 'lanczos',
                   'widget_3': 'crop',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'center',
                   'widget_6': 16,
                   'widget_7': 'cpu',
                   'widget_8': '<tr><td>Output: </td><td><b>1</b> x <b>960</b> x <b>640 | 7.03MB</b></td></tr>',
                   'image': ['73', 0]}},
 '125': {'class_type': 'SetNode', 'inputs': {'widget_0': 'reference_image', 'IMAGE': ['74', 0]}},
 '112': {'class_type': 'ImageConcatMulti',
         'inputs': {'widget_0': 2,
                    'widget_1': 'right',
                    'widget_2': False,
                    'widget_3': None,
                    'image_1': ['130', 0],
                    'image_2': ['105', 0]}},
 '97': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['127', 0], 'audio': ['129', 0]}},
 '111': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': 256,
                    'height': 256,
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'bilinear',
                    'widget_3': 'stretch',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'widget_7': 'gpu',
                    'image': ['107', 0]}},
 '130': {'class_type': 'Reroute', 'inputs': {}},
 '122': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '133': {'class_type': 'SetNode', 'inputs': {'widget_0': 'width', 'INT': ['131', 0]}},
 '132': {'class_type': 'INTConstant', 'inputs': {'widget_0': 640}},
 '134': {'class_type': 'SetNode', 'inputs': {'widget_0': 'height', 'INT': ['132', 0]}},
 '73': {'class_type': 'LoadImage', 'inputs': {'widget_0': '2b.jpg', 'widget_1': 'image'}},
 '137': {'class_type': 'GetNode', 'inputs': {'widget_0': 'width'}},
 '138': {'class_type': 'GetNode', 'inputs': {'widget_0': 'height'}},
 '107': {'class_type': 'DWPreprocessor',
         'inputs': {'widget_0': 'disable',
                    'widget_1': 'disable',
                    'widget_2': 'enable',
                    'widget_3': 640,
                    'widget_4': 'yolox_l.torchscript.pt',
                    'widget_5': 'dw-ll_ucoco_384_bs5.torchscript.pt',
                    'image': ['110', 0]}},
 '141': {'class_type': 'GetNode', 'inputs': {'widget_0': 'width'}},
 '142': {'class_type': 'GetNode', 'inputs': {'widget_0': 'height'}},
 '117': {'class_type': 'WanVideoAddS2VEmbeds',
         'inputs': {'widget_0': 80,
                    'widget_1': 1,
                    'widget_2': 0,
                    'widget_3': 1,
                    'widget_4': True,
                    'embeds': ['37', 0],
                    'audio_encoder_output': ['64', 0],
                    'ref_latent': ['72', 0],
                    'pose_latent': ['109', 0],
                    'vae': ['121', 0]}},
 '118': {'class_type': 'PreviewAny', 'inputs': {'source': ['117', 1]}},
 '139': {'class_type': 'GetNode', 'inputs': {'widget_0': 'width'}},
 '140': {'class_type': 'GetNode', 'inputs': {'widget_0': 'height'}},
 '116': {'class_type': 'VHS_LoadVideo',
         'inputs': {'video': 'wolf_interpolated.mp4',
                    'custom_width': ['139', 0],
                    'custom_height': ['140', 0],
                    'frame_load_cap': ['71', 0]}},
 '106': {'class_type': 'VHS_LoadVideo',
         'inputs': {'video': 'wolf_interpolated.mp4',
                    'custom_width': ['141', 0],
                    'custom_height': ['142', 0],
                    'frame_load_cap': ['71', 0]}},
 '110': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': ['139', 0],
                    'height': ['140', 0],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'bilinear',
                    'widget_3': 'crop',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'widget_7': 'cpu',
                    'image': ['116', 0]}},
 '131': {'class_type': 'INTConstant', 'inputs': {'widget_0': 640}},
 '67': {'class_type': 'WanVideoTextEncodeCached',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': '3D animated scene of a young woman singing melancholically',
                   'widget_3': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_4': 'disabled',
                   'widget_5': True,
                   'widget_6': 'gpu'}},
 '70': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['28', 0]}},
 '127': {'class_type': 'LazySwitchKJ', 'inputs': {'widget_0': True, 'on_false': ['105', 0], 'on_true': ['112', 0]}},
 '143': {'class_type': 'GetImageRangeFromBatch',
         'inputs': {'widget_0': 0, 'widget_1': 501, 'images': ['70', 0], 'num_frames': ['71', 0]}},
 '129': {'class_type': 'Reroute', 'inputs': {}},
 '71': {'class_type': 'PrimitiveNode', 'inputs': {'widget_0': 501, 'widget_1': 'fixed'}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 1,
                   'widget_2': 4,
                   'widget_3': 45,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'lcm',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': False,
                   'widget_10': 'comfy',
                   'widget_11': 0,
                   'widget_12': -1,
                   'widget_13': False,
                   'model': ['56', 0],
                   'image_embeds': ['117', 0],
                   'text_embeds': ['67', 0]}},
 '105': {'class_type': 'ColorMatch',
         'inputs': {'widget_0': 'mkl',
                    'widget_1': 1,
                    'widget_2': True,
                    'image_ref': ['126', 0],
                    'image_target': ['143', 0]}},
 '126': {'class_type': 'GetNode', 'inputs': {'widget_0': 'reference_image'}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4865},
 'ready_template': 'video/wanvideo_wrapper_22_s2v_framepack_pose',
 'workflow_template': 'wanvideo_wrapper_22_s2v_framepack_pose',
 'capability': 'speech_to_video_pose_control',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan22_s2v_framepack_pose.json',
 'coverage_tier': 'supplemental',
 'approach': 'S2V framepack pose workflow',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [],
 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper', 'comfyui_controlnet_aux']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_22_s2v_framepack_pose"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
