from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'46': {'class_type': 'WanVideoTextEmbedBridge', 'inputs': {'positive': ['49', 0], 'negative': ['50', 0]}},
 '50': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'clip': ['48', 0]}},
 '48': {'class_type': 'CLIPLoader',
        'inputs': {'widget_0': 'umt5_xxl_fp16.safetensors', 'widget_1': 'wan', 'widget_2': 'default'}},
 '49': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': 'high quality nature video featuring a red panda balancing on a bamboo stem while a '
                               "bird lands on it's head, on the background there is a waterfall",
                   'clip': ['48', 0]}},
 '45': {'class_type': 'WanVideoVRAMManagement', 'inputs': {'widget_0': 1}},
 '39': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 10, 'widget_1': False, 'widget_2': False, 'widget_3': True, 'widget_4': 0}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '59': {'class_type': 'CLIPVisionLoader', 'inputs': {'widget_0': 'clip_vision_h.safetensors'}},
 '73': {'class_type': 'DownloadAndLoadDepthAnythingV2Model',
        'inputs': {'widget_0': 'depth_anything_v2_vitl_fp16.safetensors'}},
 '69': {'class_type': 'WanVideoEmptyEmbeds',
        'inputs': {'width': ['76', 1],
                   'height': ['76', 2],
                   'num_frames': ['76', 3],
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'control_embeds': ['78', 0]}},
 '71': {'class_type': 'VHS_LoadVideo', 'inputs': {'video': 'wolf_interpolated.mp4'}},
 '77': {'class_type': 'WanVideoEncode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 0,
                   'widget_6': 1,
                   'vae': ['84', 0],
                   'image': ['76', 0]}},
 '84': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '85': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '52': {'class_type': 'WanVideoTeaCache',
        'inputs': {'widget_0': 0.08000000000000002,
                   'widget_1': 1,
                   'widget_2': -1,
                   'widget_3': 'offload_device',
                   'widget_4': 'true',
                   'widget_5': 'e'}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\wan2.1_fun_control_1.3B_bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa'}},
 '11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '83': {'class_type': 'SetNode', 'inputs': {'widget_0': 'VAE', 'WANVAE': ['38', 0]}},
 '75': {'class_type': 'ImageResizeKJ',
        'inputs': {'widget_0': 640,
                   'widget_1': 640,
                   'widget_2': 'lanczos',
                   'widget_3': False,
                   'widget_4': 16,
                   'widget_5': 0,
                   'widget_6': 0,
                   'widget_7': 'disabled',
                   'image': ['71', 0]}},
 '72': {'class_type': 'DepthAnything_V2', 'inputs': {'da_model': ['73', 0], 'images': ['75', 0]}},
 '88': {'class_type': 'SetNode', 'inputs': {'widget_0': 'ControlSignal', 'IMAGE': ['72', 0]}},
 '82': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['88', 0]}},
 '89': {'class_type': 'GetNode', 'inputs': {'widget_0': 'ControlSignal'}},
 '87': {'class_type': 'ImageConcatMulti',
        'inputs': {'widget_0': 2,
                   'widget_1': 'right',
                   'widget_2': False,
                   'widget_3': None,
                   'image_1': ['89', 0],
                   'image_2': ['28', 0]}},
 '28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'vae': ['86', 0],
                   'samples': ['27', 0]}},
 '86': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '30': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['87', 0]}},
 '90': {'class_type': 'WanVideoExperimentalArgs',
        'inputs': {'widget_0': '', 'widget_1': True, 'widget_2': False, 'widget_3': 0}},
 '58': {'class_type': 'LoadImage',
        'inputs': {'widget_0': 'pasted/image (758).png', 'widget_1': 'image', 'widget_2': ''}},
 '76': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['72', 0]}},
 '78': {'class_type': 'WanVideoControlEmbeds', 'inputs': {'widget_0': 0, 'widget_1': 1, 'latents': ['77', 0]}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 6,
                   'widget_2': 5,
                   'widget_3': 42,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'unipc',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': '',
                   'widget_10': 'comfy',
                   'model': ['22', 0],
                   'text_embeds': ['16', 0],
                   'image_embeds': ['79', 0],
                   'cache_args': ['52', 0],
                   'experimental_args': ['90', 0]}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': "high quality nature video of a red fox in an autumnal forest, there's a waterfall in "
                               'the background',
                   'widget_1': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_2': True,
                   't5': ['11', 0],
                   'model_to_offload': ['22', 0]}},
 '65': {'class_type': 'WanVideoClipVisionEncode',
        'inputs': {'widget_0': 1,
                   'widget_1': 1,
                   'widget_2': 'center',
                   'widget_3': 'average',
                   'widget_4': True,
                   'widget_5': 0,
                   'widget_6': 0.20000000000000004,
                   'clip_vision': ['59', 0],
                   'image_1': ['66', 0]}},
 '66': {'class_type': 'ImageResizeKJ',
        'inputs': {'widget_0': 624,
                   'widget_1': 624,
                   'widget_2': 'lanczos',
                   'widget_3': False,
                   'widget_4': 16,
                   'widget_5': 0,
                   'widget_6': 0,
                   'widget_7': 'center',
                   'image': ['58', 0],
                   'width': ['76', 1],
                   'height': ['76', 2]}},
 '79': {'class_type': 'Reroute', 'inputs': {}},
 '80': {'class_type': 'Reroute', 'inputs': {}},
 '63': {'class_type': 'WanVideoImageToVideoEncode',
        'inputs': {'width': ['66', 1],
                   'height': ['66', 2],
                   'num_frames': ['76', 3],
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'widget_3': 0.030000000000000006,
                   'widget_4': 1,
                   'widget_5': 1,
                   'widget_6': True,
                   'widget_7': True,
                   'vae': ['85', 0],
                   'clip_embeds': ['65', 0],
                   'start_image': ['66', 0],
                   'control_embeds': ['78', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4501},
 'ready_template': 'video/wanvideo_wrapper_21_14b_fun_control',
 'workflow_template': 'wanvideo_wrapper_21_14b_fun_control',
 'capability': 'fun_control_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan21_14b_fun_control.json',
 'coverage_tier': 'supplemental',
 'approach': 'WanVideoFun control workflow',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [],
 'custom_nodes': ['ComfyUI-DepthAnythingV2', 'ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_21_14b_fun_control"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
