from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'46': {'class_type': 'WanVideoTextEmbedBridge', 'inputs': {'positive': ['49', 0], 'negative': ['50', 0]}},
 '50': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'clip': ['48', 0]}},
 '48': {'class_type': 'CLIPLoader',
        'inputs': {'widget_0': 'umt5_xxl_fp16.safetensors', 'widget_1': 'wan', 'widget_2': 'default'}},
 '49': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': 'high quality nature video featuring a red panda balancing on a bamboo stem while a '
                               "bird lands on it's head, on the background there is a waterfall",
                   'clip': ['48', 0]}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '59': {'class_type': 'CLIPVisionLoader', 'inputs': {'widget_0': 'clip_vision_h.safetensors'}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': 'an old man is stroking his beard thoughtfully',
                   'widget_1': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_2': True,
                   'widget_3': False,
                   'widget_4': 'gpu',
                   't5': ['11', 0],
                   'model_to_offload': ['22', 0]}},
 '30': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['28', 0]}},
 '28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 'default',
                   'vae': ['38', 0],
                   'samples': ['27', 0]}},
 '65': {'class_type': 'WanVideoClipVisionEncode',
        'inputs': {'widget_0': 1,
                   'widget_1': 1,
                   'widget_2': 'center',
                   'widget_3': 'average',
                   'widget_4': True,
                   'widget_5': 0,
                   'widget_6': 0.20000000000000004,
                   'clip_vision': ['59', 0],
                   'image_1': ['68', 0]}},
 '58': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'oldman_upscaled.png', 'widget_1': 'image'}},
 '68': {'class_type': 'ImageResizeKJv2',
        'inputs': {'width': 256,
                   'height': 256,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 'lanczos',
                   'widget_3': 'crop',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'center',
                   'widget_6': 16,
                   'widget_7': 'cpu',
                   'image': ['58', 0]}},
 '45': {'class_type': 'WanVideoVRAMManagement', 'inputs': {'widget_0': 1}},
 '63': {'class_type': 'WanVideoImageToVideoEncode',
        'inputs': {'width': ['68', 1],
                   'height': ['68', 2],
                   'num_frames': 5,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'widget_3': 0.030000000000000006,
                   'widget_4': 1,
                   'widget_5': 1,
                   'widget_6': True,
                   'widget_7': False,
                   'widget_8': False,
                   'vae': ['38', 0],
                   'clip_embeds': ['65', 0],
                   'start_image': ['68', 0]}},
 '11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '69': {'class_type': 'WanVideoLoraSelect',
        'inputs': {'widget_0': 'WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                   'widget_1': 1,
                   'widget_2': False,
                   'widget_3': "<details><summary><b>Metadata</b></summary><table border='0' cellpadding='3'><tr><td "
                               "colspan='2'><b>Metadata</b></td></tr><tr><td>No metadata "
                               'found</td></tr></table></details>'}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 1,
                   'widget_2': 5,
                   'widget_3': 1057359483639287,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'dpm++_sde',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': '',
                   'widget_10': 'comfy',
                   'widget_11': 0,
                   'widget_12': -1,
                   'widget_13': False,
                   'model': ['70', 0],
                   'image_embeds': ['63', 0],
                   'text_embeds': ['16', 0]}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\Wan2_1-I2V-14B-480P_fp8_e4m3fn.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'fp8_e4m3fn',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'lora': ['69', 0]}},
 '39': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 10, 'widget_1': False, 'widget_2': False, 'widget_3': True, 'widget_4': 0}},
 '70': {'class_type': 'WanVideoSetBlockSwap', 'inputs': {'model': ['22', 0], 'block_swap_args': ['39', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 3581},
 'ready_template': 'video/wanvideo_wrapper_21_14b_i2v',
 'workflow_template': 'wanvideo_wrapper_21_14b_i2v',
 'capability': 'image_to_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan21_14b_i2v.json',
 'coverage_tier': 'supplemental',
 'approach': 'WanVideoWrapper 2.1 14B image-to-video',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_21_14b_i2v"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
