from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '124': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanVAE'}},
 '11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '125': {'class_type': 'SetNode', 'inputs': {'widget_0': 'WanTextEncoder', 'WANTEXTENCODER': ['11', 0]}},
 '126': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanTextEncoder'}},
 '127': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanModel'}},
 '128': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanModel'}},
 '130': {'class_type': 'GetNode', 'inputs': {'widget_0': 'start_image'}},
 '131': {'class_type': 'GetNode', 'inputs': {'widget_0': 'end_image'}},
 '132': {'class_type': 'EmptyImage',
         'inputs': {'widget_0': 8, 'widget_1': 512, 'widget_2': 1, 'widget_3': 0, 'height': ['137', 2]}},
 '133': {'class_type': 'AddLabel',
         'inputs': {'widget_0': 10,
                    'widget_1': 2,
                    'widget_2': 48,
                    'widget_3': 32,
                    'widget_4': 'white',
                    'widget_5': 'black',
                    'widget_6': 'FreeMono.ttf',
                    'widget_7': 'start_frame',
                    'widget_8': 'up',
                    'image': ['130', 0]}},
 '134': {'class_type': 'AddLabel',
         'inputs': {'widget_0': 10,
                    'widget_1': 2,
                    'widget_2': 48,
                    'widget_3': 32,
                    'widget_4': 'white',
                    'widget_5': 'black',
                    'widget_6': 'FreeMono.ttf',
                    'widget_7': 'end_frame',
                    'widget_8': 'up',
                    'image': ['131', 0]}},
 '135': {'class_type': 'ImageConcatMulti',
         'inputs': {'widget_0': 3,
                    'widget_1': 'left',
                    'widget_2': True,
                    'widget_3': None,
                    'image_1': ['137', 0],
                    'image_2': ['132', 0],
                    'image_3': ['136', 0]}},
 '137': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['138', 0]}},
 '136': {'class_type': 'ImageConcatMulti',
         'inputs': {'widget_0': 2,
                    'widget_1': 'down',
                    'widget_2': True,
                    'widget_3': None,
                    'image_1': ['133', 0],
                    'image_2': ['134', 0]}},
 '139': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['135', 0]}},
 '123': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanVAE'}},
 '138': {'class_type': 'WanVideoDecode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'vae': ['123', 0],
                    'samples': ['70', 0]}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': 'black and white cartoon character',
                   'widget_1': 'colorful, bad quality, blurry, messy, chaotic',
                   'widget_2': True,
                   't5': ['126', 0],
                   'model_to_offload': ['127', 0]}},
 '113': {'class_type': 'PreviewImage', 'inputs': {'images': ['104', 0]}},
 '142': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanVAE'}},
 '143': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanTextEncoder'}},
 '151': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanModel'}},
 '152': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanModel'}},
 '155': {'class_type': 'EmptyImage',
         'inputs': {'widget_0': 8, 'widget_1': 512, 'widget_2': 1, 'widget_3': 0, 'height': ['159', 2]}},
 '158': {'class_type': 'ImageConcatMulti',
         'inputs': {'widget_0': 3,
                    'widget_1': 'left',
                    'widget_2': True,
                    'widget_3': None,
                    'image_1': ['159', 0],
                    'image_2': ['155', 0],
                    'image_3': ['160', 0]}},
 '159': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['167', 0]}},
 '160': {'class_type': 'ImageConcatMulti',
         'inputs': {'widget_0': 2,
                    'widget_1': 'down',
                    'widget_2': True,
                    'widget_3': None,
                    'image_1': ['156', 0],
                    'image_2': ['157', 0]}},
 '166': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanVAE'}},
 '167': {'class_type': 'WanVideoDecode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'vae': ['166', 0],
                    'samples': ['172', 0]}},
 '175': {'class_type': 'DownloadAndLoadDepthAnythingV2Model',
         'inputs': {'widget_0': 'depth_anything_v2_vitl_fp16.safetensors'}},
 '153': {'class_type': 'GetNode', 'inputs': {'widget_0': 'reference_image'}},
 '156': {'class_type': 'AddLabel',
         'inputs': {'widget_0': 10,
                    'widget_1': 2,
                    'widget_2': 48,
                    'widget_3': 32,
                    'widget_4': 'white',
                    'widget_5': 'black',
                    'widget_6': 'FreeMono.ttf',
                    'widget_7': 'reference image',
                    'widget_8': 'up',
                    'image': ['153', 0]}},
 '145': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['231', 0]}},
 '154': {'class_type': 'GetNode', 'inputs': {'widget_0': 'control_video'}},
 '157': {'class_type': 'AddLabel',
         'inputs': {'widget_0': 10,
                    'widget_1': 2,
                    'widget_2': 48,
                    'widget_3': 32,
                    'widget_4': 'white',
                    'widget_5': 'black',
                    'widget_6': 'FreeMono.ttf',
                    'widget_7': 'control_video',
                    'widget_8': 'up',
                    'image': ['154', 0]}},
 '168': {'class_type': 'WanVideoTextEncode',
         'inputs': {'widget_0': 'robotic cybernetic wolf turning his head',
                    'widget_1': 'bad quality, blurry, messy, chaotic',
                    'widget_2': True,
                    't5': ['143', 0],
                    'model_to_offload': ['151', 0]}},
 '121': {'class_type': 'SetNode', 'inputs': {'widget_0': 'WanModel', 'WANVIDEOMODEL': ['22', 0]}},
 '39': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 0, 'widget_1': False, 'widget_2': False, 'widget_3': True, 'widget_4': 15}},
 '147': {'class_type': 'WanVideoTeaCache',
         'inputs': {'widget_0': 0.10000000000000002,
                    'widget_1': 0,
                    'widget_2': -1,
                    'widget_3': 'offload_device',
                    'widget_4': 'true',
                    'widget_5': 'e'}},
 '52': {'class_type': 'WanVideoTeaCache',
        'inputs': {'widget_0': 0.10000000000000002,
                   'widget_1': 0,
                   'widget_2': -1,
                   'widget_3': 'offload_device',
                   'widget_4': 'true',
                   'widget_5': 'e'}},
 '185': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanVAE'}},
 '186': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanTextEncoder'}},
 '189': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanModel'}},
 '190': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanModel'}},
 '191': {'class_type': 'EmptyImage',
         'inputs': {'widget_0': 8, 'widget_1': 512, 'widget_2': 1, 'widget_3': 0, 'height': ['193', 2]}},
 '192': {'class_type': 'ImageConcatMulti',
         'inputs': {'widget_0': 3,
                    'widget_1': 'left',
                    'widget_2': True,
                    'widget_3': None,
                    'image_1': ['193', 0],
                    'image_2': ['191', 0],
                    'image_3': ['202', 0]}},
 '193': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['196', 0]}},
 '195': {'class_type': 'GetNode', 'inputs': {'widget_0': 'WanVAE'}},
 '196': {'class_type': 'WanVideoDecode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'vae': ['195', 0],
                    'samples': ['197', 0]}},
 '211': {'class_type': 'WanVideoTextEncode',
         'inputs': {'widget_0': 'robotic cybernetic wolf turning his head',
                    'widget_1': 'bad quality, blurry, messy, chaotic',
                    'widget_2': True,
                    't5': ['186', 0],
                    'model_to_offload': ['189', 0]}},
 '214': {'class_type': 'WanVideoTeaCache',
         'inputs': {'widget_0': 0.10000000000000002,
                    'widget_1': 0,
                    'widget_2': -1,
                    'widget_3': 'offload_device',
                    'widget_4': 'true',
                    'widget_5': 'e'}},
 '221': {'class_type': 'SetNode', 'inputs': {'widget_0': 'InputVideo', 'IMAGE': ['216', 0]}},
 '201': {'class_type': 'GetNode', 'inputs': {'widget_0': 'InputVideo'}},
 '188': {'class_type': 'WanVideoExperimentalArgs',
         'inputs': {'widget_0': '',
                    'widget_1': True,
                    'widget_2': False,
                    'widget_3': 0,
                    'widget_4': False,
                    'widget_5': 1,
                    'widget_6': 1.25,
                    'widget_7': 20}},
 '187': {'class_type': 'WanVideoSLG',
         'inputs': {'widget_0': '8', 'widget_1': 0.30000000000000004, 'widget_2': 0.7000000000000002}},
 '205': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['216', 0]}},
 '220': {'class_type': 'PreviewImage', 'inputs': {'images': ['219', 0]}},
 '219': {'class_type': 'GetImageRangeFromBatch', 'inputs': {'widget_0': 0, 'widget_1': 1, 'images': ['216', 0]}},
 '209': {'class_type': 'WanVideoVACEEncode',
         'inputs': {'widget_0': 480,
                    'widget_1': 832,
                    'widget_2': 29,
                    'widget_3': 1.0000000000000002,
                    'widget_4': 0,
                    'widget_5': 1,
                    'widget_6': False,
                    'vae': ['185', 0],
                    'input_frames': ['205', 0],
                    'input_masks': ['216', 1],
                    'width': ['205', 1],
                    'height': ['205', 2],
                    'num_frames': ['205', 3]}},
 '213': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['192', 0]}},
 '202': {'class_type': 'AddLabel',
         'inputs': {'widget_0': 10,
                    'widget_1': 2,
                    'widget_2': 48,
                    'widget_3': 32,
                    'widget_4': 'white',
                    'widget_5': 'black',
                    'widget_6': 'FreeMono.ttf',
                    'widget_7': 'input',
                    'widget_8': 'up',
                    'image': ['201', 0]}},
 '197': {'class_type': 'WanVideoSampler',
         'inputs': {'steps': 1,
                    'widget_0': 1,
                    'widget_1': 4.000000000000001,
                    'widget_2': 8.000000000000002,
                    'widget_3': 18,
                    'widget_4': 'fixed',
                    'widget_5': True,
                    'widget_6': 'unipc',
                    'widget_7': 0,
                    'widget_8': 1,
                    'widget_9': False,
                    'widget_10': 'comfy',
                    'widget_11': '',
                    'model': ['190', 0],
                    'text_embeds': ['211', 0],
                    'image_embeds': ['209', 0],
                    'cache_args': ['214', 0],
                    'slg_args': ['187', 0],
                    'experimental_args': ['188', 0]}},
 '70': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 4.000000000000001,
                   'widget_2': 8.000000000000002,
                   'widget_3': 18,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'unipc',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': False,
                   'widget_10': 'comfy',
                   'widget_11': '',
                   'model': ['128', 0],
                   'text_embeds': ['16', 0],
                   'image_embeds': ['56', 0],
                   'cache_args': ['52', 0],
                   'slg_args': ['72', 0],
                   'experimental_args': ['71', 0]}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\wan2.1_t2v_1.3B_fp16.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'vace_model': ['224', 0]}},
 '224': {'class_type': 'WanVideoVACEModelSelect',
         'inputs': {'widget_0': 'WanVideo\\Wan2_1-VACE_module_1_3B_bf16.safetensors'}},
 '122': {'class_type': 'SetNode', 'inputs': {'widget_0': 'WanVAE', 'WANVAE': ['38', 0]}},
 '199': {'class_type': 'VHS_LoadVideo', 'inputs': {'video': 'wolf_interpolated.mp4'}},
 '216': {'class_type': 'ImagePadKJ',
         'inputs': {'widget_0': 0,
                    'widget_1': 0,
                    'widget_2': 0,
                    'widget_3': 0,
                    'widget_4': 128,
                    'widget_5': 'color',
                    'widget_6': '127,127,127',
                    'image': ['226', 0]}},
 '71': {'class_type': 'WanVideoExperimentalArgs',
        'inputs': {'widget_0': '',
                   'widget_1': True,
                   'widget_2': False,
                   'widget_3': 0,
                   'widget_4': False,
                   'widget_5': 1,
                   'widget_6': 1.25,
                   'widget_7': 20}},
 '72': {'class_type': 'WanVideoSLG',
        'inputs': {'widget_0': '8', 'widget_1': 0.30000000000000004, 'widget_2': 0.7000000000000002}},
 '56': {'class_type': 'WanVideoVACEEncode',
        'inputs': {'widget_0': 480,
                   'widget_1': 832,
                   'widget_2': 29,
                   'widget_3': 1.0000000000000002,
                   'widget_4': 0,
                   'widget_5': 1,
                   'widget_6': False,
                   'vae': ['124', 0],
                   'input_frames': ['104', 0],
                   'ref_images': ['227', 0],
                   'input_masks': ['111', 1],
                   'width': ['104', 1],
                   'height': ['104', 2],
                   'num_frames': ['104', 3]}},
 '226': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': 256,
                    'height': 256,
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '172,172,172',
                    'widget_5': 'center',
                    'widget_6': 2,
                    'image': ['199', 0]}},
 '64': {'class_type': 'LoadImage',
        'inputs': {'widget_0': 'replicate-prediction-5cvynz9d91rgg0cfsvqschdpww-0.webp', 'widget_1': 'image'}},
 '140': {'class_type': 'SetNode', 'inputs': {'widget_0': 'start_image', 'IMAGE': ['227', 0]}},
 '141': {'class_type': 'SetNode', 'inputs': {'widget_0': 'end_image', 'IMAGE': ['228', 0]}},
 '112': {'class_type': 'LoadImage',
         'inputs': {'widget_0': 'replicate-prediction-5cvynz9d91rgg0cfsvqschdpww-3.webp', 'widget_1': 'image'}},
 '104': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['111', 0]}},
 '228': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': ['227', 1],
                    'height': ['227', 2],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '172,172,172',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'image': ['112', 0]}},
 '227': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': 256,
                    'height': 256,
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '172,172,172',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'image': ['64', 0]}},
 '150': {'class_type': 'WanVideoExperimentalArgs',
         'inputs': {'widget_0': '',
                    'widget_1': True,
                    'widget_2': False,
                    'widget_3': 0,
                    'widget_4': False,
                    'widget_5': 1,
                    'widget_6': 1.25,
                    'widget_7': 20}},
 '165': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['158', 0]}},
 '111': {'class_type': 'WanVideoVACEStartToEndFrame',
         'inputs': {'widget_0': 33,
                    'widget_1': 0.5000000000000001,
                    'start_image': ['140', 0],
                    'end_image': ['141', 0]}},
 '174': {'class_type': 'DepthAnything_V2', 'inputs': {'da_model': ['175', 0], 'images': ['229', 0]}},
 '180': {'class_type': 'SetNode', 'inputs': {'widget_0': 'control_video', 'IMAGE': ['174', 0]}},
 '229': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': 256,
                    'height': 256,
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '172,172,172',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'image': ['173', 0]}},
 '184': {'class_type': 'ImagePadKJ',
         'inputs': {'widget_0': 0,
                    'widget_1': 0,
                    'widget_2': 0,
                    'widget_3': 0,
                    'widget_4': 128,
                    'widget_5': 'color',
                    'widget_6': '255,255,255',
                    'image': ['169', 0]}},
 '234': {'class_type': 'MaskPreview', 'inputs': {'mask': ['111', 1]}},
 '222': {'class_type': 'GetImageRangeFromBatch', 'inputs': {'widget_0': 0, 'widget_1': 1, 'masks': ['216', 1]}},
 '235': {'class_type': 'MaskPreview', 'inputs': {'mask': ['222', 1]}},
 '177': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['180', 0]}},
 '237': {'class_type': 'PreviewImage', 'inputs': {'images': ['230', 0]}},
 '230': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': ['229', 1],
                    'height': ['229', 2],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'pad',
                    'widget_4': '255,255,255',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'image': ['184', 0]}},
 '238': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': ['229', 1],
                    'height': ['229', 2],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'pad',
                    'widget_4': '255,255,255',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'image': ['169', 0]}},
 '233': {'class_type': 'MaskPreview', 'inputs': {'mask': ['231', 1]}},
 '173': {'class_type': 'VHS_LoadVideo', 'inputs': {'video': 'wolf_interpolated.mp4'}},
 '148': {'class_type': 'WanVideoVACEEncode',
         'inputs': {'widget_0': 480,
                    'widget_1': 832,
                    'widget_2': 29,
                    'widget_3': 1.0000000000000002,
                    'widget_4': 0,
                    'widget_5': 1,
                    'widget_6': False,
                    'vae': ['142', 0],
                    'input_frames': ['145', 0],
                    'ref_images': ['179', 0],
                    'input_masks': ['231', 1],
                    'width': ['145', 1],
                    'height': ['145', 2],
                    'num_frames': ['145', 3]}},
 '232': {'class_type': 'PreviewImage', 'inputs': {'images': ['231', 0]}},
 '169': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'hunhyuanwolf.png', 'widget_1': 'image'}},
 '149': {'class_type': 'WanVideoSLG',
         'inputs': {'widget_0': '8', 'widget_1': 0.30000000000000004, 'widget_2': 0.7100000000000002}},
 '172': {'class_type': 'WanVideoSampler',
         'inputs': {'steps': 1,
                    'widget_0': 1,
                    'widget_1': 4.000000000000001,
                    'widget_2': 8.000000000000002,
                    'widget_3': 0,
                    'widget_4': 'fixed',
                    'widget_5': True,
                    'widget_6': 'unipc',
                    'widget_7': 0,
                    'widget_8': 1,
                    'widget_9': False,
                    'widget_10': 'comfy',
                    'widget_11': '',
                    'model': ['152', 0],
                    'text_embeds': ['168', 0],
                    'image_embeds': ['148', 0],
                    'cache_args': ['147', 0],
                    'slg_args': ['149', 0],
                    'experimental_args': ['150', 0]}},
 '231': {'class_type': 'WanVideoVACEStartToEndFrame',
         'inputs': {'widget_0': 33,
                    'widget_1': 0.5000000000000001,
                    'start_image': ['238', 0],
                    'control_images': ['180', 0],
                    'num_frames': ['173', 1]}},
 '179': {'class_type': 'SetNode', 'inputs': {'widget_0': 'reference_image', 'IMAGE': ['230', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 3528},
 'ready_template': 'video/wanvideo_wrapper_13b_vace',
 'workflow_template': 'wanvideo_wrapper_13b_vace',
 'capability': 'vace_video_control',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan13b_vace.json',
 'coverage_tier': 'supplemental',
 'approach': 'VACE control/edit workflow',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [],
 'custom_nodes': ['ComfyUI-DepthAnythingV2', 'ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_13b_vace"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
