from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'120': {'class_type': 'MultiTalkModelLoader',
         'inputs': {'widget_0': 'WanVideo\\InfiniteTalk\\InfiniteTalk\\Wan2_1-InfiniteTalk_Single_Q8.gguf'}},
 '243': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '129': {'class_type': 'WanVideoVAELoader',
         'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '240': {'class_type': 'SetNode', 'inputs': {'widget_0': 'VAE', 'WANVAE': ['129', 0]}},
 '260': {'class_type': 'SetNode', 'inputs': {'widget_0': 'wanmodel', 'WANVIDEOMODEL': ['122', 0]}},
 '238': {'class_type': 'CLIPVisionLoader', 'inputs': {'widget_0': 'clip_vision_h.safetensors'}},
 '264': {'class_type': 'SetNode', 'inputs': {'widget_0': 'clip_vision_model', 'CLIP_VISION': ['238', 0]}},
 '247': {'class_type': 'SetNode', 'inputs': {'widget_0': 'width', 'INT': ['245', 0]}},
 '248': {'class_type': 'SetNode', 'inputs': {'widget_0': 'height', 'INT': ['246', 0]}},
 '261': {'class_type': 'GetNode', 'inputs': {'widget_0': 'wanmodel'}},
 '138': {'class_type': 'WanVideoLoraSelect',
         'inputs': {'widget_0': 'WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                    'widget_1': 1,
                    'widget_2': False,
                    'widget_3': False}},
 '134': {'class_type': 'WanVideoBlockSwap',
         'inputs': {'widget_0': 20,
                    'widget_1': False,
                    'widget_2': False,
                    'widget_3': True,
                    'widget_4': 0,
                    'widget_5': 1,
                    'widget_6': False}},
 '245': {'class_type': 'INTConstant', 'inputs': {'widget_0': 640}},
 '246': {'class_type': 'INTConstant', 'inputs': {'widget_0': 640}},
 '241': {'class_type': 'WanVideoTextEncodeCached',
         'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                    'widget_1': 'bf16',
                    'widget_2': 'a woman is singing a lullaby',
                    'widget_3': 'bright tones, overexposed, static, blurred details, subtitles, style, works, '
                                'paintings, images, static, overall gray, worst quality, low quality, JPEG compression '
                                'residue, ugly, incomplete, extra fingers, poorly drawn hands, poorly drawn faces, '
                                'deformed, disfigured, misshapen limbs, fused fingers, still picture, messy '
                                'background, three legs, many people in the background, walking backwards',
                    'widget_4': 'disabled',
                    'widget_5': False,
                    'widget_6': 'gpu'}},
 '254': {'class_type': 'GetNode', 'inputs': {'widget_0': 'input_audio'}},
 '249': {'class_type': 'GetNode', 'inputs': {'widget_0': 'height'}},
 '250': {'class_type': 'GetNode', 'inputs': {'widget_0': 'width'}},
 '192': {'class_type': 'WanVideoImageToVideoMultiTalk',
         'inputs': {'widget_0': 832,
                    'widget_1': 480,
                    'widget_2': 81,
                    'widget_3': 9,
                    'widget_4': False,
                    'widget_5': 'disabled',
                    'widget_6': False,
                    'widget_7': 'infinitetalk',
                    'vae': ['244', 0],
                    'start_image': ['291', 0],
                    'clip_embeds': ['237', 0],
                    'width': ['291', 1],
                    'height': ['291', 2]}},
 '244': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '237': {'class_type': 'WanVideoClipVisionEncode',
         'inputs': {'widget_0': 1,
                    'widget_1': 1,
                    'widget_2': 'center',
                    'widget_3': 'average',
                    'widget_4': True,
                    'widget_5': 0,
                    'widget_6': 0.5,
                    'clip_vision': ['265', 0],
                    'image_1': ['291', 0]}},
 '265': {'class_type': 'GetNode', 'inputs': {'widget_0': 'clip_vision_model'}},
 '242': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '270': {'class_type': 'INTConstant', 'inputs': {'widget_0': 1000}},
 '271': {'class_type': 'SetNode', 'inputs': {'widget_0': 'max_frames', 'INT': ['270', 0]}},
 '122': {'class_type': 'WanVideoModelLoader',
         'inputs': {'widget_0': 'WanVideo\\wan2.1-i2v-14b-480p-Q8_0.gguf',
                    'widget_1': 'fp16',
                    'widget_2': 'disabled',
                    'widget_3': 'offload_device',
                    'widget_4': 'sdpa',
                    'block_swap_args': ['134', 0],
                    'lora': ['138', 0],
                    'multitalk_model': ['120', 0]}},
 '177': {'class_type': 'WanVideoTorchCompileSettings',
         'inputs': {'widget_0': 'inductor',
                    'widget_1': False,
                    'widget_2': 'default',
                    'widget_3': False,
                    'widget_4': 64,
                    'widget_5': True,
                    'widget_6': 128}},
 '229': {'class_type': 'WanVideoEncode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'widget_5': 0,
                    'widget_6': 1,
                    'vae': ['243', 0],
                    'image': ['230', 0]}},
 '228': {'class_type': 'VHS_LoadVideo',
         'inputs': {'video': 'wolf_interpolated.mp4', 'custom_width': ['250', 0], 'custom_height': ['249', 0]}},
 '272': {'class_type': 'GetNode', 'inputs': {'widget_0': 'max_frames'}},
 '130': {'class_type': 'WanVideoDecode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'widget_5': 'default',
                    'vae': ['242', 0],
                    'samples': ['128', 0]}},
 '230': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': ['250', 0],
                    'height': ['249', 0],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'widget_7': 'cpu',
                    'image': ['228', 0]}},
 '231': {'class_type': 'GetImageRangeFromBatch', 'inputs': {'widget_0': 0, 'widget_1': 1, 'images': ['230', 0]}},
 '300': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['130', 0]}},
 '301': {'class_type': 'GetImageRangeFromBatch',
         'inputs': {'widget_0': 0, 'widget_1': 1, 'images': ['300', 0], 'num_frames': ['300', 3]}},
 '131': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['299', 0], 'audio': ['254', 0]}},
 '299': {'class_type': 'ImageConcatMulti',
         'inputs': {'widget_0': 2,
                    'widget_1': 'left',
                    'widget_2': False,
                    'widget_3': None,
                    'image_1': ['301', 0],
                    'image_2': ['230', 0]}},
 '128': {'class_type': 'WanVideoSampler',
         'inputs': {'steps': 1,
                    'widget_0': 1,
                    'widget_1': 1.0000000000000002,
                    'widget_2': 11.000000000000002,
                    'widget_3': 2,
                    'widget_4': 'fixed',
                    'widget_5': True,
                    'widget_6': 'dpm++_sde',
                    'widget_7': 0,
                    'widget_8': 1,
                    'widget_9': False,
                    'widget_10': 'comfy',
                    'widget_11': 2,
                    'widget_12': -1,
                    'widget_13': True,
                    'model': ['261', 0],
                    'image_embeds': ['192', 0],
                    'text_embeds': ['241', 0],
                    'samples': ['229', 0],
                    'multitalk_embeds': ['194', 0]}},
 '125': {'class_type': 'LoadAudio',
         'inputs': {'widget_0': 'one-does-not-simply-walk-into-mordor-its-black-gates-are-guarded-by-more-than-just-orcs.mp3',
                    'widget_1': None,
                    'widget_2': None}},
 '291': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['231', 0]}},
 '293': {'class_type': 'PreviewAny', 'inputs': {'source': ['294', 0]}},
 '294': {'class_type': 'SetNode', 'inputs': {'widget_0': 'actual_audio_frames', 'INT': ['194', 2]}},
 '194': {'class_type': 'MultiTalkWav2VecEmbeds',
         'inputs': {'widget_0': True,
                    'widget_1': 400,
                    'widget_2': 25,
                    'widget_3': 1.5,
                    'widget_4': 1,
                    'widget_5': 'para',
                    'wav2vec_model': ['137', 0],
                    'audio_1': ['304', 0],
                    'num_frames': ['272', 0]}},
 '253': {'class_type': 'SetNode', 'inputs': {'widget_0': 'input_audio', 'AUDIO': ['125', 0]}},
 '304': {'class_type': 'MelBandRoFormerSampler', 'inputs': {'model': ['303', 0], 'audio': ['253', 0]}},
 '303': {'class_type': 'MelBandRoFormerModelLoader',
         'inputs': {'widget_0': 'MelBandRoFormer\\MelBandRoformer_fp16.safetensors'}},
 '306': {'class_type': 'Wav2VecModelLoader',
         'inputs': {'widget_0': 'wav2vec2-chinese-base_fp16.safetensors',
                    'widget_1': 'fp16',
                    'widget_2': 'main_device'}},
 '137': {'class_type': 'DownloadAndLoadWav2VecModel',
         'inputs': {'widget_0': 'TencentGameMate/chinese-wav2vec2-base',
                    'widget_1': 'fp16',
                    'widget_2': 'main_device'}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 4971},
 'ready_template': 'video/wanvideo_wrapper_21_14b_v2v_infinitetalk',
 'workflow_template': 'wanvideo_wrapper_21_14b_v2v_infinitetalk',
 'capability': 'video_to_video_talking_avatar',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan21_14b_v2v_infinitetalk.json',
 'coverage_tier': 'supplemental',
 'approach': 'InfiniteTalk video-to-video talking avatar',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_21_14b_v2v_infinitetalk"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
