# vibecomfy: manual
"""Kijai WanVideoWrapper workflow bundled as a VibeComfy ready template."""
from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow

API_WORKFLOW = {'102': {'_ui': {'flags': {},
                 'id': 102,
                 'inputs': [],
                 'mode': 0,
                 'order': 28,
                 'outputs': [{'links': [185], 'name': 'sam2_model', 'type': 'SAM2MODEL'}],
                 'pos': [-470.4329528808594, -2221.738037109375],
                 'properties': {'Node name for S&R': 'DownloadAndLoadSAM2Model',
                                'cnr_id': 'ComfyUI-segment-anything-2',
                                'ver': 'c59676b008a76237002926f684d0ca3a9b29ac54'},
                 'size': [334.4137268066406, 130],
                 'type': 'DownloadAndLoadSAM2Model',
                 'widgets_values': ['sam2.1_hiera_base_plus.safetensors', 'video', 'cuda', 'fp16']},
         'class_type': 'DownloadAndLoadSAM2Model',
         'inputs': {'widget_0': 'sam2.1_hiera_base_plus.safetensors',
                    'widget_1': 'video',
                    'widget_2': 'cuda',
                    'widget_3': 'fp16'}},
 '104': {'_ui': {'flags': {},
                 'id': 104,
                 'inputs': [{'link': 185, 'name': 'sam2_model', 'type': 'SAM2MODEL'},
                            {'link': 316, 'name': 'image', 'type': 'IMAGE'},
                            {'link': None, 'name': 'coordinates_positive', 'shape': 7, 'type': 'STRING'},
                            {'link': None, 'name': 'coordinates_negative', 'shape': 7, 'type': 'STRING'},
                            {'link': 321, 'name': 'bboxes', 'shape': 7, 'type': 'BBOX'},
                            {'link': None, 'name': 'mask', 'shape': 7, 'type': 'MASK'}],
                 'mode': 0,
                 'order': 54,
                 'outputs': [{'links': [314], 'name': 'mask', 'type': 'MASK'}],
                 'pos': [83.82372283935547, -2220.965576171875],
                 'properties': {'Node name for S&R': 'Sam2Segmentation',
                                'cnr_id': 'ComfyUI-segment-anything-2',
                                'ver': 'c59676b008a76237002926f684d0ca3a9b29ac54'},
                 'size': [272.087890625, 182],
                 'type': 'Sam2Segmentation',
                 'widgets_values': [False, False]},
         'class_type': 'Sam2Segmentation',
         'inputs': {'bboxes': ['172', 3],
                    'image': ['180', 0],
                    'sam2_model': ['102', 0],
                    'widget_0': False,
                    'widget_1': False}},
 '108': {'_ui': {'flags': {},
                 'id': 108,
                 'inputs': [{'link': 315, 'name': 'masks', 'type': 'MASK'}],
                 'mode': 0,
                 'order': 61,
                 'outputs': [{'links': [245], 'name': 'mask', 'type': 'MASK'}],
                 'pos': [779.2421264648438, -2222.2099609375],
                 'properties': {'Node name for S&R': 'BlockifyMask',
                                'cnr_id': 'comfyui-kjnodes',
                                'ver': '00da1910634fbf314d407608efb281ae6f7f1ba2'},
                 'size': [270, 58],
                 'type': 'BlockifyMask',
                 'widgets_values': [32]},
         'class_type': 'BlockifyMask',
         'inputs': {'masks': ['182', 0], 'widget_0': 32}},
 '110': {'_ui': {'flags': {},
                 'id': 110,
                 'inputs': [{'link': None, 'name': 'reference_latent', 'shape': 7, 'type': 'LATENT'}],
                 'mode': 0,
                 'order': 19,
                 'outputs': [{'links': [], 'name': 'context_options', 'type': 'WANVIDCONTEXT'}],
                 'pos': [1829.0579833984375, -868.31298828125],
                 'properties': {'Node name for S&R': 'WanVideoContextOptions',
                                'cnr_id': 'ComfyUI-WanVideoWrapper',
                                'ver': '2bdd81a10b03c14443c79bdf3b783b1feb3d1fa3'},
                 'size': [275.783203125, 202],
                 'type': 'WanVideoContextOptions',
                 'widgets_values': ['static_standard', 81, 4, 32, True, False, 'linear']},
         'class_type': 'WanVideoContextOptions',
         'inputs': {'widget_0': 'static_standard',
                    'widget_1': 81,
                    'widget_2': 4,
                    'widget_3': 32,
                    'widget_4': True,
                    'widget_5': False,
                    'widget_6': 'linear'}},
 '127': {'_ui': {'bgcolor': '#653',
                 'color': '#432',
                 'flags': {},
                 'id': 127,
                 'inputs': [],
                 'mode': 0,
                 'order': 26,
                 'outputs': [],
                 'pos': [983.2726440429688, -2067.319580078125],
                 'properties': {},
                 'size': [210, 88],
                 'type': 'Note',
                 'widgets_values': ['These are new nodes in KJNodes']},
         'class_type': 'Note',
         'inputs': {'widget_0': 'These are new nodes in KJNodes'}},
 '128': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 128,
                 'inputs': [{'link': 231, 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'mode': 0,
                 'order': 46,
                 'outputs': [{'links': None, 'name': '*', 'type': '*'}],
                 'pos': [-459.54620361328125, -1650.783935546875],
                 'properties': {'previousName': 'reference_image'},
                 'size': [210, 60],
                 'title': 'Set_reference_image',
                 'type': 'SetNode',
                 'widgets_values': ['reference_image']},
         'class_type': 'SetNode',
         'inputs': {'IMAGE': ['64', 0], 'widget_0': 'reference_image'}},
 '130': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 130,
                 'inputs': [{'link': 233, 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'mode': 0,
                 'order': 65,
                 'outputs': [{'links': [251], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [1294.1051025390625, -2211.976806640625],
                 'properties': {'previousName': 'background_image'},
                 'size': [211.05747985839844, 60],
                 'title': 'Set_background_image',
                 'type': 'SetNode',
                 'widgets_values': ['background_image']},
         'class_type': 'SetNode',
         'inputs': {'IMAGE': ['99', 0], 'widget_0': 'background_image'}},
 '131': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 131,
                 'inputs': [],
                 'mode': 0,
                 'order': 7,
                 'outputs': [{'links': [234], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [1319.8330078125, -266.1221923828125],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_background_image',
                 'type': 'GetNode',
                 'widgets_values': ['background_image']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'background_image'}},
 '133': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 133,
                 'inputs': [],
                 'mode': 0,
                 'order': 13,
                 'outputs': [{'links': [235, 282], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [995.1069946289062, -382.21319580078125],
                 'properties': {},
                 'size': [210, 50],
                 'title': 'Get_reference_image',
                 'type': 'GetNode',
                 'widgets_values': ['reference_image']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'reference_image'}},
 '134': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 134,
                 'inputs': [],
                 'mode': 0,
                 'order': 2,
                 'outputs': [{'links': [236], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [2443.561279296875, -1227.2171630859375],
                 'properties': {},
                 'size': [210, 34],
                 'title': 'Get_reference_image',
                 'type': 'GetNode',
                 'widgets_values': ['reference_image']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'reference_image'}},
 '137': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 137,
                 'inputs': [],
                 'mode': 0,
                 'order': 0,
                 'outputs': [{'links': [239], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [2441.813232421875, -1173.92919921875],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_face_images',
                 'type': 'GetNode',
                 'widgets_values': ['face_images']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'face_images'}},
 '138': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 138,
                 'inputs': [],
                 'mode': 0,
                 'order': 27,
                 'outputs': [{'links': [240], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [1319.8330078125, -314.357421875],
                 'properties': {},
                 'size': [210, 50],
                 'title': 'Get_face_images',
                 'type': 'GetNode',
                 'widgets_values': ['face_images']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'face_images'}},
 '140': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 140,
                 'inputs': [],
                 'mode': 0,
                 'order': 1,
                 'outputs': [{'links': [243], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [2441.813232421875, -1124.576904296875],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_pose_images',
                 'type': 'GetNode',
                 'widgets_values': ['pose_images']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'pose_images'}},
 '141': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 141,
                 'inputs': [],
                 'mode': 0,
                 'order': 14,
                 'outputs': [{'links': [244], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [1320.70703125, -392.9727478027344],
                 'properties': {},
                 'size': [210, 34],
                 'title': 'Get_pose_images',
                 'type': 'GetNode',
                 'widgets_values': ['pose_images']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'pose_images'}},
 '142': {'_ui': {'bgcolor': '#1f401b',
                 'color': '#1c5715',
                 'flags': {'collapsed': True},
                 'id': 142,
                 'inputs': [{'link': 245, 'name': 'MASK', 'type': 'MASK'}],
                 'mode': 0,
                 'order': 63,
                 'outputs': [{'links': [246], 'name': 'MASK', 'type': 'MASK'}],
                 'pos': [1086.6927490234375, -2124.5263671875],
                 'properties': {'previousName': 'mask'},
                 'size': [210, 60],
                 'title': 'Set_mask',
                 'type': 'SetNode',
                 'widgets_values': ['mask']},
         'class_type': 'SetNode',
         'inputs': {'MASK': ['108', 0], 'widget_0': 'mask'}},
 '143': {'_ui': {'bgcolor': '#1f401b',
                 'color': '#1c5715',
                 'flags': {'collapsed': True},
                 'id': 143,
                 'inputs': [],
                 'mode': 0,
                 'order': 8,
                 'outputs': [{'links': [247], 'name': 'MASK', 'type': 'MASK'}],
                 'pos': [1319.8330078125, -213.2382354736328],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_mask',
                 'type': 'GetNode',
                 'widgets_values': ['mask']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'mask'}},
 '144': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 144,
                 'inputs': [{'link': 248, 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'mode': 0,
                 'order': 43,
                 'outputs': [{'links': [306], 'name': '*', 'type': '*'}],
                 'pos': [-522.720947265625, -3107.148681640625],
                 'properties': {'previousName': 'input_video'},
                 'size': [210, 60],
                 'title': 'Set_input_video',
                 'type': 'SetNode',
                 'widgets_values': ['input_video']},
         'class_type': 'SetNode',
         'inputs': {'IMAGE': ['63', 0], 'widget_0': 'input_video'}},
 '145': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 145,
                 'inputs': [],
                 'mode': 0,
                 'order': 17,
                 'outputs': [{'links': [249], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [2463.91552734375, -1073.7054443359375],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_input_video',
                 'type': 'GetNode',
                 'widgets_values': ['input_video']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'input_video'}},
 '146': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 146,
                 'inputs': [],
                 'mode': 0,
                 'order': 10,
                 'outputs': [{'links': [250], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [1086.932861328125, -2184.602783203125],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_input_video',
                 'type': 'GetNode',
                 'widgets_values': ['input_video']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'input_video'}},
 '148': {'_ui': {'flags': {'collapsed': True},
                 'id': 148,
                 'inputs': [{'link': 255, 'name': 'AUDIO', 'type': 'AUDIO'}],
                 'mode': 0,
                 'order': 45,
                 'outputs': [{'links': None, 'name': '*', 'type': '*'}],
                 'pos': [-548.7736206054688, -2964.476318359375],
                 'properties': {'previousName': 'input_audio'},
                 'size': [210, 60],
                 'title': 'Set_input_audio',
                 'type': 'SetNode',
                 'widgets_values': ['input_audio']},
         'class_type': 'SetNode',
         'inputs': {'AUDIO': ['63', 2], 'widget_0': 'input_audio'}},
 '149': {'_ui': {'flags': {'collapsed': True},
                 'id': 149,
                 'inputs': [],
                 'mode': 0,
                 'order': 3,
                 'outputs': [{'links': [256], 'name': 'AUDIO', 'type': 'AUDIO'}],
                 'pos': [3043.859130859375, -1156.882080078125],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_input_audio',
                 'type': 'GetNode',
                 'widgets_values': ['input_audio']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'input_audio'}},
 '150': {'_ui': {'bgcolor': '#29699c',
                 'color': '#1b4669',
                 'flags': {},
                 'id': 150,
                 'inputs': [],
                 'mode': 0,
                 'order': 30,
                 'outputs': [{'links': [257, 263, 286], 'name': 'value', 'type': 'INT'}],
                 'pos': [-1695.39013671875, -2773.4970703125],
                 'properties': {'Node name for S&R': 'INTConstant',
                                'cnr_id': 'comfyui-kjnodes',
                                'ver': '37659859825cea55940a58110525795ce5deb8be'},
                 'size': [210, 58],
                 'title': 'Width',
                 'type': 'INTConstant',
                 'widgets_values': [832]},
         'class_type': 'INTConstant',
         'inputs': {'widget_0': 832}},
 '151': {'_ui': {'bgcolor': '#29699c',
                 'color': '#1b4669',
                 'flags': {'collapsed': False},
                 'id': 151,
                 'inputs': [],
                 'mode': 0,
                 'order': 22,
                 'outputs': [{'links': [258, 264, 287], 'name': 'value', 'type': 'INT'}],
                 'pos': [-1704.931640625, -2640.54638671875],
                 'properties': {'Node name for S&R': 'INTConstant',
                                'cnr_id': 'comfyui-kjnodes',
                                'ver': '37659859825cea55940a58110525795ce5deb8be'},
                 'size': [210, 58],
                 'title': 'Height',
                 'type': 'INTConstant',
                 'widgets_values': [480]},
         'class_type': 'INTConstant',
         'inputs': {'widget_0': 480}},
 '153': {'_ui': {'bgcolor': '#29699c',
                 'color': '#1b4669',
                 'flags': {'collapsed': True},
                 'id': 153,
                 'inputs': [{'link': 263, 'name': 'INT', 'type': 'INT'}],
                 'mode': 0,
                 'order': 39,
                 'outputs': [{'links': None, 'name': '*', 'type': '*'}],
                 'pos': [-1605.1839599609375, -2832.218994140625],
                 'properties': {'previousName': 'width'},
                 'size': [210, 60],
                 'title': 'Set_width',
                 'type': 'SetNode',
                 'widgets_values': ['width']},
         'class_type': 'SetNode',
         'inputs': {'INT': ['150', 0], 'widget_0': 'width'}},
 '154': {'_ui': {'bgcolor': '#29699c',
                 'color': '#1b4669',
                 'flags': {'collapsed': True},
                 'id': 154,
                 'inputs': [{'link': 264, 'name': 'INT', 'type': 'INT'}],
                 'mode': 0,
                 'order': 37,
                 'outputs': [{'links': None, 'name': '*', 'type': '*'}],
                 'pos': [-1617.8741455078125, -2533.993408203125],
                 'properties': {'previousName': 'height'},
                 'size': [210, 60],
                 'title': 'Set_height',
                 'type': 'SetNode',
                 'widgets_values': ['height']},
         'class_type': 'SetNode',
         'inputs': {'INT': ['151', 0], 'widget_0': 'height'}},
 '155': {'_ui': {'bgcolor': '#29699c',
                 'color': '#1b4669',
                 'flags': {'collapsed': True},
                 'id': 155,
                 'inputs': [],
                 'mode': 0,
                 'order': 4,
                 'outputs': [{'links': [265], 'name': 'INT', 'type': 'INT'}],
                 'pos': [1319.8330078125, -167.58360290527344],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_width',
                 'type': 'GetNode',
                 'widgets_values': ['width']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'width'}},
 '156': {'_ui': {'bgcolor': '#29699c',
                 'color': '#1b4669',
                 'flags': {'collapsed': True},
                 'id': 156,
                 'inputs': [],
                 'mode': 0,
                 'order': 5,
                 'outputs': [{'links': [266], 'name': 'INT', 'type': 'INT'}],
                 'pos': [1319.8330078125, -117.76973724365234],
                 'properties': {},
                 'size': [210, 50],
                 'title': 'Get_height',
                 'type': 'GetNode',
                 'widgets_values': ['height']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'height'}},
 '157': {'_ui': {'bgcolor': '#29699c',
                 'color': '#1b4669',
                 'flags': {'collapsed': True},
                 'id': 157,
                 'inputs': [{'link': 267, 'name': 'INT', 'type': 'INT'}],
                 'mode': 0,
                 'order': 44,
                 'outputs': [{'links': None, 'name': '*', 'type': '*'}],
                 'pos': [-528.8223266601562, -3030.21337890625],
                 'properties': {'previousName': 'frame_count'},
                 'size': [210, 60],
                 'title': 'Set_frame_count',
                 'type': 'SetNode',
                 'widgets_values': ['frame_count']},
         'class_type': 'SetNode',
         'inputs': {'INT': ['63', 1], 'widget_0': 'frame_count'}},
 '158': {'_ui': {'bgcolor': '#29699c',
                 'color': '#1b4669',
                 'flags': {'collapsed': True},
                 'id': 158,
                 'inputs': [],
                 'mode': 0,
                 'order': 6,
                 'outputs': [{'links': [268], 'name': 'INT', 'type': 'INT'}],
                 'pos': [1319.8330078125, -70.84321594238281],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_frame_count',
                 'type': 'GetNode',
                 'widgets_values': ['frame_count']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'frame_count'}},
 '161': {'_ui': {'bgcolor': '#533',
                 'color': '#322',
                 'flags': {'collapsed': True},
                 'id': 161,
                 'inputs': [{'link': 278, 'name': 'WANVAE', 'type': 'WANVAE'}],
                 'mode': 0,
                 'order': 35,
                 'outputs': [{'links': None, 'name': '*', 'type': '*'}],
                 'pos': [-259.3302001953125, -357.3097839355469],
                 'properties': {'previousName': 'VAE'},
                 'size': [210, 60],
                 'title': 'Set_VAE',
                 'type': 'SetNode',
                 'widgets_values': ['VAE']},
         'class_type': 'SetNode',
         'inputs': {'WANVAE': ['38', 0], 'widget_0': 'VAE'}},
 '162': {'_ui': {'bgcolor': '#533',
                 'color': '#322',
                 'flags': {'collapsed': True},
                 'id': 162,
                 'inputs': [],
                 'mode': 0,
                 'order': 18,
                 'outputs': [{'links': [279], 'name': 'WANVAE', 'type': 'WANVAE'}],
                 'pos': [2483.826171875, -523.2938842773438],
                 'properties': {},
                 'size': [210, 60],
                 'title': 'Get_VAE',
                 'type': 'GetNode',
                 'widgets_values': ['VAE']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'VAE'}},
 '163': {'_ui': {'bgcolor': '#533',
                 'color': '#322',
                 'flags': {'collapsed': True},
                 'id': 163,
                 'inputs': [],
                 'mode': 0,
                 'order': 11,
                 'outputs': [{'links': [280], 'name': 'WANVAE', 'type': 'WANVAE'}],
                 'pos': [1571.3441162109375, -468.3181457519531],
                 'properties': {},
                 'size': [210, 34],
                 'title': 'Get_VAE',
                 'type': 'GetNode',
                 'widgets_values': ['VAE']},
         'class_type': 'GetNode',
         'inputs': {'widget_0': 'VAE'}},
 '164': {'_ui': {'bgcolor': '#653',
                 'color': '#432',
                 'flags': {},
                 'id': 164,
                 'inputs': [],
                 'mode': 0,
                 'order': 31,
                 'outputs': [],
                 'pos': [-1191.340087890625, -515.903564453125],
                 'properties': {},
                 'size': [541.7905883789062, 240.68362426757812],
                 'title': 'Markdown Note: Model Links',
                 'type': 'MarkdownNote',
                 'widgets_values': ['Model links:\n'
                                    '\n'
                                    '[https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/tree/main/Wan22Animate](https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/tree/main/Wan22Animate)\n'
                                    '\n'
                                    'LoRA:\n'
                                    '\n'
                                    '[https://huggingface.co/Kijai/WanVideo_comfy/tree/main/Lightx2v](https://huggingface.co/Kijai/WanVideo_comfy/tree/main/Lightx2v)\n'
                                    '\n'
                                    '[https://huggingface.co/Kijai/WanVideo_comfy/tree/main/LoRAs/Wan22_relight](https://huggingface.co/Kijai/WanVideo_comfy/tree/main/LoRAs/Wan22_relight)\n'
                                    '\n'
                                    'Text encoder:\n'
                                    '\n'
                                    '[https://huggingface.co/Kijai/WanVideo_comfy/blob/main/umt5-xxl-enc-bf16.safetensors](https://huggingface.co/Kijai/WanVideo_comfy/blob/main/umt5-xxl-enc-bf16.safetensors)\n'
                                    '\n'
                                    'VAE:\n'
                                    '\n'
                                    '[https://huggingface.co/Kijai/WanVideo_comfy/blob/main/Wan2_1_VAE_bf16.safetensors](https://huggingface.co/Kijai/WanVideo_comfy/blob/main/Wan2_1_VAE_bf16.safetensors)']},
         'class_type': 'MarkdownNote',
         'inputs': {'widget_0': 'Model links:\n'
                                '\n'
                                '[https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/tree/main/Wan22Animate](https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/tree/main/Wan22Animate)\n'
                                '\n'
                                'LoRA:\n'
                                '\n'
                                '[https://huggingface.co/Kijai/WanVideo_comfy/tree/main/Lightx2v](https://huggingface.co/Kijai/WanVideo_comfy/tree/main/Lightx2v)\n'
                                '\n'
                                '[https://huggingface.co/Kijai/WanVideo_comfy/tree/main/LoRAs/Wan22_relight](https://huggingface.co/Kijai/WanVideo_comfy/tree/main/LoRAs/Wan22_relight)\n'
                                '\n'
                                'Text encoder:\n'
                                '\n'
                                '[https://huggingface.co/Kijai/WanVideo_comfy/blob/main/umt5-xxl-enc-bf16.safetensors](https://huggingface.co/Kijai/WanVideo_comfy/blob/main/umt5-xxl-enc-bf16.safetensors)\n'
                                '\n'
                                'VAE:\n'
                                '\n'
                                '[https://huggingface.co/Kijai/WanVideo_comfy/blob/main/Wan2_1_VAE_bf16.safetensors](https://huggingface.co/Kijai/WanVideo_comfy/blob/main/Wan2_1_VAE_bf16.safetensors)'}},
 '169': {'_ui': {'bgcolor': '#653',
                 'color': '#432',
                 'flags': {},
                 'id': 169,
                 'inputs': [],
                 'mode': 0,
                 'order': 21,
                 'outputs': [],
                 'pos': [1282.7142333984375, -825.0780029296875],
                 'properties': {},
                 'size': [484.7705383300781, 194.427978515625],
                 'type': 'Note',
                 'widgets_values': ['For long generations you can use either context options, or the original long gen '
                                    'method, which is activated when frame_window_size is smaller than total '
                                    'frames(num_frames). When using this method the window size stays constant, extra '
                                    'frames are generated in the case the last window is cut short.\n'
                                    '\n'
                                    'When using context options, set num_frames and frame_window_size to be equal\n'
                                    '\n'
                                    'Otherwise set frame_window_size to something the model is capable of doing '
                                    'normally, original default is 77, 81 seems to work too.\n'
                                    '\n'
                                    'Original method is probably better for motion etc, and is faster, but the benefit '
                                    "of context windows is that it doesn't degrade over time on long clips."]},
         'class_type': 'Note',
         'inputs': {'widget_0': 'For long generations you can use either context options, or the original long gen '
                                'method, which is activated when frame_window_size is smaller than total '
                                'frames(num_frames). When using this method the window size stays constant, extra '
                                'frames are generated in the case the last window is cut short.\n'
                                '\n'
                                'When using context options, set num_frames and frame_window_size to be equal\n'
                                '\n'
                                'Otherwise set frame_window_size to something the model is capable of doing normally, '
                                'original default is 77, 81 seems to work too.\n'
                                '\n'
                                'Original method is probably better for motion etc, and is faster, but the benefit of '
                                "context windows is that it doesn't degrade over time on long clips."}},
 '171': {'_ui': {'bgcolor': '#335',
                 'color': '#223',
                 'flags': {},
                 'id': 171,
                 'inputs': [{'link': None, 'name': 'prev_lora', 'shape': 7, 'type': 'WANVIDLORA'},
                            {'link': None, 'name': 'blocks', 'shape': 7, 'type': 'SELECTEDBLOCKS'}],
                 'mode': 0,
                 'order': 24,
                 'outputs': [{'links': [289], 'name': 'lora', 'type': 'WANVIDLORA'}],
                 'pos': [3.4800829887390137, -932.2160034179688],
                 'properties': {'Node name for S&R': 'WanVideoLoraSelectMulti',
                                'cnr_id': 'ComfyUI-WanVideoWrapper',
                                'ver': 'b2c8cf969fcf60a38884ea2c29af177ae1f28b29'},
                 'size': [583.3719482421875, 342],
                 'type': 'WanVideoLoraSelectMulti',
                 'widgets_values': ['WanVideo\\WanAnimate_relight_lora_fp16.safetensors',
                                    1,
                                    'WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                                    1.2,
                                    'none',
                                    1,
                                    'none',
                                    1,
                                    'none',
                                    1,
                                    False,
                                    False]},
         'class_type': 'WanVideoLoraSelectMulti',
         'inputs': {'widget_0': 'WanVideo\\WanAnimate_relight_lora_fp16.safetensors',
                    'widget_1': 1,
                    'widget_10': False,
                    'widget_11': False,
                    'widget_2': 'WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                    'widget_3': 1.2,
                    'widget_4': 'none',
                    'widget_5': 1,
                    'widget_6': 'none',
                    'widget_7': 1,
                    'widget_8': 'none',
                    'widget_9': 1}},
 '172': {'_ui': {'flags': {},
                 'id': 172,
                 'inputs': [{'link': 290, 'name': 'model', 'type': 'POSEMODEL'},
                            {'link': 309, 'name': 'images', 'type': 'IMAGE'},
                            {'link': None, 'name': 'retarget_image', 'shape': 7, 'type': 'IMAGE'},
                            {'link': 310, 'name': 'width', 'type': 'INT', 'widget': {'name': 'width'}},
                            {'link': 311, 'name': 'height', 'type': 'INT', 'widget': {'name': 'height'}}],
                 'mode': 0,
                 'order': 50,
                 'outputs': [{'links': [294], 'name': 'pose_data', 'type': 'POSEDATA'},
                             {'links': [317], 'name': 'face_images', 'type': 'IMAGE'},
                             {'links': None, 'name': 'key_frame_body_points', 'type': 'STRING'},
                             {'links': [321], 'name': 'bboxes', 'type': 'BBOX'}],
                 'pos': [104.5530014038086, -3028.416015625],
                 'properties': {'Node name for S&R': 'PoseAndFaceDetection',
                                'aux_id': 'kijai/ComfyUI-WanAnimatePreprocess',
                                'ver': 'e63d6e71ae4c271f3f81211a7ca7f87607b7e50d'},
                 'size': [313.125, 142],
                 'type': 'PoseAndFaceDetection',
                 'widgets_values': [832, 480]},
         'class_type': 'PoseAndFaceDetection',
         'inputs': {'height': ['180', 2],
                    'images': ['180', 0],
                    'model': ['178', 0],
                    'widget_0': 832,
                    'widget_1': 480,
                    'width': ['180', 1]}},
 '173': {'_ui': {'flags': {},
                 'id': 173,
                 'inputs': [{'link': 294, 'name': 'pose_data', 'type': 'POSEDATA'},
                            {'link': 307, 'name': 'width', 'type': 'INT', 'widget': {'name': 'width'}},
                            {'link': 308, 'name': 'height', 'type': 'INT', 'widget': {'name': 'height'}}],
                 'mode': 0,
                 'order': 52,
                 'outputs': [{'links': [319], 'name': 'pose_images', 'type': 'IMAGE'}],
                 'pos': [120.56317138671875, -2811.226318359375],
                 'properties': {'Node name for S&R': 'DrawViTPose',
                                'aux_id': 'kijai/ComfyUI-WanAnimatePreprocess',
                                'ver': 'e63d6e71ae4c271f3f81211a7ca7f87607b7e50d'},
                 'size': [270, 178],
                 'type': 'DrawViTPose',
                 'widgets_values': [832, 480, 16, -1, -1, 'True']},
         'class_type': 'DrawViTPose',
         'inputs': {'height': ['180', 2],
                    'pose_data': ['172', 0],
                    'widget_0': 832,
                    'widget_1': 480,
                    'widget_2': 16,
                    'widget_3': -1,
                    'widget_4': -1,
                    'widget_5': 'True',
                    'width': ['180', 1]}},
 '174': {'_ui': {'flags': {},
                 'id': 174,
                 'inputs': [{'link': 318, 'name': 'images', 'type': 'IMAGE'},
                            {'link': None, 'name': 'audio', 'shape': 7, 'type': 'AUDIO'},
                            {'link': None, 'name': 'meta_batch', 'shape': 7, 'type': 'VHS_BatchManager'},
                            {'link': None, 'name': 'vae', 'shape': 7, 'type': 'VAE'}],
                 'mode': 0,
                 'order': 57,
                 'outputs': [{'links': None, 'name': 'Filenames', 'type': 'VHS_FILENAMES'}],
                 'pos': [714.7760009765625, -3057.50341796875],
                 'properties': {'Node name for S&R': 'VHS_VideoCombine',
                                'cnr_id': 'comfyui-videohelpersuite',
                                'ver': '0edce8ef7ce173ac97a3ed3d6f4636029d1a4530'},
                 'size': [214.7587890625, 542.7587890625],
                 'type': 'VHS_VideoCombine',
                 'widgets_values': {'crf': 19,
                                    'filename_prefix': 'vitpose',
                                    'format': 'video/h264-mp4',
                                    'frame_rate': 16,
                                    'loop_count': 0,
                                    'pingpong': False,
                                    'pix_fmt': 'yuv420p',
                                    'save_metadata': True,
                                    'save_output': False,
                                    'trim_to_audio': False,
                                    'videopreview': {'hidden': False,
                                                     'params': {'filename': 'vitpose_00004.mp4',
                                                                'format': 'video/h264-mp4',
                                                                'frame_rate': 16,
                                                                'fullpath': 'N:\\AI\\ComfyUI\\temp\\vitpose_00004.mp4',
                                                                'subfolder': '',
                                                                'type': 'temp',
                                                                'workflow': 'vitpose_00004.png'},
                                                     'paused': False}}},
         'class_type': 'VHS_VideoCombine',
         'inputs': {'crf': 19,
                    'filename_prefix': 'vitpose',
                    'format': 'video/h264-mp4',
                    'frame_rate': 16,
                    'images': ['183', 0],
                    'loop_count': 0,
                    'pingpong': False,
                    'pix_fmt': 'yuv420p',
                    'save_metadata': True,
                    'save_output': False,
                    'trim_to_audio': False,
                    'videopreview': {'hidden': False,
                                     'params': {'filename': 'vitpose_00004.mp4',
                                                'format': 'video/h264-mp4',
                                                'frame_rate': 16,
                                                'fullpath': 'N:\\AI\\ComfyUI\\temp\\vitpose_00004.mp4',
                                                'subfolder': '',
                                                'type': 'temp',
                                                'workflow': 'vitpose_00004.png'},
                                     'paused': False}}},
 '177': {'_ui': {'bgcolor': '#653',
                 'color': '#432',
                 'flags': {},
                 'id': 177,
                 'inputs': [],
                 'mode': 0,
                 'order': 32,
                 'outputs': [],
                 'pos': [-1088.8204345703125, -2393.302978515625],
                 'properties': {},
                 'size': [536.27783203125, 330.03546142578125],
                 'title': 'Preprocessor links',
                 'type': 'MarkdownNote',
                 'widgets_values': ['Nodes:\n'
                                    '\n'
                                    '[https://github.com/kijai/ComfyUI-WanAnimatePreprocess](https://github.com/kijai/ComfyUI-WanAnimatePreprocess)\n'
                                    '\n'
                                    'Models:\n'
                                    '\n'
                                    'YOLO:\n'
                                    '\n'
                                    '[https://huggingface.co/Wan-AI/Wan2.2-Animate-14B/blob/main/process_checkpoint/det/yolov10m.onnx](https://huggingface.co/Wan-AI/Wan2.2-Animate-14B/blob/main/process_checkpoint/det/yolov10m.onnx)\n'
                                    '\n'
                                    'ViTPose\n'
                                    '\n'
                                    'Large:\n'
                                    '\n'
                                    '[https://huggingface.co/JunkyByte/easy_ViTPose/blob/main/onnx/wholebody/vitpose-l-wholebody.onnx](https://huggingface.co/JunkyByte/easy_ViTPose/blob/main/onnx/wholebody/vitpose-l-wholebody.onnx)\n'
                                    '\n'
                                    'Huge (needs both files):\n'
                                    '\n'
                                    '[https://huggingface.co/Kijai/vitpose_comfy/blob/main/onnx/vitpose_h_wholebody_model.onnx](https://huggingface.co/Kijai/vitpose_comfy/blob/main/onnx/vitpose_h_wholebody_model.onnx)\n'
                                    '\n'
                                    '[https://huggingface.co/Kijai/vitpose_comfy/blob/main/onnx/vitpose_h_wholebody_data.bin](https://huggingface.co/Kijai/vitpose_comfy/blob/main/onnx/vitpose_h_wholebody_data.bin)']},
         'class_type': 'MarkdownNote',
         'inputs': {'widget_0': 'Nodes:\n'
                                '\n'
                                '[https://github.com/kijai/ComfyUI-WanAnimatePreprocess](https://github.com/kijai/ComfyUI-WanAnimatePreprocess)\n'
                                '\n'
                                'Models:\n'
                                '\n'
                                'YOLO:\n'
                                '\n'
                                '[https://huggingface.co/Wan-AI/Wan2.2-Animate-14B/blob/main/process_checkpoint/det/yolov10m.onnx](https://huggingface.co/Wan-AI/Wan2.2-Animate-14B/blob/main/process_checkpoint/det/yolov10m.onnx)\n'
                                '\n'
                                'ViTPose\n'
                                '\n'
                                'Large:\n'
                                '\n'
                                '[https://huggingface.co/JunkyByte/easy_ViTPose/blob/main/onnx/wholebody/vitpose-l-wholebody.onnx](https://huggingface.co/JunkyByte/easy_ViTPose/blob/main/onnx/wholebody/vitpose-l-wholebody.onnx)\n'
                                '\n'
                                'Huge (needs both files):\n'
                                '\n'
                                '[https://huggingface.co/Kijai/vitpose_comfy/blob/main/onnx/vitpose_h_wholebody_model.onnx](https://huggingface.co/Kijai/vitpose_comfy/blob/main/onnx/vitpose_h_wholebody_model.onnx)\n'
                                '\n'
                                '[https://huggingface.co/Kijai/vitpose_comfy/blob/main/onnx/vitpose_h_wholebody_data.bin](https://huggingface.co/Kijai/vitpose_comfy/blob/main/onnx/vitpose_h_wholebody_data.bin)'}},
 '178': {'_ui': {'flags': {},
                 'id': 178,
                 'inputs': [],
                 'mode': 0,
                 'order': 25,
                 'outputs': [{'links': [290], 'name': 'model', 'type': 'POSEMODEL'}],
                 'pos': [-506.44635009765625, -2398.935302734375],
                 'properties': {'Node name for S&R': 'OnnxDetectionModelLoader',
                                'aux_id': 'kijai/ComfyUI-WanAnimatePreprocess',
                                'ver': 'e63d6e71ae4c271f3f81211a7ca7f87607b7e50d'},
                 'size': [351.52410888671875, 106],
                 'type': 'OnnxDetectionModelLoader',
                 'widgets_values': ['vitpose-l-wholebody.onnx', 'onnx\\yolov10m.onnx', 'CUDAExecutionProvider']},
         'class_type': 'OnnxDetectionModelLoader',
         'inputs': {'widget_0': 'vitpose-l-wholebody.onnx',
                    'widget_1': 'onnx\\yolov10m.onnx',
                    'widget_2': 'CUDAExecutionProvider'}},
 '180': {'_ui': {'flags': {},
                 'id': 180,
                 'inputs': [{'link': 306, 'name': 'image', 'type': 'IMAGE'}],
                 'mode': 0,
                 'order': 48,
                 'outputs': [{'links': [309, 316], 'name': 'image', 'type': 'IMAGE'},
                             {'label': '832 width', 'links': [307, 310], 'name': 'width', 'type': 'INT'},
                             {'label': '480 height', 'links': [308, 311], 'name': 'height', 'type': 'INT'},
                             {'label': '109 count', 'links': None, 'name': 'count', 'type': 'INT'}],
                 'pos': [-246.24586486816406, -3011.47705078125],
                 'properties': {'Node name for S&R': 'GetImageSizeAndCount',
                                'cnr_id': 'comfyui-kjnodes',
                                'ver': 'bb205d809b467307b8ec3bb1a22680a4873187f8'},
                 'size': [190.86483764648438, 86],
                 'type': 'GetImageSizeAndCount',
                 'widgets_values': []},
         'class_type': 'GetImageSizeAndCount',
         'inputs': {'image': ['144', 0]}},
 '181': {'_ui': {'flags': {},
                 'id': 181,
                 'inputs': [{'link': 320, 'name': 'images', 'type': 'IMAGE'},
                            {'link': None, 'name': 'audio', 'shape': 7, 'type': 'AUDIO'},
                            {'link': None, 'name': 'meta_batch', 'shape': 7, 'type': 'VHS_BatchManager'},
                            {'link': None, 'name': 'vae', 'shape': 7, 'type': 'VAE'}],
                 'mode': 0,
                 'order': 60,
                 'outputs': [{'links': None, 'name': 'Filenames', 'type': 'VHS_FILENAMES'}],
                 'pos': [1137.4183349609375, -3026.80517578125],
                 'properties': {'Node name for S&R': 'VHS_VideoCombine',
                                'cnr_id': 'comfyui-videohelpersuite',
                                'ver': '8e4d79471bf1952154768e8435a9300077b534fa'},
                 'size': [743.6680297851562, 765.5007934570312],
                 'type': 'VHS_VideoCombine',
                 'widgets_values': {'crf': 19,
                                    'filename_prefix': 'WanVideo2_1_T2V',
                                    'format': 'video/h264-mp4',
                                    'frame_rate': 16,
                                    'loop_count': 0,
                                    'pingpong': False,
                                    'pix_fmt': 'yuv420p',
                                    'save_metadata': True,
                                    'save_output': False,
                                    'trim_to_audio': False,
                                    'videopreview': {'hidden': False,
                                                     'params': {'filename': 'WanVideo2_1_T2V_00002.mp4',
                                                                'format': 'video/h264-mp4',
                                                                'frame_rate': 16,
                                                                'fullpath': 'N:\\AI\\ComfyUI\\temp\\WanVideo2_1_T2V_00002.mp4',
                                                                'subfolder': '',
                                                                'type': 'temp',
                                                                'workflow': 'WanVideo2_1_T2V_00002.png'},
                                                     'paused': False}}},
         'class_type': 'VHS_VideoCombine',
         'inputs': {'crf': 19,
                    'filename_prefix': 'WanVideo2_1_T2V',
                    'format': 'video/h264-mp4',
                    'frame_rate': 16,
                    'images': ['184', 0],
                    'loop_count': 0,
                    'pingpong': False,
                    'pix_fmt': 'yuv420p',
                    'save_metadata': True,
                    'save_output': False,
                    'trim_to_audio': False,
                    'videopreview': {'hidden': False,
                                     'params': {'filename': 'WanVideo2_1_T2V_00002.mp4',
                                                'format': 'video/h264-mp4',
                                                'frame_rate': 16,
                                                'fullpath': 'N:\\AI\\ComfyUI\\temp\\WanVideo2_1_T2V_00002.mp4',
                                                'subfolder': '',
                                                'type': 'temp',
                                                'workflow': 'WanVideo2_1_T2V_00002.png'},
                                     'paused': False}}},
 '182': {'_ui': {'flags': {},
                 'id': 182,
                 'inputs': [{'link': 314, 'name': 'mask', 'type': 'MASK'}],
                 'mode': 0,
                 'order': 58,
                 'outputs': [{'links': [315], 'name': 'mask', 'type': 'MASK'},
                             {'links': None, 'name': 'mask_inverted', 'type': 'MASK'}],
                 'pos': [431.7315368652344, -2222.123779296875],
                 'properties': {'Node name for S&R': 'GrowMaskWithBlur',
                                'cnr_id': 'comfyui-kjnodes',
                                'ver': 'bb205d809b467307b8ec3bb1a22680a4873187f8'},
                 'size': [292.748046875, 246],
                 'type': 'GrowMaskWithBlur',
                 'widgets_values': [10, 0, True, False, 0, 1, 1, False]},
         'class_type': 'GrowMaskWithBlur',
         'inputs': {'mask': ['104', 0],
                    'widget_0': 10,
                    'widget_1': 0,
                    'widget_2': True,
                    'widget_3': False,
                    'widget_4': 0,
                    'widget_5': 1,
                    'widget_6': 1,
                    'widget_7': False}},
 '183': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 183,
                 'inputs': [{'link': 317, 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'mode': 0,
                 'order': 53,
                 'outputs': [{'links': [318], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [464.6632080078125, -3038.54296875],
                 'properties': {'previousName': 'face_images'},
                 'size': [210, 60],
                 'title': 'Set_face_images',
                 'type': 'SetNode',
                 'widgets_values': ['face_images']},
         'class_type': 'SetNode',
         'inputs': {'IMAGE': ['172', 1], 'widget_0': 'face_images'}},
 '184': {'_ui': {'bgcolor': '#3f5159',
                 'color': '#2a363b',
                 'flags': {'collapsed': True},
                 'id': 184,
                 'inputs': [{'link': 319, 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'mode': 0,
                 'order': 56,
                 'outputs': [{'links': [320], 'name': 'IMAGE', 'type': 'IMAGE'}],
                 'pos': [442.45526123046875, -2784.734375],
                 'properties': {'previousName': 'pose_images'},
                 'size': [210, 60],
                 'title': 'Set_pose_images',
                 'type': 'SetNode',
                 'widgets_values': ['pose_images']},
         'class_type': 'SetNode',
         'inputs': {'IMAGE': ['173', 0], 'widget_0': 'pose_images'}},
 '185': {'_ui': {'bgcolor': '#653',
                 'color': '#432',
                 'flags': {},
                 'id': 185,
                 'inputs': [],
                 'mode': 0,
                 'order': 29,
                 'outputs': [],
                 'pos': [257.0601806640625, -2465.42041015625],
                 'properties': {},
                 'size': [236.14007568359375, 88],
                 'title': 'Note: SAM2 detection',
                 'type': 'Note',
                 'widgets_values': ['You can use either the detected bbox or the kay_frame_body_points to positive '
                                    'coordinates, if one fails to creater proper mask, try the other']},
         'class_type': 'Note',
         'inputs': {'widget_0': 'You can use either the detected bbox or the kay_frame_body_points to positive '
                                'coordinates, if one fails to creater proper mask, try the other'}},
 '22': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 22,
                'inputs': [{'link': 100, 'name': 'compile_args', 'shape': 7, 'type': 'WANCOMPILEARGS'},
                           {'link': None, 'name': 'block_swap_args', 'shape': 7, 'type': 'BLOCKSWAPARGS'},
                           {'link': None, 'name': 'lora', 'shape': 7, 'type': 'WANVIDLORA'},
                           {'link': None, 'name': 'vram_management_args', 'shape': 7, 'type': 'VRAM_MANAGEMENTARGS'},
                           {'link': None, 'name': 'extra_model', 'shape': 7, 'type': 'VACEPATH'},
                           {'link': None, 'name': 'fantasytalking_model', 'shape': 7, 'type': 'FANTASYTALKINGMODEL'},
                           {'link': None, 'name': 'multitalk_model', 'shape': 7, 'type': 'MULTITALKMODEL'},
                           {'link': None, 'name': 'fantasyportrait_model', 'shape': 7, 'type': 'FANTASYPORTRAITMODEL'}],
                'mode': 0,
                'order': 34,
                'outputs': [{'links': [59], 'name': 'model', 'slot_index': 0, 'type': 'WANVIDEOMODEL'}],
                'pos': [-700.9990844726562, -908.7992553710938],
                'properties': {'Node name for S&R': 'WanVideoModelLoader',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': 'e5ef9752a7e846b232fc05fd993327a2e870a788'},
                'size': [601.9249267578125, 318],
                'type': 'WanVideoModelLoader',
                'widgets_values': ['WanVideo\\2_2\\Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors',
                                   'fp16_fast',
                                   'disabled',
                                   'offload_device',
                                   'sageattn',
                                   'default']},
        'class_type': 'WanVideoModelLoader',
        'inputs': {'compile_args': ['35', 0],
                   'widget_0': 'WanVideo\\2_2\\Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors',
                   'widget_1': 'fp16_fast',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sageattn',
                   'widget_5': 'default'}},
 '27': {'_ui': {'flags': {},
                'id': 27,
                'inputs': [{'link': 63, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 84, 'name': 'image_embeds', 'type': 'WANVIDIMAGE_EMBEDS'},
                           {'link': 281, 'name': 'text_embeds', 'shape': 7, 'type': 'WANVIDEOTEXTEMBEDS'},
                           {'link': None, 'name': 'samples', 'shape': 7, 'type': 'LATENT'},
                           {'link': None, 'name': 'feta_args', 'shape': 7, 'type': 'FETAARGS'},
                           {'link': None, 'name': 'context_options', 'shape': 7, 'type': 'WANVIDCONTEXT'},
                           {'link': None, 'name': 'cache_args', 'shape': 7, 'type': 'CACHEARGS'},
                           {'link': None, 'name': 'flowedit_args', 'shape': 7, 'type': 'FLOWEDITARGS'},
                           {'link': None, 'name': 'slg_args', 'shape': 7, 'type': 'SLGARGS'},
                           {'link': None, 'name': 'loop_args', 'shape': 7, 'type': 'LOOPARGS'},
                           {'link': None, 'name': 'experimental_args', 'shape': 7, 'type': 'EXPERIMENTALARGS'},
                           {'link': None, 'name': 'sigmas', 'shape': 7, 'type': 'SIGMAS'},
                           {'link': None, 'name': 'unianimate_poses', 'shape': 7, 'type': 'UNIANIMATE_POSE'},
                           {'link': None, 'name': 'fantasytalking_embeds', 'shape': 7, 'type': 'FANTASYTALKING_EMBEDS'},
                           {'link': None, 'name': 'uni3c_embeds', 'shape': 7, 'type': 'UNI3C_EMBEDS'},
                           {'link': None, 'name': 'multitalk_embeds', 'shape': 7, 'type': 'MULTITALK_EMBEDS'},
                           {'link': None, 'name': 'freeinit_args', 'shape': 7, 'type': 'FREEINITARGS'}],
                'mode': 0,
                'order': 49,
                'outputs': [{'links': [33], 'name': 'samples', 'slot_index': 0, 'type': 'LATENT'},
                            {'links': None, 'name': 'denoised_samples', 'type': 'LATENT'}],
                'pos': [2107.4375, -539.1071166992188],
                'properties': {'Node name for S&R': 'WanVideoSampler',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': 'e5ef9752a7e846b232fc05fd993327a2e870a788'},
                'size': [315, 874.1923217773438],
                'type': 'WanVideoSampler',
                'widgets_values': [4, 1, 5, 42, 'fixed', True, 'dpm++_sde', 0, 1, '', 'comfy', 0, -1, False]},
        'class_type': 'WanVideoSampler',
        'inputs': {'image_embeds': ['62', 0],
                   'model': ['50', 0],
                   'text_embeds': ['65', 0],
                   'widget_0': 4,
                   'widget_1': 1,
                   'widget_10': 'comfy',
                   'widget_11': 0,
                   'widget_12': -1,
                   'widget_13': False,
                   'widget_2': 5,
                   'widget_3': 42,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'dpm++_sde',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': ''}},
 '28': {'_ui': {'flags': {},
                'id': 28,
                'inputs': [{'link': 279, 'name': 'vae', 'type': 'WANVAE'},
                           {'link': 33, 'name': 'samples', 'type': 'LATENT'}],
                'mode': 0,
                'order': 51,
                'outputs': [{'links': [48], 'name': 'images', 'slot_index': 0, 'type': 'IMAGE'}],
                'pos': [2485.57177734375, -441.313720703125],
                'properties': {'Node name for S&R': 'WanVideoDecode',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': 'e5ef9752a7e846b232fc05fd993327a2e870a788'},
                'size': [280.3896179199219, 198],
                'type': 'WanVideoDecode',
                'widgets_values': [False, 272, 272, 144, 128, 'default']},
        'class_type': 'WanVideoDecode',
        'inputs': {'samples': ['27', 0],
                   'vae': ['162', 0],
                   'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 'default'}},
 '30': {'_ui': {'flags': {},
                'id': 30,
                'inputs': [{'link': 89, 'name': 'images', 'type': 'IMAGE'},
                           {'link': 256, 'name': 'audio', 'shape': 7, 'type': 'AUDIO'},
                           {'link': None, 'name': 'meta_batch', 'shape': 7, 'type': 'VHS_BatchManager'},
                           {'link': None, 'name': 'vae', 'shape': 7, 'type': 'VAE'}],
                'mode': 0,
                'order': 62,
                'outputs': [{'links': None, 'name': 'Filenames', 'type': 'VHS_FILENAMES'}],
                'pos': [3064.7763671875, -1021.487548828125],
                'properties': {'Node name for S&R': 'VHS_VideoCombine',
                               'cnr_id': 'comfyui-videohelpersuite',
                               'ver': '8e4d79471bf1952154768e8435a9300077b534fa'},
                'size': [1478.035400390625, 1042.3026123046875],
                'type': 'VHS_VideoCombine',
                'widgets_values': {'crf': 19,
                                   'filename_prefix': 'Wanimate',
                                   'format': 'video/h264-mp4',
                                   'frame_rate': 16,
                                   'loop_count': 0,
                                   'pingpong': False,
                                   'pix_fmt': 'yuv420p',
                                   'save_metadata': True,
                                   'save_output': True,
                                   'trim_to_audio': True,
                                   'videopreview': {'hidden': False,
                                                    'params': {'filename': 'Wanimate_00002-audio.mp4',
                                                               'format': 'video/h264-mp4',
                                                               'frame_rate': 16,
                                                               'fullpath': 'N:\\AI\\ComfyUI\\temp\\Wanimate_00002-audio.mp4',
                                                               'subfolder': '',
                                                               'type': 'temp',
                                                               'workflow': 'Wanimate_00002.png'},
                                                    'paused': False}}},
        'class_type': 'VHS_VideoCombine',
        'inputs': {'audio': ['149', 0],
                   'crf': 19,
                   'filename_prefix': 'Wanimate',
                   'format': 'video/h264-mp4',
                   'frame_rate': 16,
                   'images': ['66', 0],
                   'loop_count': 0,
                   'pingpong': False,
                   'pix_fmt': 'yuv420p',
                   'save_metadata': True,
                   'save_output': True,
                   'trim_to_audio': True,
                   'videopreview': {'hidden': False,
                                    'params': {'filename': 'Wanimate_00002-audio.mp4',
                                               'format': 'video/h264-mp4',
                                               'frame_rate': 16,
                                               'fullpath': 'N:\\AI\\ComfyUI\\temp\\Wanimate_00002-audio.mp4',
                                               'subfolder': '',
                                               'type': 'temp',
                                               'workflow': 'Wanimate_00002.png'},
                                    'paused': False}}},
 '35': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 35,
                'inputs': [],
                'mode': 0,
                'order': 15,
                'outputs': [{'links': [100], 'name': 'torch_compile_args', 'slot_index': 0, 'type': 'WANCOMPILEARGS'}],
                'pos': [-1146.0887451171875, -909.5626831054688],
                'properties': {'Node name for S&R': 'WanVideoTorchCompileSettings',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': 'e5ef9752a7e846b232fc05fd993327a2e870a788'},
                'size': [390.5999755859375, 202],
                'type': 'WanVideoTorchCompileSettings',
                'widgets_values': ['inductor', False, 'default', False, 64, True, 128]},
        'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '38': {'_ui': {'bgcolor': '#533',
                'color': '#322',
                'flags': {},
                'id': 38,
                'inputs': [{'link': None, 'name': 'compile_args', 'shape': 7, 'type': 'WANCOMPILEARGS'}],
                'mode': 0,
                'order': 16,
                'outputs': [{'links': [278], 'name': 'vae', 'slot_index': 0, 'type': 'WANVAE'}],
                'pos': [-569.7952880859375, -499.9053649902344],
                'properties': {'Node name for S&R': 'WanVideoVAELoader',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': 'e5ef9752a7e846b232fc05fd993327a2e870a788'},
                'size': [416.25482177734375, 82],
                'type': 'WanVideoVAELoader',
                'widgets_values': ['wanvideo\\Wan2_1_VAE_bf16.safetensors', 'bf16']},
        'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '42': {'_ui': {'flags': {},
                'id': 42,
                'inputs': [{'link': 48, 'name': 'image', 'type': 'IMAGE'}],
                'mode': 0,
                'order': 55,
                'outputs': [{'links': [87], 'name': 'image', 'slot_index': 0, 'type': 'IMAGE'},
                            {'label': '832 width', 'links': None, 'name': 'width', 'type': 'INT'},
                            {'label': '480 height', 'links': None, 'name': 'height', 'type': 'INT'},
                            {'label': '153 count', 'links': None, 'name': 'count', 'type': 'INT'}],
                'pos': [2555.719482421875, -692.73095703125],
                'properties': {'Node name for S&R': 'GetImageSizeAndCount',
                               'cnr_id': 'comfyui-kjnodes',
                               'ver': '36f6fdd7d4c393675ac622bd300ef667ee65d8b8'},
                'size': [277.20001220703125, 86],
                'type': 'GetImageSizeAndCount',
                'widgets_values': []},
        'class_type': 'GetImageSizeAndCount',
        'inputs': {'image': ['28', 0]}},
 '48': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 48,
                'inputs': [{'link': 59, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 289, 'name': 'lora', 'shape': 7, 'type': 'WANVIDLORA'}],
                'mode': 0,
                'order': 42,
                'outputs': [{'links': [62], 'name': 'model', 'type': 'WANVIDEOMODEL'}],
                'pos': [-5.091688632965088, -420.6256103515625],
                'properties': {'Node name for S&R': 'WanVideoSetLoRAs',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': 'e5ef9752a7e846b232fc05fd993327a2e870a788'},
                'size': [174.53378295898438, 46],
                'type': 'WanVideoSetLoRAs',
                'widgets_values': []},
        'class_type': 'WanVideoSetLoRAs',
        'inputs': {'lora': ['171', 0], 'model': ['22', 0]}},
 '50': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 50,
                'inputs': [{'link': 62, 'name': 'model', 'type': 'WANVIDEOMODEL'},
                           {'link': 64, 'name': 'block_swap_args', 'shape': 7, 'type': 'BLOCKSWAPARGS'}],
                'mode': 0,
                'order': 47,
                'outputs': [{'links': [63], 'name': 'model', 'type': 'WANVIDEOMODEL'}],
                'pos': [299.8666076660156, -422.0509338378906],
                'properties': {'Node name for S&R': 'WanVideoSetBlockSwap',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': 'e5ef9752a7e846b232fc05fd993327a2e870a788'},
                'size': [201.76815795898438, 46],
                'type': 'WanVideoSetBlockSwap',
                'widgets_values': []},
        'class_type': 'WanVideoSetBlockSwap',
        'inputs': {'block_swap_args': ['51', 0], 'model': ['48', 0]}},
 '51': {'_ui': {'bgcolor': '#335',
                'color': '#223',
                'flags': {},
                'id': 51,
                'inputs': [],
                'mode': 0,
                'order': 23,
                'outputs': [{'links': [64], 'name': 'block_swap_args', 'type': 'BLOCKSWAPARGS'}],
                'pos': [-20.855491638183594, -308.51751708984375],
                'properties': {'Node name for S&R': 'WanVideoBlockSwap',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': 'e5ef9752a7e846b232fc05fd993327a2e870a788'},
                'size': [281.404296875, 202],
                'type': 'WanVideoBlockSwap',
                'widgets_values': [25, False, False, True, 0, 1, False]},
        'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 25,
                   'widget_1': False,
                   'widget_2': False,
                   'widget_3': True,
                   'widget_4': 0,
                   'widget_5': 1,
                   'widget_6': False}},
 '57': {'_ui': {'flags': {},
                'id': 57,
                'inputs': [],
                'mode': 0,
                'order': 9,
                'outputs': [{'links': [82], 'name': 'IMAGE', 'type': 'IMAGE'},
                            {'links': None, 'name': 'MASK', 'type': 'MASK'}],
                'pos': [-1116.435791015625, -1679.51318359375],
                'properties': {'Node name for S&R': 'LoadImage', 'cnr_id': 'comfy-core', 'ver': '0.3.57'},
                'size': [274.080078125, 314],
                'type': 'LoadImage',
                'widgets_values': ['refer.jpeg', 'image']},
        'class_type': 'LoadImage',
        'inputs': {'widget_0': 'refer.jpeg', 'widget_1': 'image'}},
 '62': {'_ui': {'bgcolor': '#533',
                'color': '#322',
                'flags': {},
                'id': 62,
                'inputs': [{'link': 280, 'name': 'vae', 'type': 'WANVAE'},
                           {'link': 96, 'name': 'clip_embeds', 'shape': 7, 'type': 'WANVIDIMAGE_CLIPEMBEDS'},
                           {'link': 282, 'name': 'ref_images', 'shape': 7, 'type': 'IMAGE'},
                           {'link': 244, 'name': 'pose_images', 'shape': 7, 'type': 'IMAGE'},
                           {'link': 240, 'name': 'face_images', 'shape': 7, 'type': 'IMAGE'},
                           {'link': 234, 'name': 'bg_images', 'shape': 7, 'type': 'IMAGE'},
                           {'link': 247, 'name': 'mask', 'shape': 7, 'type': 'MASK'},
                           {'link': 265, 'name': 'width', 'type': 'INT', 'widget': {'name': 'width'}},
                           {'link': 266, 'name': 'height', 'type': 'INT', 'widget': {'name': 'height'}},
                           {'link': 268, 'name': 'num_frames', 'type': 'INT', 'widget': {'name': 'num_frames'}}],
                'mode': 0,
                'order': 41,
                'outputs': [{'links': [84], 'name': 'image_embeds', 'type': 'WANVIDIMAGE_EMBEDS'}],
                'pos': [1567.48046875, -396.0700988769531],
                'properties': {'Node name for S&R': 'WanVideoAnimateEmbeds',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '761b1d191e50d589465e31dc0d40ff7c59b1b7b0'},
                'size': [274.2164001464844, 370],
                'type': 'WanVideoAnimateEmbeds',
                'widgets_values': [832, 480, 501, False, 77, 'disabled', 1, 1, False]},
        'class_type': 'WanVideoAnimateEmbeds',
        'inputs': {'bg_images': ['131', 0],
                   'clip_embeds': ['70', 0],
                   'face_images': ['138', 0],
                   'height': ['156', 0],
                   'mask': ['143', 0],
                   'num_frames': ['158', 0],
                   'pose_images': ['141', 0],
                   'ref_images': ['133', 0],
                   'vae': ['163', 0],
                   'widget_0': 832,
                   'widget_1': 480,
                   'widget_2': 501,
                   'widget_3': False,
                   'widget_4': 77,
                   'widget_5': 'disabled',
                   'widget_6': 1,
                   'widget_7': 1,
                   'widget_8': False,
                   'width': ['155', 0]}},
 '63': {'_ui': {'flags': {},
                'id': 63,
                'inputs': [{'link': None, 'name': 'meta_batch', 'shape': 7, 'type': 'VHS_BatchManager'},
                           {'link': None, 'name': 'vae', 'shape': 7, 'type': 'VAE'},
                           {'link': 257, 'name': 'custom_width', 'type': 'INT', 'widget': {'name': 'custom_width'}},
                           {'link': 258, 'name': 'custom_height', 'type': 'INT', 'widget': {'name': 'custom_height'}}],
                'mode': 0,
                'order': 38,
                'outputs': [{'links': [248], 'name': 'IMAGE', 'type': 'IMAGE'},
                            {'links': [267], 'name': 'frame_count', 'type': 'INT'},
                            {'links': [255], 'name': 'audio', 'type': 'AUDIO'},
                            {'links': None, 'name': 'video_info', 'type': 'VHS_VIDEOINFO'}],
                'pos': [-876.9246826171875, -3084.905517578125],
                'properties': {'Node name for S&R': 'VHS_LoadVideo',
                               'cnr_id': 'comfyui-videohelpersuite',
                               'ver': '8e4d79471bf1952154768e8435a9300077b534fa'},
                'size': [315.8014221191406, 491.6708679199219],
                'type': 'VHS_LoadVideo',
                'widgets_values': {'choose video to upload': 'image',
                                   'custom_height': 544,
                                   'custom_width': 960,
                                   'force_rate': 16,
                                   'format': 'AnimateDiff',
                                   'frame_load_cap': 0,
                                   'select_every_nth': 1,
                                   'skip_first_frames': 0,
                                   'video': 'raw.mp4',
                                   'videopreview': {'hidden': False,
                                                    'params': {'custom_height': 544,
                                                               'custom_width': 960,
                                                               'filename': 'raw.mp4',
                                                               'force_rate': 16,
                                                               'format': 'video/mp4',
                                                               'frame_load_cap': 0,
                                                               'select_every_nth': 1,
                                                               'skip_first_frames': 0,
                                                               'type': 'input'},
                                                    'paused': False}}},
        'class_type': 'VHS_LoadVideo',
        'inputs': {'choose video to upload': 'image',
                   'custom_height': ['151', 0],
                   'custom_width': ['150', 0],
                   'force_rate': 16,
                   'format': 'AnimateDiff',
                   'frame_load_cap': 0,
                   'select_every_nth': 1,
                   'skip_first_frames': 0,
                   'video': 'raw.mp4',
                   'videopreview': {'hidden': False,
                                    'params': {'custom_height': 544,
                                               'custom_width': 960,
                                               'filename': 'raw.mp4',
                                               'force_rate': 16,
                                               'format': 'video/mp4',
                                               'frame_load_cap': 0,
                                               'select_every_nth': 1,
                                               'skip_first_frames': 0,
                                               'type': 'input'},
                                    'paused': False}}},
 '64': {'_ui': {'flags': {},
                'id': 64,
                'inputs': [{'link': 82, 'name': 'image', 'type': 'IMAGE'},
                           {'link': None, 'name': 'mask', 'shape': 7, 'type': 'MASK'},
                           {'link': 286, 'name': 'width', 'type': 'INT', 'widget': {'name': 'width'}},
                           {'link': 287, 'name': 'height', 'type': 'INT', 'widget': {'name': 'height'}}],
                'mode': 0,
                'order': 40,
                'outputs': [{'links': [231], 'name': 'IMAGE', 'type': 'IMAGE'},
                            {'links': [], 'name': 'width', 'type': 'INT'},
                            {'links': [], 'name': 'height', 'type': 'INT'},
                            {'links': None, 'name': 'mask', 'type': 'MASK'}],
                'pos': [-772.3116455078125, -1675.555419921875],
                'properties': {'Node name for S&R': 'ImageResizeKJv2',
                               'cnr_id': 'comfyui-kjnodes',
                               'ver': '468fcc86f0b29e79a8510e8239eb15714d6747a6'},
                'size': [270, 336],
                'type': 'ImageResizeKJv2',
                'widgets_values': [832,
                                   480,
                                   'lanczos',
                                   'pad_edge_pixel',
                                   '0, 0, 0',
                                   'top',
                                   16,
                                   'cpu',
                                   '<tr><td>Output: </td><td><b>1</b> x <b>832</b> x <b>480 | 4.57MB</b></td></tr>']},
        'class_type': 'ImageResizeKJv2',
        'inputs': {'height': ['151', 0],
                   'image': ['57', 0],
                   'widget_0': 832,
                   'widget_1': 480,
                   'widget_2': 'lanczos',
                   'widget_3': 'pad_edge_pixel',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'top',
                   'widget_6': 16,
                   'widget_7': 'cpu',
                   'widget_8': '<tr><td>Output: </td><td><b>1</b> x <b>832</b> x <b>480 | 4.57MB</b></td></tr>',
                   'width': ['150', 0]}},
 '65': {'_ui': {'bgcolor': '#653',
                'color': '#432',
                'flags': {},
                'id': 65,
                'inputs': [{'link': None, 'name': 'extender_args', 'shape': 7, 'type': 'WANVIDEOPROMPTEXTENDER_ARGS'}],
                'mode': 0,
                'order': 20,
                'outputs': [{'links': [281], 'name': 'text_embeds', 'type': 'WANVIDEOTEXTEMBEDS'},
                            {'links': None, 'name': 'negative_text_embeds', 'type': 'WANVIDEOTEXTEMBEDS'},
                            {'links': None, 'name': 'positive_prompt', 'type': 'STRING'}],
                'pos': [1329.64208984375, 68.953125],
                'properties': {'Node name for S&R': 'WanVideoTextEncodeCached',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '761b1d191e50d589465e31dc0d40ff7c59b1b7b0'},
                'size': [488.4488220214844, 362.56817626953125],
                'type': 'WanVideoTextEncodeCached',
                'widgets_values': ['umt5-xxl-enc-bf16.safetensors',
                                   'bf16',
                                   'man is walking, style is soft 3D render style, night time, moonlight',
                                   '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                                   'disabled',
                                   False,
                                   'gpu']},
        'class_type': 'WanVideoTextEncodeCached',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'man is walking, style is soft 3D render style, night time, moonlight',
                   'widget_3': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_4': 'disabled',
                   'widget_5': False,
                   'widget_6': 'gpu'}},
 '66': {'_ui': {'flags': {},
                'id': 66,
                'inputs': [{'link': 87, 'name': 'image_1', 'type': 'IMAGE'},
                           {'link': 107, 'name': 'image_2', 'shape': 7, 'type': 'IMAGE'}],
                'mode': 0,
                'order': 59,
                'outputs': [{'links': [89], 'name': 'images', 'type': 'IMAGE'}],
                'pos': [2660.1005859375, -950.2750244140625],
                'properties': {'cnr_id': 'comfyui-kjnodes', 'ver': '468fcc86f0b29e79a8510e8239eb15714d6747a6'},
                'size': [270, 150],
                'type': 'ImageConcatMulti',
                'widgets_values': [2, 'left', True, None]},
        'class_type': 'ImageConcatMulti',
        'inputs': {'image_1': ['42', 0],
                   'image_2': ['77', 0],
                   'widget_0': 2,
                   'widget_1': 'left',
                   'widget_2': True,
                   'widget_3': None}},
 '70': {'_ui': {'bgcolor': '#355',
                'color': '#233',
                'flags': {},
                'id': 70,
                'inputs': [{'link': 97, 'name': 'clip_vision', 'type': 'CLIP_VISION'},
                           {'link': 235, 'name': 'image_1', 'type': 'IMAGE'},
                           {'link': None, 'name': 'image_2', 'shape': 7, 'type': 'IMAGE'},
                           {'link': None, 'name': 'negative_image', 'shape': 7, 'type': 'IMAGE'}],
                'mode': 0,
                'order': 33,
                'outputs': [{'links': [96], 'name': 'image_embeds', 'type': 'WANVIDIMAGE_CLIPEMBEDS'}],
                'pos': [989.1386108398438, -306.2594299316406],
                'properties': {'Node name for S&R': 'WanVideoClipVisionEncode',
                               'cnr_id': 'ComfyUI-WanVideoWrapper',
                               'ver': '2bdd81a10b03c14443c79bdf3b783b1feb3d1fa3'},
                'size': [280.9771423339844, 262],
                'type': 'WanVideoClipVisionEncode',
                'widgets_values': [1, 1, 'center', 'average', True, 0, 0.5]},
        'class_type': 'WanVideoClipVisionEncode',
        'inputs': {'clip_vision': ['71', 0],
                   'image_1': ['133', 0],
                   'widget_0': 1,
                   'widget_1': 1,
                   'widget_2': 'center',
                   'widget_3': 'average',
                   'widget_4': True,
                   'widget_5': 0,
                   'widget_6': 0.5}},
 '71': {'_ui': {'bgcolor': '#3f5159',
                'color': '#2a363b',
                'flags': {},
                'id': 71,
                'inputs': [],
                'mode': 0,
                'order': 12,
                'outputs': [{'links': [97], 'name': 'CLIP_VISION', 'type': 'CLIP_VISION'}],
                'pos': [-512.5712890625, -245.34796142578125],
                'properties': {'Node name for S&R': 'CLIPVisionLoader', 'cnr_id': 'comfy-core', 'ver': '0.3.59'},
                'size': [270, 58],
                'type': 'CLIPVisionLoader',
                'widgets_values': ['clip_vision_h.safetensors']},
        'class_type': 'CLIPVisionLoader',
        'inputs': {'widget_0': 'clip_vision_h.safetensors'}},
 '75': {'_ui': {'flags': {},
                'id': 75,
                'inputs': [{'link': 251, 'name': 'images', 'type': 'IMAGE'},
                           {'link': None, 'name': 'audio', 'shape': 7, 'type': 'AUDIO'},
                           {'link': None, 'name': 'meta_batch', 'shape': 7, 'type': 'VHS_BatchManager'},
                           {'link': None, 'name': 'vae', 'shape': 7, 'type': 'VAE'}],
                'mode': 0,
                'order': 66,
                'outputs': [{'links': None, 'name': 'Filenames', 'type': 'VHS_FILENAMES'}],
                'pos': [2010.67431640625, -3041.57568359375],
                'properties': {'Node name for S&R': 'VHS_VideoCombine',
                               'cnr_id': 'comfyui-videohelpersuite',
                               'ver': '8e4d79471bf1952154768e8435a9300077b534fa'},
                'size': [743.6680297851562, 765.5007934570312],
                'type': 'VHS_VideoCombine',
                'widgets_values': {'crf': 19,
                                   'filename_prefix': 'WanVideo2_1_T2V',
                                   'format': 'video/h264-mp4',
                                   'frame_rate': 16,
                                   'loop_count': 0,
                                   'pingpong': False,
                                   'pix_fmt': 'yuv420p',
                                   'save_metadata': True,
                                   'save_output': False,
                                   'trim_to_audio': False,
                                   'videopreview': {'hidden': False,
                                                    'params': {'filename': 'WanVideo2_1_T2V_00004.mp4',
                                                               'format': 'video/h264-mp4',
                                                               'frame_rate': 16,
                                                               'fullpath': 'N:\\AI\\ComfyUI\\temp\\WanVideo2_1_T2V_00004.mp4',
                                                               'subfolder': '',
                                                               'type': 'temp',
                                                               'workflow': 'WanVideo2_1_T2V_00004.png'},
                                                    'paused': False}}},
        'class_type': 'VHS_VideoCombine',
        'inputs': {'crf': 19,
                   'filename_prefix': 'WanVideo2_1_T2V',
                   'format': 'video/h264-mp4',
                   'frame_rate': 16,
                   'images': ['130', 0],
                   'loop_count': 0,
                   'pingpong': False,
                   'pix_fmt': 'yuv420p',
                   'save_metadata': True,
                   'save_output': False,
                   'trim_to_audio': False,
                   'videopreview': {'hidden': False,
                                    'params': {'filename': 'WanVideo2_1_T2V_00004.mp4',
                                               'format': 'video/h264-mp4',
                                               'frame_rate': 16,
                                               'fullpath': 'N:\\AI\\ComfyUI\\temp\\WanVideo2_1_T2V_00004.mp4',
                                               'subfolder': '',
                                               'type': 'temp',
                                               'workflow': 'WanVideo2_1_T2V_00004.png'},
                                    'paused': False}}},
 '77': {'_ui': {'flags': {},
                'id': 77,
                'inputs': [{'link': 236, 'name': 'image_1', 'type': 'IMAGE'},
                           {'link': 239, 'name': 'image_2', 'shape': 7, 'type': 'IMAGE'},
                           {'link': 243, 'name': 'image_3', 'shape': 7, 'type': 'IMAGE'},
                           {'link': 249, 'name': 'image_4', 'shape': 7, 'type': 'IMAGE'}],
                'mode': 0,
                'order': 36,
                'outputs': [{'links': [107], 'name': 'images', 'type': 'IMAGE'}],
                'pos': [2653.37939453125, -1220.90087890625],
                'properties': {'cnr_id': 'comfyui-kjnodes', 'ver': '468fcc86f0b29e79a8510e8239eb15714d6747a6'},
                'size': [270, 190],
                'type': 'ImageConcatMulti',
                'widgets_values': [4, 'down', True, None]},
        'class_type': 'ImageConcatMulti',
        'inputs': {'image_1': ['134', 0],
                   'image_2': ['137', 0],
                   'image_3': ['140', 0],
                   'image_4': ['145', 0],
                   'widget_0': 4,
                   'widget_1': 'down',
                   'widget_2': True,
                   'widget_3': None}},
 '99': {'_ui': {'flags': {},
                'id': 99,
                'inputs': [{'link': 250, 'name': 'image', 'type': 'IMAGE'},
                           {'link': 246, 'name': 'mask', 'type': 'MASK'}],
                'mode': 0,
                'order': 64,
                'outputs': [{'links': [233], 'name': 'images', 'type': 'IMAGE'}],
                'pos': [1222.5340576171875, -2132.91455078125],
                'properties': {'Node name for S&R': 'DrawMaskOnImage',
                               'cnr_id': 'comfyui-kjnodes',
                               'ver': '623b5913dc7f240fd8b26422e99f8849a21c5473'},
                'size': [270, 78],
                'type': 'DrawMaskOnImage',
                'widgets_values': ['0, 0, 0']},
        'class_type': 'DrawMaskOnImage',
        'inputs': {'image': ['146', 0], 'mask': ['142', 0], 'widget_0': '0, 0, 0'}}}

READY_METADATA = {'approach': 'Kijai WanAnimate preprocessing workflow using reference image, pose video, SAM2/DWPose masking, relight '
             'LoRA, and Lightx2v LoRA',
 'capability': 'animate_character',
 'coverage_tier': 'production_parity_candidate',
 'model_assets': [{'directory': 'diffusion_models/WanVideo/2_2',
                   'name': 'Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/Wan22Animate/Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors'},
                  {'directory': 'loras/WanVideo',
                   'name': 'WanAnimate_relight_lora_fp16.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/LoRAs/Wan22_relight/WanAnimate_relight_lora_fp16.safetensors'},
                  {'directory': 'clip_vision',
                   'name': 'clip_vision_h.safetensors',
                   'url': 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors'},
                  {'directory': 'sams',
                   'name': 'sam2_hiera_base_plus.safetensors',
                   'url': 'https://huggingface.co/Kijai/sam2-safetensors/resolve/main/sam2_hiera_base_plus.safetensors'},
                  {'directory': 'onnx/yolo',
                   'name': 'yolox_l.torchscript.pt',
                   'url': 'https://huggingface.co/hr16/yolox-onnx/resolve/main/yolox_l.torchscript.pt'},
                  {'directory': 'onnx/dwpose',
                   'name': 'dw-ll_ucoco_384_bs5.torchscript.pt',
                   'url': 'https://huggingface.co/hr16/DWPose-TorchScript-BatchSize5/resolve/main/dw-ll_ucoco_384_bs5.torchscript.pt'},
                  {'directory': 'vae/wanvideo',
                   'name': 'Wan2_1_VAE_bf16.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan2_1_VAE_bf16.safetensors'},
                  {'directory': 'text_encoders',
                   'name': 'umt5-xxl-enc-bf16.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/umt5-xxl-enc-bf16.safetensors'},
                  {'directory': 'loras/WanVideo/Lightx2v',
                   'name': 'lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                   'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors'}],
 'ready_template': 'video/wanvideo_wrapper_22_wan_animate_preprocess_kijai',
 'runtime_note': 'Worker scratchpads patch reference image, motion video, prompt, seed, and output options.',
 'smoke_resolution': '832x480_motion_source',
 'source_role': 'materialized_kijai_reference_workflow',
 'source_url': 'https://raw.githubusercontent.com/kijai/ComfyUI-WanVideoWrapper/main/example_workflows/wanvideo_WanAnimate_preprocess_example_02.json',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wanvideo_WanAnimate_preprocess_example_02.json',
 'unbound_inputs': {'height': '151.widget_0',
                    'motion_video': '63.video',
                    'negative_prompt': '65.widget_3',
                    'prompt': '65.widget_2',
                    'reference_image': '57.widget_0',
                    'seed': '27.widget_3',
                    'steps': '27.widget_0',
                    'width': '150.widget_0'},
 'workflow_template': 'wanvideo_wrapper_22_wan_animate_preprocess_kijai'}

READY_REQUIREMENTS = {'custom_nodes': ['ComfyUI-KJNodes',
                  'ComfyUI-VideoHelperSuite',
                  'ComfyUI-WanVideoWrapper',
                  'ComfyUI-segment-anything-2',
                  'comfyui_controlnet_aux'],
 'models': [{'directory': 'diffusion_models/WanVideo/2_2',
             'name': 'Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy_fp8_scaled/resolve/main/Wan22Animate/Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors'},
            {'directory': 'loras/WanVideo',
             'name': 'WanAnimate_relight_lora_fp16.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/LoRAs/Wan22_relight/WanAnimate_relight_lora_fp16.safetensors'},
            {'directory': 'clip_vision',
             'name': 'clip_vision_h.safetensors',
             'url': 'https://huggingface.co/Comfy-Org/Wan_2.1_ComfyUI_repackaged/resolve/main/split_files/clip_vision/clip_vision_h.safetensors'},
            {'directory': 'sams',
             'name': 'sam2_hiera_base_plus.safetensors',
             'url': 'https://huggingface.co/Kijai/sam2-safetensors/resolve/main/sam2_hiera_base_plus.safetensors'},
            {'directory': 'onnx/yolo',
             'name': 'yolox_l.torchscript.pt',
             'url': 'https://huggingface.co/hr16/yolox-onnx/resolve/main/yolox_l.torchscript.pt'},
            {'directory': 'onnx/dwpose',
             'name': 'dw-ll_ucoco_384_bs5.torchscript.pt',
             'url': 'https://huggingface.co/hr16/DWPose-TorchScript-BatchSize5/resolve/main/dw-ll_ucoco_384_bs5.torchscript.pt'},
            {'directory': 'vae/wanvideo',
             'name': 'Wan2_1_VAE_bf16.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Wan2_1_VAE_bf16.safetensors'},
            {'directory': 'text_encoders',
             'name': 'umt5-xxl-enc-bf16.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/umt5-xxl-enc-bf16.safetensors'},
            {'directory': 'loras/WanVideo/Lightx2v',
             'name': 'lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
             'url': 'https://huggingface.co/Kijai/WanVideo_comfy/resolve/main/Lightx2v/lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors'}]}

def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        READY_METADATA,
        source_path=__file__,
        workflow_id='video/wanvideo_wrapper_22_wan_animate_preprocess_kijai',
        requirements=READY_REQUIREMENTS,
    )
