from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'66': {'class_type': 'ImageConcatMulti',
        'inputs': {'widget_0': 2,
                   'widget_1': 'left',
                   'widget_2': True,
                   'widget_3': None,
                   'image_1': ['42', 0],
                   'image_2': ['77', 0]}},
 '137': {'class_type': 'GetNode', 'inputs': {'widget_0': 'face_images'}},
 '73': {'class_type': 'DWPreprocessor',
        'inputs': {'widget_0': 'disable',
                   'widget_1': 'enable',
                   'widget_2': 'disable',
                   'widget_3': 960,
                   'widget_4': 'yolox_l.torchscript.pt',
                   'widget_5': 'dw-ll_ucoco_384_bs5.torchscript.pt',
                   'widget_6': 'disable',
                   'image': ['147', 0],
                   'resolution': ['152', 0]}},
 '140': {'class_type': 'GetNode', 'inputs': {'widget_0': 'pose_images'}},
 '134': {'class_type': 'GetNode', 'inputs': {'widget_0': 'reference_image'}},
 '148': {'class_type': 'SetNode', 'inputs': {'widget_0': 'input_audio', 'AUDIO': ['63', 2]}},
 '149': {'class_type': 'GetNode', 'inputs': {'widget_0': 'input_audio'}},
 '153': {'class_type': 'SetNode', 'inputs': {'widget_0': 'width', 'INT': ['150', 0]}},
 '155': {'class_type': 'GetNode', 'inputs': {'widget_0': 'width'}},
 '156': {'class_type': 'GetNode', 'inputs': {'widget_0': 'height'}},
 '154': {'class_type': 'SetNode', 'inputs': {'widget_0': 'height', 'INT': ['151', 0]}},
 '63': {'class_type': 'VHS_LoadVideo',
        'inputs': {'video': 'wolf_interpolated.mp4', 'custom_width': ['150', 0], 'custom_height': ['151', 0]}},
 '158': {'class_type': 'GetNode', 'inputs': {'widget_0': 'frame_count'}},
 '138': {'class_type': 'GetNode', 'inputs': {'widget_0': 'face_images'}},
 '131': {'class_type': 'GetNode', 'inputs': {'widget_0': 'background_image'}},
 '143': {'class_type': 'GetNode', 'inputs': {'widget_0': 'mask'}},
 '104': {'class_type': 'Sam2Segmentation',
         'inputs': {'widget_0': False,
                    'widget_1': False,
                    'sam2_model': ['102', 0],
                    'image': ['144', 0],
                    'coordinates_positive': ['107', 0]}},
 '102': {'class_type': 'DownloadAndLoadSAM2Model',
         'inputs': {'widget_0': 'sam2_hiera_base_plus.safetensors',
                    'widget_1': 'video',
                    'widget_2': 'cuda',
                    'widget_3': 'fp16'}},
 '157': {'class_type': 'SetNode', 'inputs': {'widget_0': 'frame_count', 'INT': ['63', 1]}},
 '144': {'class_type': 'SetNode', 'inputs': {'widget_0': 'input_video', 'IMAGE': ['63', 0]}},
 '152': {'class_type': 'PixelPerfectResolution',
         'inputs': {'widget_0': 512,
                    'widget_1': 512,
                    'widget_2': 'Just Resize',
                    'original_image': ['147', 0],
                    'image_gen_width': ['150', 0],
                    'image_gen_height': ['151', 0]}},
 '128': {'class_type': 'SetNode', 'inputs': {'widget_0': 'reference_image', 'IMAGE': ['64', 0]}},
 '64': {'class_type': 'ImageResizeKJv2',
        'inputs': {'width': ['150', 0],
                   'height': ['151', 0],
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 'lanczos',
                   'widget_3': 'pad_edge_pixel',
                   'widget_4': '0, 0, 0',
                   'widget_5': 'top',
                   'widget_6': 16,
                   'widget_7': 'cpu',
                   'widget_8': '<tr><td>Output: </td><td><b>1</b> x <b>832</b> x <b>480 | 4.57MB</b></td></tr>',
                   'image': ['57', 0]}},
 '57': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'refer.jpeg', 'widget_1': 'image'}},
 '147': {'class_type': 'Reroute', 'inputs': {}},
 '120': {'class_type': 'FaceMaskFromPoseKeypoints', 'inputs': {'widget_0': 0, 'pose_kps': ['73', 1]}},
 '139': {'class_type': 'SetNode', 'inputs': {'widget_0': 'pose_images', 'IMAGE': ['73', 0]}},
 '96': {'class_type': 'ImageCropByMaskAndResize',
        'inputs': {'widget_0': 512,
                   'widget_1': 0,
                   'widget_2': 128,
                   'widget_3': 512,
                   'image': ['147', 0],
                   'mask': ['120', 0]}},
 '135': {'class_type': 'SetNode', 'inputs': {'widget_0': 'face_images', 'IMAGE': ['96', 0]}},
 '100': {'class_type': 'GrowMask', 'inputs': {'widget_0': 10, 'widget_1': True, 'mask': ['104', 0]}},
 '108': {'class_type': 'BlockifyMask', 'inputs': {'widget_0': 32, 'masks': ['100', 0]}},
 '142': {'class_type': 'SetNode', 'inputs': {'widget_0': 'mask', 'MASK': ['108', 0]}},
 '99': {'class_type': 'DrawMaskOnImage', 'inputs': {'widget_0': '0, 0, 0', 'image': ['146', 0], 'mask': ['142', 0]}},
 '146': {'class_type': 'GetNode', 'inputs': {'widget_0': 'input_video'}},
 '130': {'class_type': 'SetNode', 'inputs': {'widget_0': 'background_image', 'IMAGE': ['99', 0]}},
 '112': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['135', 0]}},
 '163': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '71': {'class_type': 'CLIPVisionLoader', 'inputs': {'widget_0': 'clip_vision_h.safetensors'}},
 '70': {'class_type': 'WanVideoClipVisionEncode',
        'inputs': {'widget_0': 1,
                   'widget_1': 1,
                   'widget_2': 'center',
                   'widget_3': 'average',
                   'widget_4': True,
                   'widget_5': 0,
                   'widget_6': 0.5,
                   'clip_vision': ['71', 0],
                   'image_1': ['133', 0]}},
 '133': {'class_type': 'GetNode', 'inputs': {'widget_0': 'reference_image'}},
 '141': {'class_type': 'GetNode', 'inputs': {'widget_0': 'pose_images'}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '161': {'class_type': 'SetNode', 'inputs': {'widget_0': 'VAE', 'WANVAE': ['38', 0]}},
 '77': {'class_type': 'ImageConcatMulti',
        'inputs': {'widget_0': 4,
                   'widget_1': 'down',
                   'widget_2': True,
                   'widget_3': None,
                   'image_1': ['134', 0],
                   'image_2': ['137', 0],
                   'image_3': ['140', 0],
                   'image_4': ['145', 0]}},
 '145': {'class_type': 'GetNode', 'inputs': {'widget_0': 'input_video'}},
 '28': {'class_type': 'WanVideoDecode',
        'inputs': {'widget_0': False,
                   'widget_1': 272,
                   'widget_2': 272,
                   'widget_3': 144,
                   'widget_4': 128,
                   'widget_5': 'default',
                   'vae': ['162', 0],
                   'samples': ['27', 0]}},
 '162': {'class_type': 'GetNode', 'inputs': {'widget_0': 'VAE'}},
 '42': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['28', 0]}},
 '107': {'class_type': 'PointsEditor',
         'inputs': {'widget_0': '{"positive":[{"x":483.34844284815,"y":333.283583335728},{"x":479.85856239437277,"y":158.78956064686517}],"negative":[{"x":0,"y":0}]}',
                    'widget_1': '[{"x":483.34844284815,"y":333.283583335728},{"x":479.85856239437277,"y":158.78956064686517}]',
                    'widget_2': '[{"x":0,"y":0}]',
                    'widget_3': '[{}]',
                    'widget_4': '[{}]',
                    'widget_5': 'xyxy',
                    'widget_6': 832,
                    'widget_7': 480,
                    'widget_8': False,
                    'widget_9': '',
                    'widget_10': None,
                    'bg_image': ['144', 0]}},
 '110': {'class_type': 'WanVideoContextOptions',
         'inputs': {'widget_0': 'static_standard',
                    'widget_1': 81,
                    'widget_2': 4,
                    'widget_3': 32,
                    'widget_4': True,
                    'widget_5': False,
                    'widget_6': 'linear'}},
 '30': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['66', 0], 'audio': ['149', 0]}},
 '65': {'class_type': 'WanVideoTextEncodeCached',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'man is walking, style is soft 3D render style, night time, moonlight',
                   'widget_3': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_4': 'disabled',
                   'widget_5': False,
                   'widget_6': 'gpu'}},
 '75': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['130', 0]}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 1,
                   'widget_2': 5,
                   'widget_3': 42,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'dpm++_sde',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': '',
                   'widget_10': 'comfy',
                   'widget_11': 0,
                   'widget_12': -1,
                   'widget_13': False,
                   'model': ['50', 0],
                   'image_embeds': ['62', 0],
                   'text_embeds': ['65', 0]}},
 '62': {'class_type': 'WanVideoAnimateEmbeds',
        'inputs': {'widget_0': 832,
                   'widget_1': 480,
                   'widget_2': 501,
                   'widget_3': False,
                   'widget_4': 77,
                   'widget_5': 'disabled',
                   'widget_6': 1,
                   'widget_7': 1,
                   'widget_8': False,
                   'vae': ['163', 0],
                   'clip_embeds': ['70', 0],
                   'ref_images': ['133', 0],
                   'pose_images': ['141', 0],
                   'face_images': ['138', 0],
                   'bg_images': ['131', 0],
                   'mask': ['143', 0],
                   'width': ['155', 0],
                   'height': ['156', 0],
                   'num_frames': ['158', 0]}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\2_2\\Wan2_2-Animate-14B_fp8_e4m3fn_scaled_KJ.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'disabled',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'compile_args': ['35', 0]}},
 '150': {'class_type': 'INTConstant', 'inputs': {'widget_0': 832}},
 '151': {'class_type': 'INTConstant', 'inputs': {'widget_0': 480}},
 '51': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 25,
                   'widget_1': False,
                   'widget_2': False,
                   'widget_3': True,
                   'widget_4': 0,
                   'widget_5': 1,
                   'widget_6': False}},
 '50': {'class_type': 'WanVideoSetBlockSwap', 'inputs': {'model': ['48', 0], 'block_swap_args': ['51', 0]}},
 '48': {'class_type': 'WanVideoSetLoRAs', 'inputs': {'model': ['22', 0], 'lora': ['171', 0]}},
 '171': {'class_type': 'WanVideoLoraSelectMulti',
         'inputs': {'widget_0': 'WanVideo\\WanAnimate_relight_lora_fp16.safetensors',
                    'widget_1': 1,
                    'widget_2': 'WanVideo\\Lightx2v\\lightx2v_I2V_14B_480p_cfg_step_distill_rank64_bf16.safetensors',
                    'widget_3': 1.2,
                    'widget_4': 'none',
                    'widget_5': 1,
                    'widget_6': 'none',
                    'widget_7': 1,
                    'widget_8': 'none',
                    'widget_9': 1,
                    'widget_10': False,
                    'widget_11': False}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 3976},
 'ready_template': 'video/wanvideo_wrapper_wan_animate',
 'workflow_template': 'wanvideo_wrapper_wan_animate',
 'capability': 'animate_reference_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan_animate.json',
 'coverage_tier': 'supplemental',
 'approach': 'WanAnimate reference animation',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [],
 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper', 'comfyui_controlnet_aux']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_wan_animate"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
