from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'46': {'class_type': 'WanVideoTextEmbedBridge', 'inputs': {'positive': ['49', 0], 'negative': ['50', 0]}},
 '50': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'clip': ['48', 0]}},
 '48': {'class_type': 'CLIPLoader',
        'inputs': {'widget_0': 'umt5_xxl_fp16.safetensors', 'widget_1': 'wan', 'widget_2': 'default'}},
 '11': {'class_type': 'LoadWanVideoT5TextEncoder',
        'inputs': {'widget_0': 'umt5-xxl-enc-bf16.safetensors',
                   'widget_1': 'bf16',
                   'widget_2': 'offload_device',
                   'widget_3': 'disabled'}},
 '91': {'class_type': 'SetNode', 'inputs': {'widget_0': 'start_image', 'IMAGE': ['107', 0]}},
 '92': {'class_type': 'SetNode', 'inputs': {'widget_0': 'end_image', 'IMAGE': ['108', 0]}},
 '93': {'class_type': 'GetNode', 'inputs': {'widget_0': 'start_image'}},
 '94': {'class_type': 'GetNode', 'inputs': {'widget_0': 'end_image'}},
 '97': {'class_type': 'EmptyImage',
        'inputs': {'widget_0': 8, 'widget_1': 512, 'widget_2': 1, 'widget_3': 0, 'height': ['68', 2]}},
 '95': {'class_type': 'AddLabel',
        'inputs': {'widget_0': 10,
                   'widget_1': 2,
                   'widget_2': 48,
                   'widget_3': 32,
                   'widget_4': 'white',
                   'widget_5': 'black',
                   'widget_6': 'FreeMono.ttf',
                   'widget_7': 'start_frame',
                   'widget_8': 'up',
                   'image': ['93', 0]}},
 '96': {'class_type': 'AddLabel',
        'inputs': {'widget_0': 10,
                   'widget_1': 2,
                   'widget_2': 48,
                   'widget_3': 32,
                   'widget_4': 'white',
                   'widget_5': 'black',
                   'widget_6': 'FreeMono.ttf',
                   'widget_7': 'end_frame',
                   'widget_8': 'up',
                   'image': ['94', 0]}},
 '71': {'class_type': 'ImageConcatMulti',
        'inputs': {'widget_0': 3,
                   'widget_1': 'left',
                   'widget_2': True,
                   'widget_3': None,
                   'image_1': ['68', 0],
                   'image_2': ['97', 0],
                   'image_3': ['70', 0]}},
 '70': {'class_type': 'ImageConcatMulti',
        'inputs': {'widget_0': 2,
                   'widget_1': 'down',
                   'widget_2': True,
                   'widget_3': None,
                   'image_1': ['95', 0],
                   'image_2': ['96', 0]}},
 '68': {'class_type': 'GetImageSizeAndCount', 'inputs': {'image': ['101', 0]}},
 '101': {'class_type': 'WanVideoDecode',
         'inputs': {'widget_0': False,
                    'widget_1': 272,
                    'widget_2': 272,
                    'widget_3': 144,
                    'widget_4': 128,
                    'widget_5': 'default',
                    'vae': ['38', 0],
                    'samples': ['27', 0]}},
 '38': {'class_type': 'WanVideoVAELoader',
        'inputs': {'widget_0': 'wanvideo\\Wan2_1_VAE_bf16.safetensors', 'widget_1': 'bf16'}},
 '88': {'class_type': 'WanVideoClipVisionEncode',
        'inputs': {'widget_0': 1,
                   'widget_1': 1,
                   'widget_2': 'center',
                   'widget_3': 'concat',
                   'widget_4': True,
                   'widget_5': 0,
                   'widget_6': 0.5,
                   'clip_vision': ['59', 0],
                   'image_1': ['91', 0],
                   'image_2': ['92', 0]}},
 '30': {'class_type': 'VHS_VideoCombine', 'inputs': {'save_output': True, 'images': ['71', 0]}},
 '89': {'class_type': 'WanVideoImageToVideoEncode',
        'inputs': {'width': ['108', 1],
                   'height': ['108', 2],
                   'num_frames': 5,
                   'widget_0': 256,
                   'widget_1': 256,
                   'widget_2': 5,
                   'widget_3': 0,
                   'widget_4': 1,
                   'widget_5': True,
                   'widget_6': True,
                   'widget_7': True,
                   'widget_8': False,
                   'vae': ['38', 0],
                   'clip_embeds': ['88', 0],
                   'start_image': ['91', 0],
                   'end_image': ['92', 0]}},
 '16': {'class_type': 'WanVideoTextEncode',
        'inputs': {'widget_0': 'CG动画风格，一只蓝色的小鸟从地面起飞，煽动翅膀。小鸟羽毛细腻，胸前有独特的花纹，背景是蓝天白云，阳光明媚。镜跟随小鸟向上移动，展现出小鸟飞翔的姿态和天空的广阔。近景，仰视视角',
                   'widget_1': '色调艳丽，过曝，静态，细节模糊不清，字幕，风格，作品，画作，画面，静止，整体发灰，最差质量，低质量，JPEG压缩残留，丑陋的，残缺的，多余的手指，画得不好的手部，画得不好的脸部，畸形的，毁容的，形态畸形的肢体，手指融合，静止不动的画面，杂乱的背景，三条腿，背景人很多，倒着走',
                   'widget_2': True,
                   'widget_3': False,
                   'widget_4': 'gpu',
                   't5': ['11', 0],
                   'model_to_offload': ['22', 0]}},
 '49': {'class_type': 'CLIPTextEncode',
        'inputs': {'widget_0': 'CG动画风格，一只蓝色的小鸟从地面起飞，煽动翅膀。小鸟羽毛细腻，胸前有独特的花纹，背景是蓝天白云，阳光明媚。镜跟随小鸟向上移动，展现出小鸟飞翔的姿态和天空的广阔。近景，仰视视角',
                   'clip': ['48', 0]}},
 '63': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'pasted/image (852).png', 'widget_1': 'image'}},
 '39': {'class_type': 'WanVideoBlockSwap',
        'inputs': {'widget_0': 20,
                   'widget_1': False,
                   'widget_2': False,
                   'widget_3': True,
                   'widget_4': 0,
                   'widget_5': 0,
                   'widget_6': False}},
 '56': {'class_type': 'LoadWanVideoClipTextEncoder',
        'inputs': {'widget_0': 'open-clip-xlm-roberta-large-vit-huge-14_visual_fp16.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'offload_device'}},
 '59': {'class_type': 'CLIPVisionLoader', 'inputs': {'widget_0': 'clip_vision_h.safetensors'}},
 '58': {'class_type': 'LoadImage', 'inputs': {'widget_0': 'pasted/image (853).png', 'widget_1': 'image'}},
 '107': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': 256,
                    'height': 256,
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'widget_7': 'cpu',
                    'widget_8': '<tr><td>Output: </td><td><b>1</b> x <b>640</b> x <b>640 | 4.69MB</b></td></tr>',
                    'image': ['63', 0]}},
 '108': {'class_type': 'ImageResizeKJv2',
         'inputs': {'width': ['107', 1],
                    'height': ['107', 2],
                    'widget_0': 256,
                    'widget_1': 256,
                    'widget_2': 'lanczos',
                    'widget_3': 'crop',
                    'widget_4': '0, 0, 0',
                    'widget_5': 'center',
                    'widget_6': 16,
                    'widget_7': 'cpu',
                    'widget_8': '<tr><td>Output: </td><td><b>1</b> x <b>640</b> x <b>640 | 4.69MB</b></td></tr>',
                    'image': ['58', 0]}},
 '106': {'class_type': 'WanVideoLoraSelect',
         'inputs': {'widget_0': 'Wan21_T2V_14B_lightx2v_cfg_step_distill_lora_rank32.safetensors',
                    'widget_1': 1.2000000000000002,
                    'widget_2': False,
                    'widget_3': True}},
 '35': {'class_type': 'WanVideoTorchCompileSettings',
        'inputs': {'widget_0': 'inductor',
                   'widget_1': False,
                   'widget_2': 'default',
                   'widget_3': False,
                   'widget_4': 64,
                   'widget_5': True,
                   'widget_6': 128}},
 '22': {'class_type': 'WanVideoModelLoader',
        'inputs': {'widget_0': 'WanVideo\\Wan2_1-FLF2V-14B-720P_fp8_e4m3fn.safetensors',
                   'widget_1': 'fp16',
                   'widget_2': 'fp8_e4m3fn',
                   'widget_3': 'offload_device',
                   'widget_4': 'sdpa',
                   'compile_args': ['35', 0],
                   'block_swap_args': ['39', 0],
                   'lora': ['106', 0]}},
 '27': {'class_type': 'WanVideoSampler',
        'inputs': {'steps': 1,
                   'widget_0': 1,
                   'widget_1': 1.0000000000000002,
                   'widget_2': 5.000000000000001,
                   'widget_3': 43,
                   'widget_4': 'fixed',
                   'widget_5': True,
                   'widget_6': 'dpm++_sde',
                   'widget_7': 0,
                   'widget_8': 1,
                   'widget_9': '',
                   'widget_10': 'comfy',
                   'widget_11': 0,
                   'widget_12': -1,
                   'widget_13': False,
                   'model': ['22', 0],
                   'image_embeds': ['89', 0],
                   'text_embeds': ['16', 0]}}}

READY_METADATA = {'model_assets': [],
 'unbound_inputs': {'seed': 3788},
 'ready_template': 'video/wanvideo_wrapper_21_14b_flf2v',
 'workflow_template': 'wanvideo_wrapper_21_14b_flf2v',
 'capability': 'first_last_frame_video',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/custom_nodes/wanvideo_wrapper/kijai/wan21_14b_flf2v.json',
 'coverage_tier': 'supplemental',
 'approach': 'WanVideoWrapper first/last-frame video',
 'runtime_note': None,
 'discord_signal': None,
 'smoke_resolution': '256x256x5_frames'}

READY_REQUIREMENTS = {'models': [], 'custom_nodes': ['ComfyUI-KJNodes', 'ComfyUI-VideoHelperSuite', 'ComfyUI-WanVideoWrapper']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "video/wanvideo_wrapper_21_14b_flf2v"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
