from __future__ import annotations

from dataclasses import dataclass
import importlib.util
import sys
from pathlib import Path
from types import ModuleType


REPO_ROOT = Path(__file__).resolve().parents[1]
GENERATOR_PATH = REPO_ROOT / "scripts" / "generate_arnold_docs.py"


def _load_generator() -> ModuleType:
    spec = importlib.util.spec_from_file_location("generate_arnold_docs", GENERATOR_PATH)
    assert spec is not None
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


def test_arnold_docs_write_then_check_and_drift_detection(tmp_path: Path) -> None:
    generator = _load_generator()
    docs_root = tmp_path / "docs"

    assert generator.main(["--write", "--docs-root", str(docs_root)]) == 0
    reference = docs_root / generator.REFERENCE_PATH
    generated = reference.read_text(encoding="utf-8")
    assert generated.startswith("<!--\nThis file is generated by scripts/generate_arnold_docs.py.")
    assert "Do not edit by hand" in generated
    assert "## Manifest Fields" in generated
    assert "## Pipeline Discovery Facts" in generated
    assert "## Typed Port and Content-Type Surfaces" in generated
    assert "## Checker Defect Surfaces" in generated
    assert "## CLI Check and Doctor Facts" in generated
    assert "## Control Vocabulary" in generated
    assert (docs_root / "arnold" / "examples" / "jokes.md").is_file()
    assert (docs_root / "arnold" / "examples" / "select-tournament.md").is_file()

    assert generator.main(["--check", "--docs-root", str(docs_root)]) == 0

    reference.write_text(generated + "\nmanual drift\n", encoding="utf-8")
    assert generator.main(["--check", "--docs-root", str(docs_root)]) == 1

    assert generator.main(["--write", "--docs-root", str(docs_root)]) == 0
    assert reference.read_text(encoding="utf-8") == generated
    assert generator.main(["--check", "--docs-root", str(docs_root)]) == 0


def test_arnold_docs_output_is_stable_and_sorted() -> None:
    generator = _load_generator()

    first = generator.render_reference()
    second = generator.render_reference()

    assert first == second
    manifest_section = first.split("## Manifest Fields", 1)[1].split("## Pipeline Package Contract", 1)[0]
    manifest_rows = [
        line.split("|")[1].strip()
        for line in manifest_section.splitlines()
        if line.startswith("| ") and not line.startswith("| ---") and "field" not in line
    ]
    assert manifest_rows == sorted(manifest_rows)

    facts_section = first.split("## Pipeline Discovery Facts", 1)[1].split(
        "## Discovery Disposition Fields",
        1,
    )[0]
    fact_rows = [
        line.split("|")[1].strip()
        for line in facts_section.splitlines()
        if line.startswith("| ") and not line.startswith("| ---") and "fact" not in line
    ]
    assert fact_rows == sorted(fact_rows)


def test_arnold_examples_are_extracted_from_source_packs() -> None:
    generator = _load_generator()
    examples = generator.render_examples()

    assert generator.EXAMPLES_DIR / "jokes.md" in examples
    assert generator.EXAMPLES_DIR / "select-tournament.md" in examples

    for pack in generator.EXAMPLE_PACKS:
        path = generator.EXAMPLES_DIR / f"{pack.doc_slug}.md"
        if path not in examples:
            assert not pack.required
            continue
        text = examples[path]
        assert text.startswith("<!--\nThis file is generated by scripts/generate_arnold_docs.py.")
        assert f"`megaplan pipelines check {pack.slug}`" in text
        assert generator._source_lines_for_symbols(
            pack.source_dir / "__init__.py",
            pack.init_symbols,
        ).rstrip() in text
        if pack.step_symbols:
            assert generator._source_lines_for_symbols(
                pack.source_dir / "steps.py",
                pack.step_symbols,
            ).rstrip() in text
        assert (pack.source_dir / "SKILL.md").read_text(encoding="utf-8").strip() in text


def test_arnold_examples_validate_through_pipeline_check_surface() -> None:
    generator = _load_generator()

    checked = {
        pack.slug: generator._pipeline_check_result(pack.slug)
        for pack in generator.EXAMPLE_PACKS
        if pack.required or (pack.source_dir / "__init__.py").exists()
    }

    assert checked["jokes"][0], checked["jokes"][1]
    assert checked["select-tournament"][0], checked["select-tournament"][1]
    if "planning" in checked:
        examples = generator.render_examples()
        if checked["planning"][0]:
            assert generator.EXAMPLES_DIR / "planning-as-composition.md" in examples
        else:
            assert generator.EXAMPLES_DIR / "planning-as-composition.md" not in examples


def _section(text: str, heading: str, next_heading: str) -> str:
    return text.split(heading, 1)[1].split(next_heading, 1)[0]


def test_arnold_docs_typed_port_source_family_is_discoverable(monkeypatch) -> None:
    generator = _load_generator()

    @dataclass(frozen=True)
    class SyntheticGeneratedPort:
        name: str
        content_type: str

    monkeypatch.setattr(
        generator,
        "TYPED_PORT_MODELS",
        (*generator.TYPED_PORT_MODELS, SyntheticGeneratedPort),
    )

    typed_section = _section(
        generator.render_reference(),
        "## Typed Port and Content-Type Surfaces",
        "## Checker Defect Surfaces",
    )
    assert "#### SyntheticGeneratedPort" in typed_section


def test_arnold_docs_checker_source_family_identifies_source(monkeypatch) -> None:
    generator = _load_generator()
    original = generator._defect_append_rows

    def with_synthetic_defect(module, list_name):
        rows = original(module, list_name)
        if module is generator.validator:
            return [*rows, ("synthetic-validator-source:1", "synthetic validator defect")]
        return rows

    monkeypatch.setattr(generator, "_defect_append_rows", with_synthetic_defect)

    checker_section = _section(
        generator.render_reference(),
        "## Checker Defect Surfaces",
        "## CLI Check and Doctor Facts",
    )
    assert "synthetic-validator-source:1" in checker_section
    assert "synthetic validator defect" in checker_section


def test_arnold_docs_cli_source_family_identifies_source(monkeypatch) -> None:
    generator = _load_generator()
    monkeypatch.setattr(
        generator.arnold_cli,
        "MODULE_VERBS",
        (*generator.arnold_cli.MODULE_VERBS, "synthetic-verb"),
    )

    cli_section = _section(
        generator.render_reference(),
        "## CLI Check and Doctor Facts",
        "## Control Vocabulary",
    )
    assert "| module_verb | synthetic-verb | arnold/pipelines/megaplan/cli/arnold.py |" in cli_section


def test_arnold_docs_control_source_family_identifies_source(monkeypatch) -> None:
    generator = _load_generator()
    monkeypatch.setattr(
        generator.user_actions,
        "VALID_RESOLUTIONS",
        (*generator.user_actions.VALID_RESOLUTIONS, "synthetic_resolution"),
    )

    control_section = _section(
        generator.render_reference(),
        "## Control Vocabulary",
        "## Behavioral Manifest Projections",
    )
    assert "| UserActionResolution | synthetic_resolution | arnold/pipelines/megaplan/user_actions.py |" in control_section
