from __future__ import annotations

import importlib.util
import json
import pytest
import re
import subprocess
import sys
from pathlib import Path


REPO = Path(__file__).resolve().parents[1]

PILOT_TEMPLATES = (
    "ready_templates/video/ltx2_3_first_last_frame_travel_iclora_control.py",
    "ready_templates/image/qwen_image_2512.py",
    "ready_templates/video/wan_i2v.py",
    "ready_templates/audio/ace_step_1_5_t2a_song.py",
    "ready_templates/edit/qwen_image_edit.py",
)


def _run(args: list[str]) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        [sys.executable, "-m", "tools.narrate_template", *args],
        cwd=REPO,
        text=True,
        stdout=subprocess.PIPE,
        stderr=subprocess.PIPE,
        check=False,
    )


def _generate(template: str, out_path: Path) -> str:
    proc = _run([template, "--mode", "restructure", "--out", str(out_path)])
    assert proc.returncode == 0, proc.stderr
    return out_path.read_text()


def _verify(original: str, generated: Path) -> dict[str, object]:
    proc = _run(["--verify", original, str(generated), "--json"])
    assert proc.returncode == 0, proc.stderr or proc.stdout
    data = json.loads(proc.stdout)
    assert data["status"] == "ok"
    checks = data["checks"]
    for gate in (
        "api_dict_parity",
        "unbound_inputs_parity",
        "register_input_preservation",
        "params_wiring_check",
    ):
        assert checks[gate]["pass"] is True
    return data


def _module_from_path(path: Path):
    module_name = f"_v231_{path.stem}"
    spec = importlib.util.spec_from_file_location(module_name, path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def _public_inputs_block(source: str) -> str:
    match = re.search(r"PUBLIC_INPUTS = \{(?P<body>.*?)\n\}", source, re.S)
    assert match is not None
    return match.group("body")


def _assert_no_inline_long_public_defaults(source: str) -> None:
    block = _public_inputs_block(source)
    for line in block.splitlines():
        if "InputSpec(" not in line or "default=" not in line:
            continue
        default_part = line.split("default=", 1)[1].split(", type=", 1)[0]
        if default_part.startswith(("_", "PUBLIC_INPUTS")):
            continue
        literal = default_part.strip()
        if literal[:1] in {"'", '"'}:
            assert len(literal.strip("'\\\"")) <= 100


def test_default_mode_produces_restructure_output(tmp_path: Path) -> None:
    """Phase 1: bare `python -m tools.narrate_template <file>` (no --mode) produces
    restructure-form output with `node(wf, ...)` calls."""
    template = PILOT_TEMPLATES[0]  # ltx2_3_first_last_frame_travel_iclora_control.py
    out_path = tmp_path / Path(template).name
    proc = _run([template, "--out", str(out_path)])
    assert proc.returncode == 0, proc.stderr
    source = out_path.read_text()
    assert "node(wf," in source
    assert "from vibecomfy.templates import" in source
    assert "READY_METADATA = ReadyMetadata.build(" in source
    assert "_at(" not in source  # restructure mode uses node(), not _at()
    assert "def _at(" not in source


def test_v231_generated_pilots_cover_polish_contracts(tmp_path: Path) -> None:
    generated: dict[str, str] = {}
    generated_paths: dict[str, Path] = {}

    for template in PILOT_TEMPLATES:
        out_path = tmp_path / Path(template).name
        source = _generate(template, out_path)
        generated[template] = source
        generated_paths[template] = out_path

        assert "from vibecomfy.templates import InputSpec, ModelAsset, ReadyMetadata, finalize, new_workflow, node" in source
        # Enriched marker check (T8)
        assert "# vibecomfy: narrative (generated by tools/narrate_template.py @ " in source
        # Source provenance comment (T9) — only when source_workflow is a real file path
        if re.search(r"['\"]source_workflow['\"]\s*:\s*['\"]workflow_corpus/", source):
            assert "# ported from" in source
            assert "(sha256:" in source
        assert "wf = new_workflow(READY_METADATA, source_path=__file__)" in source
        assert ("def " + chr(95) + "node(") not in source
        assert "node(wf," in source
        assert "EDIT_GUIDE =" not in source
        assert "READY_METADATA = ReadyMetadata.build(" in source
        # Four-block contract: no READY_REQUIREMENTS, OUTPUT_PREFIX, or PRIVATE_KNOBS as top-level blocks
        assert re.search(r"^READY_REQUIREMENTS\s*:\s*dict", source, re.MULTILINE) is None, \
            "READY_REQUIREMENTS must not be a top-level block"
        assert re.search(r"^OUTPUT_PREFIX\s*=", source, re.MULTILINE) is None, \
            "OUTPUT_PREFIX must not be a top-level block"
        assert re.search(r"^PRIVATE_KNOBS\s*:\s*dict", source, re.MULTILINE) is None, \
            "PRIVATE_KNOBS must not be a top-level block"
        # Smoke: no dangling references to OUTPUT_PREFIX in finalize footer
        assert "filename_prefix=OUTPUT_PREFIX" not in source
        assert "requirements=READY_REQUIREMENTS" not in source
        # Requirements should be in ReadyMetadata.build() when non-empty
        if "requirements=" in source:
            assert "requirements=" in source.split("READY_METADATA = ReadyMetadata.build(", 1)[1].split("\n)", 1)[0]
        assert "output_node=" in source
        assert "output_kind=" not in source

        assert "param_on_" not in source
        assert "emptyacestep1_5latentaudio" not in source
        assert "textencodeacestepaudio1_5" not in source
        assert "conditioning_zero_out_47" not in source
        assert "vaedecode_audio" not in source
        assert "save_audio_m_p3_59" not in source
        assert "text_encode_qwen_image_edit_1" not in source
        assert "text_encode_qwen_image_edit_2" not in source
        _assert_no_inline_long_public_defaults(source)

        banner_lines = [line for line in source.splitlines() if line.strip().startswith("# ════")]
        assert len(banner_lines) == len(set(banner_lines))
        branch_comments = [line for line in source.splitlines() if "BRANCH SELECTION:" in line]
        assert len(branch_comments) == len(set(branch_comments))

        _verify(template, out_path)

        second_path = tmp_path / f"twice_{Path(template).name}"
        second = _generate(str(out_path), second_path)
        assert second == source

        module = _module_from_path(out_path)
        wf = module.build()
        assert wf.outputs

    ltx = generated["ready_templates/video/ltx2_3_first_last_frame_travel_iclora_control.py"]
    assert "'length': InputSpec(" in ltx
    assert "'frames'" in ltx.split("'length': InputSpec(", 1)[1].split("),", 1)[0]
    assert "'guide_strength': InputSpec(" in ltx
    assert "aliases=('strength',)" in ltx
    assert "'control_video': InputSpec(" in ltx
    assert "clip_name1=MODELS['gemma_clip'].filename" in ltx
    assert "PUBLIC_INPUTS['control_mode'].default" in ltx

    wan = generated["ready_templates/video/wan_i2v.py"]
    assert "'start_image': InputSpec(" in wan
    assert "aliases=('input_image', 'image')" in wan
    assert "'length': InputSpec(" in wan
    assert re.search(r"decoded_frames = node\(wf, ['\"]VAEDecode['\"]", wan)
    assert "decoded_image =" not in wan

    ace = generated["ready_templates/audio/ace_step_1_5_t2a_song.py"]
    assert "'seed_2': InputSpec(" in ace
    assert "aliases=('noise_seed',)" in ace
    assert re.search(r"empty_audio_latent = node\(wf, ['\"]EmptyAceStep1\.5LatentAudio['\"]", ace)
    assert re.search(r"positive_conditioning = node\(wf, ['\"]TextEncodeAceStepAudio1\.5['\"]", ace)
    assert re.search(r"negative_conditioning = node\(wf, ['\"]ConditioningZeroOut['\"]", ace)
    assert re.search(r"decoded_audio = node\(wf, ['\"]VAEDecodeAudio['\"]", ace)
    assert re.search(r"save_audio = node\(wf, ['\"]SaveAudioMP3['\"]", ace)

    edit = generated["ready_templates/edit/qwen_image_edit.py"]
    assert "'source_image': InputSpec(" in edit
    assert "aliases=('input_image', 'image')" in edit
    assert re.search(r"lora_steps = node\(wf, ['\"]PrimitiveInt['\"]", edit)
    assert re.search(r"lora_cfg = node\(wf, ['\"]PrimitiveFloat['\"]", edit)
    assert re.search(r"base_steps = node\(wf, ['\"]PrimitiveInt['\"]", edit)
    assert re.search(r"base_cfg = node\(wf, ['\"]PrimitiveFloat['\"]", edit)
    assert re.search(r"positive_edit_conditioning = node\(wf, ['\"]TextEncodeQwenImageEdit['\"]", edit)
    assert re.search(r"negative_edit_conditioning = node\(wf, ['\"]TextEncodeQwenImageEdit['\"]", edit)
    assert "parity-preserved leaf: wiring into edit encoding changes source API links." in edit


def test_inline_private_knobs_replaces_references_with_literal_values() -> None:
    """T6: PRIVATE_KNOBS references replaced with literal values."""
    from tools.narrate_template import _inline_private_knobs

    source = (
        "PRIVATE_KNOBS: dict[str, object] = {\n"
        "    'scheduler': 'simple',\n"
        "    'denoise': 1,\n"
        "}\n"
        "\n"
        "def build():\n"
        "    sampler = node(wf, 'KSampler', '42',\n"
        "        scheduler=PRIVATE_KNOBS['scheduler'],\n"
        "        denoise=PRIVATE_KNOBS['denoise'],\n"
        "    )\n"
    )
    private_knobs = {"scheduler": "simple", "denoise": 1}

    result = _inline_private_knobs(source, private_knobs)

    assert "PRIVATE_KNOBS[" not in result
    assert "PRIVATE_KNOBS['scheduler']" not in result
    assert "PRIVATE_KNOBS['denoise']" not in result
    assert "scheduler='simple'" in result
    assert "denoise=1" in result


def test_inline_private_knobs_preserves_source_when_empty_knobs() -> None:
    """T6: _inline_private_knobs no-ops when private_knobs is empty."""
    from tools.narrate_template import _inline_private_knobs

    source = "scheduler=PRIVATE_KNOBS['scheduler'],\n"
    result = _inline_private_knobs(source, {})
    assert result == source


def test_restructure_output_has_no_private_knobs_top_level_block(tmp_path: Path) -> None:
    """T6: Codemod restructure on an old-style _node template produces no PRIVATE_KNOBS block."""
    # Use the old-style flux2_klein_4b_image_edit_distilled template as input.
    old_template = "ready_templates/edit/flux2_klein_4b_image_edit_distilled.py"
    old_path = REPO / old_template
    if not old_path.is_file():
        pytest.skip(f"{old_template} not available")

    out_path = tmp_path / Path(old_template).name
    proc = _run([old_template, "--mode", "restructure", "--out", str(out_path)])
    # The old template may or may not convert successfully depending on its format.
    # If it fails, skip the test gracefully.
    if proc.returncode != 0:
        pytest.skip(f"codemod failed on {old_template}: {proc.stderr[:200]}")
    source = out_path.read_text()
    assert "PRIVATE_KNOBS" not in source or "PRIVATE_KNOBS[" not in source
