"""Compatibility facade for the canonical audit package."""

from __future__ import annotations

from importlib import import_module

__all__ = [
    "AUDIT_FILE",
    "aggregate_tiebreaker_audit",
    "load_tiebreaker_audit",
    "record_tiebreaker_audit",
    "render_audit_report",
    "resolve_plan_dir",
    "CriterionAudit",
    "audit_criteria",
    "classify_criteria",
    "validate_requires",
    "IterationPressureEntry",
    "compute_flag_history",
    "compute_fuzzy_groups",
    "compute_iteration_pressure",
    "has_mechanical_recurrence",
    "render_pressure_table",
    "DEFAULT_DUPLICATE_MAX_FILE_LINES",
    "DEFAULT_DUPLICATE_SIMILARITY_THRESHOLD",
    "DEFAULT_FILE_GROWTH_THRESHOLD",
    "DEFAULT_TIME_BUDGET_SECONDS",
    "capture_before_line_counts",
    "run_quality_checks",
    "CRITIQUE_CHECKS",
    "CritiqueCheckSpec",
    "JOKE_CRITIQUE_CHECKS",
    "VALID_SEVERITY_HINTS",
    "build_check_category_map",
    "build_empty_template",
    "checks_for_robustness",
    "creative_checks_for_robustness",
    "get_check_by_id",
    "get_check_ids",
    "joke_checks_for_robustness",
    "validate_critique_checks",
    "ALL_CAPABILITIES",
    "CONTAINER_CAPABILITIES",
    "DEFAULT_AGENT_ROUTING",
    "DEFAULT_CONTAINER_CAPABILITIES",
    "DEFAULT_HUMAN_CAPABILITIES",
    "HUMAN_CAPABILITIES",
    "get_worker_capabilities",
    "union_verifies",
    "validate_capabilities",
    "CONDITIONAL_RETENTION_DIRS",
    "DEAD_WEIGHT_PATTERNS",
    "JOB_B_SCOPE_FENCE_ENTRIES",
    "RUNTIME_REQUIRED_ENTRIES",
    "VendoredAgentHistoryAudit",
    "VendoredAgentTreeAudit",
    "audit_vendored_agent_history",
    "audit_vendored_agent_tree",
    "find_retention_import_sites",
]

_MODULE_EXPORTS = {
    "arnold_pipelines.megaplan.audits.audit_engine": {
        "AUDIT_FILE",
        "aggregate_tiebreaker_audit",
        "load_tiebreaker_audit",
        "record_tiebreaker_audit",
        "render_audit_report",
        "resolve_plan_dir",
    },
    "arnold_pipelines.megaplan.audits.verifiability": {
        "CriterionAudit",
        "audit_criteria",
        "classify_criteria",
        "validate_requires",
    },
    "arnold_pipelines.megaplan.audits.iteration": {
        "IterationPressureEntry",
        "compute_flag_history",
        "compute_fuzzy_groups",
        "compute_iteration_pressure",
        "has_mechanical_recurrence",
        "render_pressure_table",
    },
    "arnold_pipelines.megaplan.audits.quality_gates": {
        "DEFAULT_DUPLICATE_MAX_FILE_LINES",
        "DEFAULT_DUPLICATE_SIMILARITY_THRESHOLD",
        "DEFAULT_FILE_GROWTH_THRESHOLD",
        "DEFAULT_TIME_BUDGET_SECONDS",
        "capture_before_line_counts",
        "run_quality_checks",
    },
    "arnold_pipelines.megaplan.audits.robustness": {
        "CRITIQUE_CHECKS",
        "CritiqueCheckSpec",
        "JOKE_CRITIQUE_CHECKS",
        "VALID_SEVERITY_HINTS",
        "build_check_category_map",
        "build_empty_template",
        "checks_for_robustness",
        "creative_checks_for_robustness",
        "get_check_by_id",
        "get_check_ids",
        "joke_checks_for_robustness",
        "validate_critique_checks",
    },
    "arnold_pipelines.megaplan.audits.capabilities": {
        "ALL_CAPABILITIES",
        "CONTAINER_CAPABILITIES",
        "DEFAULT_AGENT_ROUTING",
        "DEFAULT_CONTAINER_CAPABILITIES",
        "DEFAULT_HUMAN_CAPABILITIES",
        "HUMAN_CAPABILITIES",
        "get_worker_capabilities",
        "union_verifies",
        "validate_capabilities",
    },
    "arnold_pipelines.megaplan.audits.hermes_vendoring": {
        "CONDITIONAL_RETENTION_DIRS",
        "DEAD_WEIGHT_PATTERNS",
        "JOB_B_SCOPE_FENCE_ENTRIES",
        "RUNTIME_REQUIRED_ENTRIES",
        "VendoredAgentHistoryAudit",
        "VendoredAgentTreeAudit",
        "audit_vendored_agent_history",
        "audit_vendored_agent_tree",
        "find_retention_import_sites",
    },
}


def __getattr__(name: str):
    for module_name, exports in _MODULE_EXPORTS.items():
        if name in exports:
            module = import_module(module_name)
            return getattr(module, name)
    raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
