"""Core infrastructure for megaplan — re-exports from submodules.

All public names are available via ``from megaplan._core import <name>``
so existing callers don't need to change.
"""

# Re-export shutil so monkeypatches like `megaplan._core.shutil.which` still work.
import shutil  # noqa: F401

# -- io.py: pure utilities, atomic I/O, paths, config -----------------------
from .io import (
    append_framed_json_records,
    append_framed_json_transaction,
    artifact_path,
    atomic_write_bytes,
    atomic_write_json,
    atomic_write_text,
    batch_artifact_path,
    canonical_megaplan_root,
    commit_journal_transaction,
    committed_framed_json_transactions,
    collect_git_diff_patch,
    collect_git_diff_summary,
    compute_batch_complexity,
    compute_global_batches,
    compute_task_batches,
    config_dir,
    current_iteration_artifact,
    current_iteration_raw_artifact,
    discard_uncommitted_journal_transaction,
    detect_available_agents,
    is_shannon_available,
    shannon_missing_deps,
    ensure_runtime_layout,
    find_plan_dir,
    find_command,
    framed_json_record_bytes,
    fsync_dir,
    fsync_file,
    get_effective,
    setting_is_explicit,
    has_any_plan_root,
    journal_blob_promotion,
    journal_bytes_write,
    journal_commit_path,
    journal_event_log,
    journal_prepare_path,
    journal_root,
    journal_text_write,
    json_dump,
    list_batch_artifacts,
    load_config,
    load_finalize_snapshot,
    megaplan_root,
    normalize_text,
    now_utc,
    orphan_plans_root,
    plan_search_roots,
    plans_root,
    prepare_journal_transaction,
    read_json,
    read_committed_framed_json_records,
    recover_journal,
    repo_storage_id,
    render_final_md,
    save_config,
    schemas_root,
    scrub_stale_staging_files,
    sha256_file,
    sha256_text,
    split_oversized_batches,
    slugify,
    write_journal_commit_marker,
)

# -- phase_runtime.py: centralized runtime policy ----------------------------
from .phase_runtime import (
    DEFAULT_NON_EXECUTE_TIMEOUT_CAP_SECONDS,
    PHASE_RUNTIME_POLICY,
    build_next_step_runtime,
    build_phase_observability,
    format_duration_hint,
    humanize_seconds,
    phase_runtime_policy,
    phase_stale_seconds,
    phase_timeout_seconds,
    resolve_phase_runtime,
)

# -- modes.py: mode/form helpers --------------------------------------------
from .modes import (
    creative_form_id,
    is_creative_mode,
    is_prose_mode,
)

# -- state.py: plan state, history, sessions ---------------------------------
from .state import (
    active_plan_dirs,
    active_step_is_stale,
    append_history,
    apply_session_update,
    clear_active_step,
    latest_plan_meta_path,
    latest_plan_path,
    latest_plan_record,
    load_plan,
    load_plan_from_dir,
    load_plan_locked,
    make_history_entry,
    plan_lock,
    plan_lock_is_held,
    plan_lock_path,
    record_step_failure,
    resolve_plan_dir,
    save_state,
    save_state_merge_meta,
    set_active_step,
    store_raw_worker_output,
    touch_active_step,
)

# -- registries.py: flag + debt registries -----------------------------------
from .registries import (
    add_or_increment_debt,
    debt_by_subsystem,
    escalated_subsystems,
    extract_subsystem_tag,
    find_matching_debt,
    is_scope_creep_flag,
    load_debt_registry,
    load_flag_registry,
    next_debt_id,
    resolve_debt,
    save_debt_registry,
    save_flag_registry,
    scope_creep_flags,
    subsystem_occurrence_total,
    unresolved_significant_flags,
)

# -- hermes_fanout.py: shared parallel fan-out primitives --------------------
from .hermes_fanout import (
    GenericScatterResult,
    ScatterResult,
    _merge_unique,
    scatter_gather,
    scatter_gather_checks,
    with_429_openrouter_fallback,
)

# -- workflow.py: state machine, transitions ---------------------------------
from megaplan.types import ROBUSTNESS_LEVELS, STATE_EXECUTED, STATE_REVIEWED, STATE_DONE  # noqa: F401 — accessed by tests via megaplan._core

from .workflow import (
    WORKFLOW,
    Transition,
    _ROBUSTNESS_OVERRIDES,
    adaptive_critique_enabled,
    configured_robustness,
    infer_next_steps,
    intent_and_notes_block,
    intent_brief_reference,
    require_state,
    resume_plan,
    robustness_critique_instruction,
    workflow_includes_step,
    workflow_next,
    workflow_transition,
)

__all__ = [
    # io
    "append_framed_json_records",
    "append_framed_json_transaction",
    "artifact_path",
    "atomic_write_bytes",
    "atomic_write_json",
    "atomic_write_text",
    "batch_artifact_path",
    "canonical_megaplan_root",
    "commit_journal_transaction",
    "committed_framed_json_transactions",
    "collect_git_diff_patch",
    "collect_git_diff_summary",
    "compute_batch_complexity",
    "compute_global_batches",
    "compute_task_batches",
    "config_dir",
    "current_iteration_artifact",
    "current_iteration_raw_artifact",
    "discard_uncommitted_journal_transaction",
    "detect_available_agents",
    "is_shannon_available",
    "shannon_missing_deps",
    "ensure_runtime_layout",
    "find_plan_dir",
    "find_command",
    "framed_json_record_bytes",
    "fsync_dir",
    "fsync_file",
    "get_effective",
    "setting_is_explicit",
    "has_any_plan_root",
    "journal_blob_promotion",
    "journal_bytes_write",
    "journal_commit_path",
    "journal_event_log",
    "journal_prepare_path",
    "journal_root",
    "journal_text_write",
    "json_dump",
    "list_batch_artifacts",
    "load_config",
    "load_finalize_snapshot",
    "megaplan_root",
    "normalize_text",
    "now_utc",
    "orphan_plans_root",
    "plan_search_roots",
    "plans_root",
    "prepare_journal_transaction",
    "read_json",
    "read_committed_framed_json_records",
    "recover_journal",
    "repo_storage_id",
    "render_final_md",
    "save_config",
    "schemas_root",
    "scrub_stale_staging_files",
    "sha256_file",
    "sha256_text",
    "split_oversized_batches",
    "slugify",
    "write_journal_commit_marker",
    # phase_runtime
    "DEFAULT_NON_EXECUTE_TIMEOUT_CAP_SECONDS",
    "PHASE_RUNTIME_POLICY",
    "build_next_step_runtime",
    "build_phase_observability",
    "format_duration_hint",
    "humanize_seconds",
    "phase_runtime_policy",
    "phase_stale_seconds",
    "phase_timeout_seconds",
    "resolve_phase_runtime",
    # modes
    "creative_form_id",
    "is_creative_mode",
    "is_prose_mode",
    # state
    "active_plan_dirs",
    "active_step_is_stale",
    "append_history",
    "apply_session_update",
    "clear_active_step",
    "latest_plan_meta_path",
    "latest_plan_path",
    "latest_plan_record",
    "load_plan",
    "load_plan_from_dir",
    "load_plan_locked",
    "make_history_entry",
    "plan_lock",
    "plan_lock_is_held",
    "plan_lock_path",
    "record_step_failure",
    "resolve_plan_dir",
    "save_state",
    "save_state_merge_meta",
    "set_active_step",
    "store_raw_worker_output",
    "touch_active_step",
    # registries
    "add_or_increment_debt",
    "debt_by_subsystem",
    "escalated_subsystems",
    "extract_subsystem_tag",
    "find_matching_debt",
    "is_scope_creep_flag",
    "load_debt_registry",
    "load_flag_registry",
    "next_debt_id",
    "resolve_debt",
    "save_debt_registry",
    "save_flag_registry",
    "scope_creep_flags",
    "subsystem_occurrence_total",
    "unresolved_significant_flags",
    # workflow
    "WORKFLOW",
    "Transition",
    "_ROBUSTNESS_OVERRIDES",
    "adaptive_critique_enabled",
    "configured_robustness",
    "infer_next_steps",
    "intent_and_notes_block",
    "intent_brief_reference",
    "require_state",
    "resume_plan",
    "robustness_critique_instruction",
    "workflow_includes_step",
    "workflow_next",
    "workflow_transition",
    # State constants (re-exported for convenience)
    "STATE_EXECUTED",
    "STATE_REVIEWED",
    "STATE_DONE",
    # hermes_fanout
    "GenericScatterResult",
    "ScatterResult",
    "_merge_unique",
    "scatter_gather",
    "scatter_gather_checks",
    "with_429_openrouter_fallback",
]
