"""READ-ONLY verbatim snapshot of the auto.py subprocess supervision substrate.

This module is a pinned, frozen copy of the subprocess-spawning + watcher
machinery extracted from ``megaplan/auto.py`` as it existed at the M3 hinge
point.  It exists so the version-skew oracle (and any future substrate-swap
gate) has a byte-stable reference to compare against — the oracle can diff
the live ``auto.py`` watcher against this snapshot to detect drift.

**DO NOT EDIT this file.**  Any change risks invalidating the M3 oracles.
If the real ``auto.py`` watcher needs to evolve, update it there AND
re-snapshot through the formal plan process — do not hand-edit this copy.

Public surface
--------------
legacy_supervise_subprocess(args, *, cwd, timeout, idle_timeout, env, liveness_plan_dir)
    → tuple[int, str, str]
legacy_phase_command(next_step) → list[str]

The remaining symbols are implementation details of the snapshot and are
not part of the public contract.
"""

from __future__ import annotations

import json
import logging
import os
import shlex
import subprocess
import sys
import threading
import time
from pathlib import Path
from typing import Any

from arnold.pipelines.megaplan._core import active_phase_name
from arnold.pipelines.megaplan.handlers.shared import _warn_read_fallback
from arnold.pipelines.megaplan.runtime.process import kill_group, spawn

# ---------------------------------------------------------------------------
# Verbatim constants from auto.py
# ---------------------------------------------------------------------------

DEFAULT_PHASE_HEARTBEAT_SECONDS = 60.0
PHASE_TIMEOUT_EXIT_CODE = 124  # conventional; matches GNU `timeout`

# ---------------------------------------------------------------------------
# Verbatim: _plan_liveness_mtime  (auto.py ~L395-413)
# ---------------------------------------------------------------------------


def _plan_liveness_mtime(plan_dir: Path | None) -> float | None:
    """Return newest plan artifact mtime that proves a quiet phase is alive."""

    if plan_dir is None:
        return None
    candidates = [plan_dir / "state.json"]
    try:
        candidates.extend(plan_dir.glob("execution_batch_*.json"))
    except OSError:
        pass
    newest: float | None = None
    for path in candidates:
        try:
            mtime = path.stat().st_mtime
        except OSError:
            continue
        if newest is None or mtime > newest:
            newest = mtime
    return newest


# ---------------------------------------------------------------------------
# Verbatim: _phase_heartbeat_interval_seconds  (auto.py ~L416-426)
# ---------------------------------------------------------------------------


def _phase_heartbeat_interval_seconds() -> float | None:
    raw = os.getenv("MEGAPLAN_AUTO_HEARTBEAT_SECONDS")
    if raw is None:
        return DEFAULT_PHASE_HEARTBEAT_SECONDS
    try:
        value = float(raw)
    except ValueError:
        return DEFAULT_PHASE_HEARTBEAT_SECONDS
    if value <= 0:
        return None
    return value


# ---------------------------------------------------------------------------
# Verbatim: _format_phase_heartbeat  (auto.py ~L429-481)
# ---------------------------------------------------------------------------


def _format_phase_heartbeat(
    args: list[str],
    *,
    elapsed_s: float,
    plan_dir: Path | None,
    progress_changed: bool,
) -> str:
    command = "megaplan " + " ".join(args)
    bits = [
        f"[megaplan auto] heartbeat command={command!r}",
        f"elapsed={int(elapsed_s)}s",
        f"progress_mtime_changed={'yes' if progress_changed else 'no'}",
    ]
    state_path = plan_dir / "state.json" if plan_dir is not None else None
    if state_path is not None:
        try:
            raw = json.loads(state_path.read_text(encoding="utf-8"))
        except FileNotFoundError:
            raw = None
        except json.JSONDecodeError:
            _warn_read_fallback(
                "M3A_WARN_HEARTBEAT_STATE_READ",
                path=state_path,
                reason="corrupt_json",
            )
            raw = None
        except (OSError, UnicodeDecodeError):
            _warn_read_fallback(
                "M3A_WARN_HEARTBEAT_STATE_READ",
                path=state_path,
                reason="unreadable",
            )
            raw = None
        if isinstance(raw, dict):
            plan_name = raw.get("name")
            current_state = raw.get("current_state")
            active = raw.get("active_step")
            if isinstance(plan_name, str) and plan_name:
                bits.append(f"plan={plan_name}")
            if isinstance(current_state, str) and current_state:
                bits.append(f"state={current_state}")
            if isinstance(active, dict):
                step = active_phase_name(active)
                agent = active.get("agent")
                mode = active.get("mode")
                worker = "/".join(
                    part
                    for part in (
                        str(agent) if agent else "",
                        str(mode) if mode else "",
                    )
                    if part
                )
                if isinstance(step, str) and step:
                    bits.append(f"active_step={step}")
                if worker:
                    bits.append(f"worker={worker}")
    return " ".join(bits)


# ---------------------------------------------------------------------------
# Verbatim: _phase_command  (auto.py ~L504-535)
# ---------------------------------------------------------------------------


def _phase_command(next_step: str) -> list[str]:
    """Translate a `next_step` from status into the CLI args that run it.

    Most phases are one-to-one: next_step == command. Execute adds the
    destructive + user-approved flags because auto-mode implies both.

    Multi-token values like ``"override add-note"`` must be split into
    ``["override", "add-note"]`` so argparse sees the sub-subcommand —
    otherwise the whole string is passed as a single positional and
    argparse rejects it with `invalid choice`.
    """
    if next_step == "execute":
        # --retry-blocked-tasks is safe to pass on every iteration. Within a
        # single auto session, tasks that report status=blocked terminate the
        # auto loop via STATE_AWAITING_HUMAN_VERIFY (see eb4ac447), so re-dispatch
        # only happens on a *fresh* `megaplan auto` invocation — which is the
        # user's signal that any external prereq has been resolved and stale
        # blocked statuses should be retried instead of short-circuiting.
        # If there are no blocked tasks, the flag is a no-op.
        return [
            "execute",
            "--confirm-destructive",
            "--user-approved",
            "--retry-blocked-tasks",
        ]
    if next_step == "feedback":
        # The auto driver must dispatch the *workflow* operation, not the
        # default "edit" operation — otherwise the handler would open $EDITOR
        # and block on human input.  "feedback workflow" scaffolds the file
        # non-interactively and transitions reviewed → done.
        return ["feedback", "workflow"]
    return shlex.split(next_step)


# ---------------------------------------------------------------------------
# Public surface — the pinned, importable legacy API
# ---------------------------------------------------------------------------


def legacy_supervise_subprocess(
    args: list[str],
    *,
    cwd: Path | None = None,
    timeout: float | None = None,
    idle_timeout: float | None = None,
    env: dict[str, str] | None = None,
    liveness_plan_dir: Path | None = None,
) -> tuple[int, str, str]:
    """Verbatim snapshot of the auto.py watcher block (~L303-392).

    Spawns ``megaplan`` as a subprocess with ``start_new_session=True``,
    reads stdout/stderr on background threads, monitors plan-artifact
    mtime for liveness, emits heartbeats, and applies wall + idle
    timeouts with ``kill_group`` reaping.

    Returns ``(exit_code, stdout, stderr)`` — identical contract to the
    original ``_run_megaplan``.
    """
    # --- verbatim block: auto.py L303-312 ---
    try:
        proc = spawn(
            [sys.executable, "-m", "arnold.pipelines.megaplan", *args],
            cwd=str(cwd) if cwd else None,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            env=env,
        )
    except FileNotFoundError as error:
        return 127, "", str(error)

    # --- verbatim block: auto.py L314-340 ---
    stdout_parts: list[bytes] = []
    stderr_parts: list[bytes] = []
    last_activity = time.monotonic()
    last_hard_progress = last_activity
    last_liveness_mtime = _plan_liveness_mtime(liveness_plan_dir)
    heartbeat_interval = _phase_heartbeat_interval_seconds()
    last_heartbeat = last_activity
    liveness_changed_since_heartbeat = False

    def _reader(stream: Any, parts: list[bytes]) -> None:
        nonlocal last_activity, last_hard_progress
        if stream is None:
            return
        while True:
            chunk = stream.read(4096)
            if not chunk:
                break
            parts.append(chunk)
            last_activity = time.monotonic()
            last_hard_progress = last_activity

    threads = [
        threading.Thread(target=_reader, args=(proc.stdout, stdout_parts), daemon=True),
        threading.Thread(target=_reader, args=(proc.stderr, stderr_parts), daemon=True),
    ]
    for thread in threads:
        thread.start()

    # --- verbatim block: auto.py L342-377 ---
    started = time.monotonic()
    timed_out_reason: str | None = None
    while proc.poll() is None:
        now = time.monotonic()
        current_liveness_mtime = _plan_liveness_mtime(liveness_plan_dir)
        if (
            current_liveness_mtime is not None
            and (
                last_liveness_mtime is None
                or current_liveness_mtime > last_liveness_mtime
            )
        ):
            last_liveness_mtime = current_liveness_mtime
            last_activity = now
            last_hard_progress = now
            liveness_changed_since_heartbeat = True
        if heartbeat_interval is not None and now - last_heartbeat >= heartbeat_interval:
            logging.getLogger("megaplan").info(
                "%s",
                _format_phase_heartbeat(
                    args,
                    elapsed_s=now - started,
                    plan_dir=liveness_plan_dir,
                    progress_changed=liveness_changed_since_heartbeat,
                ),
            )
            last_heartbeat = now
            liveness_changed_since_heartbeat = False
        timeout_base = last_hard_progress if idle_timeout is not None else started
        if timeout is not None and now - timeout_base >= timeout:
            timed_out_reason = f"subprocess timed out after {timeout}s"
            break
        if idle_timeout is not None and now - last_activity >= idle_timeout:
            timed_out_reason = (
                f"subprocess idle timed out after {idle_timeout}s without output"
            )
            break
        time.sleep(0.2)

    # --- verbatim block: auto.py L379-392 (kill_group + join + decode) ---
    if timed_out_reason is not None:
        kill_group(proc, label="megaplan auto idle/timeout")
        for thread in threads:
            thread.join(timeout=1)
        stdout = b"".join(stdout_parts).decode("utf-8", errors="replace")
        stderr = b"".join(stderr_parts).decode("utf-8", errors="replace")
        marker = f"\n[megaplan auto] {timed_out_reason}"
        return PHASE_TIMEOUT_EXIT_CODE, stdout, (stderr + marker).strip()

    for thread in threads:
        thread.join(timeout=1)
    stdout = b"".join(stdout_parts).decode("utf-8", errors="replace")
    stderr = b"".join(stderr_parts).decode("utf-8", errors="replace")
    return int(proc.returncode or 0), stdout, stderr


def legacy_phase_command(next_step: str) -> list[str]:
    """Verbatim snapshot wrapper of ``auto._phase_command``."""
    return _phase_command(next_step)
