from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path
from typing import Any

try:
    import tomllib
except ModuleNotFoundError:  # pragma: no cover - Python < 3.11 compatibility
    import tomli as tomllib  # type: ignore[no-redef]


@dataclass
class LockEntry:
    name: str
    git_commit_sha: str
    url: str
    semantic_label: str | None = None
    source_sha256: dict[str, str] = field(default_factory=dict)


def read_lockfile(path: Path = Path("custom_nodes.lock")) -> list[LockEntry]:
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8")
    stripped = text.strip()
    if not stripped:
        return []
    first_content = next(
        (line.strip() for line in stripped.splitlines() if line.strip() and not line.lstrip().startswith("#")),
        "",
    )
    if first_content.startswith("[") or first_content.startswith("=") or "=" in first_content:
        return _read_toml_lockfile(stripped)
    return _read_legacy_lockfile(stripped)


def write_lockfile(entries: list[LockEntry], path: Path) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    lines = [
        "# Generated by vibecomfy nodes lock.",
        "# git_commit_sha is the immutable primary pin; semantic_label is advisory.",
        "",
    ]
    for entry in sorted(entries, key=lambda item: item.name):
        lines.append(f"[nodepacks.{_toml_quote(entry.name)}]")
        lines.append(f"git_commit_sha = {_toml_quote(entry.git_commit_sha)}")
        lines.append(f"url = {_toml_quote(entry.url)}")
        if entry.semantic_label is not None:
            lines.append(f"semantic_label = {_toml_quote(entry.semantic_label)}")
        if entry.source_sha256:
            lines.append(f"[nodepacks.{_toml_quote(entry.name)}.source_sha256]")
            for name, digest in sorted(entry.source_sha256.items()):
                lines.append(f"{_toml_quote(name)} = {_toml_quote(digest)}")
        lines.append("")
    path.write_text("\n".join(lines), encoding="utf-8")


def upsert_lockfile_entry(entry: LockEntry, path: Path = Path("custom_nodes.lock")) -> None:
    entries = read_lockfile(path)
    for index, existing in enumerate(entries):
        if existing.name == entry.name:
            entries[index] = entry
            break
    else:
        entries.append(entry)
    write_lockfile(entries, path)


def _read_legacy_lockfile(text: str) -> list[LockEntry]:
    entries: list[LockEntry] = []
    for lineno, line in enumerate(text.splitlines(), start=1):
        stripped = line.strip()
        if not stripped or stripped.startswith("#"):
            continue
        parts = stripped.split()
        if len(parts) != 3:
            raise ValueError(f"Invalid legacy custom_nodes.lock line {lineno}: expected 3 whitespace tokens")
        name, git_commit_sha, url = parts
        entries.append(LockEntry(name=name, git_commit_sha=git_commit_sha, url=url))
    return entries


def _read_toml_lockfile(text: str) -> list[LockEntry]:
    data = tomllib.loads(text)
    entries: list[LockEntry] = []
    if isinstance(data.get("entries"), list):
        for raw in data["entries"]:
            if isinstance(raw, dict):
                entries.append(_entry_from_mapping(raw.get("name"), raw))
        return entries
    nodepacks = data.get("nodepacks")
    if isinstance(nodepacks, dict):
        for name, raw in nodepacks.items():
            if isinstance(raw, dict):
                entries.append(_entry_from_mapping(name, raw))
        return entries
    for name, raw in data.items():
        if isinstance(raw, dict) and ("git_commit_sha" in raw or "git_sha" in raw):
            entries.append(_entry_from_mapping(name, raw))
    return entries


def _entry_from_mapping(name: Any, raw: dict[str, Any]) -> LockEntry:
    entry_name = str(raw.get("name") or name)
    git_commit_sha = raw.get("git_commit_sha", raw.get("git_sha"))
    if git_commit_sha is None:
        raise ValueError(f"Lock entry {entry_name!r} is missing git_commit_sha")
    url = raw.get("url")
    if url is None:
        raise ValueError(f"Lock entry {entry_name!r} is missing url")
    source_sha256 = raw.get("source_sha256") or {}
    if not isinstance(source_sha256, dict):
        raise ValueError(f"Lock entry {entry_name!r} source_sha256 must be a table")
    semantic_label = raw.get("semantic_label")
    return LockEntry(
        name=entry_name,
        git_commit_sha=str(git_commit_sha),
        url=str(url),
        semantic_label=str(semantic_label) if semantic_label is not None else None,
        source_sha256={str(key): str(value) for key, value in source_sha256.items()},
    )


def _toml_quote(value: str) -> str:
    escaped = value.replace("\\", "\\\\").replace('"', '\\"')
    return f'"{escaped}"'
