"""Oracle-gate replay test for the M5a composed pipeline.

Runs a composed pipeline built from:

* :func:`critique_revise_gate_loop`
* :func:`escalate_via_subpipeline`
* :func:`majority_vote` (``default_on_tie='tiebreaker'``)

under ``MEGAPLAN_UNIFIED_DISPATCH=1``, drives it with stubbed Step
verdicts forcing the escalate and tiebreaker paths, records
``(stage_name, edge.label, edge.kind, edge.recommendation)`` tuples
in execution order, and asserts field-equal against fixture files
under ``tests/fixtures/oracle/``.

The fixtures are *synthetic-but-recorded* — generated by this exact
composed pipeline with stub Steps whose verdicts are controlled
programmatically.  See ``tests/fixtures/oracle/README.md`` for
provenance.
"""

from __future__ import annotations

import dataclasses
import json
from pathlib import Path
from typing import Any, Mapping

import pytest

from megaplan._pipeline.pattern_joins import majority_vote
from megaplan._pipeline.pattern_topology import (
    critique_revise_gate_loop,
    escalate_via_subpipeline,
)
from megaplan._pipeline.types import (
    Edge,
    ParallelStage,
    Pipeline,
    PipelineVerdict,
    Stage,
    StepContext,
    StepResult,
)

# ── Paths ──────────────────────────────────────────────────────────────

FIXTURE_DIR = Path(__file__).resolve().parent.parent / "fixtures" / "oracle"
ESCALATE_FIXTURE = FIXTURE_DIR / "escalate_trace.json"
TIEBREAKER_FIXTURE = FIXTURE_DIR / "tiebreaker_trace.json"

# ── Stub Steps ─────────────────────────────────────────────────────────


@dataclasses.dataclass
class _FixedNextStep:
    """Step that returns a fixed ``next`` label and optional state_patch."""

    name: str
    kind: str = "produce"
    prompt_key: str | None = None
    slot: str | None = None
    _next: str = "halt"
    _state_patch: Mapping[str, Any] = dataclasses.field(default_factory=dict)

    def run(self, ctx: StepContext) -> StepResult:
        return StepResult(next=self._next, state_patch=dict(self._state_patch))


@dataclasses.dataclass
class _VerdictStep:
    """Step that emits a fixed :class:`PipelineVerdict.recommendation`."""

    name: str
    recommendation: str
    kind: str = "judge"
    prompt_key: str | None = None
    slot: str | None = None

    def run(self, ctx: StepContext) -> StepResult:
        return StepResult(
            verdict=PipelineVerdict(score=1.0, recommendation=self.recommendation),  # type: ignore[arg-type]
            next=self.recommendation,
        )


# ── Trace recorder ─────────────────────────────────────────────────────


def _trace_pipeline(
    pipeline: Pipeline,
    ctx: StepContext,
    *,
    artifact_root: Path,
) -> list[tuple[str, str, str, str | None]]:
    """Run *pipeline* and collect ``(stage_name, edge.label, edge.kind, edge.recommendation)``.

    Mirrors the executor's dispatch logic (``run_pipeline``) but records
    each edge taken in execution order.  The returned list is the
    *oracle trace* for the pipeline under the given stub configuration.
    """
    trace: list[tuple[str, str, str, str | None]] = []

    state: dict[str, Any] = dict(ctx.state) if isinstance(ctx.state, Mapping) else {}
    cursor = pipeline.entry

    while True:
        node = pipeline.stages[cursor]
        stage_name = node.name

        ctx = dataclasses.replace(ctx, state=state)

        # ── run the step ──
        if isinstance(node, ParallelStage):
            # Run each step sequentially (single-thread trace is deterministic).
            results: list[StepResult] = []
            for step in node.steps:
                results.append(step.run(ctx))
            result = node.join(results, ctx)
        else:
            assert isinstance(node, Stage)
            result = node.step.run(ctx)

        # ── apply state patch ──
        state.update(dict(result.state_patch))

        # ── terminal sentinel ──
        if result.next == "halt":
            break

        # ── edge dispatch (mirrors executor) ──
        edge: Edge | None = None
        rec = None
        if result.verdict is not None and result.verdict.override is not None:
            # override edges not relevant for this trace
            pass
        if edge is None and result.verdict is not None and result.verdict.recommendation is not None:
            rec = result.verdict.recommendation
            edge = next(
                (e for e in node.edges if e.kind == "gate" and e.recommendation == rec),
                None,
            )
        if edge is None:
            edge = next(
                (e for e in node.edges if e.kind == "normal" and e.label == result.next),
                None,
            )
        if edge is None:
            raise LookupError(
                f"Stage {stage_name!r} produced next={result.next!r} "
                f"recommendation={rec!r} but no matching edge was found"
            )

        # ── record the transition ──
        trace.append((stage_name, edge.label, edge.kind, edge.recommendation))

        # ── terminal target ──
        if edge.target == "halt":
            break

        cursor = edge.target

    return trace


# ── Composed pipeline builder ──────────────────────────────────────────


def _build_composed_pipeline(gate_recommendation: str) -> tuple[Pipeline, list[tuple[str, str, str, str | None]]]:
    """Build the composed pipeline and return it along with the recorded trace.

    The pipeline composes:
    * ``critique_revise_gate_loop`` — critique → gate → revise cycle
    * ``escalate_via_subpipeline`` — escalation subpipeline with escape edge
    * ``majority_vote(default_on_tie='tiebreaker')`` — tiebreaker panel

    *gate_recommendation* controls which path the gate Step forces:
    ``"escalate"`` or ``"tiebreaker"``.
    """
    # ── Escalate subpipeline ──
    child_step = _FixedNextStep(name="resolve_step", _next="halt", _state_patch={"current_state": "critiqued"})
    child = Pipeline(
        stages={"resolve_step": Stage(name="resolve_step", step=child_step, edges=())},
        entry="resolve_step",
    )

    def _promote(state: dict[str, Any]) -> str:
        return "proceed" if state.get("current_state") == "critiqued" else "escalate"

    subloop, escape_edge = escalate_via_subpipeline(
        condition=lambda s: True,
        deadlock_pipeline=child,
        promote=_promote,
        name="escalate_sub",
        artifact_subdir="escalate_artifacts",
    )

    # ── Tiebreaker panel ──
    reviewer_proceed = _VerdictStep(name="reviewer_1", recommendation="proceed")
    reviewer_iterate = _VerdictStep(name="reviewer_2", recommendation="iterate")
    tiebreaker_panel = ParallelStage(
        name="tiebreaker_panel",
        steps=(reviewer_proceed, reviewer_iterate),
        join=majority_vote(default_on_tie="tiebreaker"),
        edges=(Edge(label="tiebreaker", target="halt"),),
    )

    # ── Critique-revise-gate loop ──
    critique_step = _FixedNextStep(name="critique", _next="gate")
    gate_step = _VerdictStep(name="gate", recommendation=gate_recommendation)
    revise_step = _FixedNextStep(name="revise", _next="critique")

    stages = critique_revise_gate_loop(
        critique_step=critique_step,
        gate_step=gate_step,
        revise_step=revise_step,
        on_proceed="halt",
        on_iterate="revise",
        on_tiebreaker="tiebreaker_panel",
        on_escalate="escalate_sub",
    )

    # ── Assemble full pipeline ──
    # Add the escalate_sub stage (wrapping the SubloopStep) and the
    # tiebreaker panel.  Append the escape edge to the gate stage per
    # escalate_via_subpipeline's contract.
    escalate_stage = Stage(
        name="escalate_sub",
        step=subloop,
        edges=(Edge(label="proceed", target="halt"),),
    )

    # The gate stage gets the escape edge appended.
    gate_stage = stages["gate"]
    gate_stage = Stage(
        name=gate_stage.name,
        step=gate_stage.step,
        edges=tuple(gate_stage.edges) + (escape_edge,),
    )

    all_stages: dict[str, Stage | ParallelStage] = {
        **stages,
        "gate": gate_stage,
        "escalate_sub": escalate_stage,
        "tiebreaker_panel": tiebreaker_panel,
    }

    pipeline = Pipeline(stages=all_stages, entry="critique")

    # ── Trace it ──
    plan_dir = Path("/tmp/oracle_gate_trace")
    plan_dir.mkdir(parents=True, exist_ok=True)

    ctx = StepContext(plan_dir=plan_dir, state={}, profile=None, mode="test")
    trace = _trace_pipeline(pipeline, ctx, artifact_root=plan_dir)

    return pipeline, trace


# ── Tests ──────────────────────────────────────────────────────────────


@pytest.fixture(autouse=True)
def _set_unified_dispatch_flag(monkeypatch: pytest.MonkeyPatch) -> None:
    """Ensure MEGAPLAN_UNIFIED_DISPATCH=1 for the oracle gate tests."""
    monkeypatch.setenv("MEGAPLAN_UNIFIED_DISPATCH", "1")


def _load_fixture(path: Path) -> list[tuple[str, str, str, str | None]]:
    """Load a JSON fixture and return list of trace tuples."""
    data = json.loads(path.read_text())
    return [tuple(item) for item in data]  # type: ignore[return-value]


class TestOracleGateEscalate:
    """Escalate path: gate emits ``"escalate"`` → escalate_sub → halt."""

    def test_escalate_trace_matches_fixture(self) -> None:
        _pipeline, actual_trace = _build_composed_pipeline(gate_recommendation="escalate")
        expected_trace = _load_fixture(ESCALATE_FIXTURE)
        assert actual_trace == expected_trace, (
            f"Escalate trace mismatch.\n"
            f"Expected: {expected_trace}\n"
            f"Actual:   {actual_trace}"
        )


class TestOracleGateTiebreaker:
    """Tiebreaker path: gate emits ``"tiebreaker"`` → panel vote → tie → halt."""

    def test_tiebreaker_trace_matches_fixture(self) -> None:
        _pipeline, actual_trace = _build_composed_pipeline(gate_recommendation="tiebreaker")
        expected_trace = _load_fixture(TIEBREAKER_FIXTURE)
        assert actual_trace == expected_trace, (
            f"Tiebreaker trace mismatch.\n"
            f"Expected: {expected_trace}\n"
            f"Actual:   {actual_trace}"
        )
