/**
 * Asset metadata — portable public contracts.
 *
 * Exports asset integrity, GPS, consent, provenance, enrichment,
 * parser metadata, and related public SDK shapes consumed by
 * parser, search, and output-format declarations.
 *
 * All contracts are data-only types and read-only surfaces; no
 * registry, provider, resolver, upload, or storage behaviour lives here.
 *
 * @publicContract
 */

// ---------------------------------------------------------------------------
// M6: Asset metadata types
// ---------------------------------------------------------------------------

/**
 * Integrity metadata for an asset (checksum, algorithm, byte size).
 * Host-owned top-level shape under `AssetMetadata.integrity`.
 */
export interface AssetIntegrityMetadata {
  /** Checksum algorithm (e.g. 'sha256'). */
  algorithm: string;
  /** Hex-encoded checksum digest. */
  hash: string;
  /** File size in bytes. */
  size: number;
}

/**
 * GPS / geolocation metadata extracted from asset headers.
 * Host-owned top-level shape under `AssetMetadata.gps`.
 */
export interface AssetGPSMetadata {
  /** Latitude in decimal degrees (WGS84). */
  latitude?: number;
  /** Longitude in decimal degrees (WGS84). */
  longitude?: number;
  /** Altitude in metres above WGS84 ellipsoid. */
  altitude?: number;
  /** GPS timestamp if available (epoch ms). */
  timestamp?: number;
}

/**
 * Consent / rights metadata for an asset.
 * Host-owned top-level shape under `AssetMetadata.consent`.
 */
export interface AssetConsentMetadata {
  /** Human-readable source attribution. */
  source?: string;
  /** Consent / rights note (e.g. 'CC BY 4.0', 'all rights reserved'). */
  rightsNote?: string;
  /** Whether consent has been explicitly recorded. */
  consentRecorded?: boolean;
  /** ISO 8601 timestamp when consent was recorded. */
  consentTimestamp?: string;
}

/**
 * Provenance metadata describing where an asset came from.
 * Host-owned top-level shape under `AssetMetadata.provenance`.
 */
export interface AssetProvenanceMetadata {
  /** Human-readable origin description. */
  origin?: string;
  /** ID of the asset this was derived from, if any. */
  derivedFromAssetId?: string;
  /** Whether this asset was generated by AI/ML. */
  generated?: boolean;
  /** ISO 8601 capture or import timestamp. */
  capturedAt?: string;
  /** ISO 8601 import timestamp. */
  importedAt?: string;
}

/**
 * Enrichment status lifecycle state machine.
 *
 *   pending   → record created, not yet claimed
 *   claimed   → claimed by an extension/agent for processing
 *   resolving → processing in progress
 *   resolved  → enrichment completed successfully
 *   failed    → enrichment failed with a diagnostic
 *   expired   → enrichment timed out or was cancelled
 */
export type EnrichmentStatus =
  | 'pending'
  | 'claimed'
  | 'resolving'
  | 'resolved'
  | 'failed'
  | 'expired';

/**
 * A deferred enrichment record persisted inside asset metadata.
 *
 * Parsers that need ML inference may emit deferred enrichment records
 * instead of blocking ingestion.  The record carries an asset reference,
 * enrichment kind, input parameters, status, and owning extension.
 * M6 persists and displays the shape; M10/M12 activate claim/resolve
 * execution through agent/process contracts.
 */
export interface DeferredEnrichmentRecord {
  /** Unique record identifier. */
  id: string;
  /** The asset this enrichment targets. */
  assetId: string;
  /** Enrichment kind (e.g. 'embedding', 'caption', 'object-detection'). */
  kind: string;
  /** Input parameters for the enrichment process. */
  input?: Record<string, unknown>;
  /** Current lifecycle state. */
  status: EnrichmentStatus;
  /** The extension that owns this enrichment record. */
  extensionId: string;
  /** Contribution ID within the extension, if any. */
  contributionId?: string;
  /** ISO 8601 timestamp when the record was created. */
  createdAt: string;
  /** ISO 8601 timestamp when the record was last updated. */
  updatedAt: string;
  /** Diagnostic message when status is 'failed' or 'expired'. */
  diagnostic?: string;
  /** Enrichment output when status is 'resolved'. */
  output?: Record<string, unknown>;
}

/**
 * Top-level asset metadata shape persisted in AssetRegistryEntry.
 *
 * Host-owned keys (integrity, gps, consent, provenance, enrichment) are
 * at the top level.  Extension-owned metadata is namespaced under
 * `extensions[extensionId]`.
 */
export interface AssetMetadata {
  /** Integrity / checksum metadata. */
  integrity?: AssetIntegrityMetadata;
  /** GPS / geolocation metadata. */
  gps?: AssetGPSMetadata;
  /** Consent / rights metadata. */
  consent?: AssetConsentMetadata;
  /** Provenance / origin metadata. */
  provenance?: AssetProvenanceMetadata;
  /**
   * Extension-owned metadata namespaced by extension ID.
   * Extensions may store arbitrary structured data under their own key.
   */
  extensions?: Record<string, Record<string, unknown>>;
  /**
   * Deferred enrichment records for this asset.
   * Parsers may enqueue enrichment tasks without blocking ingestion.
   */
  enrichment?: readonly DeferredEnrichmentRecord[];
}

// ---------------------------------------------------------------------------
// M6: Metadata facet descriptors
// ---------------------------------------------------------------------------

/**
 * The value kind of a metadata facet field.
 *
 * Determines how the host renders filter/aggregation UI for the facet.
 */
export type MetadataFacetValueKind =
  | 'string'
  | 'number'
  | 'boolean'
  | 'date'
  | 'enum';

/**
 * A descriptor that tells the host how to surface a metadata field
 * as a searchable/filterable facet in the asset panel.
 *
 * The host owns facet rendering and aggregation; extensions provide
 * the descriptor and the metadata values.
 */
export interface MetadataFacetDescriptor {
  /**
   * Dot-separated path to the metadata field.
   * E.g. 'gps.latitude', 'integrity.algorithm', 'extensions.myExt.tags'.
   */
  fieldPath: string;
  /** Human-readable display name for the facet. */
  displayName: string;
  /** The value kind — determines rendering and filtering strategy. */
  valueKind: MetadataFacetValueKind;
  /**
   * Sort order for this facet relative to others (lower = first).
   * Default 0.
   */
  order?: number;
  /**
   * Aggregation posture hint for the host.
   * - `exact` — values should be surfaced individually
   * - `range` — numeric values can be bucketed
   * - `presence` — only show whether the field exists
   */
  aggregationPosture?: 'exact' | 'range' | 'presence';
  /**
   * Allowed values when `valueKind` is 'enum'.
   * The host uses this for dropdown/checkbox filter UI.
   */
  enumValues?: readonly string[];
}

// ---------------------------------------------------------------------------
// M6: Asset detail section descriptors
// ---------------------------------------------------------------------------

/**
 * A descriptor for a named section slot inside the asset detail panel.
 *
 * Asset detail sections are named slots within the asset panel (not whole
 * replacement panels).  The host owns section placement, empty/error states,
 * search result badges, and provenance-chain rendering.  Extensions provide
 * section descriptors to declare what metadata they surface.
 */
export interface AssetDetailSectionDescriptor {
  /** Unique section identifier within the extension. */
  id: string;
  /** Human-readable section title. */
  title: string;
  /**
   * Placement within the asset detail panel.
   * - `before-default` — before host-owned metadata sections
   * - `after-default` — after host-owned metadata sections
   */
  placement: 'before-default' | 'after-default';
  /**
   * The metadata field paths this section reads.
   * The host uses these to determine section visibility and data binding.
   */
  fieldPaths?: readonly string[];
  /** Lower values sort first within their placement group. Default 0. */
  order?: number;
  /**
   * Optional visibility predicate (evaluated by host).
   * E.g. 'asset.metadata.integrity != null'.
   */
  when?: string;
}

// SearchMatch, SearchProviderResult, SearchProviderHandler, and SearchProviderContext
// are now defined in src/sdk/video/assets/search.ts.
// (M2b extraction)

// ---------------------------------------------------------------------------
// M6: Asset read surface
// ---------------------------------------------------------------------------

/**
 * Read-only asset metadata surface exposed to extension code.
 *
 * Extensions can query asset metadata by key and list all asset keys
 * known to the registry.  This is a read-only projection — no mutation
 * or persistence surface is exposed.
 */
export interface AssetReadSurface {
  /**
   * Get metadata for a single asset by its registry key.
   * Returns undefined if the asset is not found.
   */
  get(assetKey: string): Readonly<AssetMetadata> | undefined;

  /**
   * List all asset keys known to the registry.
   */
  keys(): readonly string[];

  /**
   * Check whether an asset key exists in the registry.
   */
  has(assetKey: string): boolean;

  /**
   * Search assets by a metadata field path and value.
   * Returns matching asset keys.  Bounded to exact field matches
   * on host-owned metadata fields; extension-owned fields may be
   * searched only when a search provider is active.
   */
  search(fieldPath: string, value: string): readonly string[];
}

/**
 * Read-only material metadata surface exposed to extension code.
 *
 * Materials reference assets with additional media-specific metadata
 * (resolution, frame rate, codec, etc.).  This is a read-only projection.
 */
export interface MaterialReadSurface {
  /**
   * Get material metadata by its registry key.
   * Returns undefined if the material is not found.
   */
  get(materialKey: string): Readonly<Record<string, unknown>> | undefined;

  /**
   * List all material keys known to the registry.
   */
  keys(): readonly string[];

  /**
   * Check whether a material key exists in the registry.
   */
  has(materialKey: string): boolean;
}


