"""Security broker contracts and helpers."""

from arnold.security.audit import (
    BrokerAuditEntry,
    claim_broker_audit_entry,
    record_broker_audit_entry,
)
from arnold.security.broker_client import (
    BROKER_SOCKET_ENV,
    BROKER_URL_ENV,
    BrokerClient,
    BrokerClientError,
    fail_closed_result,
)
from arnold.security.broker_service import (
    DEFAULT_COVERED_SECRET_NAMES,
    PROTOCOL_VERSION,
    BrokerSecretStore,
    BrokerService,
    BrokerServiceError,
    UnixBrokerServer,
    serve_unix,
)
from arnold.security.coverage_matrix import (
    CoverageEntry,
    CoverageStatus,
    ResidualRisk,
    get_coverage_matrix,
    get_covered_surfaces,
    get_high_risk_deferrals,
    get_uncovered_surfaces,
)
from arnold.security.git import (
    McpGitAuthorization,
    authorize_mcp_git_action,
    build_mcp_git_action_request,
)
from arnold.security.llm_proxy import (
    BROKER_LLM_PROXY_BASE_URL_ENV,
    BROKER_PRODUCTION_ENV,
    COVERED_OPENAI_COMPATIBLE_PROVIDERS,
    DEFERRED_OAUTH_PROVIDERS,
    LLM_PROXY_BASE_URL_ENV,
    LlmProxyCredential,
    LlmProxyUnavailable,
    broker_llm_proxy_base_url,
    broker_production_mode_requested,
    covered_openai_compatible_provider,
    resolve_brokered_llm_proxy,
    warn_deferred_oauth_provider,
)
from arnold.security.policy import (
    DEFAULT_APPROVAL_REQUIRED_ACTIONS,
    DEFAULT_PROTECTED_BRANCHES,
    SecurityPolicy,
    normalize_branch_name,
)
from arnold.security.redaction import (
    REDACTED,
    is_sensitive_key,
    redact_mapping,
    redact_text,
    redact_value,
)
from arnold.security.types import (
    ActionRequest,
    ActionResult,
    ActionVerdict,
    RedactionStatus,
    RetentionPolicy,
)

__all__ = [
    "ActionRequest",
    "ActionResult",
    "ActionVerdict",
    "BROKER_LLM_PROXY_BASE_URL_ENV",
    "BROKER_PRODUCTION_ENV",
    "BROKER_SOCKET_ENV",
    "BROKER_URL_ENV",
    "BrokerAuditEntry",
    "BrokerClient",
    "BrokerClientError",
    "BrokerSecretStore",
    "BrokerService",
    "BrokerServiceError",
    "CoverageEntry",
    "CoverageStatus",
    "COVERED_OPENAI_COMPATIBLE_PROVIDERS",
    "DEFERRED_OAUTH_PROVIDERS",
    "DEFAULT_COVERED_SECRET_NAMES",
    "DEFAULT_APPROVAL_REQUIRED_ACTIONS",
    "DEFAULT_PROTECTED_BRANCHES",
    "McpGitAuthorization",
    "PROTOCOL_VERSION",
    "LLM_PROXY_BASE_URL_ENV",
    "LlmProxyCredential",
    "LlmProxyUnavailable",
    "REDACTED",
    "RedactionStatus",
    "ResidualRisk",
    "RetentionPolicy",
    "SecurityPolicy",
    "UnixBrokerServer",
    "authorize_mcp_git_action",
    "broker_llm_proxy_base_url",
    "broker_production_mode_requested",
    "build_mcp_git_action_request",
    "claim_broker_audit_entry",
    "covered_openai_compatible_provider",
    "fail_closed_result",
    "get_coverage_matrix",
    "get_covered_surfaces",
    "get_high_risk_deferrals",
    "get_uncovered_surfaces",
    "is_sensitive_key",
    "normalize_branch_name",
    "redact_mapping",
    "redact_text",
    "redact_value",
    "record_broker_audit_entry",
    "resolve_brokered_llm_proxy",
    "serve_unix",
    "warn_deferred_oauth_provider",
]
