"""Project-level custody helpers for future worktree execute support."""

from __future__ import annotations

from .paths import (
    CustodyPaths,
    custody_paths,
    ensure_megaplan_worktrees_ignored,
    scratch_task_worktree_path,
    scratch_worktree_path,
    scratch_worktree_root_path,
    validate_run_id,
    validate_task_id,
)
from .identity import (
    TASK_ID_TRAILER_ENCODING,
    TASK_KEY_SCHEMA_VERSION,
    TaskIdentity,
    TaskIdentityError,
    build_task_identity_map,
    decode_original_task_id,
    encode_original_task_id,
    identity_map_payload,
    make_task_identity,
    validate_task_key,
    validate_trailer_identity,
)
from .lifecycle import (
    DEFAULT_CONTEXT_FILES,
    TaskWorktreeLifecycleError,
    TaskWorktreeRecord,
    prepare_task_worktree,
)
from .integration import (
    TaskIntegrationError,
    TaskIntegrationResult,
    integrate_task_patch,
)
from .recovery import (
    TaskRecoveryError,
    TaskRecoveryResult,
    reconcile_task_integration,
)
from .patches import (
    DIFF_FLAGS,
    PatchBundleRecord,
    PatchCaptureError,
    PatchCaptureResult,
    SECRET_SCAN_MODES,
    capture_patch_bundle,
    git_apply_check_bundle,
    load_patch_bundle,
    patch_bundle_dir,
    patch_manifest_path,
    patch_payload_path,
    patch_task_dir,
    prevalidate_patch_apply,
    validate_bundle_for_apply,
)
from .registry import (
    ANCHORED_TAIL_TRUNCATION,
    BROKEN_CHAIN,
    DIGEST_MISMATCH,
    LOCK_FAILURE,
    MALFORMED_JSON,
    MISSING_ANCHOR,
    MISSING_REGISTRY,
    WRITE_FAILURE,
    IDENTITY_MISMATCH,
    RegistryError,
    RegistryValidation,
    RegistryValidationError,
    append_registry_entry,
    read_registry_entries,
    registry_head_path,
    registry_jsonl_path,
    registry_lock_path,
    validate_registry,
)
from .report import (
    build_custody_report,
    custody_report_dir,
    custody_report_path,
    custody_report_run_dir,
)
from .secrets import GITLEAKS_POLICY_NAME, SecretScanError, run_gitleaks_policy, secret_scan_report_path

__all__ = [
    "CustodyPaths",
    "ANCHORED_TAIL_TRUNCATION",
    "BROKEN_CHAIN",
    "DIGEST_MISMATCH",
    "DIFF_FLAGS",
    "DEFAULT_CONTEXT_FILES",
    "GITLEAKS_POLICY_NAME",
    "IDENTITY_MISMATCH",
    "LOCK_FAILURE",
    "MALFORMED_JSON",
    "MISSING_ANCHOR",
    "MISSING_REGISTRY",
    "PatchCaptureError",
    "PatchCaptureResult",
    "PatchBundleRecord",
    "RegistryError",
    "RegistryValidation",
    "RegistryValidationError",
    "SECRET_SCAN_MODES",
    "TASK_ID_TRAILER_ENCODING",
    "TASK_KEY_SCHEMA_VERSION",
    "SecretScanError",
    "TaskIdentity",
    "TaskIdentityError",
    "TaskIntegrationError",
    "TaskIntegrationResult",
    "TaskRecoveryError",
    "TaskRecoveryResult",
    "TaskWorktreeLifecycleError",
    "TaskWorktreeRecord",
    "WRITE_FAILURE",
    "append_registry_entry",
    "build_task_identity_map",
    "build_custody_report",
    "capture_patch_bundle",
    "custody_paths",
    "decode_original_task_id",
    "encode_original_task_id",
    "custody_report_dir",
    "custody_report_path",
    "custody_report_run_dir",
    "ensure_megaplan_worktrees_ignored",
    "git_apply_check_bundle",
    "identity_map_payload",
    "integrate_task_patch",
    "load_patch_bundle",
    "make_task_identity",
    "patch_bundle_dir",
    "patch_manifest_path",
    "patch_payload_path",
    "patch_task_dir",
    "prevalidate_patch_apply",
    "prepare_task_worktree",
    "reconcile_task_integration",
    "read_registry_entries",
    "registry_head_path",
    "registry_jsonl_path",
    "registry_lock_path",
    "scratch_worktree_path",
    "scratch_task_worktree_path",
    "scratch_worktree_root_path",
    "secret_scan_report_path",
    "run_gitleaks_policy",
    "validate_run_id",
    "validate_task_key",
    "validate_bundle_for_apply",
    "validate_registry",
    "validate_task_id",
    "validate_trailer_identity",
]
