from __future__ import annotations

from vibecomfy.registry.ready_template import build_api_ready_workflow


API_WORKFLOW = {'105': {'class_type': 'DualCLIPLoader',
         'inputs': {'clip_name1': 'qwen_0.6b_ace15.safetensors',
                    'clip_name2': 'qwen_4b_ace15.safetensors',
                    'type': 'ace',
                    'device': 'default'}},
 '106': {'class_type': 'VAELoader', 'inputs': {'vae_name': 'ace_1.5_vae.safetensors'}},
 '122': {'class_type': 'EmptyAceStep1.5LatentAudio', 'inputs': {'seconds': 2, 'batch_size': 1}},
 '47': {'class_type': 'ConditioningZeroOut', 'inputs': {'conditioning': ['124', 0]}},
 '3': {'class_type': 'KSampler',
       'inputs': {'seed': 561594583201063,
                  'steps': 1,
                  'cfg': 1,
                  'sampler_name': 'euler',
                  'scheduler': 'simple',
                  'denoise': 1,
                  'model': ['78', 0],
                  'positive': ['124', 0],
                  'negative': ['47', 0],
                  'latent_image': ['122', 0]}},
 '78': {'class_type': 'ModelSamplingAuraFlow', 'inputs': {'shift': 3, 'model': ['125', 0]}},
 '123': {'class_type': 'VAEDecodeAudio', 'inputs': {'samples': ['3', 0], 'vae': ['106', 0]}},
 '124': {'class_type': 'TextEncodeAceStepAudio1.5',
         'inputs': {'seed': 561594583201063,
                    'duration': 2,
                    'tags': 'synthwave, short instrumental',
                    'lyrics': 'Verse\nTiny signal in the night.',
                    'bpm': 120,
                    'timesignature': '4',
                    'language': 'en',
                    'keyscale': 'E minor',
                    'generate_audio_codes': True,
                    'cfg_scale': 1.5,
                    'top_p': 0.85,
                    'min_p': 0.9,
                    'top_k': 0,
                    'temperature': 0,
                    'clip': ['105', 0]}},
 '125': {'class_type': 'UNETLoader',
         'inputs': {'unet_name': 'acestep_v1.5_turbo.safetensors', 'weight_dtype': 'default'}},
 '59': {'class_type': 'SaveAudioMP3',
        'inputs': {'filename_prefix': 'audio/vibecomfy_ace_step_smoke', 'quality': 'V0', 'audio': ['123', 0]}}}

READY_METADATA = {'model_assets': [{'name': 'qwen_0.6b_ace15.safetensors',
                   'url': 'https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/text_encoders/qwen_0.6b_ace15.safetensors',
                   'subdir': 'text_encoders'},
                  {'name': 'qwen_4b_ace15.safetensors',
                   'url': 'https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/text_encoders/qwen_4b_ace15.safetensors',
                   'subdir': 'text_encoders'},
                  {'name': 'ace_1.5_vae.safetensors',
                   'url': 'https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/vae/ace_1.5_vae.safetensors',
                   'subdir': 'vae'},
                  {'name': 'acestep_v1.5_turbo.safetensors',
                   'url': 'https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/diffusion_models/acestep_v1.5_turbo.safetensors',
                   'subdir': 'diffusion_models'}],
 'unbound_inputs': {'seed': 3020},
 'ready_template': 'audio/ace_step_1_5_t2a_song',
 'workflow_template': 'ace_step_1_5_t2a_song',
 'capability': 'text_to_audio_song',
 'source_role': 'materialized_ready_python_template',
 'source_workflow': 'workflow_corpus/official/audio/ace_step_1_5_t2a_song.json',
 'coverage_tier': 'required',
 'approach': 'ACE-Step 1.5 text-to-audio song generation',
 'runtime_note': 'Official subgraph materialized to API-shaped nodes for VibeComfy smoke execution.',
 'discord_signal': None,
 'smoke_duration_seconds': 2,
 'subgraph_materialized': True}

READY_REQUIREMENTS = {'models': [{'name': 'qwen_0.6b_ace15.safetensors',
             'url': 'https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/text_encoders/qwen_0.6b_ace15.safetensors',
             'subdir': 'text_encoders'},
            {'name': 'qwen_4b_ace15.safetensors',
             'url': 'https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/text_encoders/qwen_4b_ace15.safetensors',
             'subdir': 'text_encoders'},
            {'name': 'ace_1.5_vae.safetensors',
             'url': 'https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/vae/ace_1.5_vae.safetensors',
             'subdir': 'vae'},
            {'name': 'acestep_v1.5_turbo.safetensors',
             'url': 'https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/diffusion_models/acestep_v1.5_turbo.safetensors',
             'subdir': 'diffusion_models'}],
 'custom_nodes': ['EmptyAceStep1', 'TextEncodeAceStepAudio1']}


def build():
    return build_api_ready_workflow(
        API_WORKFLOW,
        source_path=__file__,
        workflow_id=READY_METADATA.get("ready_template", "audio/ace_step_1_5_t2a_song"),
        ready_metadata=READY_METADATA,
        requirements=READY_REQUIREMENTS,
    )
