# vibecomfy: manual
# Promoted during sprint 7 to preserve snapshot parity while curating public output contracts.
"""Auto-generated ready_template — see tools/convert_ready_templates.py."""
from __future__ import annotations

from vibecomfy.workflow import VibeWorkflow
from vibecomfy.templates import InputSpec, ModelAsset, ReadyMetadata, finalize, new_workflow, node

PRIVATE_KNOBS: dict[str, object] = {
    'scheduler': 'simple',
    'denoise': 1,
}

MODELS = {
    'qwen_0_6b_ace15': ModelAsset(
        filename='qwen_0.6b_ace15.safetensors',
        url='https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/text_encoders/qwen_0.6b_ace15.safetensors',
        subdir='text_encoders',
    ),
    'qwen_4b_ace15': ModelAsset(
        filename='qwen_4b_ace15.safetensors',
        url='https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/text_encoders/qwen_4b_ace15.safetensors',
        subdir='text_encoders',
    ),
    'ace_1_5_vae': ModelAsset(
        filename='ace_1.5_vae.safetensors',
        url='https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/vae/ace_1.5_vae.safetensors',
        subdir='vae',
    ),
    'acestep_v1_5_turbo': ModelAsset(
        filename='acestep_v1.5_turbo.safetensors',
        url='https://huggingface.co/Comfy-Org/ace_step_1.5_ComfyUI_files/resolve/main/split_files/diffusion_models/acestep_v1.5_turbo.safetensors',
        subdir='diffusion_models',
    ),
}

PUBLIC_INPUTS = {
    'lyrics': InputSpec(node='124', field='lyrics', default='Verse\nTiny signal in the night.', type='STRING', required=True, description='Song lyrics.', media_semantics='text'),
    'tags': InputSpec(node='124', field='tags', default='synthwave, short instrumental', type='STRING', description='Style tags.', media_semantics='text'),
    'duration': InputSpec(node='124', field='duration', default=2, type='FLOAT', description='Duration in seconds.'),
    'bpm': InputSpec(node='124', field='bpm', default=120, type='INT', description='Tempo in beats per minute.'),
    'seed': InputSpec(node='124', field='seed', default=561594583201063, type='INT', description='Random seed.'),
    'steps': InputSpec(node='3', field='steps', default=1, type='INT', description='Sampling steps.'),
    'cfg': InputSpec(node='3', field='cfg', default=1, type='INT', description='Classifier-free guidance scale.'),
    'sampler_name': InputSpec(node='3', field='sampler_name', default='euler', type='STRING', description='Sampler algorithm.'),
    'seed_2': InputSpec(node='3', field='seed', default=561594583201063, type='INT', aliases=('noise_seed',), description='Secondary random seed.'),
}

OUTPUT_PREFIX = 'audio/vibecomfy_ace_step_smoke'

READY_REQUIREMENTS: dict[str, object] = {
    'custom_nodes': ['EmptyAceStep1', 'TextEncodeAceStepAudio1'],
}

# generated by vibecomfy port convert; see READY_METADATA["provenance"]
READY_METADATA = ReadyMetadata.build(
    template_id='ace_step_1_5_t2a_song',
    capability='text_to_audio_song',
    inputs=PUBLIC_INPUTS,
    models=MODELS,
    output_prefix=OUTPUT_PREFIX,
    provenance={'source_workflow': 'workflow_corpus/official/audio/ace_step_1_5_t2a_song.json', 'approach': 'ACE-Step 1.5 text-to-audio song generation', 'source_role': 'materialized_ready_python_template'},
    coverage_tier='required',
    runtime_note='Official subgraph materialized to API-shaped nodes for VibeComfy smoke execution.',
    smoke_duration_seconds=2,
    subgraph_materialized=True,
)

READY_METADATA["unbound_inputs"].update({'bpm': '124.bpm', 'duration': '124.duration', 'lyrics': '124.lyrics', 'seed': '124.seed', 'steps': '3.steps', 'tags': '124.tags'})

def build() -> VibeWorkflow:
    """Build the workflow (auto-generated)."""
    wf = new_workflow(READY_METADATA, source_path=__file__)

    # ════ LOADERS ════
    text_encoder = node(wf, 'DualCLIPLoader', '105',
        clip_name1=MODELS['qwen_0_6b_ace15'].filename,
        clip_name2=MODELS['qwen_4b_ace15'].filename,
        type='ace',
        device='default',
    )
    vae = node(wf, 'VAELoader', '106',
        vae_name=MODELS['ace_1_5_vae'].filename,
    )
    # ════ LATENT ════
    empty_audio_latent = node(wf, 'EmptyAceStep1.5LatentAudio', '122',
        batch_size=1,
        seconds=2,
    )
    base_diffusion_model = node(wf, 'UNETLoader', '125',
        unet_name=MODELS['acestep_v1_5_turbo'].filename,
        weight_dtype='default',
    )
    # ════ SAMPLING ════
    model_sampling = node(wf, 'ModelSamplingAuraFlow', '78',
        shift=3,
        model=base_diffusion_model.out('MODEL'),
    )
    # ════ TEXT CONDITIONING ════
    positive_conditioning = node(wf, 'TextEncodeAceStepAudio1.5', '124',
        bpm=PUBLIC_INPUTS['bpm'].default,
        cfg_scale=1.5,
        duration=PUBLIC_INPUTS['duration'].default,
        generate_audio_codes=True,
        keyscale='E minor',
        language='en',
        lyrics=PUBLIC_INPUTS['lyrics'].default,
        min_p=0.9,
        seed=PUBLIC_INPUTS['seed'].default,
        tags=PUBLIC_INPUTS['tags'].default,
        temperature=0,
        timesignature='4',
        top_k=0,
        top_p=0.85,
        clip=text_encoder.out('CLIP'),
    )
    negative_conditioning = node(wf, 'ConditioningZeroOut', '47',
        conditioning=positive_conditioning.out('CONDITIONING'),
    )
    sampler = node(wf, 'KSampler', '3',
        seed=PUBLIC_INPUTS['seed_2'].default,
        steps=PUBLIC_INPUTS['steps'].default,
        cfg=PUBLIC_INPUTS['cfg'].default,
        sampler_name=PUBLIC_INPUTS['sampler_name'].default,
        scheduler=PRIVATE_KNOBS['scheduler'],
        denoise=PRIVATE_KNOBS['denoise'],
        latent_image=empty_audio_latent.out('LATENT'),
        model=model_sampling.out('MODEL'),
        negative=negative_conditioning.out('CONDITIONING'),
        positive=positive_conditioning.out('CONDITIONING'),
    )
    # ════ DECODE ════
    decoded_audio = node(wf, 'VAEDecodeAudio', '123',
        samples=sampler.out('LATENT'),
        vae=vae.out('VAE'),
    )
    # ════ OUTPUT ════
    save_audio = node(wf, 'SaveAudioMP3', '59',
        filename_prefix=OUTPUT_PREFIX,
        quality='V0',
        audio=decoded_audio.out('AUDIO'),
    )

    return finalize(
        wf,
        PUBLIC_INPUTS,
        READY_METADATA,
        output_node='59',
        output_type='SaveAudioMP3',
        name='audio',
        mime_type='audio/mpeg',
        expected_cardinality='one',
        filename_prefix=OUTPUT_PREFIX,
        source_path=__file__,
        requirements=READY_REQUIREMENTS,
    )

