#!/usr/bin/env python
"""Generate Arnold reference docs from code-owned contracts."""

from __future__ import annotations

import argparse
import ast
import contextlib
import dataclasses
import difflib
import inspect
import io
import re
import sys
import types
from pathlib import Path
from typing import Annotated, Any, Iterable, Union, get_args, get_origin

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

from megaplan._pipeline import registry
from megaplan._pipeline.behavioral_manifest import (
    RuntimeTopologyProjection,
    StaticBehavioralInput,
    StaticBehavioralManifest,
    UnresolvedDynamicInput,
)
from megaplan._pipeline import contracts, validator
from megaplan._pipeline.discovery import manifest as discovery_manifest
from megaplan._pipeline import judge_manifest, judge_manifest_discovery
from megaplan._pipeline.types import (
    CONTENT_TYPES,
    EdgeKind,
    GateRecommendation,
    OverrideAction,
    Port,
    PortRef,
    RoutingKey,
)
from megaplan.cli import arnold as arnold_cli
from megaplan.cli.parser import build_parser
from megaplan import control_interface
from megaplan.control_interface import (
    CONTROL_TARGET_ABORT,
    CONTROL_TARGET_FORCE_ADVANCE,
    CONTROL_TARGET_RECOVER_FROM_STUCK,
    CONTROL_TARGET_REROUTE,
)
from megaplan.run_outcome import RunOutcome
from megaplan.schemas import (
    Capsule,
    CapsuleContract,
    CapsuleDefinition,
    CapsuleEvidence,
    CapsuleLineage,
    Warrant,
    WarrantAccount,
    WarrantAuthority,
    WarrantRationaleAnchor,
    WarrantSignature,
    WarrantSourceCompleteness,
    WarrantSourceProjection,
)
from megaplan import quality_resolutions, user_actions
from megaplan import types as megaplan_types


DEFAULT_DOCS_ROOT = REPO_ROOT / "docs"
REFERENCE_PATH = Path("reference/arnold-projections.md")
EXAMPLES_DIR = Path("arnold/examples")
GENERATED_HEADER = """\
<!--
This file is generated by scripts/generate_arnold_docs.py.
Do not edit by hand; run `python scripts/generate_arnold_docs.py --write`.
-->
"""

PROJECTION_MODELS = (
    Capsule,
    CapsuleContract,
    CapsuleDefinition,
    CapsuleEvidence,
    CapsuleLineage,
    Warrant,
    WarrantAccount,
    WarrantAuthority,
    WarrantRationaleAnchor,
    WarrantSignature,
    WarrantSourceCompleteness,
    WarrantSourceProjection,
)

BEHAVIORAL_MANIFEST_MODELS = (
    RuntimeTopologyProjection,
    StaticBehavioralInput,
    StaticBehavioralManifest,
    UnresolvedDynamicInput,
)

TYPED_PORT_MODELS = (
    Port,
    PortRef,
    RoutingKey,
)

PACKAGE_CONTRACT_FACTS = {
    "api_version_range": (
        "arnold_api_version must be major.minor with 1 <= major < "
        f"{discovery_manifest.CURRENT_MAJOR}."
    ),
    "manifest_reader": (
        "Pipeline manifests are parsed with ast.parse and ast.literal_eval; "
        "the module is not imported during manifest reads."
    ),
    "package_module_skill": (
        "Package pipelines use <pipeline>/__init__.py and require a sibling SKILL.md."
    ),
    "scan_statuses": "Pipeline discovery dispositions are discovered, rejected, or skipped.",
    "sibling_file_skill": (
        "Sibling-file pipelines use <name>.py; SKILL.md is read from a matching "
        "hyphenated resource directory when present, otherwise from the module directory."
    ),
}

DISCOVERY_FACTS = {
    "canonical_name_aliasing": "Registry names are canonicalized through _NAME_ALIASES.",
    "manifest_flag": "MEGAPLAN_M6_MANIFEST_DISCOVERY=1 enables manifest-first discovery.",
    "manifest_metadata": (
        "Manifest metadata includes arnold_api_version, capabilities, manifest_hash, "
        "source_path, manifest_origin, and trust_tier when available."
    ),
    "runtime_topology": (
        "Runtime topology is a separate trusted projection and name-based builds "
        "require allow_import=True."
    ),
    "static_behavioral_identity": (
        "Static behavioral identity includes source/SKILL/resource/helper file hashes, "
        "declared inputs, and unresolved dynamic inputs."
    ),
}


@dataclasses.dataclass(frozen=True)
class ExamplePack:
    """Source-owned Arnold worked example."""

    slug: str
    doc_slug: str
    title: str
    source_dir: Path
    required: bool
    init_symbols: tuple[str, ...]
    step_symbols: tuple[str, ...]
    notes: tuple[str, ...]


EXAMPLE_PACKS: tuple[ExamplePack, ...] = (
    ExamplePack(
        slug="jokes",
        doc_slug="jokes",
        title="Jokes Graph Pipeline",
        source_dir=REPO_ROOT / "megaplan" / "pipelines" / "jokes",
        required=True,
        init_symbols=(
            "name",
            "description",
            "driver",
            "entrypoint",
            "arnold_api_version",
            "capabilities",
            "STAGE_SPECS",
            "build_pipeline",
        ),
        step_symbols=("JokeStep",),
        notes=(
            "A minimal graph module: three stages, one local step class, and no planning gate vocabulary.",
            "The final stage writes the durable artifact path into state as `joke_artifact`.",
        ),
    ),
    ExamplePack(
        slug="planning",
        doc_slug="planning-as-composition",
        title="Planning as Composition",
        source_dir=REPO_ROOT / "megaplan" / "pipelines" / "planning",
        required=False,
        init_symbols=(
            "name",
            "description",
            "driver",
            "entrypoint",
            "arnold_api_version",
            "capabilities",
            "build_pipeline",
        ),
        step_symbols=(),
        notes=(
            "The built-in planning workflow is represented as the same discovered package shape as other Arnold modules.",
            "The critique/gate/revise loop is assembled by composition helpers and exposed through a regular `build_pipeline()` entrypoint.",
        ),
    ),
    ExamplePack(
        slug="select-tournament",
        doc_slug="select-tournament",
        title="Select Tournament Port Pipeline",
        source_dir=REPO_ROOT / "megaplan" / "pipelines" / "select-tournament",
        required=True,
        init_symbols=(
            "name",
            "description",
            "driver",
            "entrypoint",
            "arnold_api_version",
            "capabilities",
            "DEFAULT_CANDIDATES",
            "build_pipeline",
        ),
        step_symbols=(
            "SCORE_CONTENT_TYPE",
            "BRACKET_CONTENT_TYPE",
            "WINNER_CONTENT_TYPE",
            "CANDIDATE_SCORES_PORT",
            "BRACKET_RESULT_PORT",
            "WINNER_PORT",
            "CandidateScoreStep",
            "join_candidate_scores",
            "PairwiseBracketStep",
            "WinnerStep",
        ),
        notes=(
            "A non-planning pack with typed Port boundaries across fanout, reduction, and terminal artifact emission.",
            "This is the load-bearing example for builders who need cross-stage data contracts.",
        ),
    ),
)


def _literal_values(alias: Any) -> tuple[str, ...]:
    return tuple(str(value) for value in sorted(get_args(alias)))


def _source_path(obj: Any) -> str:
    return _relative(Path(inspect.getsourcefile(obj) or ""))


def _relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def _annotation_name(annotation: Any) -> str:
    if annotation is type(None):
        return "None"
    origin = get_origin(annotation)
    if origin is Annotated:
        args = get_args(annotation)
        return _annotation_name(args[0]) if args else "Annotated"
    if origin in {Union, types.UnionType}:
        return " | ".join(_annotation_name(arg) for arg in get_args(annotation))
    text = getattr(annotation, "__name__", None)
    if text:
        return text
    return str(annotation).replace("typing.", "")


def _default_description(field: Any) -> str:
    if field.is_required():
        return "required"
    if field.default_factory is not None:
        factory = getattr(field.default_factory, "__name__", repr(field.default_factory))
        return f"default_factory={factory}"
    return repr(field.default)


def _pydantic_field_rows(model: type[Any]) -> list[tuple[str, str, str]]:
    rows = []
    for name, field in sorted(model.model_fields.items()):
        rows.append((name, _annotation_name(field.annotation), _default_description(field)))
    return rows


def _dataclass_field_rows(model: type[Any]) -> list[tuple[str, str, str]]:
    rows = []
    for field in sorted(dataclasses.fields(model), key=lambda item: item.name):
        if field.default is not dataclasses.MISSING:
            default = repr(field.default)
        elif field.default_factory is not dataclasses.MISSING:  # type: ignore[comparison-overlap]
            factory = getattr(field.default_factory, "__name__", repr(field.default_factory))
            default = f"default_factory={factory}"
        else:
            default = "required"
        rows.append((field.name, _annotation_name(field.type), default))
    return rows


def _table(headers: tuple[str, ...], rows: Iterable[tuple[Any, ...]]) -> list[str]:
    def cell(value: Any) -> str:
        return str(value).replace("\n", " ").replace("|", "\\|")

    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(value) for value in row) + " |")
    return lines


def _node_name(node: ast.AST) -> str | None:
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
        return node.name
    if isinstance(node, ast.Assign):
        for target in node.targets:
            if isinstance(target, ast.Name):
                return target.id
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        return node.target.id
    return None


def _source_lines_for_symbols(path: Path, symbols: Iterable[str]) -> str:
    wanted = set(symbols)
    source = path.read_text(encoding="utf-8")
    lines = source.splitlines()
    tree = ast.parse(source, filename=str(path))
    ranges: list[tuple[int, int]] = []
    for node in tree.body:
        name = _node_name(node)
        if name not in wanted:
            continue
        end_lineno = getattr(node, "end_lineno", None)
        if end_lineno is None:
            continue
        ranges.append((node.lineno, end_lineno))
    ranges.sort()

    chunks: list[str] = []
    previous_end = 0
    for start, end in ranges:
        if chunks and start > previous_end + 1:
            chunks.append("")
        chunks.extend(lines[start - 1:end])
        previous_end = end
    return "\n".join(chunks).rstrip() + "\n"


def _pipeline_check_result(name: str) -> tuple[bool, str]:
    from argparse import Namespace

    from megaplan.cli import _handle_pipelines

    args = Namespace(pipelines_action="check", pipeline_name=name)
    stdout = io.StringIO()
    stderr = io.StringIO()
    with contextlib.redirect_stdout(stdout), contextlib.redirect_stderr(stderr):
        rc = _handle_pipelines(REPO_ROOT, args)
    details = "\n".join(
        part.strip()
        for part in (stdout.getvalue(), stderr.getvalue())
        if part.strip()
    )
    return rc == 0, details


def _example_pack_exists(pack: ExamplePack) -> bool:
    return (pack.source_dir / "__init__.py").is_file() and (
        pack.source_dir / "SKILL.md"
    ).is_file()


def _render_example(pack: ExamplePack) -> str | None:
    if not _example_pack_exists(pack):
        if pack.required:
            raise RuntimeError(f"required Arnold example pack is missing: {pack.slug}")
        return None

    check_ok, check_details = _pipeline_check_result(pack.slug)
    if not check_ok:
        if pack.required:
            raise RuntimeError(
                f"required Arnold example pack failed `megaplan pipelines check {pack.slug}`: "
                f"{check_details}"
            )
        return None

    init_path = pack.source_dir / "__init__.py"
    steps_path = pack.source_dir / "steps.py"
    skill_path = pack.source_dir / "SKILL.md"
    source_rows = [
        ("Package", _relative(pack.source_dir)),
        ("Manifest and builder", _relative(init_path)),
        ("Skill", _relative(skill_path)),
        ("Validation", f"`megaplan pipelines check {pack.slug}`"),
    ]
    if pack.step_symbols and steps_path.is_file():
        source_rows.insert(2, ("Steps", _relative(steps_path)))

    lines: list[str] = [
        GENERATED_HEADER.rstrip(),
        "",
        f"# {pack.title}",
        "",
        *pack.notes,
        "",
        "## Source Pack",
        "",
        *_table(("item", "value"), source_rows),
        "",
        "## Builder Surface",
        "",
        "The following snippet is extracted verbatim from the pack's `__init__.py`.",
        "",
        "```python",
        _source_lines_for_symbols(init_path, pack.init_symbols).rstrip(),
        "```",
        "",
    ]

    if pack.step_symbols and steps_path.is_file():
        lines.extend(
            [
                "## Step Surface",
                "",
                "The following snippet is extracted verbatim from the pack's `steps.py`.",
                "",
                "```python",
                _source_lines_for_symbols(steps_path, pack.step_symbols).rstrip(),
                "```",
                "",
            ]
        )

    lines.extend(
        [
            "## Package Skill",
            "",
            "The following module instructions are extracted verbatim from the pack's `SKILL.md`.",
            "",
            "````markdown",
            skill_path.read_text(encoding="utf-8").strip(),
            "````",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_examples() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for pack in sorted(EXAMPLE_PACKS, key=lambda item: item.slug):
        content = _render_example(pack)
        if content is not None:
            rendered[EXAMPLES_DIR / f"{pack.doc_slug}.md"] = content
    return rendered


def _literal_table(name: str, values: Iterable[str], source: str) -> list[tuple[str, str, str]]:
    return [(name, value, source) for value in sorted(values)]


def _manifest_rows() -> list[tuple[str, str]]:
    manifest_fields = {
        field.name: _annotation_name(field.type)
        for field in dataclasses.fields(discovery_manifest.Manifest)
    }
    return [
        (field_name, manifest_fields.get(field_name, "object"))
        for field_name in sorted(discovery_manifest.REQUIRED_FIELDS)
    ]


def _content_type_rows() -> list[tuple[str, str]]:
    return [(name, CONTENT_TYPES.get(name)) for name in CONTENT_TYPES.names()]


def _legal_coercion_rows() -> list[tuple[str, str, str]]:
    explicit = [
        (from_ct, to_ct, "registered")
        for from_ct, to_ct in sorted(contracts.legal_coercions)
    ]
    identity = [(name, name, "identity") for name in CONTENT_TYPES.names()]
    return sorted({*explicit, *identity})


def _repair_gradient_error_kinds() -> tuple[str, ...]:
    doc = inspect.getdoc(contracts.RepairGradient) or ""
    match = re.search(r"one of ([^.]+)\.", doc)
    if not match:
        return ()
    return tuple(sorted(re.findall(r"``([^`]+)``", match.group(1))))


def _string_template(node: ast.AST) -> str:
    if isinstance(node, ast.Constant):
        return repr(node.value) if not isinstance(node.value, str) else node.value
    if isinstance(node, ast.JoinedStr):
        parts: list[str] = []
        for value in node.values:
            if isinstance(value, ast.Constant):
                parts.append(str(value.value))
            elif isinstance(value, ast.FormattedValue):
                parts.append("{...}")
        return "".join(parts)
    if isinstance(node, ast.BinOp) and isinstance(node.op, ast.Add):
        return f"{_string_template(node.left)}{_string_template(node.right)}"
    return ast.unparse(node)


def _defect_append_rows(module: Any, list_name: str) -> list[tuple[str, str]]:
    source = inspect.getsource(module)
    tree = ast.parse(source)
    rows: list[tuple[str, str]] = []
    for node in ast.walk(tree):
        if not isinstance(node, ast.Call):
            continue
        func = node.func
        if not (isinstance(func, ast.Attribute) and func.attr == "append" and node.args):
            continue
        receiver = func.value
        local_list = isinstance(receiver, ast.Name) and receiver.id == list_name
        attribute_list = isinstance(receiver, ast.Attribute) and receiver.attr == list_name
        if not (local_list or attribute_list):
            continue
        rows.append((f"{module.__name__}:{node.lineno}", _string_template(node.args[0])))
    return sorted(rows)


def _cli_subcommand_rows(parser: argparse.ArgumentParser) -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for action in parser._actions:
        choices = getattr(action, "choices", None)
        if not isinstance(choices, dict):
            continue
        for name, subparser in sorted(choices.items()):
            if not isinstance(subparser, argparse.ArgumentParser):
                continue
            for sub_action in subparser._actions:
                sub_choices = getattr(sub_action, "choices", None)
                if not isinstance(sub_choices, dict):
                    continue
                for sub_name in sorted(sub_choices):
                    rows.append((name, sub_name, _source_path(build_parser)))
    return rows


def _doctor_option_rows(parser: argparse.ArgumentParser) -> list[tuple[str, str]]:
    for action in parser._actions:
        choices = getattr(action, "choices", None)
        if isinstance(choices, dict) and "doctor" in choices:
            doctor_parser = choices["doctor"]
            rows: list[tuple[str, str]] = []
            for doctor_action in doctor_parser._actions:
                for option in doctor_action.option_strings:
                    rows.append((option, doctor_action.help or ""))
            return sorted(rows)
    return []


def _state_rows() -> list[tuple[str, str, str]]:
    rows: list[tuple[str, str, str]] = []
    for name in sorted(dir(megaplan_types)):
        if name.startswith("STATE_"):
            value = getattr(megaplan_types, name)
            if isinstance(value, str):
                rows.append((name, value, _source_path(megaplan_types)))
    return rows


def render_reference() -> str:
    parser = build_parser()
    lines: list[str] = [
        GENERATED_HEADER.rstrip(),
        "",
        "# Arnold Projection Reference",
        "",
        "This page is generated from the schema, manifest-discovery, and pipeline-registry code.",
        "",
        "## Manifest Fields",
        "",
        *(_table(("field", "type"), _manifest_rows())),
        "",
        "## Pipeline Package Contract",
        "",
        *(_table(("fact", "value"), sorted(PACKAGE_CONTRACT_FACTS.items()))),
        "",
        "## Pipeline Discovery Facts",
        "",
        *(_table(("fact", "value"), sorted(DISCOVERY_FACTS.items()))),
        "",
        "## Discovery Disposition Fields",
        "",
        *(_table(("field", "type", "default"), _dataclass_field_rows(registry.Disposition))),
        "",
        "## Typed Port and Content-Type Surfaces",
        "",
        "### Port Models",
        "",
    ]

    for model in TYPED_PORT_MODELS:
        lines.extend(
            [
                f"#### {model.__name__}",
                "",
                inspect.getdoc(model) or "",
                "",
                *_table(("field", "type", "default"), _dataclass_field_rows(model)),
                "",
            ]
        )

    lines.extend(
        [
            "### Content Types",
            "",
            *_table(("content_type", "schema_sha256"), _content_type_rows()),
            "",
            "### Legal Content-Type Coercions",
            "",
            *_table(("from", "to", "kind"), _legal_coercion_rows()),
            "",
            "## Checker Defect Surfaces",
            "",
            "### Pipeline Graph Validator Defects",
            "",
            *_table(
                ("source", "defect_template"),
                _defect_append_rows(validator, "defects"),
            ),
            "",
            "### Judge Manifest Validator Defects",
            "",
            *_table(
                ("source", "defect_template"),
                _defect_append_rows(judge_manifest_discovery, "defects"),
            ),
            "",
            "### Contract Repair Error Kinds",
            "",
            *_table(
                ("error_kind", "source"),
                [
                    (kind, _source_path(contracts.RepairGradient))
                    for kind in _repair_gradient_error_kinds()
                ],
            ),
            "",
            "## CLI Check and Doctor Facts",
            "",
            "### Megaplan Nested Subcommands",
            "",
            *_table(("command", "subcommand", "source"), _cli_subcommand_rows(parser)),
            "",
            "### Doctor Options",
            "",
            *_table(("option", "help"), _doctor_option_rows(parser)),
            "",
            "### Arnold Module Verbs",
            "",
            *_table(
                ("vocabulary", "value", "source"),
                [
                    *_literal_table("module_verb", arnold_cli.MODULE_VERBS, _source_path(arnold_cli)),
                    *_literal_table(
                        "planning_module_verb",
                        arnold_cli.PLANNING_MODULE_VERBS,
                        _source_path(arnold_cli),
                    ),
                ],
            ),
            "",
            "## Control Vocabulary",
            "",
            "### Pipeline Literals",
            "",
            *_table(
                ("vocabulary", "value", "source"),
                [
                    *_literal_table("EdgeKind", _literal_values(EdgeKind), _source_path(Port)),
                    *_literal_table(
                        "GateRecommendation",
                        _literal_values(GateRecommendation),
                        _source_path(Port),
                    ),
                    *_literal_table(
                        "OverrideAction",
                        _literal_values(OverrideAction),
                        _source_path(Port),
                    ),
                ],
            ),
            "",
            "### Planning State Constants",
            "",
            *_table(("constant", "value", "source"), _state_rows()),
            "",
            "### Run and Control Targets",
            "",
            *_table(
                ("vocabulary", "value", "source"),
                [
                    *_literal_table("RunOutcome", [item.value for item in RunOutcome], _source_path(RunOutcome)),
                    *_literal_table(
                        "ControlTarget",
                        [
                            CONTROL_TARGET_ABORT,
                            CONTROL_TARGET_FORCE_ADVANCE,
                            CONTROL_TARGET_RECOVER_FROM_STUCK,
                            CONTROL_TARGET_REROUTE,
                        ],
                        _source_path(control_interface),
                    ),
                    *_literal_table(
                        "UserActionResolution",
                        user_actions.VALID_RESOLUTIONS,
                        _source_path(user_actions),
                    ),
                    *_literal_table(
                        "QualityResolution",
                        quality_resolutions.VALID_RESOLUTIONS,
                        _source_path(quality_resolutions),
                    ),
                ],
            ),
            "",
            "### Judge Manifest Constants",
            "",
            *_table(
                ("constant", "value", "source"),
                [
                    ("JUDGE_MANIFEST_SCHEMA", judge_manifest.JUDGE_MANIFEST_SCHEMA, _source_path(judge_manifest)),
                    ("JUDGE_KIND", judge_manifest.JUDGE_KIND, _source_path(judge_manifest)),
                    (
                        "EVALUAND_RECORD_CONTENT_TYPE",
                        judge_manifest.EVALUAND_RECORD_CONTENT_TYPE,
                        _source_path(judge_manifest),
                    ),
                ],
            ),
            "",
        ]
    )

    lines.extend(
        [
        "## Behavioral Manifest Projections",
        "",
        ]
    )

    for model in sorted(BEHAVIORAL_MANIFEST_MODELS, key=lambda item: item.__name__):
        lines.extend(
            [
                f"### {model.__name__}",
                "",
                inspect.getdoc(model) or "",
                "",
                *_table(("field", "type", "default"), _dataclass_field_rows(model)),
                "",
            ]
        )

    lines.extend(["## Outward Projection Schemas", ""])
    for model in sorted(PROJECTION_MODELS, key=lambda item: item.__name__):
        lines.extend(
            [
                f"### {model.__name__}",
                "",
                inspect.getdoc(model) or "",
                "",
                *_table(("field", "type", "default"), _pydantic_field_rows(model)),
                "",
            ]
        )

    return "\n".join(lines).rstrip() + "\n"


def generated_files(docs_root: Path) -> dict[Path, str]:
    files = {docs_root / REFERENCE_PATH: render_reference()}
    for relative_path, content in render_examples().items():
        files[docs_root / relative_path] = content
    return files


def _check_files(files: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in files.items():
        try:
            current = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            failures.append(f"{_relative(path)} is missing")
            continue
        if current != expected:
            diff = difflib.unified_diff(
                current.splitlines(),
                expected.splitlines(),
                fromfile=f"{_relative(path)} (current)",
                tofile=f"{_relative(path)} (generated)",
                lineterm="",
            )
            failures.append("\n".join(diff))
    return failures


def write_files(files: dict[Path, str]) -> None:
    for path, content in sorted(files.items(), key=lambda item: item[0].as_posix()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Fail if generated docs are stale.")
    mode.add_argument("--write", action="store_true", help="Write generated docs to disk.")
    parser.add_argument(
        "--docs-root",
        type=Path,
        default=DEFAULT_DOCS_ROOT,
        help=argparse.SUPPRESS,
    )
    args = parser.parse_args(argv)

    files = generated_files(args.docs_root)
    if args.write:
        write_files(files)
        for path in sorted(files):
            print(f"wrote {_relative(path)}")
        return 0

    failures = _check_files(files)
    if failures:
        print("Arnold generated docs are stale. Run `python scripts/generate_arnold_docs.py --write`.")
        print()
        print("\n\n".join(failures))
        return 1
    print("Arnold generated docs are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
