#!/usr/bin/env python
"""Generate Arnold reference docs, skills, and registries from workflow APIs.

The generator consumes only public ``arnold.workflow`` primitives and the final
``arnold_pipelines.discovery`` helper.  It does not import legacy Megaplan
builder, CLI, or registry surfaces.
"""

from __future__ import annotations

import argparse
import ast
import dataclasses
import difflib
import json
import subprocess
import sys
import tempfile
from datetime import datetime, timezone
from pathlib import Path
from typing import Any, Iterable

REPO_ROOT = Path(__file__).resolve().parents[1]
if str(REPO_ROOT) not in sys.path:
    sys.path.insert(0, str(REPO_ROOT))

import arnold.pipeline as native_pipeline
import arnold.workflow as workflow
from arnold.cli.workflow import build_parser as build_workflow_parser
from arnold.execution import ExecutionLogger, ExecutionRegistries, SkeletalBackend, run
from arnold.manifest.manifests import (
    WorkflowEdge,
    WorkflowManifest,
    WorkflowNode,
)
from arnold.pipeline import NativeProgram
from arnold.workflow import compile_pipeline, dry_run, inspect_manifest, to_dot, to_yaml
from arnold_pipelines.discovery import (
    ShippedPipelineInfo,
    discover_migrated_pipelines,
    discover_shipped_pipelines,
    load_builder,
)

DEFAULT_DOCS_ROOT = REPO_ROOT / "docs"
REFERENCE_PATH = Path("reference/arnold-projections.md")
EXAMPLES_DIR = Path("arnold/examples")
SKILLS_DIR = REPO_ROOT / "arnold_pipelines" / "megaplan" / "data" / "_codex_skills"
COMPOSED_DIR = REPO_ROOT / "arnold_pipelines" / "megaplan" / "data" / "_composed"

GENERATED_HEADER = """\
<!--
This file is generated by scripts/generate_arnold_docs.py.
Do not edit by hand; run `python scripts/generate_arnold_docs.py --write`.

Provenance:
- generator: {generator}
- source_package: {source_package}
- manifest_hash: {manifest_hash}
- generated_at: regenerated on demand (not embedded)
- m6_disposition: {m6_disposition}
- policy: regenerate from compiled surviving registries; fail on stale examples.
-->
"""

INIT_SYMBOLS = (
    "name",
    "description",
    "driver",
    "entrypoint",
    "arnold_api_version",
    "capabilities",
    "build_pipeline",
)


def _now() -> str:
    return datetime.now(timezone.utc).isoformat()


def _relative(path: Path) -> str:
    try:
        return path.resolve().relative_to(REPO_ROOT).as_posix()
    except ValueError:
        return path.as_posix()


def _provenance_header(
    *,
    generator: str = "scripts/generate_arnold_docs.py",
    source_package: str,
    manifest_hash: str,
    m6_disposition: str,
) -> str:
    return GENERATED_HEADER.format(
        generator=generator,
        source_package=source_package,
        manifest_hash=manifest_hash,
        m6_disposition=m6_disposition,
    )


def _annotation_name(annotation: Any) -> str:
    if annotation is type(None):
        return "None"
    origin = getattr(annotation, "__origin__", None)
    if origin is not None:
        args = getattr(annotation, "__args__", ())
        if origin is type:
            return f"type[{_annotation_name(args[0])}]" if args else "type"
        if origin is tuple:
            inner = ", ".join(_annotation_name(arg) for arg in args)
            return f"tuple[{inner}]"
        if origin is dict:
            return "dict"
        if origin is list:
            return "list"
        if origin is type(Any):
            return "Any"
        return str(annotation).replace("typing.", "")
    text = getattr(annotation, "__name__", None)
    if text:
        return text
    return str(annotation).replace("typing.", "")


def _dataclass_field_rows(model: type[Any]) -> list[tuple[str, str, str]]:
    rows = []
    for field in sorted(dataclasses.fields(model), key=lambda item: item.name):
        if field.default is not dataclasses.MISSING:
            default = repr(field.default)
        elif field.default_factory is not dataclasses.MISSING:  # type: ignore[comparison-overlap]
            factory = getattr(field.default_factory, "__name__", repr(field.default_factory))
            default = f"default_factory={factory}"
        else:
            default = "required"
        rows.append((field.name, _annotation_name(field.type), default))
    return rows


def _table(headers: tuple[str, ...], rows: Iterable[tuple[Any, ...]]) -> list[str]:
    def cell(value: Any) -> str:
        return str(value).replace("\n", " ").replace("|", "\\|")

    lines = [
        "| " + " | ".join(headers) + " |",
        "| " + " | ".join("---" for _ in headers) + " |",
    ]
    for row in rows:
        lines.append("| " + " | ".join(cell(value) for value in row) + "|")
    return lines


def _node_name(node: ast.AST) -> str | None:
    if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
        return node.name
    if isinstance(node, ast.Assign):
        for target in node.targets:
            if isinstance(target, ast.Name):
                return target.id
    if isinstance(node, ast.AnnAssign) and isinstance(node.target, ast.Name):
        return node.target.id
    return None


def _source_lines_for_symbols(path: Path, symbols: Iterable[str]) -> str:
    wanted = set(symbols)
    source = path.read_text(encoding="utf-8")
    lines = source.splitlines()
    tree = ast.parse(source, filename=str(path))
    ranges: list[tuple[int, int]] = []
    for node in tree.body:
        name = _node_name(node)
        if name not in wanted:
            continue
        end_lineno = getattr(node, "end_lineno", None)
        if end_lineno is None:
            continue
        ranges.append((node.lineno, end_lineno))
    ranges.sort()

    chunks: list[str] = []
    previous_end = 0
    for start, end in ranges:
        if chunks and start > previous_end + 1:
            chunks.append("")
        chunks.extend(lines[start - 1 : end])
        previous_end = end
    return "\n".join(chunks).rstrip() + "\n"


def _extract_step_symbols(steps_path: Path) -> tuple[str, ...]:
    source = steps_path.read_text(encoding="utf-8")
    tree = ast.parse(source, filename=str(steps_path))
    symbols: list[str] = []
    for node in tree.body:
        name = _node_name(node)
        if name and (isinstance(node, ast.ClassDef) or isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef))):
            symbols.append(name)
    return tuple(symbols)


def _builder_target(info: ShippedPipelineInfo) -> str:
    if info.canonical_builder_path:
        return info.canonical_builder_path
    module = info.package_path.replace("/", ".")
    if module.endswith(".py"):
        module = module[:-3]
    return f"{module}:build_pipeline"


def _builder_source_path(info: ShippedPipelineInfo) -> Path:
    module = _builder_target(info).split(":", 1)[0]
    module_path = REPO_ROOT / module.replace(".", "/")
    file_path = module_path.with_suffix(".py")
    if file_path.is_file():
        return file_path
    return module_path / "__init__.py"


def _compile_and_validate_workflow(info: ShippedPipelineInfo) -> WorkflowManifest:
    if info.builder_contract != "workflow" or info.load_state != "workflow":
        raise RuntimeError(
            f"pipeline {info.id!r} is {info.builder_contract}/{info.load_state}, expected workflow"
        )
    builder = info.builder
    if builder is None:
        raise RuntimeError(f"pipeline {info.id!r} has no builder")
    pipeline = builder()
    if not isinstance(pipeline, workflow.Pipeline):
        raise RuntimeError(
            f"builder for {info.id!r} returned {type(pipeline).__name__}, expected Pipeline"
        )
    return compile_pipeline(pipeline)


def _validate_native_builder(info: ShippedPipelineInfo) -> native_pipeline.Pipeline:
    if info.builder_contract != "native" or info.load_state != "loadable-native":
        raise RuntimeError(
            f"pipeline {info.id!r} is {info.builder_contract}/{info.load_state}, expected loadable-native"
        )
    builder = info.builder
    if builder is None:
        raise RuntimeError(f"pipeline {info.id!r} has no builder")
    pipeline = builder()
    if not isinstance(pipeline, native_pipeline.Pipeline):
        raise RuntimeError(
            f"builder for {info.id!r} returned {type(pipeline).__module__}.{type(pipeline).__name__}, "
            "expected arnold.pipeline.Pipeline"
        )
    if not isinstance(pipeline.native_program, NativeProgram):
        raise RuntimeError(f"native builder for {info.id!r} did not attach NativeProgram")
    return pipeline


def _pipeline_identity(info: ShippedPipelineInfo) -> str:
    if info.builder_contract == "workflow" and info.load_state == "workflow":
        return _compile_and_validate_workflow(info).manifest_hash or ""
    if info.builder_contract == "native" and info.load_state == "loadable-native":
        return f"native:{_validate_native_builder(info).native_program.name}"
    return info.load_state


def _fake_run(manifest: WorkflowManifest) -> None:
    with tempfile.TemporaryDirectory() as tmpdir:
        result = run(
            manifest,
            artifact_root=Path(tmpdir) / manifest.id,
            backend=SkeletalBackend(),
            registries=ExecutionRegistries(),
            logger=ExecutionLogger(),
        )
        if result.state.value != "completed":
            raise RuntimeError(f"fake run did not complete: {result.state.value}")


def _render_example(info: ShippedPipelineInfo) -> Path | None:
    docs_path = info.docs_path
    if docs_path is None:
        return None
    skill_path = REPO_ROOT / docs_path
    if not skill_path.is_file():
        return None

    package_path = REPO_ROOT / info.package_path
    builder_path = _builder_source_path(info)
    if not builder_path.is_file() and info.load_state not in {"deferred-native", "not-loadable"}:
        return None

    package_dir = package_path.parent if package_path.is_file() else package_path
    if not package_dir.exists() and builder_path.is_file():
        package_dir = builder_path.parent

    steps_path = package_dir / "steps.py"
    step_symbols = _extract_step_symbols(steps_path) if steps_path.is_file() else ()
    manifest_hash = ""
    dry_report: dict[str, Any] | None = None
    native_pipeline_obj: native_pipeline.Pipeline | None = None

    if info.builder_contract == "workflow" and info.load_state == "workflow":
        manifest = _compile_and_validate_workflow(info)
        dry_report = dry_run(manifest)
        _fake_run(manifest)
        manifest_hash = manifest.manifest_hash or ""
    elif info.builder_contract == "native" and info.load_state == "loadable-native":
        native_pipeline_obj = _validate_native_builder(info)
        manifest_hash = f"native:{native_pipeline_obj.native_program.name}"

    source_rows = [
        ("Package", _relative(package_path)),
        ("Builder target", _builder_target(info)),
        ("Builder source", _relative(builder_path)),
        ("Skill", _relative(skill_path)),
        ("Contract", info.builder_contract),
        ("Load state", info.load_state),
        ("Identity", manifest_hash or info.load_state),
    ]
    if info.builder_contract == "workflow" and info.load_state == "workflow":
        source_rows.insert(4, ("Validation", f"`arnold workflow check --module {_builder_target(info)}`"))
    elif info.builder_contract == "native" and info.load_state == "loadable-native":
        source_rows.insert(
            4,
            (
                "Validation",
                "`build_pipeline()` returns `arnold.pipeline.Pipeline` with `NativeProgram`",
            ),
        )
    elif info.diagnostic:
        source_rows.insert(4, ("Diagnostic", info.diagnostic))
    if step_symbols:
        source_rows.insert(2, ("Steps", _relative(steps_path)))

    lines: list[str] = [
        _provenance_header(
            source_package=info.package_path,
            manifest_hash=manifest_hash,
            m6_disposition="keep",
        ).rstrip(),
        "",
        f"# {info.id}",
        "",
        "## Source Pack",
        "",
        *_table(("item", "value"), source_rows),
        "",
        "## Builder Surface",
        "",
        "The following snippet is extracted verbatim from the pack's canonical builder source.",
        "",
        "```python",
        _source_lines_for_symbols(builder_path, INIT_SYMBOLS).rstrip() if builder_path.is_file() else "",
        "```",
        "",
    ]

    if step_symbols:
        lines.extend(
            [
                "## Step Surface",
                "",
                "The following snippet is extracted verbatim from the pack's `steps.py`.",
                "",
                "```python",
                _source_lines_for_symbols(steps_path, step_symbols).rstrip(),
                "```",
                "",
            ]
        )

    if dry_report is not None:
        lines.extend(
            [
                "## Dry-run report",
                "",
                "```yaml",
                to_yaml(dry_report).rstrip(),
                "```",
                "",
            ]
        )
    elif native_pipeline_obj is not None:
        lines.extend(
            [
                "## Native builder report",
                "",
                "```yaml",
                to_yaml(
                    {
                        "id": info.id,
                        "entry": native_pipeline_obj.entry,
                        "stage_count": len(native_pipeline_obj.stages),
                        "native_program": native_pipeline_obj.native_program.name,
                        "instruction_count": len(native_pipeline_obj.native_program.instructions),
                    }
                ).rstrip(),
                "```",
                "",
            ]
        )
    elif info.diagnostic:
        lines.extend(["## Deferred native diagnostic", "", info.diagnostic, ""])

    lines.extend(
        [
            "## Package Skill",
            "",
            "The following module instructions are extracted verbatim from the pack's `SKILL.md`.",
            "",
            "````markdown",
            skill_path.read_text(encoding="utf-8").strip(),
            "````",
            "",
        ]
    )

    doc_slug = info.id.replace(".", "-").replace("_", "-")
    out_path = DEFAULT_DOCS_ROOT / EXAMPLES_DIR / f"{doc_slug}.md"
    return out_path, "\n".join(lines).rstrip() + "\n"


def render_examples() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for info in discover_shipped_pipelines():
        if not info.public or info.disposition != "migrate" or info.docs_path is None:
            continue
        result = _render_example(info)
        if result is None:
            continue
        path, content = result
        rendered[path] = content
    return rendered


def _workflow_subcommand_rows(parser: argparse.ArgumentParser) -> list[tuple[str, str]]:
    rows: list[tuple[str, str]] = []
    for action in parser._actions:
        choices = getattr(action, "choices", None)
        if not isinstance(choices, dict):
            continue
        for name, subparser in sorted(choices.items()):
            if not isinstance(subparser, argparse.ArgumentParser):
                continue
            rows.append((name, subparser.description or ""))
    return rows


def _manifest_field_rows() -> list[tuple[str, str, str]]:
    return _dataclass_field_rows(WorkflowManifest)


def _node_field_rows() -> list[tuple[str, str, str]]:
    return _dataclass_field_rows(WorkflowNode)


def _edge_field_rows() -> list[tuple[str, str, str]]:
    return _dataclass_field_rows(WorkflowEdge)


def _pipeline_registry_rows() -> list[tuple[str, str, str, str, str]]:
    rows = []
    for info in discover_shipped_pipelines():
        if info.registry_id is None:
            continue
        rows.append(
            (
                info.registry_id,
                info.id,
                _pipeline_identity(info),
                _relative(REPO_ROOT / info.package_path),
                "keep",
            )
        )
    return sorted(rows)


def render_reference() -> str:
    parser = build_workflow_parser()
    manifest_sample = compile_pipeline(
        workflow.Pipeline(
            id="example",
            version="1.0",
            steps=(workflow.Step(id="plan", kind="agent"),),
        )
    )
    lines: list[str] = [
        _provenance_header(
            source_package="arnold.workflow",
            manifest_hash=manifest_sample.manifest_hash or "",
            m6_disposition="keep",
        ).rstrip(),
        "",
        "# Arnold Projection Reference",
        "",
        "This page is generated from the ``arnold.workflow`` manifest contract, "
        "the shipped-pipeline discovery helper, and the ``arnold workflow`` CLI parser.",
        "",
        "## Workflow Manifest Fields",
        "",
        *(_table(("field", "type", "default"), _manifest_field_rows())),
        "",
        "## Workflow Node Fields",
        "",
        *(_table(("field", "type", "default"), _node_field_rows())),
        "",
        "## Workflow Edge Fields",
        "",
        *(_table(("field", "type", "default"), _edge_field_rows())),
        "",
        "## Shipped Pipeline Registry",
        "",
        *(
            _table(
                ("stable_id", "alias", "manifest_hash", "package_path", "m6_disposition"),
                _pipeline_registry_rows(),
            )
        ),
        "",
        "## Workflow CLI Subcommands",
        "",
        *(_table(("subcommand", "description"), _workflow_subcommand_rows(parser))),
        "",
        "## Stable Inspect Fields",
        "",
        "- ``node_ids``: tuple of manifest node IDs.",
        "- ``refs``: durable node and edge refs.",
        "- ``dependencies``: per-node value dependencies from input bindings.",
        "- ``capabilities``: per-node and manifest-level capability requirements.",
        "- ``control_routes``: edge-derived control routes.",
        "- ``suspension_points``: suspension routes with reentry IDs.",
        "- ``unresolved_inputs``: inputs with no declared ``value_ref``.",
        "- ``source_spans``: per-node and manifest-level source spans.",
        "- ``hash_inputs``: topology and manifest hash inputs used for identity.",
        "",
        "## Stable Dry-run Fields",
        "",
        "- ``id``: manifest alias.",
        "- ``manifest_hash``: runtime identity hash.",
        "- ``node_count``: number of nodes.",
        "- ``edge_count``: number of edges.",
        "- ``possible_routes``: forward control routes the runner may traverse.",
        "- ``unresolved_inputs``: inputs with no bound ``value_ref``.",
        "- ``suspension_point_count``: number of suspension routes.",
        "",
    ]
    return "\n".join(lines).rstrip() + "\n"


def _render_skill(info: ShippedPipelineInfo) -> str:
    target = _builder_target(info)
    identity = _pipeline_identity(info)
    if info.builder_contract == "workflow" and info.load_state == "workflow":
        surface = "workflow-only"
        commands = [
            f"- Validate: `arnold workflow check --module {target}`",
            f"- Inspect: `arnold workflow describe --module {target}`",
            f"- Dry-run: `arnold workflow dry-run --module {target}`",
            f"- Run (fake backend): `arnold workflow run --module {target} --backend fake`",
        ]
    elif info.builder_contract == "native" and info.load_state == "loadable-native":
        surface = "native"
        commands = [
            f"- Validate import: `{target}`",
            "- Contract: `build_pipeline()` returns `arnold.pipeline.Pipeline` with `NativeProgram`",
        ]
    else:
        surface = info.builder_contract
        commands = [f"- Load state: `{info.load_state}`"]
    lines = [
        "---",
        f"name: {info.id}",
        f"description: Workflow skill for {info.id}.",
        "---",
        "",
        f"# {info.id}",
        "",
        f"This skill describes the {surface} surface for the shipped pipeline.",
        "It does not reference legacy Megaplan CLI commands.",
        "",
        "## Builder target",
        "",
        f"```text\n{target}\n```",
        "",
        "## Validation",
        "",
        *commands,
        "",
        "## Pipeline identity",
        "",
        f"- stable_id: `{info.registry_id or info.id}`",
        f"- identity: `{identity}`",
        f"- package_path: `{info.package_path}`",
        "",
    ]
    if info.diagnostic:
        lines.extend(["## Diagnostic", "", info.diagnostic, ""])
    if info.docs_path:
        skill_path = REPO_ROOT / info.docs_path
        if skill_path.is_file():
            lines.extend(
                [
                    "## Operator instructions",
                    "",
                    skill_path.read_text(encoding="utf-8").strip(),
                    "",
                ]
            )
    return "\n".join(lines).rstrip() + "\n"


def render_codex_skills() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for info in discover_shipped_pipelines():
        if not info.public or info.disposition != "migrate":
            continue
        slug = info.id.replace(".", "-").replace("_", "-")
        rendered[SKILLS_DIR / slug / "SKILL.md"] = _render_skill(info)
    return rendered


def _render_composed_skill(name: str, description: str) -> str:
    lines = [
        "---",
        f"name: {name}",
        f"description: {description}",
        "---",
        "",
        f"# {name}",
        "",
        "This composed rule is the workflow-only successor to the legacy Megaplan "
        "skill bundles.  It references only ``arnold.workflow`` and the shipped "
        "pipeline registry.",
        "",
        "## Launcher",
        "",
        "Use the ``arnold`` console script installed by the wheel:",
        "",
        "```bash",
        "arnold workflow --help",
        "arnold workflow check --module <package.module>:build_pipeline",
        "```",
        "",
        "## Shipped pipelines",
        "",
    ]
    for info in discover_migrated_pipelines():
        if info.registry_id is None:
            continue
        lines.append(f"- `{info.registry_id}` -> `arnold workflow check --module {_builder_target(info)}`")
    lines.extend(
        [
            "",
            "## Disallowed surfaces",
            "",
            "Do not author new packages with ``PipelineBuilder``, ``Stage``, public ``Edge``, "
            "hand-built graph fallback builders, or deleted Megaplan-root imports.  New "
            "packages must be native-first: use native declarations and return an "
            "``arnold.pipeline.Pipeline`` with ``native_program`` set.",
            "",
        ]
    )
    return "\n".join(lines).rstrip() + "\n"


def render_composed_rules() -> dict[Path, str]:
    return {
        COMPOSED_DIR / "claude_skill.md": _render_composed_skill(
            "workflow-claude", "Workflow-only composed skill for Claude."
        ),
        COMPOSED_DIR / "codex_skill.md": _render_composed_skill(
            "workflow-codex", "Workflow-only composed skill for Codex."
        ),
        COMPOSED_DIR / "cursor_rule.mdc": _render_composed_skill(
            "workflow-cursor", "Workflow-only composed rule for Cursor."
        ),
    }


def _registries_to_update() -> dict[Path, tuple[ShippedPipelineInfo, ...]]:
    """Map registry JSON paths to the pipeline infos that belong in them."""

    by_registry: dict[Path, list[ShippedPipelineInfo]] = {
        REPO_ROOT / "arnold_pipelines" / "evidence_pack" / "pipeline_ids.json": [],
    }
    for info in discover_migrated_pipelines():
        if info.registry_id is None:
            continue
        if info.registry_id == "evidence_pack.verifier":
            by_registry[
                REPO_ROOT / "arnold_pipelines" / "evidence_pack" / "pipeline_ids.json"
            ].append(info)
        else:
            continue
    return {path: tuple(infos) for path, infos in by_registry.items()}


def _load_registry(path: Path) -> dict[str, Any]:
    if path.exists():
        return json.loads(path.read_text(encoding="utf-8"))
    return {"version": 1, "pipelines": []}


def render_registries() -> dict[Path, str]:
    rendered: dict[Path, str] = {}
    for path, infos in _registries_to_update().items():
        data = _load_registry(path)
        hashes_by_stable_id = {
            info.registry_id: (_compile_and_validate_workflow(info).manifest_hash or "")
            for info in infos
            if info.registry_id
        }
        pipelines = []
        for item in data.get("pipelines", []):
            if not isinstance(item, dict):
                continue
            stable_id = item.get("stable_id")
            if stable_id not in hashes_by_stable_id:
                continue
            item = dict(item)
            item["manifest_hash"] = hashes_by_stable_id[stable_id]
            item["m6_disposition"] = "keep"
            pipelines.append(item)
        data = {"version": data.get("version", 1), "pipelines": pipelines}
        rendered[path] = json.dumps(data, indent=2, sort_keys=True) + "\n"
    return rendered


def generated_files() -> dict[Path, str]:
    files: dict[Path, str] = {}
    files[DEFAULT_DOCS_ROOT / REFERENCE_PATH] = render_reference()
    files.update(render_examples())
    files.update(render_codex_skills())
    files.update(render_composed_rules())
    files.update(render_registries())
    return files


def _is_gitignored(path: Path) -> bool:
    """Return True if *path* is ignored by git (generated, not committed)."""
    try:
        result = subprocess.run(
            ["git", "check-ignore", "-q", str(path)],
            cwd=REPO_ROOT,
            capture_output=True,
        )
    except FileNotFoundError:
        return False
    return result.returncode == 0


def _check_files(files: dict[Path, str]) -> list[str]:
    failures: list[str] = []
    for path, expected in files.items():
        if _is_gitignored(path):
            continue
        try:
            current = path.read_text(encoding="utf-8")
        except FileNotFoundError:
            failures.append(f"{_relative(path)} is missing")
            continue
        if current != expected:
            diff = difflib.unified_diff(
                current.splitlines(),
                expected.splitlines(),
                fromfile=f"{_relative(path)} (current)",
                tofile=f"{_relative(path)} (generated)",
                lineterm="",
            )
            failures.append("\n".join(diff))
    return failures


def write_files(files: dict[Path, str]) -> None:
    for path, content in sorted(files.items(), key=lambda item: item[0].as_posix()):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group(required=True)
    mode.add_argument("--check", action="store_true", help="Fail if generated artifacts are stale.")
    mode.add_argument("--write", action="store_true", help="Write generated artifacts to disk.")
    args = parser.parse_args(argv)

    files = generated_files()
    if args.write:
        write_files(files)
        for path in sorted(files):
            print(f"wrote {_relative(path)}")
        return 0

    failures = _check_files(files)
    if failures:
        print("Arnold generated artifacts are stale. Run `python scripts/generate_arnold_docs.py --write`.")
        print()
        print("\n\n".join(failures))
        return 1
    print("Arnold generated artifacts are up to date.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
