#!/usr/bin/env python3
"""Render docs/arnold/package-disposition.yaml to Markdown.

The YAML manifest is authoritative; the Markdown output is generated and
human-readable.  Use `--check` to verify that the on-disk Markdown file
matches the regenerated output (drift detection).
"""

from __future__ import annotations

import argparse
import difflib
import sys
from collections import defaultdict
from pathlib import Path
from typing import Any

try:
    import yaml
except ImportError:
    sys.exit("PyYAML is required. Install with: pip install pyyaml")


# ── constants ──────────────────────────────────────────────────────────────

REPO_ROOT = Path(__file__).resolve().parents[1]

GENERATED_HEADER = (
    "<!--\n"
    "This file is generated by scripts/render_package_disposition_md.py.\n"
    "Do not edit by hand.  The YAML manifest is authoritative.\n"
    "Run `python scripts/render_package_disposition_md.py --write` to regenerate.\n"
    "-->\n"
)

EXPECTED_DISPOSITIONS = [
    "arnold-core",
    "arnold-service-interface",
    "arnold-adapter",
    "arnold-shared-leaf",
    "megaplan-plugin",
    "product-app",
    "legacy-hold",
    "delete-merge",
    "split-required",
]


# ── YAML loading ───────────────────────────────────────────────────────────

def _load_manifest(path: Path) -> dict[str, Any]:
    data = yaml.safe_load(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"{path} must parse to a YAML mapping")
    return data


# ── grouping helpers ───────────────────────────────────────────────────────

def _group_rows_by_disposition(
    rows: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    """Group rows by their disposition value, preserving row order within groups."""
    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        disposition = row.get("disposition", "")
        groups[disposition].append(row)
    return dict(groups)


def _group_rows_by_source_prefix(
    rows: list[dict[str, Any]],
) -> dict[str, list[dict[str, Any]]]:
    """Group rows by their top-level source directory."""
    groups: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        source = row.get("source", "")
        prefix = source.split("/")[0] if "/" in source else source
        groups[prefix].append(row)
    return dict(groups)


def _split_parents_and_children(
    rows: list[dict[str, Any]],
) -> tuple[list[dict[str, Any]], dict[str, list[dict[str, Any]]]]:
    """Separate split-parent rows from child rows (children keyed by source path)."""
    split_rows: list[dict[str, Any]] = []
    child_map: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in rows:
        if row.get("granularity") == "split":
            split_rows.append(row)
        elif row.get("granularity") == "symbol":
            # Symbol children are matched to their parent split's source
            source = row.get("source", "")
            # Find the parent split row that owns this source path
            child_map[source].append(row)
        else:
            # file/directory rows are not split children in the grouping sense
            pass
    return split_rows, dict(child_map)


# ── string/list helpers ────────────────────────────────────────────────────

def _md_code(s: str) -> str:
    """Wrap a string in backticks if it looks like a path or identifier."""
    if not s:
        return "`(empty)`"
    return f"`{s}`"


def _md_bullet_list(items: list[str], indent: int = 0) -> str:
    if not items:
        return f"{' ' * indent}- _(none)_\n"
    return "\n".join(f"{' ' * indent}- {item}" for item in items)


def _md_bullet_list_from_strs(items: list[Any], indent: int = 0) -> str:
    if not items:
        return f"{' ' * indent}- _(none)_\n"
    return "\n".join(f"{' ' * indent}- {item!s}" for item in items)


def _obj_list_to_table(
    items: list[dict[str, Any]],
    columns: list[str],
    column_labels: list[str] | None = None,
) -> str:
    """Render a list of dicts as a Markdown table."""
    if not items:
        return "_(none)_\n"
    if column_labels is None:
        column_labels = columns
    header = "| " + " | ".join(column_labels) + " |"
    sep = "|" + "|".join(" --- " for _ in columns) + "|"
    lines = [header, sep]
    for item in items:
        vals = [str(item.get(col, "")).replace("\n", " ").replace("|", "\\|") for col in columns]
        lines.append("| " + " | ".join(vals) + " |")
    return "\n".join(lines) + "\n"


# ── section renderers ──────────────────────────────────────────────────────

def _render_header() -> str:
    return (
        GENERATED_HEADER
        + "\n# Package Disposition Manifest\n\n"
        + "> **Source of truth:** `docs/arnold/package-disposition.yaml`\n"
        + "> **Validator:** `scripts/validate_package_disposition.py`\n"
        + "> **Renderer:** `scripts/render_package_disposition_md.py`\n\n"
    )


def _render_overview(data: dict[str, Any]) -> str:
    rows = data.get("rows") or []
    exclusions = data.get("coverage_exclusions") or []
    parity_gates = data.get("parity_gates") or []
    runtime_gates = data.get("runtime_settings_gates") or []

    # Count by disposition
    disp_counts: dict[str, int] = defaultdict(int)
    gran_counts: dict[str, int] = defaultdict(int)
    for row in rows:
        disp_counts[row.get("disposition", "?")] += 1
        gran_counts[row.get("granularity", "?")] += 1

    lines = [
        "## Overview\n",
        f"**Schema version:** {data.get('schema_version', '?')}",
        f"**Disposition rows:** {len(rows)}",
        f"**Exclusions:** {len(exclusions)}",
        f"**Parity gates:** {len(parity_gates)}",
        f"**Runtime settings gates:** {len(runtime_gates)}",
        "",
        "### Disposition counts\n",
    ]
    for disposition in EXPECTED_DISPOSITIONS:
        count = disp_counts.get(disposition, 0)
        lines.append(f"- {disposition}: {count}")
    lines.extend(["", "### Granularity counts\n"])
    for gran in ["directory", "file", "symbol", "split"]:
        count = gran_counts.get(gran, 0)
        lines.append(f"- {gran}: {count}")
    return "\n".join(lines) + "\n"


def _render_exclusions(data: dict[str, Any]) -> str:
    exclusions = data.get("coverage_exclusions") or []
    lines = ["## Coverage Exclusions\n"]
    if not exclusions:
        lines.append("_(none — all tracked files must have disposition rows)_\n")
        return "\n".join(lines)

    lines.append(
        f"\nExclusions are limited to generated/cache artifacts. "
        f"{len(exclusions)} exclusion(s) defined.\n"
    )
    for i, exc in enumerate(exclusions, start=1):
        lines.append(f"### Exclusion {i}: `{exc.get('source', '?')}`\n")
        lines.append(f"- **Reason:** {exc.get('reason', '?')}")
        lines.append(f"- **Evidence:** {exc.get('evidence', '?')}")
        lines.append("")
    return "\n".join(lines)


def _render_row_detail(row: dict[str, Any], heading_level: int = 3) -> str:
    """Render the full detail section for a single disposition row."""
    h = "#" * heading_level
    source = row.get("source", "?")
    disposition = row.get("disposition", "?")
    granularity = row.get("granularity", "?")
    target = row.get("target", "?")

    lines = [
        f"{h} {source}",
        f"**Disposition:** `{disposition}` | **Granularity:** `{granularity}` | **Target:** {target}",
        "",
        f"**Reason:** {row.get('reason', '?')}",
        "",
    ]

    # Blockers
    blockers = row.get("blockers") or []
    lines.append("**Blockers:**")
    lines.append(_md_bullet_list(blockers, indent=0))
    lines.append("")

    # Import policies
    allowed_imports = row.get("allowed_imports") or []
    forbidden_imports = row.get("forbidden_imports") or []
    if allowed_imports or forbidden_imports:
        lines.append("**Import policy:**")
        if allowed_imports:
            lines.append(f"- Allowed: {', '.join(f'`{x}`' for x in allowed_imports)}")
        if forbidden_imports:
            lines.append(f"- Forbidden: {', '.join(f'`{x}`' for x in forbidden_imports)}")
        lines.append("")

    # Vocabulary owned
    vocabulary_owned = row.get("vocabulary_owned") or []
    if vocabulary_owned:
        lines.append("**Vocabulary owned:**")
        lines.append(
            _obj_list_to_table(
                vocabulary_owned,
                columns=["kind", "owner", "terms"],
                column_labels=["Kind", "Owner", "Terms"],
            )
        )

    # String policy
    string_policy = row.get("string_policy") or []
    if string_policy:
        lines.append("**String policy:**")
        lines.append(
            _obj_list_to_table(
                string_policy,
                columns=["category", "owner", "policy"],
                column_labels=["Category", "Owner", "Policy"],
            )
        )

    # Extraction prerequisites
    prereqs = row.get("extraction_prerequisite") or []
    if prereqs:
        lines.append("**Extraction prerequisites:**")
        lines.append(_md_bullet_list(prereqs, indent=0))
        lines.append("")

    # First extraction unit
    feu = row.get("first_extraction_unit")
    if feu:
        lines.append(f"**First extraction unit:** `{feu}`\n")

    # Tests gates
    tests_gates = row.get("tests_gates") or []
    if tests_gates:
        lines.append("**Tests / gates:**")
        lines.append(_md_bullet_list(tests_gates, indent=0))
        lines.append("")

    # Configurable seams
    configurable_seams = row.get("configurable_seams") or []
    if configurable_seams:
        lines.append("**Configurable seams:**")
        lines.append(
            _obj_list_to_table(
                configurable_seams,
                columns=[
                    "declaration_site",
                    "inherits_via",
                    "override_mechanism",
                    "meaning_owner",
                    "supported_state",
                ],
                column_labels=[
                    "Declaration Site",
                    "Inherits Via",
                    "Override Mechanism",
                    "Meaning Owner",
                    "Supported State",
                ],
            )
        )

    lines.append("---\n")
    return "\n".join(lines)


def _render_split_section(
    split_rows: list[dict[str, Any]],
    all_rows: list[dict[str, Any]],
) -> str:
    """Render split-required rows with their child rows grouped together."""
    if not split_rows:
        return ""

    # Build child lookup by source
    children_by_source: dict[str, list[dict[str, Any]]] = defaultdict(list)
    for row in all_rows:
        if row.get("granularity") == "symbol":
            children_by_source[row.get("source", "")].append(row)

    lines = ["## Split-Required Rows (with children)\n"]
    for split_row in split_rows:
        source = split_row.get("source", "?")
        lines.append(_render_row_detail(split_row, heading_level=3))
        child_rows = children_by_source.get(source, [])
        if child_rows:
            lines.append(f"**Child symbols** ({len(child_rows)}):\n")
            for child in child_rows:
                lines.append(f"- `{child.get('source', '?')}` → {child.get('target', '?')}")
            lines.append("")
        else:
            lines.append("**Child symbols:** _(none)_\n")
    return "\n".join(lines)


def _render_rows_by_disposition(data: dict[str, Any]) -> str:
    """Render all non-split rows grouped by disposition."""
    rows = data.get("rows") or []
    # Separate splits from others
    non_split = [r for r in rows if r.get("granularity") != "split" and r.get("granularity") != "symbol"]
    grouped = _group_rows_by_disposition(non_split)

    lines = ["## Disposition Rows by Classification\n"]
    for disposition in EXPECTED_DISPOSITIONS:
        group = grouped.get(disposition, [])
        if not group:
            continue
        lines.append(f"### {disposition} ({len(group)} rows)\n")
        for row in group:
            lines.append(_render_row_detail(row, heading_level=4))
    return "\n".join(lines)


def _render_parity_gates(data: dict[str, Any]) -> str:
    gates = data.get("parity_gates") or []
    lines = ["## Parity Gates\n"]
    if not gates:
        lines.append("_(none defined)_\n")
        return "\n".join(lines)

    lines.append(
        _obj_list_to_table(
            gates,
            columns=["name", "description", "status", "tests"],
            column_labels=["Name", "Description", "Status", "Tests"],
        )
    )
    return "\n".join(lines)


def _render_runtime_settings_gates(data: dict[str, Any]) -> str:
    gates = data.get("runtime_settings_gates") or []
    lines = ["## Runtime Settings Gates\n"]
    if not gates:
        lines.append("_(none defined)_\n")
        return "\n".join(lines)

    for i, gate in enumerate(gates, start=1):
        lines.append(f"### {gate.get('name', f'Gate {i}')}\n")
        lines.append(f"- **Description:** {gate.get('description', '?')}")
        lines.append(f"- **Declaration site:** `{gate.get('declaration_site', '?')}`")
        lines.append(f"- **Inherits via:** {gate.get('inherits_via', '?')}")
        lines.append(f"- **Override mechanism:** {gate.get('override_mechanism', '?')}")
        lines.append(f"- **Meaning owner:** {gate.get('meaning_owner', '?')}")
        lines.append(f"- **Supported state:** {gate.get('supported_state', '?')}")
        tests = gate.get("tests") or []
        lines.append(f"- **Tests:** {', '.join(tests) if tests else '_(none)_'}")
        lines.append("")
    return "\n".join(lines)


def _render_next_milestone_recommendations(data: dict[str, Any]) -> str:
    """Render next-milestone recommendations based on manifest state."""
    rows = data.get("rows") or []
    lines = ["## Next-Milestone Recommendations\n"]

    split_rows = [r for r in rows if r.get("granularity") == "split"]
    legacy_rows = [r for r in rows if r.get("disposition") == "legacy-hold"]
    delete_rows = [r for r in rows if r.get("disposition") == "delete-merge"]
    symbol_rows = [r for r in rows if r.get("granularity") == "symbol"]

    if split_rows:
        lines.append(f"- **Resolve {len(split_rows)} split-required row(s):** "
                      "each split parent needs child symbols finalized before extraction can begin.")
    if legacy_rows:
        lines.append(f"- **Investigate {len(legacy_rows)} legacy-hold row(s):** "
                      "these files have unclear ownership and need deeper inspection.")
    if delete_rows:
        lines.append(f"- **Audit {len(delete_rows)} delete-merge candidate(s):** "
                      "confirm no remaining callers before removal.")

    if not rows:
        lines.append("- **Populate the manifest:** no disposition rows have been classified yet.")
    else:
        lines.append("- **Extract capability seams** (M2a) before relocating plugins (M2b) to `arnold/pipelines/megaplan/`.")

    if not data.get("parity_gates"):
        lines.append("- **Define parity gates:** no behavior-preservation gates have been declared.")
    if not data.get("runtime_settings_gates"):
        lines.append("- **Define runtime settings gates:** no configurable-seam gates have been declared.")

    return "\n".join(lines) + "\n"


def _render_import_policy_summary(data: dict[str, Any]) -> str:
    """Summarize import policies across all rows."""
    rows = data.get("rows") or []
    lines = ["## Import / String Policy Summary\n"]

    # Collect unique import policies
    all_allowed: dict[str, set[str]] = defaultdict(set)
    all_forbidden: dict[str, set[str]] = defaultdict(set)
    vocab_by_owner: dict[str, list[str]] = defaultdict(list)
    string_policy_by_owner: dict[str, list[str]] = defaultdict(list)

    for row in rows:
        source = row.get("source", "?")
        for imp in row.get("allowed_imports") or []:
            all_allowed[imp].add(source)
        for imp in row.get("forbidden_imports") or []:
            all_forbidden[imp].add(source)
        for vocab in row.get("vocabulary_owned") or []:
            owner = vocab.get("owner", "?")
            terms = vocab.get("terms") or []
            vocab_by_owner[owner].extend(terms)
        for sp in row.get("string_policy") or []:
            owner = sp.get("owner", "?")
            category = sp.get("category", "?")
            string_policy_by_owner[owner].append(category)

    # Forbidden imports
    if all_forbidden:
        lines.append("### Forbidden Imports\n")
        for pattern in sorted(all_forbidden):
            sources = sorted(all_forbidden[pattern])
            lines.append(f"- `{pattern}` — forbidden from: {', '.join(f'`{s}`' for s in sources[:5])}"
                         f"{f' (+{len(sources)-5} more)' if len(sources) > 5 else ''}")
        lines.append("")

    # Allowed imports
    if all_allowed:
        lines.append("### Allowed Import Overrides\n")
        for pattern in sorted(all_allowed):
            sources = sorted(all_allowed[pattern])
            lines.append(f"- `{pattern}` — allowed in: {', '.join(f'`{s}`' for s in sources[:5])}"
                         f"{f' (+{len(sources)-5} more)' if len(sources) > 5 else ''}")
        lines.append("")

    # Vocabulary ownership
    if vocab_by_owner:
        lines.append("### Vocabulary Ownership\n")
        for owner in sorted(vocab_by_owner):
            terms = sorted(set(vocab_by_owner[owner]))
            lines.append(f"- **{owner}:** {', '.join(f'`{t}`' for t in terms)}")
        lines.append("")

    # String policy ownership
    if string_policy_by_owner:
        lines.append("### String Policy Ownership\n")
        for owner in sorted(string_policy_by_owner):
            cats = sorted(set(string_policy_by_owner[owner]))
            lines.append(f"- **{owner}** owns string categories: {', '.join(f'`{c}`' for c in cats)}")
        lines.append("")

    if not (all_forbidden or all_allowed or vocab_by_owner or string_policy_by_owner):
        lines.append("_(no import/string policies defined)_\n")

    return "\n".join(lines)


# ── main renderer ──────────────────────────────────────────────────────────

def render_markdown(data: dict[str, Any]) -> str:
    """Render the full Markdown document from a parsed YAML manifest."""
    parts: list[str] = [
        _render_header(),
        _render_overview(data),
        _render_exclusions(data),
        _render_rows_by_disposition(data),
    ]

    # Split rows section
    rows = data.get("rows") or []
    split_rows = [r for r in rows if r.get("granularity") == "split"]
    if split_rows:
        parts.append(_render_split_section(split_rows, rows))

    parts.extend([
        _render_import_policy_summary(data),
        _render_parity_gates(data),
        _render_runtime_settings_gates(data),
        _render_next_milestone_recommendations(data),
    ])

    return "\n".join(parts)


# ── CLI ────────────────────────────────────────────────────────────────────

def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--manifest",
        default="docs/arnold/package-disposition.yaml",
        help="Path to the YAML manifest (default: docs/arnold/package-disposition.yaml).",
    )
    parser.add_argument(
        "--output",
        default="docs/arnold/package-disposition.md",
        help="Path for the generated Markdown output (default: docs/arnold/package-disposition.md).",
    )
    parser.add_argument(
        "--write",
        action="store_true",
        help="Write the generated Markdown to --output. Without this, prints to stdout.",
    )
    parser.add_argument(
        "--check",
        action="store_true",
        help="Compare generated output against on-disk --output and fail if they differ.",
    )
    args = parser.parse_args(argv)

    repo_root = REPO_ROOT
    manifest_path = (repo_root / args.manifest).resolve()
    output_path = (repo_root / args.output).resolve()

    # Load YAML
    try:
        data = _load_manifest(manifest_path)
    except FileNotFoundError:
        print(f"Manifest not found: {manifest_path}", file=sys.stderr)
        return 1
    except (ValueError, yaml.YAMLError) as exc:
        print(f"Failed to parse manifest: {exc}", file=sys.stderr)
        return 1

    # Render
    generated = render_markdown(data)

    # --check mode
    if args.check:
        try:
            existing = output_path.read_text(encoding="utf-8")
        except FileNotFoundError:
            print(f"Output file not found: {output_path}", file=sys.stderr)
            return 1

        if existing != generated:
            # Show diff
            diff_lines = list(
                difflib.unified_diff(
                    existing.splitlines(keepends=True),
                    generated.splitlines(keepends=True),
                    fromfile=str(output_path),
                    tofile="(generated)",
                )
            )
            sys.stderr.writelines(diff_lines)
            print(
                f"DRIFT DETECTED: {output_path} differs from generated output.",
                file=sys.stderr,
            )
            return 1

        print(f"OK: {output_path.relative_to(repo_root)} matches generated output.")
        return 0

    # --write mode
    if args.write:
        output_path.parent.mkdir(parents=True, exist_ok=True)
        output_path.write_text(generated, encoding="utf-8")
        print(f"Wrote {output_path.relative_to(repo_root)}")
        return 0

    # Default: print to stdout
    print(generated, end="")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
