"""Contract tests for the authoritative read-only CL2 admission command
(``scripts/check_cl2_admission.py``).

These tests verify the executable admission boundary contract:

* **read-only** — the command performs no writes on success or failure;
* **path-bounded** — only the manifest and the four declared artifact paths
  are opened (relative paths resolve against the manifest's parent dir);
* **nonzero on every invalid state** — missing manifest, malformed manifest,
  missing artifacts, the landed rejected oracle, hash drift, and any typed
  gate error all exit nonzero with a stderr diagnostic;
* **prints only the accepted binding hash on success** — stdout is exactly the
  64-character hex digest and nothing else.

The positive path is exercised against a fixture bundle whose receipt carries
a genuine Ed25519 detached signature generated by the test fixture (acting as
the "U1" reviewer). The command and the gate themselves never create
signatures, trust entries, or acceptance data — they only read and verify.
"""

from __future__ import annotations

import hashlib
import json
import os
import subprocess
import sys
from pathlib import Path

import pytest

REPO_ROOT = Path(__file__).resolve().parent.parent.parent.parent
COMMAND = REPO_ROOT / "scripts" / "check_cl2_admission.py"
REJECTED_ORACLE_PATH = (
    REPO_ROOT / "docs" / "critique-ledger" / "handoffs" / "cl1-contract-oracle.json"
)

U1_DIR_ENV = "CL2_U1_BUNDLE_DIR"

EXIT_OK = 0
EXIT_USAGE = 1
EXIT_REJECTED = 2


# ────────────────────────────────────────────────────────────────────
# Helpers
# ────────────────────────────────────────────────────────────────────


def _write_json(path: Path, data: dict) -> str:
    """Write *data* as deterministic JSON and return the SHA-256 of the bytes."""
    text = json.dumps(data, sort_keys=True, indent=2)
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(text, encoding="utf-8")
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def _run(manifest: Path) -> subprocess.CompletedProcess:
    """Invoke the admission command against *manifest*."""
    return subprocess.run(
        [sys.executable, str(COMMAND), str(manifest)],
        capture_output=True,
        text=True,
        cwd=str(REPO_ROOT),
        timeout=60,
    )


def _policy_revisions(seed: str = "p") -> dict:
    return {
        "prompt_revision": (seed + "1") * 32,
        "implementation_revision": (seed + "2") * 32,
        "briefing_revision": (seed + "3") * 32,
        "near_match_policy_revision": (seed + "4") * 32,
        "false_positive_budget_revision": (seed + "5") * 32,
        "audit_policy_revision": (seed + "6") * 32,
    }


def _accepted_handoff(amendment: str) -> dict:
    return {
        "schema": "cl.handoff.v1",
        "target_milestone": "CL2",
        "amendment_checksum": amendment,
        "accepted_for_cl2": {
            "value": True,
            "checks": {
                "cl1_must_gates_pass": {"passed": True, "detail": "ok"},
                "review_status_present": {"passed": True, "detail": "ok"},
                "hashes_fresh": {"passed": True, "detail": "ok"},
                "blocker_bearing_gaps_empty": {"passed": True, "detail": "ok"},
            },
            "blocking_reasons": [],
        },
        "open_gates": {
            "example_gate": {"status": "PASSED", "detail": "ok"},
        },
    }


def _make_receipt_payload(
    handoff_sha: str,
    policy_sha: str,
    fingerprint: str,
    amendment: str,
) -> dict:
    return {
        "scope": ["cl2_admission"],
        "reviewer_fingerprint": fingerprint,
        "reviewed_artifact_sha256": handoff_sha,
        "policy_bundle_sha256": policy_sha,
        "amendment_checksum": amendment,
        "expires_at": "",
    }


def _canonical_receipt_message(receipt: dict) -> bytes:
    redacted = {k: v for k, v in receipt.items() if k != "signature"}
    return json.dumps(redacted, sort_keys=True, separators=(",", ":")).encode("utf-8")


def _build_valid_bundle(bundle_dir: Path) -> tuple[Path, dict]:
    """Write a complete valid accepted bundle into *bundle_dir* and return
    (manifest_path, manifest_dict).

    A fresh Ed25519 keypair is generated by the test fixture to mint a genuine
    test bundle — the gate and command never create signatures, trust entries,
    or acceptance data; they only read and verify.
    """
    import base64

    from cryptography.hazmat.primitives.asymmetric.ed25519 import Ed25519PrivateKey
    from cryptography.hazmat.primitives.serialization import (
        Encoding,
        PublicFormat,
    )

    amendment = "a" * 64
    revisions = _policy_revisions()

    # 1. handoff
    handoff = _accepted_handoff(amendment)
    handoff_sha = _write_json(bundle_dir / "amended_handoff.json", handoff)

    # 2. policy bundle
    policy = dict(revisions)
    policy_sha = _write_json(bundle_dir / "policy_bundle.json", policy)

    # 3. keypair (fixture only)
    priv = Ed25519PrivateKey.generate()
    pub_bytes = priv.public_key().public_bytes(
        encoding=Encoding.Raw, format=PublicFormat.Raw
    )
    fingerprint = hashlib.sha256(pub_bytes).hexdigest()
    public_key_b64 = base64.b64encode(pub_bytes).decode()

    # 4. receipt — sign the canonical message over the unsigned payload.
    receipt = _make_receipt_payload(handoff_sha, policy_sha, fingerprint, amendment)
    message = _canonical_receipt_message(receipt)
    receipt["signature"] = base64.b64encode(priv.sign(message)).decode()
    receipt_sha = _write_json(bundle_dir / "review_receipt.json", receipt)

    # 5. reviewer trust
    trust = {
        "trusted_reviewers": [
            {
                "fingerprint": fingerprint,
                "public_key": public_key_b64,
                "scope": ["cl2_admission"],
                "expires_at": "",
            }
        ]
    }
    trust_sha = _write_json(bundle_dir / "reviewer_trust.json", trust)

    manifest = {
        "amended_handoff": {"path": "amended_handoff.json", "sha256": handoff_sha},
        "policy_bundle": {"path": "policy_bundle.json", "sha256": policy_sha},
        "review_receipt": {"path": "review_receipt.json", "sha256": receipt_sha},
        "reviewer_trust": {"path": "reviewer_trust.json", "sha256": trust_sha},
        "reviewer_fingerprint": fingerprint,
        "target_schema": "cl.handoff.v1",
        "amendment_checksum": amendment,
        "policy_revisions": revisions,
    }
    manifest_path = bundle_dir / "manifest.json"
    _write_json(manifest_path, manifest)
    return manifest_path, manifest


def _snapshot(root: Path) -> dict[str, str]:
    """Return {relative_path: sha256(content)} for every file under *root*."""
    snap: dict[str, str] = {}
    for p in sorted(root.rglob("*")):
        if p.is_file():
            rel = p.relative_to(root).as_posix()
            snap[rel] = hashlib.sha256(p.read_bytes()).hexdigest()
    return snap


# ────────────────────────────────────────────────────────────────────
# Usage / manifest errors — exit nonzero before any admission attempt
# ────────────────────────────────────────────────────────────────────


class TestUsageErrors:
    def test_no_argument_exits_nonzero(self, tmp_path):
        result = subprocess.run(
            [sys.executable, str(COMMAND)],
            capture_output=True,
            text=True,
            cwd=str(REPO_ROOT),
            timeout=60,
        )
        assert result.returncode == EXIT_USAGE
        assert result.stdout == ""

    def test_missing_manifest_file_exits_nonzero(self, tmp_path):
        result = _run(tmp_path / "does_not_exist.json")
        assert result.returncode == EXIT_USAGE
        assert result.stdout == ""
        assert "not found" in result.stderr.lower()

    def test_malformed_json_manifest_exits_nonzero(self, tmp_path):
        bad = tmp_path / "manifest.json"
        bad.write_text("{not valid json", encoding="utf-8")
        result = _run(bad)
        assert result.returncode == EXIT_USAGE
        assert result.stdout == ""

    def test_non_object_manifest_exits_nonzero(self, tmp_path):
        bad = tmp_path / "manifest.json"
        bad.write_text("[1, 2, 3]", encoding="utf-8")
        result = _run(bad)
        assert result.returncode == EXIT_USAGE

    def test_manifest_missing_required_keys_exits_nonzero(self, tmp_path):
        manifest = tmp_path / "manifest.json"
        _write_json(manifest, {"amended_handoff": {"path": "x", "sha256": "y"}})
        result = _run(manifest)
        assert result.returncode == EXIT_USAGE
        assert "missing required keys" in result.stderr


# ────────────────────────────────────────────────────────────────────
# Admission rejection — typed gate errors exit nonzero (code 2)
# ────────────────────────────────────────────────────────────────────


class TestAdmissionRejection:
    def test_missing_artifact_exits_nonzero(self, tmp_path):
        manifest, _ = _build_valid_bundle(tmp_path)
        # Declare an artifact path that does not exist.
        data = _load_json(manifest)
        data["review_receipt"]["path"] = "absent_receipt.json"
        _write_json(manifest, data)
        result = _run(manifest)
        assert result.returncode == EXIT_REJECTED
        assert result.stdout == ""
        assert "PrerequisiteUnresolvedError" in result.stderr

    def test_rejected_oracle_exits_nonzero(self, tmp_path):
        oracle = _load_json(REJECTED_ORACLE_PATH)
        handoff_sha = _write_json(tmp_path / "amended_handoff.json", oracle)
        revisions = _policy_revisions()
        policy_sha = _write_json(tmp_path / "policy_bundle.json", dict(revisions))
        receipt_sha = _write_json(tmp_path / "review_receipt.json", {"placeholder": True})
        trust_sha = _write_json(
            tmp_path / "reviewer_trust.json", {"trusted_reviewers": []}
        )
        manifest = {
            "amended_handoff": {"path": "amended_handoff.json", "sha256": handoff_sha},
            "policy_bundle": {"path": "policy_bundle.json", "sha256": policy_sha},
            "review_receipt": {"path": "review_receipt.json", "sha256": receipt_sha},
            "reviewer_trust": {"path": "reviewer_trust.json", "sha256": trust_sha},
            "reviewer_fingerprint": "deadbeef" * 8,
            "target_schema": "cl.handoff.v1",
            "amendment_checksum": "a" * 64,
            "policy_revisions": revisions,
        }
        manifest_path = tmp_path / "manifest.json"
        _write_json(manifest_path, manifest)
        result = _run(manifest_path)
        assert result.returncode == EXIT_REJECTED
        assert result.stdout == ""
        assert "DerivedAcceptanceFalseError" in result.stderr

    def test_hash_drift_exits_nonzero(self, tmp_path):
        manifest, _ = _build_valid_bundle(tmp_path)
        data = _load_json(manifest)
        # Declare a deliberately wrong hash for the policy bundle.
        data["policy_bundle"]["sha256"] = "0" * 64
        _write_json(manifest, data)
        result = _run(manifest)
        assert result.returncode == EXIT_REJECTED
        assert "HashDriftError" in result.stderr

    def test_bad_signature_exits_nonzero(self, tmp_path):
        import base64

        manifest, _ = _build_valid_bundle(tmp_path)
        # Corrupt the receipt signature in place and recompute its disk hash.
        receipt = _load_json(tmp_path / "review_receipt.json")
        receipt["signature"] = base64.b64encode(b"\xff" * 64).decode()
        data = _load_json(manifest)
        data["review_receipt"]["sha256"] = _write_json(
            tmp_path / "review_receipt.json", receipt
        )
        _write_json(manifest, data)
        result = _run(manifest)
        assert result.returncode == EXIT_REJECTED
        assert "DetachedSignatureInvalidError" in result.stderr


# ────────────────────────────────────────────────────────────────────
# Read-only — no writes on success or failure
# ────────────────────────────────────────────────────────────────────


class TestReadOnly:
    def test_no_writes_on_failure(self, tmp_path):
        manifest, _ = _build_valid_bundle(tmp_path)
        data = _load_json(manifest)
        data["amended_handoff"]["sha256"] = "0" * 64  # induce hash drift
        _write_json(manifest, data)
        before = _snapshot(tmp_path)
        result = _run(manifest)
        assert result.returncode == EXIT_REJECTED
        after = _snapshot(tmp_path)
        assert before == after, "command wrote or modified files on failure"

    def test_no_writes_on_success(self, tmp_path):
        manifest, _ = _build_valid_bundle(tmp_path)
        before = _snapshot(tmp_path)
        result = _run(manifest)
        assert result.returncode == EXIT_OK
        after = _snapshot(tmp_path)
        assert before == after, "command wrote or modified files on success"


# ────────────────────────────────────────────────────────────────────
# Success — prints only the accepted binding hash
# ────────────────────────────────────────────────────────────────────


class TestSuccessPath:
    def test_prints_only_binding_hash(self, tmp_path):
        manifest, manifest_data = _build_valid_bundle(tmp_path)
        result = _run(manifest)
        assert result.returncode == EXIT_OK
        stdout = result.stdout.rstrip("\n")
        # stdout is exactly one 64-char hex line.
        assert len(stdout) == 64
        assert all(c in "0123456789abcdef" for c in stdout)
        # No additional lines or content.
        assert result.stdout.count("\n") <= 1
        assert result.stderr == ""

    def test_binding_hash_is_deterministic(self, tmp_path):
        manifest, _ = _build_valid_bundle(tmp_path)
        r1 = _run(manifest)
        r2 = _run(manifest)
        assert r1.returncode == EXIT_OK
        assert r2.returncode == EXIT_OK
        assert r1.stdout == r2.stdout

    def test_binding_hash_matches_gate_directly(self, tmp_path):
        """The command's stdout must equal the gate's binding_hash."""
        from arnold.critique_ledger.contract_gate import (
            CL2AdmissionInput,
            PolicyRevisions,
            sha256_file,
            verify_cl2_admission,
        )

        manifest, md = _build_valid_bundle(tmp_path)
        base = manifest.resolve().parent
        admission = CL2AdmissionInput(
            amended_handoff_path=base / md["amended_handoff"]["path"],
            amended_handoff_sha256=md["amended_handoff"]["sha256"],
            policy_bundle_path=base / md["policy_bundle"]["path"],
            policy_bundle_sha256=md["policy_bundle"]["sha256"],
            review_receipt_path=base / md["review_receipt"]["path"],
            review_receipt_sha256=md["review_receipt"]["sha256"],
            reviewer_trust_path=base / md["reviewer_trust"]["path"],
            reviewer_trust_sha256=md["reviewer_trust"]["sha256"],
            reviewer_fingerprint=md["reviewer_fingerprint"],
            target_schema=md["target_schema"],
            amendment_checksum=md["amendment_checksum"],
            policy_revisions=PolicyRevisions.from_dict(md["policy_revisions"]),
        )
        binding = verify_cl2_admission(admission)
        result = _run(manifest)
        assert result.returncode == EXIT_OK
        assert result.stdout.rstrip("\n") == binding.binding_hash


# ────────────────────────────────────────────────────────────────────
# Path-boundedness — relative resolution + no path invention
# ────────────────────────────────────────────────────────────────────


class TestPathBoundedness:
    def test_relative_paths_resolve_against_manifest_dir(self, tmp_path):
        # Put the manifest in a subdirectory; declare relative artifact paths
        # that resolve against that subdirectory.
        bundle_dir = tmp_path / "bundle"
        manifest, _ = _build_valid_bundle(bundle_dir)
        result = _run(manifest)
        assert result.returncode == EXIT_OK

    def test_absolute_paths_also_work(self, tmp_path):
        manifest, md = _build_valid_bundle(tmp_path)
        base = tmp_path.resolve()
        for key in ("amended_handoff", "policy_bundle", "review_receipt", "reviewer_trust"):
            md[key]["path"] = str(base / md[key]["path"])
        _write_json(manifest, md)
        result = _run(manifest)
        assert result.returncode == EXIT_OK

    def test_manifest_outside_bundle_dir_resolves_relative_to_manifest(self, tmp_path):
        bundle_dir = tmp_path / "bundle"
        manifest, md = _build_valid_bundle(bundle_dir)
        # Move the manifest to tmp_path root and keep relative paths.
        new_manifest = tmp_path / "manifest.json"
        new_manifest.write_text(manifest.read_text(encoding="utf-8"), encoding="utf-8")
        result = _run(new_manifest)
        # Relative paths now resolve against tmp_path, where artifacts don't
        # exist → prerequisite failure (path-bounded: no searching up/down).
        assert result.returncode == EXIT_REJECTED
        assert "PrerequisiteUnresolvedError" in result.stderr


# ────────────────────────────────────────────────────────────────────
# U1-gated real bundle (skipped when U1 is not supplied)
# ────────────────────────────────────────────────────────────────────


class TestU1AcceptedBundle:
    def _u1_dir(self):
        val = os.environ.get(U1_DIR_ENV)
        if not val:
            return None
        p = Path(val)
        return p if p.is_dir() else None

    def test_real_u1_bundle_accepted(self, tmp_path):
        u1 = self._u1_dir()
        if u1 is None:
            pytest.skip(f"U1 accepted bundle not supplied (set ${U1_DIR_ENV})")
        meta_path = u1 / "bundle_meta.json"
        if not meta_path.is_file():
            pytest.skip("U1 bundle_meta.json not found")
        meta = _load_json(meta_path)
        manifest = {
            "amended_handoff": {
                "path": str(u1 / "amended_handoff.json"),
                "sha256": meta["amended_handoff_sha256"],
            },
            "policy_bundle": {
                "path": str(u1 / "policy_bundle.json"),
                "sha256": meta["policy_bundle_sha256"],
            },
            "review_receipt": {
                "path": str(u1 / "review_receipt.json"),
                "sha256": meta["review_receipt_sha256"],
            },
            "reviewer_trust": {
                "path": str(u1 / "reviewer_trust.json"),
                "sha256": meta["reviewer_trust_sha256"],
            },
            "reviewer_fingerprint": meta["reviewer_fingerprint"],
            "target_schema": meta["target_schema"],
            "amendment_checksum": meta["amendment_checksum"],
            "policy_revisions": meta["policy_revisions"],
        }
        manifest_path = tmp_path / "manifest.json"
        _write_json(manifest_path, manifest)
        result = _run(manifest_path)
        assert result.returncode == EXIT_OK
        stdout = result.stdout.rstrip("\n")
        assert len(stdout) == 64
