"""Megaplan-specific authority contracts and shadow projections."""

from .batch_scope import (
    BATCH_SCOPE_KEY,
    BATCH_SCOPE_SCHEMA_VERSION,
    BatchScope,
    BatchScopeQuarantine,
    BatchScopeResolution,
    resolve_batch_scope,
)
from .binding import (
    DispatchGrant,
    SENSE_CHECK_ACK_CLAIM,
    SENSE_CHECK_RESULT_CAPABILITY,
    TASK_COMPLETION_CLAIM,
    TASK_RESULT_CAPABILITY,
    TaskAttempt,
    TaskClaim,
    TaskValidationDecision,
)
from .views import (
    LegacyTaskLabel,
    PlanExecutionDiagnostic,
    PlanExecutionView,
    PublicationDiagnostic,
    PublicationObservation,
    PublicationView,
    RunnerDiagnostic,
    RunnerObservation,
    RunnerView,
    TaskExecutionState,
    derive_plan_execution_view,
    derive_publication_view,
    derive_runner_view,
)

__all__ = [
    "BATCH_SCOPE_KEY",
    "BATCH_SCOPE_SCHEMA_VERSION",
    "BatchScope",
    "BatchScopeQuarantine",
    "BatchScopeResolution",
    "resolve_batch_scope",
    "DispatchGrant",
    "SENSE_CHECK_ACK_CLAIM",
    "SENSE_CHECK_RESULT_CAPABILITY",
    "TASK_COMPLETION_CLAIM",
    "TASK_RESULT_CAPABILITY",
    "TaskAttempt",
    "TaskClaim",
    "TaskValidationDecision",
    "LegacyTaskLabel",
    "PlanExecutionDiagnostic",
    "PlanExecutionView",
    "PublicationDiagnostic",
    "PublicationObservation",
    "PublicationView",
    "RunnerDiagnostic",
    "RunnerObservation",
    "RunnerView",
    "TaskExecutionState",
    "derive_plan_execution_view",
    "derive_publication_view",
    "derive_runner_view",
]
