"""Megaplan schema package.

This package keeps the historical ``megaplan.schemas`` import surface stable
while opening a dedicated namespace for the Sprint 1 storage models.
"""

from .models import (
    AutomationActor,
    BotTurn,
    ChecklistItem,
    CodeArtifact,
    Codebase,
    ControlMessage,
    Epic,
    EpicEvent,
    EpicLock,
    ExecutionLease,
    ExternalRequest,
    Feedback,
    HomeBackend,
    Image,
    Message,
    MigrationRun,
    Plan,
    PlanArtifact,
    ProgressEvent,
    SecondOpinion,
    Sprint,
    SprintItem,
    StorageModel,
    SystemLog,
    ToolCall,
    utc_now,
)
from .runtime import (
    SCHEMAS,
    STANCE_SCHEMA,
    STOP_SIGNAL_SCHEMA,
    get_execution_schema_key,
    strict_schema,
)

__all__ = [
    "AutomationActor",
    "BotTurn",
    "ChecklistItem",
    "CodeArtifact",
    "Codebase",
    "ControlMessage",
    "Epic",
    "EpicEvent",
    "EpicLock",
    "ExecutionLease",
    "ExternalRequest",
    "Feedback",
    "HomeBackend",
    "Image",
    "Message",
    "MigrationRun",
    "Plan",
    "PlanArtifact",
    "ProgressEvent",
    "SecondOpinion",
    "Sprint",
    "SprintItem",
    "SCHEMAS",
    "STANCE_SCHEMA",
    "STOP_SIGNAL_SCHEMA",
    "StorageModel",
    "SystemLog",
    "ToolCall",
    "get_execution_schema_key",
    "strict_schema",
    "utc_now",
]
