"""M5-cal — Calibration Ledger: CapabilityClaims + decay/exploration; routing = a query.

This package provides the calibration ledger that records CapabilityClaim events
alongside the existing events.ndjson journal. Claims are *never* bare numerics —
outcomes are represented as :class:`EvaluandRef` references that join against
:func:`read_evaluand_events` via the deterministic 4-tuple attribution key.
"""

from megaplan.calibration.ledger import (
    AggregationPolicy,
    CapabilityClaim,
    EvaluandRef,
    EvaluandResolution,
    EvaluandStatus,
    ModelIdentity,
    QueryPolicy,
    RouteSuggestion,
    aggregate_weighted_tier,
    capability_class_prior,
    check_reviewer_invariant,
    classify_claim_taint,
    derive_aggregation_policy,
    filter_shared_claims,
    half_life_weight,
    is_shared_claim,
    iter_capability_claim_payloads,
    normalize_projected_complexity,
    project_batch_complexity,
    project_claimed_complexity,
    project_tier_models,
    project_tier_models_if_enabled,
    query_route_if_enabled,
    read_capability_claims,
    resolve_evaluand,
    route,
    write_capability_claim,
)
from megaplan.calibration.experiments import (
    CALIBRATION_EXPERIMENT_EVENT_KIND,
    CalibrationExperimentFinding,
    CheapestRoutingExperiment,
    MonocultureExperiment,
    run_cheapest_routing_experiment,
    run_monoculture_experiment,
    write_experiment_finding,
)

__all__ = [
    "AggregationPolicy",
    "CALIBRATION_EXPERIMENT_EVENT_KIND",
    "CapabilityClaim",
    "CalibrationExperimentFinding",
    "CheapestRoutingExperiment",
    "EvaluandRef",
    "EvaluandResolution",
    "EvaluandStatus",
    "ModelIdentity",
    "MonocultureExperiment",
    "QueryPolicy",
    "RouteSuggestion",
    "aggregate_weighted_tier",
    "capability_class_prior",
    "check_reviewer_invariant",
    "classify_claim_taint",
    "derive_aggregation_policy",
    "filter_shared_claims",
    "half_life_weight",
    "is_shared_claim",
    "iter_capability_claim_payloads",
    "normalize_projected_complexity",
    "project_batch_complexity",
    "project_claimed_complexity",
    "project_tier_models",
    "project_tier_models_if_enabled",
    "query_route_if_enabled",
    "read_capability_claims",
    "resolve_evaluand",
    "route",
    "run_cheapest_routing_experiment",
    "run_monoculture_experiment",
    "write_capability_claim",
    "write_experiment_finding",
]
